import { z } from "zod";
const cents = z.number().int().min(0).max(99_999_999_999);
export const receiptInput = z.object({ invoiceId: z.string().min(1).max(150), amountCents: cents.min(1), method: z.enum(["cash", "check", "card", "link", "other"]), receivedAtISO: z.iso.date(), feeCents: cents, reference: z.string().trim().min(1).max(160), evidence: z.string().trim().min(3).max(2000), reviewed: z.literal(true) }).strict().refine(v => v.feeCents <= v.amountCents, "The processing fee cannot exceed the received amount.");
export const returnInput = z.object({ paymentId: z.string().min(1).max(150), date: z.iso.date(), reference: z.string().trim().min(1).max(160), reason: z.string().trim().min(3).max(1000), evidence: z.string().trim().min(3).max(2000), bankFeeCents: cents, customerFeeCents: cents, customerFeeTaxCents: cents, customerFeeEvidence: z.string().trim().max(2000), reviewed: z.literal(true) }).strict().refine(v => v.customerFeeTaxCents <= v.customerFeeCents, "Tax included cannot exceed the customer fee.").refine(v => v.customerFeeCents === 0 || v.customerFeeEvidence.length >= 3, "Record the reviewed basis for charging the customer a returned-payment fee.");
export const followupInput = z.object({ invoiceId: z.string().min(1).max(150), revision: z.number().int().min(0), promisedDate: z.iso.date().nullable(), escalatedTo: z.string().trim().min(1).max(150).nullable(), note: z.string().trim().max(2000) }).strict();
export const reminderInput = z.object({ invoiceId: z.string().min(1).max(150), date: z.iso.date(), note: z.string().trim().min(3).max(2000) }).strict();
export const receivableCommandInput = z.object({ requestId: z.uuid(), action: z.enum(["payment.record", "payment.return", "collection.update", "reminder.record"]), input: z.record(z.string(), z.unknown()) }).strict();
export const receivableSchemas = { "payment.record": receiptInput, "payment.return": returnInput, "collection.update": followupInput, "reminder.record": reminderInput } as const;
export function receivableCatalog() { return Object.entries(receivableSchemas).map(([action, schema]) => ({ action, inputSchema: z.toJSONSchema(schema) })); }
