/** Original engineering acceptance criteria, referenced to the 210-page source PDF.
 * These are requirements, not claims that a route or a passing catalog test is parity. */
export const QBD_MANUAL_URL = "https://quickbooks.intuit.com/oidam/intuit/sbseg/en_us/priority-circle/content/QBD-Level1-Manual-2021.pdf";
export const QBD_CHAPTERS = [
  [1, "Company setup and edition capabilities", 9, 24], [2, "Lists and directories", 25, 34], [3, "Accounts and financial statements", 35, 46], [4, "Item accounting", 47, 54],
  [5, "Invoicing and receivables", 55, 66], [6, "Other sales and customer credits", 67, 78], [7, "Document templates", 79, 84], [8, "Search and recurring work", 85, 93],
  [9, "Sales tax", 95, 104], [10, "Vendors and purchasing costs", 105, 120], [11, "Banking and reconciliation", 121, 130], [12, "Returned payments and deposits", 131, 136],
  [13, "Payroll configuration", 137, 148], [14, "Time and billable costs", 149, 156], [15, "Payroll processing", 157, 166], [16, "User access and audit", 167, 172],
  [17, "Report configuration and export", 173, 188], [18, "Backup, restore and upgrades", 189, 194], [19, "Period close and accountant exchange", 195, 200], [20, "Inventory execution", 201, 207],
] as const;
export type ManualStatus = "verified" | "partial" | "missing" | "unverified";
export interface ManualRequirement { id: string; chapter: number; title: string; pdfPage: number; acceptance: string; status: ManualStatus; route: string | null; evidence: string[]; remaining: string }
type Row = [id: string, title: string, pdfPage: number, acceptance: string];
function chapter(number: number, rows: Row[]): ManualRequirement[] { return rows.map(([id, title, pdfPage, acceptance]) => ({ id, chapter: number, title, pdfPage, acceptance, status: "unverified", route: null, evidence: [], remaining: "Inspect implementation and verify the complete workflow, permissions, persistence and user controls." })); }

export const QBD_REQUIREMENTS: ManualRequirement[] = [
  ...chapter(1, [
    ["company-create", "Organization creation and setup", 18, "Create an isolated organization, save identity and accounting preferences, and resume setup without losing records."],
    ["opening-balances", "Opening balances and historical conversion", 19, "Choose a start date, review balanced opening amounts, import intervening transactions in dependency order and reconcile the opening books."],
    ["company-navigation", "Workspace navigation and shortcuts", 20, "Find each enabled business workflow through the home screen, section navigation and contextual controls; hide irrelevant tools without deleting data."],
    ["company-preferences", "Company and personal preferences", 23, "Persist organization defaults separately from a user's view preferences and enforce who can change each."],
    ["dashboard-panels", "Configurable dashboards and insights", 24, "Add, remove, move and configure dashboard panels; preserve choices and provide print output."],
    ["concurrent-capacity", "Concurrent users and large directories", 12, "Exercise simultaneous workers, protected administration and sustained directory/report performance at the edition capacities described by the source."],
    ["office-integrations", "Office document and mail integration", 12, "Generate usable word-processing/spreadsheet documents and send reviewed business mail through a connected mail account."],
    ["customer-price-levels", "Customer and item price levels", 12, "Apply customer-specific and item-specific prices to reviewed quotes and sales, preserving the accepted price."],
    ["budget-generation", "Budget generation", 12, "Create an editable period budget from reviewed prior results and compare budget against actual accounting."],
    ["mileage", "Vehicle mileage", 12, "Record dated trips, vehicle, purpose, distance and job allocation; report reimbursable and nonbillable mileage."],
    ["loans", "Loan tracking", 12, "Track loan principal, payment schedule, interest and remaining obligation with reviewed postings and payment history."],
    ["cash-forecast", "Cash forecasting", 12, "Project cash from actual cash, dated collections, payables and planned commitments; distinguish assumptions from recorded amounts."],
    ["fixed-assets", "Fixed assets", 12, "Register assets, acquisition cost, disposal and reviewed depreciation schedules; reconcile carrying value to the ledger."],
    ["ship-addresses", "Multiple delivery addresses", 12, "Keep multiple customer destinations and capture the selected address on each order and shipment."],
    ["multicurrency", "Multiple currencies", 12, "Maintain account/transaction currency, dated exchange rates, home-currency postings and realized/unrealized exchange differences."],
    ["sales-backorders", "Sales orders and backorders", 13, "Reserve and partially fulfill accepted sales orders while preserving outstanding quantities, prices and invoicing history."],
    ["assembly-builds", "Inventory assemblies and bills of materials", 13, "Build finished stock from versioned components and labor/charges, consume inputs once and carry the resulting cost."],
    ["business-planner", "Business plans and forecasts", 13, "Save explicit planning assumptions and period forecasts tied to actual business results."],
    ["purchase-from-sales", "Purchasing from quotes or sales orders", 13, "Create linked purchasing demand from accepted work without duplicating already purchased quantities."],
    ["units-conversion", "Simple and advanced units", 13, "Convert purchase, stocking and selling units with controlled precision and preserved conversion evidence."],
    ["consolidation", "Multiple-company reporting", 14, "Select isolated organizations and map accounts/currencies for reviewed combined statements and elimination adjustments."],
    ["statement-designer", "Financial statement design", 14, "Save statement layouts and account groupings and generate consistent, reconcilable financial packages."],
    ["advanced-fields", "Advanced custom fields", 14, "Persist typed, validated custom fields on appropriate records and use them in forms, filters and reporting."],
    ["report-data-access", "Advanced reporting data access", 14, "Expose a documented, permissioned reporting dataset suitable for external query tools, with consistent snapshots."],
    ["enhanced-receiving", "Receipt and supplier-bill separation", 14, "Receive valued goods before a supplier bill arrives and match the later bill without duplicating stock or expense."],
    ["contractor-profile", "Contractor workspace and change orders", 15, "Configure job work, priced approved changes and billing-rate levels with distinct operational records."],
    ["contractor-reports", "Contractor cost and completion reports", 15, "Report job status, vendor costs, remaining cost, unpaid job bills, unassigned expenses and the named certified-payroll information."],
    ["nonprofit-profile", "Nonprofit accounting workspace", 15, "Use donor, grant, program, pledge and donation workflows with an appropriate nonprofit chart and financial presentation."],
    ["nonprofit-reports", "Nonprofit funding and functional reports", 15, "Report donor/grant rankings, program activity, budget comparisons, financial position and functional expenses from reviewed allocations."],
    ["manufacturing-profile", "Manufacturing and wholesale workspace", 16, "Connect quotes, sales worksheets, bills of materials, purchasing, production and shipments."],
    ["manufacturing-reports", "Wholesale sales and reorder reporting", 16, "Report supplier reorder needs, customer-type sales, customer volumes and product profitability from actual stock and transactions."],
    ["quality-return-forms", "Return and material-quality workflows", 16, "Record return authorizations, nonconforming materials and damaged goods with disposition, evidence and inventory/financial effects."],
    ["retail-profile", "Retail sales and vendor returns", 16, "Post reviewed daily retail sales and execute supplier returns; retain their stock and financial history."],
    ["retail-reports", "Retail comparison and margin reports", 16, "Compare monthly income/balance sheets and report item margin, payment-method receipts, supplier purchase volume and returns."],
    ["professional-profile", "Professional-service workspace", 17, "Connect proposals, rate levels, project work, billable time/costs and accurate invoicing."],
    ["professional-reports", "Project billing and cost reports", 17, "Report cost detail, unbilled/unassigned costs, proposal versus billing, billed/unbilled hours, status, balances and aging by class."],
    ["accountant-reports", "Accountant review reports", 17, "Provide adjusted and working trial balances, adjusting entries and entries created today with drill-through evidence."],
    ["accountant-tools", "Accountant data review and tax export", 17, "Review client accounting exceptions and export mapped general-ledger balances for the referenced tax-software workflows."],
    ["company-management", "Multiple-company and sample workspaces", 17, "Manage separate company datasets, switch industry views and provide clearly isolated sample companies without contaminating real books."],
    ["keyboard-workflows", "Keyboard operation", 208, "Provide accessible transaction search/history/copy, list navigation, field undo, date shortcuts, register access and form navigation equivalent to the appendix tasks."],
  ]),
  ...chapter(2, [
    ["contact-directories", "Customer, job, vendor, employee and other-name lists", 26, "Create and maintain the separate directories and inspect identity, relationship and record totals."],
    ["lookup-directories", "Supporting accounting lists", 27, "Maintain representatives, price levels, tax codes, job/vendor/customer types, payroll items, classes, terms, payment/shipping methods, customer messages and saved work."],
    ["contact-conversion", "Other-name conversion", 29, "Move an eligible general contact into a business role with identity/history preserved and incompatible duplicates rejected."],
    ["list-create-inline", "List creation from lists and forms", 30, "Create a validated record in its directory or while completing a dependent transaction and select the resulting record."],
    ["list-edit-delete", "List edits and unused-record deletion", 31, "Edit records with stale-change protection; delete only permitted unused records and retain an audit trail."],
    ["list-inactive", "Inactive records", 31, "Hide inactive records from new transactions, optionally show them in lists and retain historical references."],
    ["list-merge", "List merge", 32, "Preview and confirm a compatible merge, remap dependent records atomically and preserve accounting and history."],
    ["list-sort", "List sorting and ordering", 33, "Sort by columns, restore alphabetical/default ordering and persist manual hierarchy/order where applicable."],
    ["list-print", "Printable directories", 34, "Print the selected directory with complete readable fields and the user's filters."],
  ]),
  ...chapter(3, [
    ["account-types", "Accounting types and classifications", 39, "Represent every listed balance-sheet and income-statement account subtype and classify all postings correctly."],
    ["accounts-edit", "Editable chart of accounts", 40, "Create and edit organization accounts, reject incompatible changes and retain referenced accounts and transaction history."],
    ["account-hierarchy", "Five-level account hierarchy", 41, "Create and move subaccounts with type, cycle and depth checks; subtotal each hierarchy without double counting."],
    ["statement-collapse", "Expandable statement groups", 43, "Expand/collapse individual account branches and all branches in screen and print statements."],
    ["journal-post", "Balanced general journals", 44, "Post a dated, reviewed multi-line entry exactly once, validate accounts/cents and show its effect on the trial balance."],
    ["journal-corrections", "Journal correction history", 43, "Correct an entry with retained original values, actor, date and reason; reject duplicate corrections and preserve balanced books."],
    ["statement-pnl", "Period income statements", 45, "Generate ledger-derived period income/cost/expense statements with monthly columns and percentage-of-income views."],
    ["statement-balance", "Comparative balance sheets", 44, "Generate as-of assets/liabilities/equity and prior-year comparisons, including opening balances and retained earnings."],
    ["cash-accrual", "Cash and accrual report bases", 45, "Change report basis using actual receipt/disbursement allocations without substituting invoice dates for cash dates."],
  ]),
  ...chapter(4, [
    ["item-service", "Service items", 49, "Price services and subcontracted services with separate purchase/sales details and their assigned accounts."],
    ["item-inventory", "Stocked items", 50, "Maintain tracked quantities, on-order quantities, cost and sales values linked to accounts."],
    ["item-noninventory", "Non-stock purchase and sale items", 50, "Use non-stock items that are purchased, sold or both, with independent account treatment."],
    ["item-assembly", "Assembly item definitions", 50, "Define reusable assemblies from eligible component item types and connect to controlled stock builds."],
    ["item-other-charge", "Additional charges", 50, "Apply defined freight/handling/other charge lines to purchasing and sales with correct account and tax treatment."],
    ["item-subtotal", "Subtotal lines", 50, "Calculate subtotal lines at defined points in forms without posting extra revenue."],
    ["item-group", "Grouped items", 50, "Expand a reusable group into its underlying priced/accounted items and control displayed detail."],
    ["item-discount", "Discount items", 50, "Apply a fixed/percentage reduction to the proper subtotal with reviewed tax and account allocation."],
    ["item-payment", "Payment items", 50, "Apply a captured prepayment to an invoice without duplicating cash receipts or revenue."],
    ["item-tax", "Tax and tax-group items", 50, "Apply one or multiple identified tax components and retain amounts owed to each agency."],
    ["item-maintenance", "Item maintenance and type controls", 51, "Create, edit and inactivate item definitions while preventing incompatible type changes after use."],
    ["item-report-sales", "Sales by item", 53, "Summarize sold quantities and net sales by item with transaction drill-through."],
    ["item-report-purchases", "Purchases by item", 53, "Summarize actual received/billed item quantities and costs with source documents."],
    ["item-report-profit", "Item profitability", 54, "Compare recognized item revenue with captured costs and flag missing costs rather than treating them as zero."],
  ]),
  ...chapter(5, [
    ["customer-settings", "Customer billing and payment settings", 57, "Maintain customer billing/delivery data, terms, credit settings and agreed payment preferences."],
    ["customer-jobs", "Customer job hierarchy", 58, "Create customer projects/jobs and track their income, costs and status separately."],
    ["invoice-create", "Service and product invoices", 60, "Create a dated itemized invoice with terms, accounts, tax and captured customer/job details; post and retain the receivable."],
    ["invoice-email", "Invoice mail templates and delivery", 61, "Preview a branded invoice message, send through the configured provider and retain delivery/failure evidence."],
    ["invoice-print", "Individual and batch invoice printing", 62, "Select invoices, preview a readable print batch and record print/reprint state without reposting transactions."],
    ["customer-payment", "Customer payments and partial allocations", 63, "Receive money, allocate partial amounts to eligible customer invoices and preserve unapplied credit and payment provenance."],
    ["deposit-grouping", "Grouped bank deposits", 64, "Select undeposited receipts by payment method, add reviewed deposit lines and post one bank deposit without duplicating receipts."],
    ["deposit-print", "Deposit slips and summaries", 64, "Produce selected deposit details for bank preparation and bookkeeping review."],
    ["open-invoices", "Open-invoice and collections reports", 65, "Show remaining amounts, due dates and collection information reconciled to customer allocations."],
    ["income-tracker", "Unbilled, unpaid and paid sales views", 66, "Navigate each sales stage from the original record through billing, collection and settlement."],
  ]),
  ...chapter(6, [
    ["sales-receipt", "Immediate paid sales", 68, "Record a sale and payment together, then include the receipt in a bank deposit without duplicate revenue."],
    ["statement-charges", "Periodic customer charges", 69, "Record unbilled periodic charges, establish statement terms, issue the statement and collect/deposit payment with supported-item constraints."],
    ["direct-income-deposit", "Direct income deposits", 71, "Record account-coded income directly on a deposit while preventing duplicate itemized sales or unsupported tax treatment."],
    ["import-sales", "Sales from external systems", 72, "Import reviewed external sales using mappings, stable identities and retry protection; reconcile imported totals."],
    ["customer-credit", "Customer credit creation and allocation", 72, "Issue a credit against a prior sale, apply it partially to eligible invoices and retain remaining customer credit."],
    ["customer-refund", "Customer refunds", 73, "Create and settle a reviewed refund from available credit, preserving original payment, account and audit history."],
    ["customer-statements", "Customer statements", 75, "Generate open-transaction and date-activity statements with optional invoice summaries/details, customer selection, print and email."],
    ["customer-sales-report", "Customer sales summaries", 77, "Summarize customer/job sales with collapsed levels, percentage of total and cash/accrual basis."],
  ]),
  ...chapter(7, [
    ["form-branding", "Reusable business-document design", 80, "Apply logo, fonts, colors and grid styling consistently across business documents with a preview."],
    ["form-layout", "Document fields and layout", 82, "Choose, label and position fields/columns independently for screen and print; add text, data fields and images."],
    ["form-types", "Templates for every listed form", 82, "Generate invoices, credits, receipts, purchase orders, statements, estimates and sales orders from the correct typed records."],
    ["form-copy-share", "Copy and import document templates", 84, "Duplicate a template for another supported form and import/export reviewed definitions without business secrets."],
  ]),
  ...chapter(8, [
    ["business-calendar", "Financial calendar and to-dos", 86, "Show bills, invoices, recorded activity and tasks by day; edit task type, priority, date, detail and status."],
    ["transaction-navigation", "Previous/next and contextual lookup", 87, "Navigate original transactions from forms and customer/vendor centers with usable filters."],
    ["global-search", "Global business search", 89, "Search authorized records, transactions and navigation; refresh stale index data and filter results."],
    ["recurring-definitions", "Reusable transaction templates", 90, "Save/edit the content and schedule of repeated invoices, bills, checks and other supported transaction types."],
    ["recurring-execution", "Due recurring transactions", 92, "Review due occurrences, create selected transactions exactly once or defer them, preserving each occurrence's identity."],
    ["recurring-maintenance", "Recurring schedule changes and removal", 93, "Change schedules without accidental posting; stop future occurrences without losing existing transactions."],
  ]),
  ...chapter(9, [
    ["tax-preferences", "Tax accounting preferences", 96, "Save reviewed tax recognition/payment settings and applicable business defaults."],
    ["tax-agencies", "Tax agencies, rates and groups", 97, "Maintain dated single/group rates, tax payees and component liabilities independently."],
    ["tax-codes", "Taxability and exemption reasons", 98, "Classify taxable and exempt sales with explicit reporting reasons rather than only a global percentage."],
    ["tax-item-defaults", "Item tax treatment", 99, "Assign tax treatment to service, stocked/non-stock, charge and discount items and preserve transaction evidence."],
    ["tax-customer-defaults", "Customer tax treatment", 100, "Apply customer exemptions and rate defaults appropriately, including otherwise taxable items."],
    ["tax-invoices", "Tax on sales documents", 101, "Calculate mixed taxable/exempt line amounts, compound/group components and captured invoice totals consistently."],
    ["tax-reports", "Taxable sales and liability reporting", 102, "Reconcile tax revenue classifications and component agency liabilities for a chosen reporting period."],
    ["tax-adjustments", "Reviewed tax adjustments", 103, "Post a supported adjustment with agency, date, reason and offset account while preserving the original sales."],
    ["tax-payments", "Tax liability payments", 104, "Select agency liabilities, record reviewed payment allocations and retain remaining obligations and bank evidence."],
  ]),
  ...chapter(10, [
    ["vendors", "Vendor records and tax identity", 107, "Maintain addresses, payment defaults and protected tax/reporting identity with duplicate controls."],
    ["bills", "Supplier bills and payables", 108, "Enter item/account-coded bills before payment and track due dates, open balances and source attachments."],
    ["bill-tracker", "Bill tracker", 109, "Inspect pending, open and paid supplier documents with links to their actual accounting state."],
    ["bill-discount-credit-policy", "Payment discounts and automatic credits", 110, "Configure reviewed credit/discount application and its account, while validating every resulting allocation."],
    ["bill-batch-payment", "Selected bill payments", 111, "Pay selected full/partial bills from an identified funding account with credits/discounts applied once."],
    ["check-printing", "Check printing and batches", 112, "Select pending checks, assign/confirm check numbers and style, print and handle reprints without duplicate payments."],
    ["direct-checks", "Direct vendor checks", 113, "Record account/item-coded vendor checks without creating a second bill; support written and print-later checks."],
    ["debit-transactions", "Debit-card payments", 114, "Record bank-funded card spending without advancing check numbers and include it in reconciliation."],
    ["credit-card-accounts", "Credit-card accounts and charges", 115, "Maintain card liability accounts, record purchases/credits and reconcile card balances and payments."],
    ["vendor-credits", "Supplier credits", 117, "Record a supplier credit and allocate eligible amounts to bills without duplicate stock or payable changes."],
    ["vendor-reports", "Vendor costs and balances", 119, "Report expenses, unpaid bill detail, vendor balance detail and payable aging with consistent source drill-through."],
  ]),
  ...chapter(11, [
    ["bank-feeds", "Bank account feeds", 122, "Connect an account, securely retrieve bank transactions, preserve provider IDs and reject duplicated imports."],
    ["bank-online-payments", "Online bank payments", 123, "Submit reviewed check/bill payments through a configured bank provider and reconcile actual submission, failure and settlement."],
    ["bank-match-add", "Matching and adding bank transactions", 126, "Review downloaded transactions, match existing entries or create supported new entries without double posting."],
    ["bank-rules", "Bank classification rules", 124, "Create/edit reviewed matching/category rules and explain proposed allocations before posting."],
    ["bank-reconciliation", "Statement reconciliation", 127, "Enter statement date/balances, select cleared items, reconcile exactly and preserve the reconciliation report."],
    ["reconciliation-recovery", "Reconciliation discrepancies and undo", 128, "Detect changed reconciled items, inspect prior reports and perform an audited undo/restart of the appropriate reconciliation."],
    ["check-void-delete", "Void versus unused-check deletion", 129, "Retain used check numbers when voiding and preserve prior periods; permit audited deletion only for genuinely unused drafts."],
    ["missing-checks", "Missing-check reports", 130, "Report gaps and duplicates in the selected bank account's actual check-number sequence."],
  ]),
  ...chapter(12, [
    ["bounced-payments", "Returned customer payments", 132, "Reverse a returned payment, reopen the correct receivable, record bank fees and optionally bill a separate customer fee."],
    ["customer-deposits", "Unapplied deposits and later invoicing", 134, "Receive a customer advance, preserve unused credit/liability, invoice delivered work and apply the advance once."],
  ]),
  ...chapter(13, [
    ["payroll-service", "Payroll provider and employer setup", 138, "Capture employer identifiers, provider configuration and reviewed opening payroll figures without treating a connector placeholder as processing."],
    ["payroll-tax-tables", "Current payroll calculation inputs", 138, "Version applicable payroll tax tables/rules by jurisdiction and pay date with reviewed update and calculation evidence."],
    ["workers-compensation", "Workers compensation", 138, "Maintain compensation classifications, eligible wage bases, rates and reports with reconciled liability/cost amounts."],
    ["net-to-gross", "Net-to-gross payroll", 138, "Solve and review gross compensation for a requested net payment using the applicable deductions and taxes."],
    ["direct-deposit", "Payroll direct deposit", 139, "Protect employee banking details, send an authorized payroll batch and reconcile provider acceptance and settlement."],
    ["payroll-schedules", "Payroll schedules and defaults", 141, "Assign pay frequency, period boundaries and pay dates to employees; persist controlled employee defaults."],
    ["payroll-wages", "Wages, salary, commissions and bonuses", 143, "Define and calculate each compensation type with effective dates, accounts and employee assignments."],
    ["payroll-benefits", "Insurance and retirement benefits", 143, "Maintain employee/employer, pre-tax and taxable benefit items with limits and liability allocations."],
    ["payroll-pto", "Sick leave and vacation", 143, "Accrue, use and report employee leave balances and paid-leave compensation according to reviewed policies."],
    ["payroll-additions", "Reimbursements and advances", 143, "Apply reviewed reimbursements and employee advances with the correct taxable and accounting treatment."],
    ["payroll-deductions", "Deductions and custom payroll items", 143, "Apply garnishments, dues and jurisdiction-specific items with priorities, limits and protected evidence."],
    ["payroll-item-maintenance", "Payroll item setup and changes", 144, "Create/edit item definitions with effective dating and preserve the definitions used on completed payroll."],
    ["employee-payroll-records", "Employee payroll records", 145, "Maintain personal/contact/employment data, compensation, federal/state elections and leave settings with scoped access."],
  ]),
  ...chapter(14, [
    ["time-preferences", "Time-entry preferences", 150, "Configure the workweek and time/billing behavior for employees, contractors and owners."],
    ["weekly-timesheets", "Weekly job timesheets", 151, "Enter and review time by person, job, service and day, with billable/nonbillable classification and corrections."],
    ["timesheet-print", "Timesheet print batches", 152, "Select people and dates and generate readable timesheets for review or records."],
    ["bill-time-costs", "Invoice selected time and costs", 153, "Review eligible unbilled time/expenses by customer/job and invoice selected lines once at the appropriate rates."],
    ["time-reports", "Time and job productivity reports", 155, "Report billed, unbilled and nonbillable time by person/job and reconcile profitability to actual posted labor and other costs."],
  ]),
  ...chapter(15, [
    ["payroll-run", "Scheduled and unscheduled payroll", 158, "Select the period/employees, review hours and computed pay, amend before approval and commit a payroll run exactly once."],
    ["payroll-checks", "Payroll check output", 161, "Generate individual/batch checks tied to approved payroll, preserving numbers and print/reprint history."],
    ["payroll-stubs", "Pay statements", 162, "Produce private employee pay statements with earnings, deductions, taxes and year-to-date totals; support print/email delivery."],
    ["payroll-liabilities", "Payroll liability schedules and payments", 163, "Track due and overdue payroll obligations, allocate payments and account for penalties/expenses without duplicating liabilities."],
    ["payroll-941", "Quarterly payroll return workflow", 164, "Prepare Form 941 and Schedule B as applicable, validate values, retain corrections and provide reviewed filing output for the configured filing year."],
    ["payroll-state-annual", "State returns and annual wage forms", 138, "Produce supported state filings and annual W-2 employee wage reporting from reconciled payroll and retain provider/file evidence for the configured filing year."],
    ["payroll-reports", "Payroll and labor-profitability reports", 165, "Report compensation, hours, rates, employer costs and job profitability from completed payroll."],
  ]),
  ...chapter(16, [
    ["owner-identity", "Administrator identity", 169, "Create a protected owner identity and recover access without exposing passwords or silently elevating staff."],
    ["employee-identity", "User accounts and roles", 170, "Invite, activate, authenticate and revoke users; enforce view/edit authority in pages, APIs and mutations."],
    ["accountant-access", "External-accountant access", 170, "Provide the required accounting authority while withholding unrelated confidential payment/customer data."],
    ["exclusive-maintenance", "Concurrent work and exclusive maintenance", 171, "Allow safe concurrent business operations and enforce an exclusive, recoverable maintenance window for conflicting administrative work."],
    ["accounting-audit", "Accounting audit report", 172, "Search additions, changes and deletions by date, actor and transaction with preserved before/after values."],
  ]),
  ...chapter(17, [
    ["report-center", "Report center", 174, "Find and run every required report by business category with appropriate permissions and real records."],
    ["report-columns", "Report columns and sorting", 175, "Select columns, sort field/direction and preserve widths/order in a reusable view."],
    ["report-format", "Report presentation", 178, "Configure headers/footers, fonts, numeric display and organization-wide defaults for screen and print."],
    ["report-filters", "Report filters", 180, "Filter by the relevant dates, accounts, people, items, classes and transaction state without leaking excluded records."],
    ["saved-reports", "Saved report definitions", 182, "Save a named report configuration and rerun it against current records without copying stale values."],
    ["report-groups", "Saved report groups", 183, "Organize saved reports and run/print a chosen batch with date overrides."],
    ["report-excel", "Spreadsheet export", 185, "Export report data and formatting to a usable workbook with explicit numeric/date cells."],
    ["report-excel-refresh", "Refresh existing spreadsheets", 186, "Refresh a saved workbook's linked report while retaining supported user titles, layout, inserted content and formulas; surface conflicts."],
    ["report-template-share", "Share report templates", 13, "Export/import report definitions independently from customer data, credentials and generated report values."],
  ]),
  ...chapter(18, [
    ["backup-manual", "Manual verified backups", 190, "Create a complete consistent backup with integrity checks and clear file location."],
    ["backup-automatic", "Automatic and scheduled backups", 190, "Configure reminders/schedules, run backups durably and surface failures and retention state."],
    ["backup-offsite", "Off-site backups", 190, "Send protected backups to a configured remote destination and verify retrieval without exposing credentials."],
    ["backup-restore", "Restore and historical review", 192, "Verify a backup, restore into a chosen isolated location and authenticate against the recovered records."],
    ["upgrades", "Versioned data upgrades", 193, "Show deployed/schema versions, prepare a backup, migrate supported data safely and explain compatibility/rollback boundaries."],
    ["update-delivery", "Maintenance update controls", 194, "Check for reviewed releases, choose automatic/manual delivery and ensure all application instances use a compatible version."],
  ]),
  ...chapter(19, [
    ["period-lock", "Protected accounting closing date", 196, "Set an organization closing date and enforce it across every posting/edit/delete path, including integrations, with controlled audited overrides."],
    ["prior-period-authority", "Prior-period edit authority", 197, "Grant and revoke narrowly scoped prior-period authority independently from ordinary bookkeeping edit access."],
    ["accountant-copy", "Accountant working copy", 198, "Export a restricted accounting snapshot with a dividing date while ordinary current-period work continues."],
    ["accountant-import", "Accountant adjustment import", 200, "Preview, validate and apply accountant changes once, detecting conflicts and preserving original/current-period work."],
  ]),
  ...chapter(20, [
    ["stock-status", "Stock status and reorder demand", 202, "Report quantity available/on order and reorder demand by item from actual inventory movements."],
    ["stock-locations", "Inventory locations and transfers", 202, "Maintain location-level quantities/values and execute traceable transfers without creating income or duplicating inventory."],
    ["purchase-orders", "Inventory purchase orders", 203, "Create, issue and track itemized supplier orders, partial receipts and outstanding quantities."],
    ["receive-with-bill", "Receive purchases with bills", 204, "Select relevant purchase orders, receive actual quantities and post the supplier bill and valued stock atomically."],
    ["inventory-pay-bill", "Pay inventory bills", 205, "Allocate verified full/partial payment to the original inventory payable without purchasing stock a second time."],
    ["physical-worksheet", "Physical count worksheets", 206, "Produce a complete scoped count worksheet and review observations against recorded stock."],
    ["stock-adjustment", "Quantity and value adjustments", 206, "Review new quantity/difference and valuation adjustments, preserve count evidence and post the appropriate account effect."],
    ["stock-reports", "Open purchases and valuation reports", 207, "Report detailed open purchase commitments and inventory valuation reconciled to quantities, costs and accounting."],
  ]),
];

const partial: Record<string, { route: string; evidence: string[]; remaining: string }> = {
  "company-create": { route: "/setup", evidence: ["src/lib/industry/catalog.ts", "scripts/workspace-smoke.ts"], remaining: "Accounting conversion, historical opening balances and full company-level financial preferences remain incomplete." },
  "company-navigation": { route: "/branding", evidence: ["src/lib/navigation/catalog.ts", "docs/WORKSPACE-NAVIGATION.md"], remaining: "Each missing accounting workflow still needs its actual controls and proper navigation destination." },
  "company-preferences": { route: "/branding", evidence: ["src/lib/branding/store.ts"], remaining: "The full financial, payroll, tax and document preference set has not been implemented and verified." },
  "accounts-edit": { route: "/ledger/accounts", evidence: ["src/lib/accounting/account-model.ts", "src/lib/accounting/accounts.test.ts", "src/components/ChartOfAccounts.test.tsx", "scripts/journal-http-check.ts"], remaining: "Reviewed custom accounts, edits, inactive status, stale-change protection and history are implemented. Unused-account deletion/merge, full subledger integration and visual acceptance remain open." },
  "account-types": { route: "/ledger/accounts", evidence: ["src/lib/accounting/account-model.ts", "src/lib/accounting/accounts.test.ts"], remaining: "All 15 classifications are available and mapped into the ledger. Full specialized subledger behavior and statement presentation still need verification." },
  "journal-corrections": { route: "/ledger", evidence: ["src/lib/accounting/journal-store.ts", "src/lib/accounting/journal-store.test.ts", "src/components/GeneralLedger.test.tsx", "scripts/journal-http-check.ts"], remaining: "Reviewed reversals preserve original values and actors. Global period locks and complete source-transaction correction integration remain open." },
  "account-hierarchy": { route: "/ledger/accounts", evidence: ["src/lib/accounting/account-model.ts", "src/lib/accounting/accounts.test.ts"], remaining: "Five-level creation/moves, type matching, cycle/depth checks and ordered display are implemented. Expandable financial-statement subtotals and visual acceptance remain open." },
  "journal-post": { route: "/ledger", evidence: ["src/lib/accounting/journal-store.ts", "src/lib/accounting/ledger.test.ts", "src/lib/accounting/journal-store.test.ts", "scripts/journal-http-check.ts"], remaining: "Reviewed posting, author history and durable retry protection are implemented. Global prior-period rules and complete source-transaction integration remain open." },
  "statement-pnl": { route: "/ledger", evidence: ["src/lib/accounting/ledger-load.ts", "src/lib/accounting/posting.ts"], remaining: "Legacy posting is regenerated from operational records; period, monthly, cash-basis and complete posting evidence are not established." },
  "statement-balance": { route: "/ledger", evidence: ["src/lib/accounting/ledger-load.ts"], remaining: "All transaction sources, opening balances, as-of dates and prior-year comparisons need implementation and verification." },
  "customer-price-levels": { route: "/customers", evidence: ["docs/CUSTOMER-WEBSITE.md", "scripts/customer-http-check.ts"], remaining: "Customer portal prices work; full typed-item/accounting price-level parity remains open." },
  "customer-jobs": { route: "/modules/service-work", evidence: ["src/lib/workspace/store.ts"], remaining: "Service job execution exists; a unified accounting customer/job hierarchy and every job report remain incomplete." },
  "invoice-create": { route: "/modules/service-billing", evidence: ["src/lib/workspace/store.ts", "docs/WORKFLOWS-AND-RELEASE.md"], remaining: "Service invoices work; a unified product/service accounting invoice and item/tax ledger lifecycle remain open." },
  "customer-payment": { route: "/collections", evidence: ["src/lib/payments/ar-store.ts", "src/lib/payments/receivables.test.ts", "src/components/CollectionsBoard.test.tsx", "scripts/receivable-http-check.ts"], remaining: "Product-invoice receipts capture actual dates, evidence, fees and balanced journal entries atomically. Unified specialist allocations, unapplied credit, undeposited funds, grouped deposits and complete invoice/terms snapshots remain open." },
  "customer-credit": { route: "/restaurant/finance?tab=credits", evidence: ["src/lib/restaurant/credits.ts", "scripts/restaurant-credit-http-check.ts"], remaining: "Restaurant credits work; general customer credits and cross-invoice application remain missing." },
  "bounced-payments": { route: "/collections", evidence: ["src/lib/payments/receivables.test.ts", "src/components/CollectionsBoard.test.tsx", "scripts/receivable-http-check.ts"], remaining: "Reviewed bank returns retain original receipts, reopen debt, record bank fees and reviewed customer fee/tax, and permit replacement settlement. Separate printable fee invoices, all payment-provider workflows and visual acceptance remain open." },
  "customer-refund": { route: "/restaurant/finance?tab=credits", evidence: ["docs/RESTAURANT-ACCEPTANCE.md"], remaining: "Restaurant recorded-refund workflows exist; general customer credit/refund execution and live payment acceptance remain open." },
  "customer-statements": { route: "/customers", evidence: ["src/lib/customer-access/service.ts"], remaining: "Private customer history is not the required selectable open/activity statement and print/email workflow." },
  "professional-profile": { route: "/setup", evidence: ["docs/INDUSTRY-AND-WEBSITE-ACCEPTANCE.md"], remaining: "Core service workflows are tested; all source billing/accounting reports and accounting mappings remain incomplete." },
  "nonprofit-profile": { route: "/setup", evidence: ["docs/WORKFLOWS-AND-RELEASE.md"], remaining: "Donor/program workflows are tested; complete nonprofit accounting/chart/statements remain incomplete." },
  "form-branding": { route: "/branding", evidence: ["src/lib/branding/templates.ts"], remaining: "Workspace branding and some documents exist; a shared business-document design/layout system remains incomplete." },
  "weekly-timesheets": { route: "/timeclock", evidence: ["src/lib/timeclock/schedule.ts", "docs/EMPLOYEE-ACCOUNTS.md"], remaining: "Clock/attendance and service time exist; unified weekly contractor/employee billing/payroll classification and print controls remain open." },
  "employee-identity": { route: "/admin", evidence: ["scripts/workspace-smoke.ts", "docs/EMPLOYEE-ACCOUNTS.md"], remaining: "Employee identity is exercised; every new accounting path still needs role tests and production deployment review." },
  "accounting-audit": { route: "/ledger", evidence: ["src/lib/workspace/database.ts", "src/lib/accounting/journal-store.ts"], remaining: "Some domain audit histories exist; a complete accounting additions/edits/deletions report does not." },
  "backup-manual": { route: "/admin", evidence: ["scripts/workspace-backup.ts", "docs/WORKFLOWS-AND-RELEASE.md"], remaining: "CLI backup/recovery exists; owner-facing backup configuration and complete deployment acceptance remain open." },
  "backup-restore": { route: "/admin", evidence: ["scripts/workspace-backup.ts"], remaining: "Isolated restore has been exercised; UI workflow, operating recovery drills and deployment proof remain open." },
  "receive-with-bill": { route: "/restaurant/manage?tab=purchasing", evidence: ["src/lib/restaurant/business.ts", "scripts/restaurant-business-http-check.ts"], remaining: "Restaurant receipt/payable execution is tested; general typed-item inventory execution and all purchasing flows remain open." },
  "stock-adjustment": { route: "/restaurant/manage?tab=stocktakes", evidence: ["src/lib/restaurant/stocktake.ts", "scripts/restaurant-stocktake-http-check.ts"], remaining: "Restaurant physical-count posting exists; general inventory quantity/value and location accounting parity remain open." },
};
const missing = new Set(["account-hierarchy", "accounts-edit", "statement-collapse", "cash-accrual", "statement-designer", "loans", "multicurrency", "consolidation", "form-layout", "recurring-execution", "customer-statements"]);
for (const row of QBD_REQUIREMENTS) if (missing.has(row.id)) { row.status = "missing"; row.remaining = "The required end-to-end workflow has not been implemented."; }
for (const row of QBD_REQUIREMENTS) if (partial[row.id]) Object.assign(row, { status: "partial" }, partial[row.id]);
export function manualCoverage() {
  return { total: QBD_REQUIREMENTS.length, verified: QBD_REQUIREMENTS.filter(r => r.status === "verified").length, partial: QBD_REQUIREMENTS.filter(r => r.status === "partial").length, missing: QBD_REQUIREMENTS.filter(r => r.status === "missing").length, unverified: QBD_REQUIREMENTS.filter(r => r.status === "unverified").length };
}
