import { defineModule } from "@/lib/sdk/module";
import type { Field } from "@/lib/features/model";
import type { AppModuleManifest, ModuleRecord } from "@/lib/sdk/types";
const field = (id: string, label: string, type: Field["type"] = "text", required = false, options: string[] = []): Field => ({ id, label, type, required, options });
const text = (id: string, label: string, required = false) => field(id, label, "text", required);
const money = (id: string, label: string, required = false) => field(id, label, "money", required);
const number = (id: string, label: string, required = false) => field(id, label, "number", required);
const date = (id: string, label: string, required = false) => field(id, label, "date", required);
const notes = field("notes", "Notes", "notes");
const status = (options: string[]) => field("status", "Status", "select", true, options);
const sum = (rows: ModuleRecord[], key: string) => rows.filter(r => !r.archived).reduce((total, row) => total + (Number(row.values[key]) || 0), 0);
function record(id: string, label: string, group: string, section: AppModuleManifest["section"], capabilityPacks: string[], fields: Field[], description: string, panels?: AppModuleManifest["panels"]) {
  return defineModule({ id, label, group, section, capabilityPacks, fields, description, panels, version: "1.0.0", author: "Shuug" });
}
export const industryRecords = [
  record("vehicles", "Vehicles", "Services", "services", ["auto_repair"], [text("customer_id", "Service client ID", true), text("vin", "VIN", true), text("registration", "Registration / plate"), text("make", "Make", true), text("model", "Model", true), number("year", "Model year", true), number("odometer", "Odometer"), text("fleet_id", "Fleet account ID"), notes], "Vehicle identities, customer ownership and service reference records."),
  record("vehicle-inspections", "Vehicle inspections", "Services", "services", ["auto_repair"], [text("vehicle_id", "Vehicle record ID", true), text("job_id", "Work order ID", true), text("technician", "Technician", true), date("inspected", "Inspection date", true), status(["In progress", "Needs work", "Reviewed"]), field("brakes", "Brakes", "select", true, ["Not checked", "Pass", "Attention", "Unsafe"]), field("tires", "Tires", "select", true, ["Not checked", "Pass", "Attention", "Unsafe"]), field("fluids", "Fluids", "select", true, ["Not checked", "Pass", "Attention", "Unsafe"]), field("findings", "Findings and required work", "notes", true), text("reviewer", "Reviewer"), notes], "Document multi-point findings and review alongside the service work order."),
  record("labor-rates", "Labor & parts pricing", "Services", "services", ["auto_repair"], [text("category", "Job / customer category", true), money("hourly_rate", "Hourly rate", true), number("minimum_minutes", "Minimum billed minutes"), date("effective_from", "Effective from", true), date("effective_to", "Effective to"), notes], "Publish reviewed labor and parts pricing versions and apply them to vehicle estimates."),
  record("parts-markups", "Parts markup rules", "Services", "services", ["auto_repair", "inventory"], [text("category", "Part category", true), money("cost_from", "Cost band from", true), money("cost_to", "Cost band to"), number("markup_percent", "Markup percent", true), date("effective_from", "Effective from", true), notes], "Maintain reviewed part cost bands and pricing rules."),
  record("fleet-accounts", "Fleet & commercial accounts", "Services", "services", ["fleet"], [text("client_id", "Service client ID", true), text("fleet_name", "Fleet name", true), text("billing_contact", "Billing contact"), text("purchase_order_rule", "Purchase order requirements"), text("agreement_id", "Service agreement ID"), number("payment_terms_days", "Payment terms (days)"), notes], "Fleet billing instructions and agreements, separate from individual vehicles."),
  record("service-reminders", "Service reminders", "Services", "services", ["auto_repair"], [text("vehicle_id", "Vehicle record ID", true), text("service", "Service due", true), date("due", "Due date"), number("due_odometer", "Due odometer"), status(["Due", "Contacted", "Booked", "Completed", "Dismissed"]), text("assigned_to", "Assigned technician"), notes], "Track service follow-ups and their recorded outcome."),
  record("restaurant-menu", "Menu", "Operations", "operations", ["restaurant"], [text("name", "Menu item", true), text("category", "Menu category", true), money("price", "Selling price", true), text("recipe_id", "Recipe ID"), field("available", "Available", "checkbox", true), field("allergens", "Allergen information", "notes"), notes], "Menu items, prices, availability and recipe references."),
  record("suppliers", "Suppliers", "Operations", "operations", ["purchasing"], [text("name", "Supplier name", true), text("contact", "Contact"), text("email", "Email"), text("phone", "Phone"), text("terms", "Payment terms"), text("account", "Supplier account reference"), notes], "Supplier contacts and purchasing terms."),
  record("ingredient-inventory", "Ingredient inventory", "Operations", "operations", ["restaurant", "inventory"], [text("name", "Ingredient", true), text("unit", "Stock unit", true), number("on_hand", "Quantity on hand", true), number("reorder_at", "Reorder level"), money("unit_cost", "Cost per stock unit", true), text("supplier_id", "Supplier record ID"), date("expiry", "Expiry date"), notes], "Ingredient stock quantities, units, costs and expiry dates."),
  record("purchase-orders", "Purchase orders", "Operations", "operations", ["purchasing"], [text("supplier_id", "Supplier record ID", true), text("reference", "Purchase reference", true), date("ordered", "Order date", true), date("expected", "Expected delivery"), status(["Draft", "Approved", "Ordered", "Part received", "Received", "Canceled"]), money("total", "Order total", true), field("items", "Items and quantities", "notes", true), notes], "Purchasing requests and recorded receipt progress."),
  record("restaurant-recipes", "Recipes & food costs", "Operations", "operations", ["restaurant", "production"], [text("name", "Recipe", true), number("yield", "Yield (portions)", true), money("ingredients_cost", "Ingredient cost for batch", true), money("labor_cost", "Labor cost for batch"), money("other_cost", "Other batch cost"), money("selling_price", "Selling price per portion"), field("ingredients", "Ingredients and quantities", "notes", true), notes], "Recipe yields and recorded batch costs; summary derives total batch costs.", [{ id: "cost", label: "Recipe costs", compute: rows => [{ label: "Recipes", value: String(rows.filter(r => !r.archived).length) }, { label: "Recorded batch costs", value: ((sum(rows, "ingredients_cost") + sum(rows, "labor_cost") + sum(rows, "other_cost")) / 100).toFixed(2) }] }]),
  record("staff-shifts", "Staff scheduling & shifts", "Team", "team", ["time"], [text("employee_id", "Employee ID", true), date("day", "Shift date", true), text("start", "Start time", true), text("end", "End time", true), text("role", "Role / station", true), status(["Draft", "Assigned", "Confirmed", "Completed", "Canceled"]), notes], "Staff shift assignments alongside the employee time clock."),
  record("food-waste", "Waste", "Operations", "operations", ["restaurant"], [text("ingredient_id", "Ingredient or menu record ID", true), date("day", "Waste date", true), number("quantity", "Quantity", true), text("unit", "Unit", true), money("cost", "Recorded waste cost", true), field("reason", "Reason", "select", true, ["Expired", "Preparation", "Overproduction", "Returned", "Damaged", "Other"]), notes], "Record food waste and its cost.", [{ id: "cost", label: "Waste cost", compute: rows => [{ label: "Recorded waste cost", value: (sum(rows, "cost") / 100).toFixed(2) }] }]),
  record("restaurant-reservations", "Tables & reservations", "Services", "services", ["restaurant", "appointments"], [text("guest", "Guest name", true), text("contact", "Guest contact", true), date("day", "Reservation date", true), text("time", "Reservation time", true), number("party_size", "Party size", true), text("table", "Table"), status(["Requested", "Confirmed", "Seated", "Completed", "Canceled", "No show"]), notes], "Track restaurant reservation requests and table assignments."),
  record("daily-close", "Daily close", "Money", "money", ["restaurant", "accounting"], [date("day", "Business date", true), money("cash_sales", "Cash sales", true), money("card_sales", "Card sales", true), money("refunds", "Refunds", true), money("cash_expected", "Expected closing cash", true), money("cash_counted", "Counted closing cash", true), text("reviewer", "Reviewed by"), text("ledger_reference", "Ledger posting reference"), status(["Open", "Counted", "Reviewed", "Posted"]), notes], "Daily sales and cash counts with explicit ledger references.", [{ id: "cash", label: "Cash review", compute: rows => [{ label: "Recorded cash variance", value: ((sum(rows, "cash_counted") - sum(rows, "cash_expected")) / 100).toFixed(2) }] }]),
  record("member-subscriptions", "Members & subscriptions", "Sales", "sales", ["memberships"], [text("contact_id", "Contact ID", true), text("plan", "Membership plan", true), date("starts", "Starts", true), date("renews", "Renews"), money("dues", "Dues", true), status(["Pending", "Active", "Grace period", "Paused", "Canceled"]), text("payment_reference", "Payment provider reference"), notes], "Membership records and renewal dates. Provider payment references remain explicit."),
];
