import type { Field, TrackerDefinition } from "./model";

export interface Feature {
  id: string; name: string; description: string; href: string;
  category: "Sales" | "Operations" | "Marketing" | "Money";
  aliases: string[]; core?: boolean; requirement?: string;
}
export const FEATURES: Feature[] = [
  {id:"social",name:"Social marketing",description:"Drop website or social links, compare profiles and plan campaigns with real metrics and brand artwork.",href:"/social",category:"Marketing",aliases:["social marketing","social media","social campaigns","social links","instagram","tiktok","facebook","youtube","linkedin","pinterest","threads","bluesky"],core:true,requirement:"Public profiles work from URLs; private analytics require account authorization. Optional Gemini or OpenAI keys for images."},
  {id:"expenses",name:"Expenses & receipts",description:"Read receipt photos, review expenses and keep searchable digital records.",href:"/expenses",category:"Money",aliases:["expenses","expense","receipts","receipt","business spending","expense tracker"],core:true},
  {id:"calendar",name:"Business calendar",description:"Browse sales, margins, expenses and business activity by day, month and year.",href:"/calendar",category:"Money",aliases:["calendar","business history","daily margins","daily sales","monthly profit","yearly profit"],core:true},
  { id:"customers",name:"Customers",description:"Buyer contacts, customer pricing and account details.",href:"/customers",category:"Sales",aliases:["customers","customer","buyer contacts","crm"],core:true },
  { id:"orders",name:"Orders",description:"Create orders and see orders by sales channel.",href:"/orders",category:"Sales",aliases:["orders","order management"],core:true },
  { id:"visits",name:"Store finder",description:"Find businesses, save prospects and order a day of visits.",href:"/visits",category:"Sales",aliases:["store visits","store finder","route planning","routes","map","delis","supermarkets","restaurants","prospects"],core:true,requirement:"Google Maps connection for live search and route optimization." },
  { id:"products",name:"Products & pricing",description:"Catalog, case pricing and margin calculations.",href:"/products",category:"Sales",aliases:["products","pricing","price list","catalog"],core:true },
  { id:"marketing",name:"Marketing",description:"Compare competitors, evaluate keywords and review paused campaigns.",href:"/ads",category:"Marketing",aliases:["competitors","competition","ads","advertising","ppc","keywords","marketing"],core:true,requirement:"Google Ads for live CPCs and campaign creation; research sources label estimates." },
  { id:"amazon-marketing",name:"Amazon Marketing",description:"Build Sponsored Products ads, review budgets, launch campaigns and measure Amazon results.",href:"/amazon-marketing",category:"Marketing",aliases:["amazon marketing","amazon ads","amazon advertising","sponsored products","amazon campaigns"],core:true,requirement:"Connect Amazon Ads in Settings with an approved advertising app." },
  { id:"reports",name:"Sales reports",description:"Sales, products, customers and channel comparisons from recorded orders.",href:"/analytics",category:"Sales",aliases:["reports","analytics","sales reports"],core:true },
  { id:"money",name:"Money",description:"Accounting connections and a reviewed invoice handoff.",href:"/finance",category:"Money",aliases:["money","accounting","finance"],core:true,requirement:"Connect QuickBooks for accounting data." },
  { id:"operations",name:"Inventory & shipping",description:"Stock counts, reorder calculations and shipment recording.",href:"/operations",category:"Operations",aliases:["inventory","stock","shipping","reorder","production"],requirement:"Existing demo workspace; stock and shipments currently reset with the server." },
  { id:"invoice-audit",name:"Invoice checker",description:"Compare supplier invoices and flag price changes.",href:"/invoices",category:"Money",aliases:["invoice audit","invoice checker","check invoices","invoice checking" ],requirement:"Existing demo workspace; uploaded invoices currently reset with the server." },
  { id:"amazon",name:"Amazon shipping pipeline",description:"Track products, fulfillment, packages and payment information from Amazon.",href:"/amazon",category:"Sales",aliases:["amazon","shipping pipeline","fulfillment pipeline"],core:true,requirement:"Connect Amazon in Settings to refresh live orders." },
];
export interface TrackerTemplate extends TrackerDefinition { id: string; category: Feature["category"]; aliases: string[] }
const field = (id:string,label:string,type:Field["type"]="text",required=false,options:string[]=[]):Field => ({id,label,type,required,options});
const company = field("company","Business","text",true), owner = field("owner","Owner"), notes = field("notes","Notes","notes");
const status = (options:string[]) => field("status","Status","select",true,options);
export const TEMPLATES: TrackerTemplate[] = [
  {id:"sample-requests",name:"Sample requests",category:"Sales",description:"Record samples, the buyer receiving them and the next follow-up.",aliases:["sample requests","samples","sample tracking"],fields:[company,field("buyer","Buyer"),field("product","Product"),field("quantity","Quantity","number"),field("sent","Sent on","date"),field("followup","Follow up on","date"),status(["Requested","Sent","Follow up","Converted","Closed"]),owner,notes]},
  {id:"follow-ups",name:"Buyer follow-ups",category:"Sales",description:"Keep each buyer's next action, owner and due date in one list.",aliases:["follow ups","followups","follow up","buyer follow ups","buyer followup"],fields:[company,field("buyer","Buyer"),field("phone","Phone"),field("next_action","Next action","text",true),field("due","Due date","date"),status(["To do","Waiting","Done"]),owner,notes]},
  {id:"returns",name:"Returns & credits",category:"Money",description:"Track return requests and credit decisions. Records do not issue a refund.",aliases:["returns","refunds","credits","return requests"],fields:[company,field("order","Order reference"),field("reason","Reason","text",true),field("amount","Requested credit (USD)","money"),status(["Requested","Approved","Received","Credit recorded","Declined"]),owner,notes]},
  {id:"deliveries",name:"Delivery tracking",category:"Operations",description:"Record promised deliveries, carriers and delivery confirmation.",aliases:["deliveries","delivery tracking","delivery"],fields:[company,field("order","Order reference"),field("due","Promised date","date"),field("carrier","Carrier"),field("tracking","Tracking number"),status(["Planned","Dispatched","Delivered","Issue"]),owner,notes]},
  {id:"promotions",name:"Promotions",category:"Marketing",description:"Plan offers, dates and budgets across bulk, stores and online.",aliases:["promotions","promos","promotional calendar"],fields:[field("campaign","Promotion","text",true),field("offer","Offer"),field("start","Start date","date"),field("end","End date","date"),field("budget","Budget (USD)","money"),status(["Draft","Scheduled","Running","Complete"]),owner,notes]},
  {id:"purchase-orders",name:"Purchase orders",category:"Operations",description:"Track supplier orders, expected arrivals and agreed costs.",aliases:["purchase orders","supplier orders","suppliers","purchasing"],fields:[field("supplier","Supplier","text",true),field("reference","PO number","text",true),field("expected","Expected date","date"),field("cost","Cost (USD)","money"),status(["Draft","Ordered","Part received","Received","Cancelled"]),owner,notes]},
  {id:"quality",name:"Quality & batch log",category:"Operations",description:"Keep batch references, best-before dates and quality observations.",aliases:["quality","batches","batch tracking","expiry","expiration","lot tracking"],fields:[field("batch","Batch / lot","text",true),field("product","Product","text",true),field("expiry","Best before","date"),status(["Pending check","Released","On hold","Closed"]),owner,notes]},
  {id:"tasks",name:"Team tasks",category:"Sales",description:"Assign work, set due dates and keep progress visible.",aliases:["tasks","task","to do list","todo","team tasks"],fields:[field("task","Task","text",true),owner,field("due","Due date","date"),status(["To do","In progress","Waiting","Done"]),notes]},
  {id:"commissions",name:"Sales commissions",category:"Money",description:"Record commission amounts and payment status. Enter approved amounts yourself.",aliases:["commissions","commission","sales reps"],fields:[field("rep","Sales rep","text",true),company,field("order","Order reference"),field("amount","Commission (USD)","money",true),field("due","Due date","date"),status(["Pending","Approved","Paid"]),notes]},
];
