import { expenseCommandInput } from "../expenses/accounting-model";
import { receivableCommandInput } from "../payments/receivable-model";
import { accountCommandInput } from "../accounting/account-model";
import { journalCommandInput } from "../accounting/journal-model";
import { reportQuery } from "../restaurant/report-model";
import { inspectionCommandInput } from "../auto-repair/inspection-model";
import { repairCommandInput } from "../auto-repair/model";
import { lookupInput } from "../vehicles/vpic";
import { vinApplyInput } from "../vehicles/service";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { diningCommandSchema } from "../restaurant/dining-model";
import { businessResources } from "./catalog";
import { trackerDefinitionSchema, channelSchema } from "../features/model";
import { commandSchema, resourceKinds } from "../shopify-backend/model";
import { saveRecordSchema, } from "../workspace/model";
import { scheduleCommandSchema } from "../timeclock/schedule-model";
import { restaurantCommandSchema } from "../restaurant/business";
import { transitionSchema } from "../workspace/store";

export type InvokeBackend = (operation: string, args?: Record<string, unknown>) => Promise<unknown>;
export function createBusinessMcp(invoke: InvokeBackend) {
  const server = new McpServer({ name: "shuug-business", version: "1.0.0" }, { instructions: "Shuug is a standalone business backend. Shopify is optional. Read capabilities and status first. Planned/demo business features retain their limitations. Queue receipts are not proof of an applied Shopify change; inspect the job. Keep money currencies and product units unchanged. Backend credentials authorize this client's whole workspace." });
  function tool(name: string, description: string, inputSchema: z.ZodRawShape, readOnly: boolean, operation = name) {
    server.registerTool(name, { description, inputSchema, annotations: { readOnlyHint: readOnly, destructiveHint: !readOnly, idempotentHint: readOnly || ["expense_command", "receivable_command", "account_command", "journal_command", "inspection_command", "repair_command", "vehicle_vin_apply", "dining_command", "schedule_command", "restaurant_command", "tracker_create", "tracker_save_record", "shopify_command", "shopify_configure"].includes(name), openWorldHint: name.startsWith("shopify_") || name === "vehicle_vin_lookup" } }, async (args) => {
      try { const data = await invoke(operation, args as Record<string, unknown>); return { content: [{ type: "text" as const, text: JSON.stringify(data) }] }; }
      catch (error) { return { isError: true, content: [{ type: "text" as const, text: error instanceof Error ? error.message : "Backend request failed." }] }; }
    });
  }
  tool("expense_catalog", "Read reviewed expense and bill posting, dated settlement, correction, bank return, void and bank/card transfer contracts. Read expense-accounting for saved receipts, balances, account classes and revisions.", {}, true);
  tool("expense_command", "Post reviewed expense or vendor-credit account allocations and actual dated settlements into a permanent ledger. Amounts and allocations use whole cents; foreign receipts require reviewed USD carrying values, and settlement differences require appropriate exchange gain/loss accounts. Corrections append entries, archives retain postings, and returned settlements preserve fees unless a verified fee refund is recorded. Reuse the exact requestId on retry. This records accounting evidence; it does not move funds or synchronize an external provider.", expenseCommandInput.shape, false);
  tool("receivable_catalog", "Read reviewed receipt, bank-return and collection-follow-up command contracts. Read receivables with business_read for current invoice balances, receipts and revisions.", {}, true);
  tool("receivable_command", "Record verified product-invoice receipts or bank-return events with actual dates, references, evidence and reviewed fees. These actions capture ledger entries atomically; returns retain original receipts and processing fees and reopen the amount due. Optional customer fees include explicitly reviewed tax and supporting basis. Use the same requestId and inputs on retry; duplicate references and excess allocations are rejected. Follow-up changes require a current revision; reminder.record logs a reminder actually made. This does not transfer money, send messages, refund a sale, charge a card or reconcile a bank feed.", receivableCommandInput.shape, false);
  tool("account_catalog", "Read account classifications and versioned account commands. Five hierarchy levels are supported. Read accounts with business_read for current revisions and history.", {}, true);
  tool("account_command", "Create or edit a reviewed accounting account. Reuse requestId on retry and supply the current revision (zero for creation). Parent and child classifications must match. System posting accounts retain classification and active status; used accounts retain classification. Inactive accounts preserve history and cannot receive new manual postings. This does not create a bank connection or migrate subledger balances.", accountCommandInput.shape, false);
  tool("journal_catalog", "Read the manual journal posting and reversal schemas. Read accounting-journal with business_read for current history. Full prior-period controls are not yet available.", {}, true);
  tool("journal_command", "Record a reviewed balanced manual journal or a dated reversal. Amounts are integer cents. Read journal_catalog and accounting-journal first. Preserve the requestId and exact input on retry; an entry can have only one direct reversal. Original postings and actor history are retained. This does not execute a payment or change an automatically generated source transaction.", journalCommandInput.shape, false);
  tool("business_capabilities", "Discover business modules, data limitations, HTTP resources and optional Shopify functions.", {}, true, "capabilities");
  tool("business_read", "Read an existing Shuug business module. Shopify snapshots use shopify_records.", { resource: z.enum(businessResources) }, true);
  tool("inspection_catalog", "Read versioned inspection checklist and assigned technician command contracts. Read auto-repair-inspections with business_read before making changes.", {}, true);
  tool("inspection_command", "Publish reusable inspection checklists, assign active employee logins to booked vehicle jobs, record assigned technician time/findings/photos, submit and review outcomes and labor cost. Read inspection_catalog first. Backend acts as owner; technician actions require the actual assignee. Reuse requestId and exact inputs on retry. Review preserves evidence and creates one approved costed time entry; customer sharing is explicit. This does not certify roadworthiness, authorize unagreed repairs, send messages or take payment.", inspectionCommandInput.shape, false);
  tool("repair_catalog", "Read versioned labor and parts pricing and reviewed estimate command contracts. Read auto-repair-pricing with business_read for current versions and vehicles.", {}, true);
  tool("repair_command", "Save, review, publish, retire or share repair pricing versions; calculate a vehicle estimate and create its reviewed service proposal. Money is integer currency cents; percentages use basis points. Read repair_catalog first. Costs and staff review notes are private. Reuse requestId and exact inputs on retry; edits require current revision. Estimate review proofs belong to this actor and expire in 15 minutes. Customer acceptance and billing use existing workflow tools. This does not reserve parts, post taxes, send messages or take payment.", repairCommandInput.shape, false);
  tool("vehicle_vin_lookup", "Send a complete VIN and optional known model year to NHTSA vPIC after explicit consent. Customer, plate, mileage and notes are not sent. Read vehicles first to choose an existing record. Results require review; provider errors cannot be applied automatically.", lookupInput.shape, true);
  tool("vehicle_vin_apply", "Apply a clean VIN lookup after comparing it with the vehicle and choosing a service client. Use the actor-bound proof within 15 minutes and reuse the exact requestId on retry. Newer edits are never overwritten. Saving retains review evidence; it does not establish ownership, condition or recall clearance.", vinApplyInput.shape, false);
  tool("dining_catalog", "Read restaurant reservation, opening hours and floor command contracts. Read restaurant-dining with business_read before editing.", {}, true);
  tool("dining_command", "Publish restaurant booking hours, edit reservations, record arrivals, wait quotes, seating and visit completion. Read dining_catalog first. Use current revisions and reuse requestId on retry. Staff reservations may be scheduled outside website hours; table conflicts still apply. This does not send guest messages.", diningCommandSchema.shape, false);
  tool("schedule_catalog", "Read staff scheduling, time-away and attendance command contracts. Personal actions affect only the authenticated actor; backend credentials act as the workspace owner.", {}, true);
  tool("schedule_command", "Manage draft/published shifts, conflicts, time-away reviews and audited attendance corrections. Read schedule_catalog first and staff-schedule via business_read. Reuse the exact requestId on retry. This does not run payroll or send employee messages.", scheduleCommandSchema.shape, false);
  tool("restaurant_report", "Read aggregate restaurant sales patterns for optional inclusive business dates from/to (at most 366 days). Compare per reviewed open_hour (default) or open_day. Reports expose coverage, ties and missing hours, not customer details. Date-range comparisons are descriptive and do not establish campaign causation. Use hours.review via restaurant_command to record opening-time evidence without changing closed books.", reportQuery.shape, true);
  tool("restaurant_catalog", "Read validated restaurant command inputs before using restaurant_command. Money is integer USD cents; ingredient quantities use g, ml or each. Read restaurant and restaurant-accounting through business_read.", {}, true);
  tool("restaurant_command", "Apply a restaurant menu/options, guest credit/refund, stocktake, special, stock, order, kitchen or bookkeeping action. Menu option IDs resolve to server-owned prices and ingredient adjustments; repeated menu items with different choices have distinct check-line IDs. Use lineId when crediting a repeated item. Credits create the reviewed guest balance; refund.record records a verified return to an original payment and does not send money. Physical counts capture lot observations and require explicit submission and reviewed posting; changed stock requires a recount. Specials use reviewed schedules, menu eligibility, discount budgets and redemption caps. Read restaurant_catalog first. Reuse the exact requestId and inputs on retry; edits use current revision. All stock and ledger changes commit together. Tender and bill actions record externally verified transactions; they do not charge cards, pay suppliers, buy advertising or send messages. Staff must review allergens, tax and financial evidence.", restaurantCommandSchema.shape, false);
  tool("workflow_catalog", "Read service and nonprofit record schemas, fields, permissions and allowed transitions.", {}, true);
  tool("workflow_records", "Read durable service and nonprofit records. The backend credential authorizes the whole client workspace, including confidential participant records.", { kind: z.string().max(50).optional() }, true);
  tool("workflow_save", "Create or edit a distinct business record. Reuse requestId for an exact creation retry. Updates require the latest revision. Financial and approved records have restricted edits.", saveRecordSchema.shape, false);
  tool("workflow_transition", "Apply a validated workflow step. Reuse the exact commandId for retries. Payment confirmation records evidence of an external transaction; it does not charge a card or send a message.", transitionSchema.shape, false);
  tool("trackers_list", "Read persistent custom business trackers and their records.", {}, true);
  tool("tracker_create", "Create a persistent business tracker. Reuse requestId for an exact retry.", { requestId: z.uuid(), definition: trackerDefinitionSchema }, false);
  tool("tracker_save_record", "Create or update a tracker record with revision checking. Revision zero creates; updates use the last observed revision.", { trackerId: z.uuid(), id: z.uuid(), revision: z.number().int().nonnegative(), channel: channelSchema, values: z.record(z.string(), z.union([z.string(), z.number(), z.boolean()])) }, false);
  tool("shopify_status", "Check whether a client enabled Shopify, connection state, sync cursors and queue counts. Works without a store.", {}, true);
  tool("shopify_configure", "Enable or disable the optional Shopify connector. Enable writes only when the client wants Shuug to send product or inventory changes; reconnect to approve required scopes.", { enabled: z.boolean(), writesEnabled: z.boolean().default(false) }, false);
  tool("shopify_records", "Read durable Shopify products, customers, orders or inventory with cursor pagination and original values.", { kind: z.enum(resourceKinds), limit: z.number().int().min(1).max(250).default(100), after: z.string().max(250).default("") }, true);
  tool("shopify_jobs", "List recent delivery and command receipts. Uncertain writes need reconciliation.", {}, true);
  tool("shopify_job", "Inspect one delivery or command, including its result. Data-request exports require owner delivery to the requester.", { id: z.uuid() }, true);
  tool("shopify_tick", "Process one queued job or one reconciliation page. The supervised worker normally runs this.", {}, false);
  tool("shopify_reconcile", "Schedule a fresh paginated Shopify reconciliation. The worker processes it incrementally.", {}, false);
  tool("shopify_command", "Queue a product title/description update, variant price, or an inventory count with compare-and-set. Requires enabled writes. Reuse the idempotencyKey for retries and poll the returned job.", { idempotencyKey: z.uuid(), command: commandSchema }, false);
  tool("shopify_resolve", "Release an uncertain write ONLY after its outcome was checked in Shopify. Records the reconciliation note; it does not resend the write.", { id: z.uuid(), note: z.string().trim().min(10).max(1000) }, false);
  server.registerResource("business-capabilities", "shuug://capabilities", { description: "Available business modules and provider boundaries", mimeType: "application/json" }, async uri => ({ contents: [{ uri: uri.href, mimeType: "application/json", text: JSON.stringify(await invoke("capabilities")) }] }));
  return server;
}
