"use client";
import Link from "next/link";
import { expenseOutstanding } from "@/lib/expenses/accounting-model";
import { ExpenseAccountingPanel } from "./ExpenseAccountingPanel";
import type { WorkspaceAccount } from "@/lib/accounting/account-model";
import { useRef, useState } from "react";
import { archiveExpenseAction, refreshExpensesAction, saveExpenseAction } from "@/app/expenses/actions";
import { blankExpense, CATEGORIES, CURRENCIES, decimalCents, expensesCsv, money, signedAmount, type Expense, type ExpenseFields } from "@/lib/expenses/model";
import { useSalesChannel } from "../WorkspaceShell";

const button="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-medium text-slate-700 shadow-sm hover:bg-slate-50 disabled:opacity-50";
const primary="rounded-lg bg-[#2d4b3d] px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-emerald-900 disabled:opacity-50";
const input="mt-1.5 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900";
export function downloadFile(name:string,text:string,type="application/json") {const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

export function ExpensesWorkspace({initial,today,canEdit=false,accounts=[]}:{initial:Expense[];today:string;canEdit?:boolean;accounts?:WorkspaceAccount[]}) {
  const [rows,setRows]=useState(initial),[selected,setSelected]=useState<Expense|null|undefined>(undefined),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[search,setSearch]=useState("");
  const [status,setStatus]=useState("active"),[category,setCategory]=useState("all"),[from,setFrom]=useState(""),[to,setTo]=useState("");
  const files=useRef<HTMLInputElement>(null),camera=useRef<HTMLInputElement>(null);const {channel}=useSalesChannel();
  const matchesChannel=(r:Expense)=>channel==="all"||r.fields.channel===channel||r.fields.channel==="shared";
  const statusMatches=(r:Expense)=>status==="outstanding"?!!r.accounting&&expenseOutstanding(r.accounting).amountCents>0:status==="unposted"?!r.accounting&&(r.status==="recorded"||r.archivedFrom==="recorded"):status==="posted"?r.accounting?.status==="posted":status==="active"?r.status!=="archived":r.status===status;
  const visible=rows.filter(r=>matchesChannel(r)&&statusMatches(r)&&(category==="all"||r.fields.category===category)&&(!from||r.fields.date>=from)&&(!to||r.fields.date<=to)&&`${r.fields.merchant} ${r.fields.reference} ${r.fields.notes} ${r.receipt?.text??""} ${r.receipt?.name??""}`.toLowerCase().includes(search.toLowerCase()));
  const totals=CURRENCIES.map(currency=>({currency,total:visible.filter(r=>r.status==="recorded"&&r.fields.currency===currency).reduce((n,r)=>n+signedAmount(r.fields),0)})).filter(r=>visible.some(x=>x.status==="recorded"&&x.fields.currency===r.currency));
  function upsert(row:Expense){setRows(old=>[row,...old.filter(r=>r.id!==row.id)].sort((a,b)=>b.fields.date.localeCompare(a.fields.date)));}
  async function upload(list:FileList|File[]|null) {
    if(!list?.length||busy||!canEdit)return;
    if(list.length>20){setNotice("Upload up to 20 receipts at a time.");return;}
    setBusy(true);let last:Expense|undefined;const messages:string[]=[];
    try {for(const file of Array.from(list)) {
      setNotice(`Reading ${file.name}… Original files stay with your expense records.`);
      if(file.size>10*1024*1024){messages.push(`${file.name}: over the 10 MB limit.`);continue;}
      const form=new FormData();form.set("file",file);
      try {const response=await fetch("/api/receipts/upload",{method:"POST",body:form});const result=await response.json();if(!response.ok||!result.expense)throw new Error(result.error||"Upload failed.");last=result.expense;upsert(result.expense);messages.push(result.duplicate?`${file.name}: already saved; opened the existing record.`:`${file.name}: saved for review.`);}
      catch(e){messages.push(`${file.name}: ${e instanceof Error?e.message:"Upload failed."}`);}
    }}finally{setBusy(false);if(last)setSelected(last);setNotice(messages.join(" "));if(files.current)files.current.value="";if(camera.current)camera.current.value="";}
  }
  async function refresh(){setBusy(true);try{setRows(await refreshExpensesAction());setNotice("Expense history refreshed.");}catch{setNotice("History could not refresh. Try again.");}finally{setBusy(false);}}
  return <div className="space-y-6">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="mb-1 text-xs font-medium uppercase tracking-widest text-slate-400">Money</p><h1 className="text-2xl font-bold tracking-tight text-slate-900">Expenses & receipts</h1><p className="mt-2 text-sm text-slate-500">A photo, a quick review, a record you can find later.</p></div><div className="flex gap-2"><Link className={button} href="/calendar">Business calendar →</Link>{selected===undefined&&<button className={primary} disabled={busy||!canEdit} onClick={()=>{setSelected(null);setNotice("");}}>+ Add expense</button>}</div></header>
    {notice&&<p role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900">{notice}</p>}
    {selected!==undefined?<ExpenseEditor key={selected?.id??"new"} expense={selected} today={today} canEdit={canEdit} accounts={accounts} saved={r=>{upsert(r);setSelected(r);setNotice(r.status==="archived"?"Expense archived. The original and change history are retained.":r.status==="recorded"?"Expense recorded. Your calendar totals are updated.":"Draft saved. It will count toward expenses after you review and record it.");}} close={()=>setSelected(undefined)} />:<>
      <section className="grid gap-4 lg:grid-cols-[1.5fr_1fr]">
        <div onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void upload(e.dataTransfer.files);}} className="rounded-2xl border-2 border-dashed border-emerald-200 bg-[#f0f6ed] p-6">
          <div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-white text-2xl text-emerald-800" aria-hidden>▤</span><div><h2 className="font-semibold text-slate-900">Drop your receipts here</h2><p className="mt-1 text-sm text-slate-500">Photos and PDFs · up to 10 MB each · 20 at a time</p></div></div>
          <div className="mt-5 flex flex-wrap gap-2"><button className={primary} disabled={busy||!canEdit} onClick={()=>files.current?.click()}>{busy?"Reading receipts…":"Upload receipts"}</button><button className={button} disabled={busy||!canEdit} onClick={()=>camera.current?.click()}>Take a photo</button></div>
          <input aria-label="Upload receipt files" ref={files} hidden type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif,application/pdf,.heic,.heif" multiple onChange={e=>void upload(e.target.files)}/><input aria-label="Take receipt photo" ref={camera} hidden type="file" accept="image/*" capture="environment" onChange={e=>void upload(e.target.files)}/>
          <p className="mt-4 text-xs leading-5 text-slate-500">Original files are saved with searchable text. Check the merchant, date, currency and total before recording. PDF text reading covers the first three pages.</p>
        </div>
        <div className="grid grid-cols-2 gap-3"><div className="rounded-xl border border-slate-200 bg-white p-5"><p className="text-xs text-slate-500">Needs review</p><p className="mt-2 text-3xl font-semibold">{rows.filter(r=>r.status==="draft"&&matchesChannel(r)).length}</p><button className="mt-4 text-xs font-semibold text-emerald-700" onClick={()=>{setStatus("draft");setFrom("");setTo("");}}>Review receipts →</button></div><div className="rounded-xl border border-slate-200 bg-white p-5"><p className="text-xs text-slate-500">Recorded total in this view</p>{totals.length?totals.map(r=><p key={r.currency} className="mt-2 text-lg font-semibold tabular-nums">{money(r.total,r.currency)} <span className="text-[10px] font-normal text-slate-400">{r.currency}</span></p>):<p className="mt-2 text-2xl font-semibold">—</p>}<p className="mt-3 text-xs leading-5 text-slate-400">Receipt totals less refunds, including recorded tax.</p></div></div>
      </section>
      <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
        <div className="mb-4 flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold">Your expense history</h2><button className={button} onClick={()=>{setStatus("outstanding");setFrom("");setTo("");}}>Unsettled bills &amp; credits</button><div className="flex gap-2"><button className={button} disabled={busy} onClick={()=>void refresh()}>Refresh</button><button className={button} disabled={!visible.length} onClick={()=>downloadFile(`expenses-${today}.csv`,expensesCsv(visible),"text/csv;charset=utf-8")}>Export CSV</button></div></div>
        <div className="mb-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><label className="text-xs text-slate-500">Search receipts<input className={input} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Merchant, note, receipt text…"/></label><label className="text-xs text-slate-500">Status<select className={input} value={status} onChange={e=>setStatus(e.target.value)}><option value="active">All active</option><option value="unposted">Needs ledger review</option><option value="posted">Posted to ledger</option><option value="outstanding">Unsettled bills &amp; credits</option><option value="draft">Needs review</option><option value="recorded">Recorded</option><option value="archived">Archived</option></select></label><label className="text-xs text-slate-500">Category<select className={input} value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All categories</option>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label><label className="text-xs text-slate-500">From<input className={input} type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="text-xs text-slate-500">Through<input className={input} type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div>
        {channel!=="all"&&<p className="mb-3 text-xs text-slate-500">Includes shared business expenses. Shared costs stay separate from channel margins in the calendar.</p>}
        <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-xs text-slate-400">{["Date","Merchant / receipt","Category","Status","Total","Ledger / balance", ""].map((x,i)=><th key={i} className="px-2 py-3 font-medium">{x}</th>)}</tr></thead><tbody>{visible.map(r=><tr key={r.id} className="border-b border-slate-100 last:border-0"><td className="whitespace-nowrap px-2 py-4 text-slate-500">{r.fields.date}</td><td className="max-w-[250px] px-2 py-4"><button className="font-semibold text-slate-800 hover:text-emerald-700" onClick={()=>setSelected(r)}>{r.fields.merchant||"Receipt awaiting review"}</button><p className="mt-1 truncate text-xs text-slate-400">{r.receipt?.name||r.fields.reference||"Manual entry"}</p></td><td className="px-2 py-4 text-slate-500">{r.fields.category}</td><td className="px-2 py-4"><span className={`rounded-full px-2 py-1 text-xs ${r.status==="draft"?"bg-amber-50 text-amber-800":r.status==="recorded"?"bg-emerald-50 text-emerald-800":"bg-slate-100 text-slate-500"}`}>{r.status==="draft"?"Needs review":r.status}</span>{r.fields.paymentStatus==="unpaid"&&<p className="mt-1 text-xs text-slate-400">Unpaid</p>}</td><td className="whitespace-nowrap px-2 py-4 text-right font-medium tabular-nums">{r.fields.amountCents===null?"—":money(signedAmount(r.fields),r.fields.currency)}<span className="ml-1 text-[10px] text-slate-400">{r.fields.currency}</span></td><td className="px-2 py-4 text-xs">{r.accounting?<><p>{r.accounting.status}</p>{r.accounting.mode==="bill"&&r.accounting.status==="posted"&&<><p>{r.fields.kind==="refund"?"Credit owed":"Bill due"}: {money(expenseOutstanding(r.accounting).amountCents,r.fields.currency)}</p><p>Due {r.accounting.dueDate}</p></>}</>:r.status==="draft"?"Document review":"Needs ledger review"}</td><td className="px-2 py-4 text-right"><button className="text-xs font-semibold text-emerald-700" onClick={()=>setSelected(r)}>{r.status==="draft"?"Review →":"Open →"}</button></td></tr>)}</tbody></table></div>
        {!visible.length&&<div className="py-12 text-center"><p className="font-medium text-slate-700">{rows.length?"No receipts match these filters.":"Your first receipt starts your expense history."}</p><p className="mt-2 text-sm text-slate-400">Upload a photo or add an expense by hand.</p></div>}
      </section>
    </>}
  </div>;
}

function ExpenseEditor({expense,today,saved,close,canEdit,accounts}:{expense:Expense|null;today:string;saved:(r:Expense)=>void;close:()=>void;canEdit:boolean;accounts:WorkspaceAccount[]}) {
  const [row,setRow]=useState(expense),[fields,setFields]=useState<ExpenseFields>(expense?.fields??blankExpense(today)),[amount,setAmount]=useState(expense?.fields.amountCents===null||!expense?"":(expense.fields.amountCents/100).toFixed(2)),[tax,setTax]=useState(expense?.fields.taxCents==null?"":(expense.fields.taxCents/100).toFixed(2));
  const [busy,setBusy]=useState(false),[error,setError]=useState(""),[duplicate,setDuplicate]=useState(false),[dirty,setDirty]=useState(false);
  const archived=row?.status==="archived";
  const change=<K extends keyof ExpenseFields>(key:K,value:ExpenseFields[K])=>{setFields(f=>({...f,[key]:value}));setDirty(true);setDuplicate(false);};
  async function save(status:"draft"|"recorded") {
    setBusy(true);setError("");try {
      const result=await saveExpenseAction({id:row?.id,revision:row?.revision,fields:{...fields,amountCents:decimalCents(amount),taxCents:decimalCents(tax)},status,confirmDuplicate:duplicate});
      if(!result.ok)throw new Error(result.error);if(!result.expense){setDuplicate(true);setError("A recorded expense has the same merchant, date and total. Check your history. If this is a separate purchase, choose Record separate purchase.");return;}
      setRow(result.expense);setDirty(false);setDuplicate(false);saved(result.expense);
    }catch(e){setError(e instanceof Error?e.message:"Expense could not be saved.");}finally{setBusy(false);}
  }
  async function archive(){if(!row)return;setBusy(true);setError("");try{const result=await archiveExpenseAction(row.id,row.revision,archived);if(!result.ok)throw new Error(result.error);setRow(result.expense);setDirty(false);saved(result.expense);}catch(e){setError(e instanceof Error?e.message:"Update failed.");}finally{setBusy(false);}}
  const receipt=row?.receipt;
  return <div className="space-y-4"><button disabled={busy} className="text-sm font-medium text-emerald-800" onClick={()=>{if(!dirty||window.confirm("Discard unsaved edits to this expense?"))close();}}>← All expenses</button><div className="grid items-start gap-5 xl:grid-cols-[1fr_1.1fr]">
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-100 p-4"><h2 className="font-semibold">Original receipt</h2>{receipt&&<a className="text-xs font-medium text-emerald-700" href={`/api/receipts/${row!.id}?download=1`}>Download original</a>}</div>{receipt?<>
      <div className="flex min-h-[300px] items-center justify-center bg-[#e8ece8] p-4">{receipt.extension==="pdf"?<iframe title="Original receipt PDF" src={`/api/receipts/${row!.id}`} className="h-[560px] w-full rounded bg-white"/>:receipt.extension==="heic"?<div className="p-8 text-center"><p className="font-medium">HEIC photo saved</p><a className="mt-3 inline-block text-sm text-emerald-700 underline" href={`/api/receipts/${row!.id}?download=1`}>Open the original photo</a></div>:
      // eslint-disable-next-line @next/next/no-img-element -- private authenticated original; never send a receipt to an image optimizer.
      <img src={`/api/receipts/${row!.id}`} alt="Uploaded business receipt" className="max-h-[560px] max-w-full rounded object-contain shadow-sm"/>}</div>
      <div className="p-4"><p className="break-all text-xs text-slate-500">{receipt.name} · {(receipt.bytes/1024).toFixed(0)} KB</p><p className="mt-2 text-sm text-slate-600">{receipt.message}</p>{receipt.text&&<details className="mt-4"><summary className="cursor-pointer text-xs font-semibold text-emerald-700">View extracted receipt text</summary><pre className="mt-3 max-h-64 overflow-auto whitespace-pre-wrap rounded bg-slate-50 p-3 text-xs text-slate-600">{receipt.text}</pre></details>}</div>
    </>:<div className="px-6 py-20 text-center"><p className="font-medium text-slate-600">Manual expense</p><p className="mt-2 text-sm text-slate-400">No receipt attached. To read a receipt photo, return to All expenses and upload it.</p></div>}</section>
    <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-semibold">{archived?"Archived expense":row?.status==="recorded"?"Expense details":"Review receipt details"}</h2><span className="rounded-full bg-slate-100 px-3 py-1 text-xs text-slate-600">{row?.status??"New"}</span></div>
      {error&&<p role="alert" className="mb-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">{error}</p>}
      <form onSubmit={e=>{e.preventDefault();void save("recorded");}}><fieldset disabled={busy||archived||!canEdit||!!row?.accounting} className="grid gap-4 sm:grid-cols-2">
        <label className="text-xs font-medium text-slate-600 sm:col-span-2">Merchant / business<input className={input} required maxLength={160} value={fields.merchant} onChange={e=>change("merchant",e.target.value)} placeholder="Where did you spend it?"/></label>
        <label className="text-xs font-medium text-slate-600">Receipt date<input className={input} type="date" min="1900-01-01" max="2199-12-31" required value={fields.date} onChange={e=>change("date",e.target.value)}/></label>
        <label className="text-xs font-medium text-slate-600">Currency<select className={input} value={fields.currency} onChange={e=>change("currency",e.target.value as ExpenseFields["currency"])}>{CURRENCIES.map(c=><option key={c}>{c}</option>)}</select></label>
        <label className="text-xs font-medium text-slate-600">Receipt total (including tax)<input className={input} required inputMode="decimal" value={amount} onChange={e=>{setAmount(e.target.value);setDirty(true);setDuplicate(false);}} placeholder="0.00"/></label>
        <label className="text-xs font-medium text-slate-600">Tax included (optional)<input className={input} inputMode="decimal" value={tax} onChange={e=>{setTax(e.target.value);setDirty(true);}} placeholder="0.00"/></label>
        <label className="text-xs font-medium text-slate-600">Category<select className={input} value={fields.category} onChange={e=>{change("category",e.target.value as ExpenseFields["category"]);if(e.target.value==="Inventory & ingredients")change("treatment","inventory");else if(e.target.value==="Equipment")change("treatment","asset");}}>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label>
        <label className="text-xs font-medium text-slate-600">Sales channel<select className={input} value={fields.channel} onChange={e=>change("channel",e.target.value as ExpenseFields["channel"])}><option value="shared">Shared business expense</option><option value="bulk">Bulk</option><option value="stores">Stores</option><option value="online">Online</option></select></label>
        <label className="text-xs font-medium text-slate-600 sm:col-span-2">How it counts in reports<select className={input} value={fields.treatment} onChange={e=>change("treatment",e.target.value as ExpenseFields["treatment"])}><option value="operating">Operating expense — subtract from contribution</option><option value="inventory">Inventory purchase — product cost is counted when sold</option><option value="asset">Equipment / asset — keep separate from contribution</option><option value="transfer">Transfer / card payment — keep separate from expenses</option></select></label>
        <label className="text-xs font-medium text-slate-600">Entry type<select className={input} value={fields.kind} onChange={e=>change("kind",e.target.value as ExpenseFields["kind"])}><option value="expense">Purchase / expense</option><option value="refund">Expense refund / credit</option></select></label>
        <label className="text-xs font-medium text-slate-600">Payment status<select className={input} value={fields.paymentStatus} onChange={e=>change("paymentStatus",e.target.value as ExpenseFields["paymentStatus"])}><option value="paid">Paid</option><option value="unpaid">Unpaid / payable</option></select></label>
        <label className="text-xs font-medium text-slate-600">Paid with (optional)<input className={input} maxLength={80} placeholder="Business card •1234" value={fields.paymentMethod} onChange={e=>change("paymentMethod",e.target.value)}/></label>
        <label className="text-xs font-medium text-slate-600">Receipt / invoice number<input className={input} maxLength={120} value={fields.reference} onChange={e=>change("reference",e.target.value)}/></label>
        <label className="text-xs font-medium text-slate-600 sm:col-span-2">Business purpose / notes<textarea className={input} rows={3} maxLength={5000} value={fields.notes} onChange={e=>change("notes",e.target.value)} placeholder="What was this for?"/></label>
      </fieldset><p className="mt-4 text-xs leading-5 text-slate-400">Saving records the receipt details. Review Bill and payment accounting below to post account allocations and actual dated settlements to Shuug’s ledger. External accounting connections are separate.</p>
      {!archived&&canEdit&&!row?.accounting&&<div className="mt-5 flex flex-wrap gap-2"><button type="submit" className={primary} disabled={busy}>{busy?"Saving…":duplicate?"Record separate purchase":row?.status==="recorded"?"Save changes":"Record expense"}</button>{row?.status!=="recorded"&&<button type="button" className={button} disabled={busy} onClick={()=>void save("draft")}>Save draft</button>}</div>}</form>
      {row?.accounting&&canEdit&&!archived&&<form className="mt-5 space-y-3 rounded-lg border p-4" onSubmit={e=>{e.preventDefault();void save("recorded");}}><fieldset disabled={busy} className="space-y-3"><label className="block text-sm">Receipt notes<textarea className={input} rows={3} value={fields.notes} maxLength={5000} onChange={e=>change("notes",e.target.value)}/></label><label className="block text-sm">Expense channel<select className={input} value={fields.channel} onChange={e=>change("channel",e.target.value as ExpenseFields["channel"])}><option value="shared">Shared</option><option value="bulk">Bulk</option><option value="stores">Stores</option><option value="online">Online</option></select></label><button className={button} disabled={!dirty||busy}>Save receipt notes and channel</button></fieldset></form>}
      {row&&<ExpenseAccountingPanel key={`accounting:${row.revision}`} row={row} accounts={accounts} today={today} disabled={!canEdit||busy||dirty} saved={r=>{setRow(r);setFields(r.fields);setAmount(r.fields.amountCents===null?"":(r.fields.amountCents/100).toFixed(2));setTax(r.fields.taxCents===null?"":(r.fields.taxCents/100).toFixed(2));setDirty(false);saved(r);}}/>}
      {row&&<div className="mt-5 flex flex-wrap gap-4 border-t border-slate-100 pt-4"><button className="text-xs font-medium text-slate-500" disabled={busy||dirty||!canEdit} onClick={()=>void archive()}>{archived?"Restore expense":"Archive expense"}</button><button className="text-xs font-medium text-emerald-700" onClick={()=>downloadFile(`expense-${row.fields.date}-${row.id.slice(0,8)}.json`,JSON.stringify(row,null,2))}>Download digital record</button><Link className="text-xs font-medium text-emerald-700" href={`/calendar?date=${row.fields.date}&view=day`}>View this day →</Link></div>}
      {!!row?.history.length&&<details className="mt-5"><summary className="cursor-pointer text-xs font-semibold text-slate-600">Change history · {row.history.length} saved versions</summary><ol className="mt-3 space-y-3">{[...row.history].reverse().map(h=><li className="rounded-lg bg-slate-50 p-3 text-xs" key={h.revision}><p className="font-medium">{h.action} · version {h.revision}</p><p className="mt-1 text-slate-400">{new Date(h.at).toLocaleString()} · {h.fields.merchant||"No merchant"} · {h.fields.amountCents===null?"No total":money(signedAmount(h.fields),h.fields.currency)}</p><details className="mt-2"><summary className="cursor-pointer text-slate-500">Saved details</summary><pre className="mt-2 overflow-auto whitespace-pre-wrap text-[11px]">{JSON.stringify(h.fields,null,2)}</pre></details></li>)}</ol></details>}
    </section>
  </div></div>;
}
