"use client";
import { useRef, useState } from "react";
import type { diningManagementData } from "@/lib/restaurant/dining";
import type { DiningSettings as Settings } from "@/lib/restaurant/dining-model";
const days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"], field = "dd-input mt-1 block w-full";
const window = () => ({ start: "17:00", end: "22:00", overnight: false });
export function DiningSettings({ initial, canConfigure }: { initial: ReturnType<typeof diningManagementData>; canConfigure: boolean }) {
  const [data, setData] = useState(initial), [settings, setSettings] = useState(initial.settings), [busy, setBusy] = useState(false), [message, setMessage] = useState(""); const requests = useRef(new Map<string, string>());
  const set = <K extends keyof Settings>(key: K, value: Settings[K]) => setSettings(s => ({ ...s, [key]: value }));
  async function save() {
    const input = { ...settings, origins: settings.origins.map(v => v.trim()).filter(Boolean) };
    const key = JSON.stringify(input), requestId = requests.current.get(key) ?? crypto.randomUUID(); requests.current.set(key, requestId); setBusy(true); setMessage("");
    try { const response = await fetch("/api/restaurant/dining", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ requestId, action: "settings.save", input }) }), result = await response.json(); if (!response.ok) throw new Error(result.error); setData(result.data); setSettings(result.data.settings); requests.current.delete(key); setMessage("Reservation hours and booking rules saved."); } catch (e) { setMessage(e instanceof Error ? e.message : "Could not save. Retry to check the original request."); } finally { setBusy(false); }
  }
  return <div className="space-y-5"><p className="text-sm">All seating times use <strong>{data.timezone}</strong>. Set the restaurant timezone in <a className="underline" href="/restaurant/manage?tab=settings">restaurant settings</a> before accepting reservations.</p><p className="flex flex-wrap gap-4 text-sm"><a className="underline" href="/restaurant">Open floor and waitlist</a><a className="underline" href="/api/website/reservations" target="_blank" rel="noreferrer">Open customer reservations</a></p><p className="text-sm">In WordPress, select <strong>Reserve a restaurant table</strong> and add <code>[shuug_restaurant_booking]</code>. Other sites can link to the customer reservation page or embed it after their exact HTTPS origin is allowed below.</p>{message && <p role="status" className="rounded-lg border bg-white p-3">{message}</p>}{!canConfigure && <p>Only the workspace owner can change public reservation rules.</p>}
    <form className="space-y-5" onSubmit={e => { e.preventDefault(); void save(); }}><fieldset disabled={busy || !canConfigure} className="space-y-5"><section className="dd-card space-y-4"><h2 className="text-xl font-semibold">Website access and tables</h2><label className="flex gap-2"><input type="checkbox" checked={settings.enabled} onChange={e => set("enabled", e.target.checked)}/>Accept confirmed website reservations</label><label className="block text-sm">Guest instructions and restaurant contact details<textarea className={field} value={settings.instructions} onChange={e => set("instructions", e.target.value)} minLength={10} maxLength={2000} required/></label><label className="block text-sm">Allowed embed origins, one exact HTTPS origin per line<textarea className={field} value={settings.origins.join("\n")} onChange={e => set("origins", e.target.value.split("\n"))} placeholder="https://www.yourrestaurant.com"/></label><p className="text-sm">Choose which existing tables guests may reserve. Removing a table here preserves bookings already made.</p><div className="grid gap-2 sm:grid-cols-3">{data.tables.map(t => <label className="flex gap-2 rounded-lg border p-3 text-sm" key={t.id}><input type="checkbox" checked={settings.tableIds.includes(t.id)} onChange={e => set("tableIds", e.target.checked ? [...settings.tableIds, t.id] : settings.tableIds.filter(id => id !== t.id))}/>{t.name} · {t.seats} seats · {t.area}</label>)}</div>{!data.tables.length && <p>Add actual tables on the floor screen first.</p>}</section>
      <section className="dd-card space-y-4"><h2 className="text-xl font-semibold">Seating and arrival rules</h2><div className="grid gap-4 sm:grid-cols-3">{([ ["turnMinutes", "Seating duration (minutes)", 15, 360], ["bufferMinutes", "Cleanup buffer (minutes)", 0, 120], ["leadMinutes", "Minimum booking notice (minutes)", 0, 1440], ["horizonDays", "How many days ahead guests may book", 1, 180], ["maxPartySize", "Maximum online party size", 1, 50], ["maxArrivingCovers", "Maximum arriving guests per interval", 1, 500], ["changeLeadMinutes", "Online change/cancellation cutoff (minutes before visit)", 0, 10080] ] as const).map(([key, label, min, max]) => <label className="text-sm" key={key}>{label}<input className={field} type="number" min={min} max={max} value={settings[key]} onChange={e => set(key, Number(e.target.value))} required/></label>)}<label className="text-sm">Seating interval<select className={field} value={settings.intervalMinutes} onChange={e => set("intervalMinutes", e.target.value as Settings["intervalMinutes"])}>{["15", "30", "60"].map(v => <option key={v} value={v}>{v} minutes</option>)}</select></label></div><p className="text-sm">The seating and buffer must fit before the service window ends. Existing reservations retain their captured duration and guest change policy when these defaults change.</p></section>
      <section className="dd-card space-y-4"><h2 className="text-xl font-semibold">Weekly service hours</h2><p className="text-sm">Add separate lunch and dinner windows when needed. Check “Ends next day” for service past midnight.</p>{settings.weekly.map((w, i) => <div className="grid items-end gap-3 rounded-lg border p-3 sm:grid-cols-5" key={i}><label className="text-sm">Weekday<select className={field} value={w.weekday} onChange={e => set("weekly", settings.weekly.map((v, n) => n === i ? { ...v, weekday: Number(e.target.value) } : v))}>{days.map((day, n) => <option value={n} key={day}>{day}</option>)}</select></label><label className="text-sm">Service starts<input className={field} type="time" value={w.start} onChange={e => set("weekly", settings.weekly.map((v, n) => n === i ? { ...v, start: e.target.value } : v))} required/></label><label className="text-sm">Service ends<input className={field} type="time" value={w.end} onChange={e => set("weekly", settings.weekly.map((v, n) => n === i ? { ...v, end: e.target.value } : v))} required/></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={w.overnight} onChange={e => set("weekly", settings.weekly.map((v, n) => n === i ? { ...v, overnight: e.target.checked } : v))}/>Ends next day</label><button type="button" className="dd-secondary" onClick={() => set("weekly", settings.weekly.filter((_, n) => n !== i))}>Remove window</button></div>)}<button type="button" className="dd-secondary" disabled={settings.weekly.length >= 21} onClick={() => set("weekly", [...settings.weekly, { ...window(), weekday: 1 }])}>Add service window</button></section>
      <section className="dd-card space-y-4"><h2 className="text-xl font-semibold">Holidays and date overrides</h2><p className="text-sm">An exception replaces the normal windows starting on that date. Leaving it without windows closes that date to new arrivals. Existing reservations remain scheduled for staff review.</p>{settings.exceptions.map((exception, i) => <article className="space-y-3 rounded-lg border p-3" key={i}><div className="flex flex-wrap gap-3"><label className="text-sm">Exception date<input className={field} type="date" value={exception.date} onChange={e => set("exceptions", settings.exceptions.map((v, n) => n === i ? { ...v, date: e.target.value } : v))} required/></label><button type="button" className="dd-secondary self-end" onClick={() => set("exceptions", settings.exceptions.filter((_, n) => n !== i))}>Remove exception</button></div>{!exception.windows.length && <p className="text-sm">Closed to new arrivals on this date.</p>}{exception.windows.map((w, j) => <div key={j} className="flex flex-wrap gap-3"><label className="text-sm">Override starts<input className={field} type="time" value={w.start} onChange={e => set("exceptions", settings.exceptions.map((v, n) => n === i ? { ...v, windows: v.windows.map((x, m) => m === j ? { ...x, start: e.target.value } : x) } : v))} required/></label><label className="text-sm">Override ends<input className={field} type="time" value={w.end} onChange={e => set("exceptions", settings.exceptions.map((v, n) => n === i ? { ...v, windows: v.windows.map((x, m) => m === j ? { ...x, end: e.target.value } : x) } : v))} required/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={w.overnight} onChange={e => set("exceptions", settings.exceptions.map((v, n) => n === i ? { ...v, windows: v.windows.map((x, m) => m === j ? { ...x, overnight: e.target.checked } : x) } : v))}/>Ends next day</label><button type="button" className="dd-secondary self-end" onClick={() => set("exceptions", settings.exceptions.map((v, n) => n === i ? { ...v, windows: v.windows.filter((_, m) => m !== j) } : v))}>Remove override window</button></div>)}<button type="button" className="dd-secondary" disabled={exception.windows.length >= 3} onClick={() => set("exceptions", settings.exceptions.map((v, n) => n === i ? { ...v, windows: [...v.windows, window()] } : v))}>Add override window</button></article>)}<button type="button" className="dd-secondary" disabled={settings.exceptions.length >= 366} onClick={() => set("exceptions", [...settings.exceptions, { date: "", windows: [] }])}>Add closed date or override</button></section>
      <label className="flex gap-2 text-sm"><input type="checkbox" required/>I reviewed the timezone, tables, opening windows and guest instructions.</label><button className="dd-primary">Save reservation settings</button>
    </fieldset></form>
  </div>;
}
