"use client";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { reservationTransitions } from "@/lib/restaurant/transitions";
import type { Reservation, RestaurantTable } from "@/lib/restaurant/reservations";
import { instantsForLocal } from "@/lib/timeclock/zoned-time";
export function DiningVisitControls({ reservation: r, tables, disabled, timezone }: { reservation: Reservation; tables: RestaurantTable[]; disabled: boolean; timezone: string }) {
  const router = useRouter(), [busy, setBusy] = useState(false), [message, setMessage] = useState(""); const requests = useRef(new Map<string, string>());
  async function command(action: string, input: unknown) {
    const key = JSON.stringify({ action, input }), requestId = requests.current.get(key) ?? crypto.randomUUID(); requests.current.set(key, requestId); setBusy(true); setMessage("");
    try { const response = await fetch("/api/restaurant/dining", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ requestId, action, input }) }), result = await response.json(); if (!response.ok) throw new Error(result.error); requests.current.delete(key); router.refresh(); } catch (e) { setMessage(e instanceof Error ? e.message : "Could not save. Try the action again."); } finally { setBusy(false); }
  }
  const version = { id: r.id, revision: r.revision ?? 1 }, block = disabled || busy, field = "dd-input mt-1 block w-full";
  let occurrence = "first";
  try { if (r.startAt && instantsForLocal(`${r.dateISO}T${r.time}`, r.timezone ?? timezone)[1] === r.startAt) occurrence = "second"; } catch {}
  return <div className="mt-3 space-y-3">{message && <p role="status" className="text-sm text-red-800">{message}</p>}<div className="flex flex-wrap items-center gap-2 text-xs"><label>Table<select value={r.tableId ?? ""} disabled={block || !["requested", "confirmed", "waiting", "seated"].includes(r.status)} onChange={e => void command("visit.table", { ...version, tableId: e.target.value || null })} className="dd-input ml-2"><option value="">Unassigned</option>{tables.map(t => <option key={t.id} value={t.id}>{t.name} ({t.seats})</option>)}</select></label>{reservationTransitions[r.status].map(status => <button className="dd-secondary capitalize" key={status} disabled={block} onClick={() => void command(status === "waiting" ? "visit.arrive" : "visit.status", { ...version, ...(status === "waiting" ? {} : { status }) })}>{status === "waiting" ? "Guest arrived" : status.replace("-", " ")}</button>)}</div>
    {r.status === "waiting" && <form className="flex flex-wrap items-end gap-3" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void command("visit.quote", { ...version, quotedWaitMinutes: Number(f.get("wait")), host: String(f.get("host")) }); }}><label className="text-xs">Quoted wait (minutes)<input className={field} name="wait" type="number" min="0" max="240" defaultValue={r.quotedWaitMinutes ?? 15} required disabled={block}/></label><label className="text-xs">Host<input className={field} name="host" defaultValue={r.host} maxLength={100} required disabled={block}/></label><button className="dd-secondary" disabled={block}>Save quoted wait</button></form>}
    {["requested", "confirmed"].includes(r.status) && <details><summary className="cursor-pointer text-xs font-semibold">Edit or reschedule guest reservation</summary><p className="mt-2 text-xs">Times use {timezone}. Staff may schedule private events outside website service hours; table conflicts still apply.</p><form className="mt-3 grid gap-3 text-xs sm:grid-cols-2" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void command("reservation.save", { ...version, name: String(f.get("name")), phone: String(f.get("phone")), email: String(f.get("email")), notes: String(f.get("notes")), partySize: Number(f.get("partySize")), dateISO: String(f.get("date")), time: String(f.get("time")), occurrence: String(f.get("occurrence")), tableId: r.tableId, walkIn: false, quotedWaitMinutes: r.quotedWaitMinutes ?? null, host: r.host ?? "" }); }}><fieldset disabled={block} className="contents"><label>Guest name<input className={field} name="name" defaultValue={r.name} maxLength={120} required/></label><label>Party size<input className={field} name="partySize" type="number" min="1" max="50" defaultValue={r.partySize} required/></label><label>Visit date<input className={field} name="date" type="date" defaultValue={r.dateISO} required/></label><label>Seating time<input className={field} name="time" type="time" defaultValue={r.time} required/></label><label>Repeated hour when clocks go back<select className={field} name="occurrence" defaultValue={occurrence}><option value="first">First occurrence (usual default)</option><option value="second">Second occurrence</option></select></label><label>Phone<input className={field} name="phone" defaultValue={r.phone} maxLength={40}/></label><label>Email<input className={field} name="email" type="email" defaultValue={r.email ?? ""} maxLength={160}/></label><label>Notes<textarea className={field} name="notes" defaultValue={r.notes} maxLength={500}/></label><button className="dd-primary w-fit">Save guest reservation</button></fieldset></form></details>}
  </div>;
}
