"use client";
import { useState, type ReactNode } from "react";
import type { restaurantManagementData } from "@/lib/restaurant/management";
import { creditTaxDelta } from "@/lib/restaurant/credit-model";
type Finance = NonNullable<ReturnType<typeof restaurantManagementData>["financial"]>;
type Check = Finance["checks"][number];
type Command = (action: string, input: unknown) => Promise<boolean>;
const money = (v: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(v / 100);
const text = (f: FormData, key: string) => String(f.get(key) ?? "");
const cents = (v: string) => Math.round(Number(v) * 100);
const inputClass = "dd-input mt-1 block w-full";
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block text-sm">{label}{children}</label>; }
export function RestaurantCredits({ financial, command, disabled }: { financial: Finance; command: Command; disabled: boolean }) {
  const [selected, select] = useState("");
  const check = financial.checks.find(c => c.id === selected) ?? financial.checks.at(-1);
  return <div className="space-y-5"><section className="dd-card space-y-3"><h2 className="text-xl font-semibold">Guest credits and refunds</h2><p>A credit corrects the amount charged and records what the restaurant owes the guest. Record the refund only after the cash or card processor has actually returned the money.</p><p className="text-sm">Total refunds payable {money(financial.refundsPayable)} · Tips still held {money(financial.tipsPayable)}. Credits keep the original check, menu prices, tax and payments in history. Adjustments use the current open business day.</p><Field label="Check to review"><select className={inputClass} value={check?.id ?? ""} onChange={e => select(e.target.value)}><option value="" disabled>Choose check</option>{financial.checks.slice().reverse().map(c => <option value={c.id} key={c.id}>{c.ref} · {c.status} · Balance {money(c.balance.due)} · Refund owed {money(c.balance.refundDue)}</option>)}</select></Field></section>
    {check ? <section className="dd-card space-y-5"><h2 className="text-xl font-semibold">{check.ref} · {check.status}</h2><p>Original food {money(check.subtotal)} · Tax {money(check.tax)} · Check {money(check.total)} · Payments received {money(check.paid)}</p><p>Food credits {money(check.balance.foodCredit)} · Tax credits {money(check.balance.taxCredit)} · Tip credits {money(check.balance.tipCredit)}<br/><strong>Guest still owes {money(check.balance.due)} · Restaurant owes guest {money(check.balance.refundDue)}</strong> · Refunds recorded {money(check.balance.refunded)}</p>
      {["served", "closed", "cancelled"].includes(check.status) && <CreditForm key={`credit:${check.id}:${check.revision}`} check={check} command={command} disabled={disabled} tipsHeld={financial.tipsPayable}/>}
      {check.status === "fired" && check.paid > 0 && <CancelCreditForm key={`cancel:${check.id}:${check.revision}`} check={check} command={command} disabled={disabled}/>}
      {check.status === "fired" && !check.paid && <p>Cancel an unpaid check from Operations → Restaurant orders. Serve it before issuing a sale credit.</p>}
      {check.balance.refundDue > 0 && <RefundForm key={`refund:${check.id}:${check.revision}`} check={check} command={command} disabled={disabled}/>}
      <section className="space-y-3"><h3 className="text-lg font-semibold">Credit history</h3>{check.credits.map(c => <article key={c.id} className="rounded-lg border p-3"><strong>{c.reference} · {c.date} · {c.kind === "cancellation" ? "Paid cancellation" : "Reviewed credit"}</strong><p>{c.reason}</p>{c.lines.map(l => <p key={l.lineId ?? l.menuId}>{l.name} · {money(l.amount)}</p>)}<p className="text-sm">Food {money(c.subtotal)} · Tax {money(c.tax)} · Tips {money(c.tips)} · Cancelled deposit {money(c.deposit)}<br/>Reduced unpaid balance {money(c.receivableReduction)} · Added refund owed {money(c.refundLiability)} · Reviewed by {c.actor}</p></article>)}{!check.credits.length && <p>No credits issued.</p>}</section>
      <section className="space-y-3"><h3 className="text-lg font-semibold">Refund payment history</h3>{check.refunds.map(r => <article key={r.id} className="rounded-lg border p-3"><strong>{r.date} · {money(r.amount)} · {r.method === "cash" ? "Cash returned" : "Card processor refund recorded"}</strong><p className="text-sm">Original receipt {check.tenders.find(t => t.id === r.tenderId)?.reference} · Refund reference {r.reference}<br/>{r.evidence} · Recorded by {r.actor}</p></article>)}{!check.refunds.length && <p>No money returned yet.</p>}</section>
    </section> : <p>No restaurant checks to review yet.</p>}
  </div>;
}
function CreditForm({ check, command, disabled, tipsHeld }: { check: Check; command: Command; disabled: boolean; tipsHeld: number }) {
  const [amounts, setAmounts] = useState<Record<string, string>>({}), [tips, setTips] = useState("0.00");
  const lines = check.lines.map(l => ({ menuId: l.menuId, lineId: l.lineId, amount: cents(amounts[l.lineId] ?? "0") })).filter(l => l.amount > 0);
  const subtotal = lines.reduce((n, l) => n + l.amount, 0), tip = cents(tips || "0"), tax = Number.isSafeInteger(subtotal) ? creditTaxDelta(check.subtotal, check.tax, check.balance.foodCredit, check.balance.taxCredit, subtotal) : 0;
  const reduction = Math.min(check.balance.due, subtotal + tax), owed = subtotal + tax + tip - reduction, tipAvailable = check.tenders.reduce((n, t) => n + t.tip, 0) - check.balance.tipCredit;
  return <details><summary className="cursor-pointer font-medium">Issue a reviewed credit</summary><form className="mt-3 space-y-3" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void command("credit.issue", { id: check.id, revision: check.revision, reference: text(f, "reference"), reason: text(f, "reason"), lines, tips: tip, reviewed: true }); }}><fieldset disabled={disabled} className="space-y-3"><p className="text-sm">Enter the food amount to credit after any discount, before tax. Tax is prorated from the original check and rounded cumulatively. Served food remains consumed; a credit does not put it back into inventory.</p>{check.status !== "cancelled" && check.lines.filter(l => l.credited < l.subtotal).map(l => <Field key={l.lineId ?? l.menuId} label={`Credit for ${l.name} (USD), up to ${money(l.subtotal - l.credited)}`}><input className={inputClass} type="number" min="0" max={((l.subtotal - l.credited) / 100).toFixed(2)} step="0.01" value={amounts[l.lineId] ?? "0.00"} onChange={e => setAmounts({ ...amounts, [l.lineId]: e.target.value })}/></Field>)}{tipAvailable > 0 && <Field label="Held tips to credit (USD)"><input className={inputClass} type="number" min="0" step="0.01" max={(Math.min(tipAvailable, Math.max(0, tipsHeld)) / 100).toFixed(2)} value={tips} onChange={e => setTips(e.target.value)}/></Field>}<p className="text-sm">Tips already paid to staff need a reviewed payout/payroll correction before they can be credited here.</p><Field label="Unique credit reference"><input className={inputClass} name="reference" maxLength={100} required/></Field><Field label="Reason and review evidence"><textarea className={inputClass} name="reason" minLength={3} maxLength={1000} required/></Field><p role="status">Review: food {money(subtotal)} + tax {money(tax)} + tips {money(tip)}. Reduce unpaid balance by {money(reduction)}; add {money(owed)} to the refund owed.</p><label className="flex gap-2 text-sm"><input type="checkbox" required/>I reviewed the original sale, tax treatment, credit amounts and reason. Issue this credit without changing the original check.</label><button className="dd-primary" disabled={subtotal + tip <= 0}>Issue reviewed credit</button></fieldset></form></details>;
}
function CancelCreditForm({ check, command, disabled }: { check: Check; command: Command; disabled: boolean }) {
  const tips = check.tenders.reduce((n, t) => n + t.tip, 0) - check.balance.tipCredit;
  return <details><summary className="cursor-pointer font-medium">Cancel this unserved paid check</summary><form className="mt-3 space-y-3" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void command("credit.cancel", { id: check.id, revision: check.revision, reference: text(f, "reference"), reason: text(f, "reason"), tips: cents(text(f, "tips")), reviewed: true }); }}><fieldset disabled={disabled} className="space-y-3"><p className="text-sm">Cancel the full unserved check and move its received {money(check.paid)} deposit to refunds payable. Untouched ingredients return to storage. Once cooking begins, the captured food cost becomes waste. No sale or sales-tax reversal is created for food never served.</p><Field label="Cancellation credit reference"><input className={inputClass} name="reference" maxLength={100} required/></Field><Field label="Paid cancellation reason"><textarea className={inputClass} name="reason" minLength={3} maxLength={1000} required/></Field><Field label="Held tips to include in cancellation (USD)"><input className={inputClass} type="number" name="tips" min="0" max={(tips / 100).toFixed(2)} step="0.01" defaultValue="0.00" required/></Field><label className="flex gap-2 text-sm"><input type="checkbox" required/>I reviewed the cancellation with the kitchen and verified the deposit and held tips. I will record money returned separately.</label><button className="dd-primary">Cancel and record refund owed</button></fieldset></form></details>;
}
function RefundForm({ check, command, disabled }: { check: Check; command: Command; disabled: boolean }) {
  const available = check.tenders.filter(t => t.available > 0), [selected, select] = useState(available[0]?.id ?? ""), tender = available.find(t => t.id === selected);
  return <form className="rounded-lg border p-4 space-y-3" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void command("refund.record", { id: check.id, revision: check.revision, tenderId: selected, amount: cents(text(f, "amount")), reference: text(f, "reference"), evidence: text(f, "evidence"), returned: true }); }}><h3 className="text-lg font-semibold">Record money returned to the guest</h3><fieldset disabled={disabled} className="space-y-3"><p className="text-sm">Return funds using the original payment method. For split payments, record each verified refund separately. Card refunds reduce processor clearing; if the processor later debits the bank, record that settlement under Payments & daily close.</p><Field label="Original payment to refund"><select className={inputClass} value={selected} onChange={e => select(e.target.value)} required>{available.map(t => <option key={t.id} value={t.id}>{t.reference} · {t.method === "cash" ? "Cash" : "Card"} · {money(t.available)} not yet refunded</option>)}</select></Field><Field label="Verified refund amount (USD)"><input key={selected} className={inputClass} type="number" name="amount" min="0.01" max={(Math.min(check.balance.refundDue, tender?.available ?? 0) / 100).toFixed(2)} step="0.01" defaultValue={(Math.min(check.balance.refundDue, tender?.available ?? 0) / 100).toFixed(2)} required/></Field><Field label="Unique refund receipt or processor reference"><input className={inputClass} name="reference" maxLength={100} required/></Field><Field label="Refund payment evidence"><textarea className={inputClass} name="evidence" minLength={3} maxLength={1000} required/></Field><label className="flex gap-2 text-sm"><input type="checkbox" required/>I verified the money has been returned to the guest and this payment has not already been recorded. This action records it; it does not send money.</label><button className="dd-primary">Record verified refund</button></fieldset></form>;
}
