"use client";
import { useState } from "react";
import { instantForLocal } from "@/lib/timeclock/zoned-time";
import type { restaurantManagementData } from "@/lib/restaurant/management";
export function RestaurantWebsite({ data, command, disabled, canConfigure }: { data: ReturnType<typeof restaurantManagementData>; command: (action: string, input: unknown) => Promise<boolean>; disabled: boolean; canConfigure: boolean }) {
  const [error, setError] = useState("");
  return <div className="space-y-5"><section className="dd-card space-y-4"><h2 className="text-xl font-semibold">Online pickup ordering</h2><p><a className="underline" href="/restaurant/reservations">Configure table reservations and opening hours</a></p><p>Customers choose published pickup times, review prices and dietary information, and pay at pickup. Orders allocate ingredients and reach the kitchen with a required staff review.</p><p><a className="underline" href="/api/website/restaurant" target="_blank" rel="noreferrer">Open customer menu</a> · <a className="underline" href="/setup#attach">Website connections</a></p><p className="text-sm">In the WordPress plugin, enable Restaurant ordering and add <code>[shuug_restaurant_ordering]</code>. For other websites, link to this customer menu.</p>{canConfigure && <form key={data.website.revision} className="space-y-3" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void command("website.configure", { revision: data.website.revision, enabled: f.has("enabled"), instructions: String(f.get("instructions")), origins: String(f.get("origins")).split(/\r?\n/).map(s => s.trim()).filter(Boolean) }); }}><fieldset disabled={disabled} className="space-y-3"><label className="flex gap-2"><input name="enabled" type="checkbox" defaultChecked={data.website.enabled}/>Open online pickup orders</label><label className="block text-sm">Pickup instructions and restaurant contact details<textarea className="dd-input mt-1 w-full" name="instructions" minLength={10} maxLength={1000} defaultValue={data.website.instructions} required/></label><label className="block text-sm">Websites allowed to embed the menu (one exact HTTPS origin per line)<textarea className="dd-input mt-1 w-full" name="origins" defaultValue={data.website.origins.join("\n")} placeholder="https://www.yourrestaurant.com"/></label><button className="dd-primary">Save online ordering settings</button></fieldset></form>}</section>
    <section className="dd-card space-y-4"><h2 className="text-xl font-semibold">Pickup capacity</h2><p className="text-sm">Times are in {data.config.timezone}. Customers see available times 15 minutes to 2 hours ahead on the current calendar date. Capacity counts accepted orders, including those already collected. Cancelled orders release capacity.</p>{error && <p role="alert">{error}</p>}<form className="grid gap-3 sm:grid-cols-3" onSubmit={async e => { e.preventDefault(); setError(""); const form = e.currentTarget, f = new FormData(form); try { if (await command("pickup.save", { at: instantForLocal(String(f.get("at")), data.config.timezone), capacity: Number(f.get("capacity")), enabled: true })) form.reset(); } catch (e) { setError(e instanceof Error ? e.message : "Check pickup time."); } }}><fieldset disabled={disabled} className="contents"><label className="text-sm">Pickup time<input className="dd-input mt-1 w-full" name="at" type="datetime-local" required/></label><label className="text-sm">Maximum orders<input className="dd-input mt-1 w-full" name="capacity" type="number" min="1" max="100" defaultValue="5" required/></label><button className="dd-primary self-end">Publish pickup time</button></fieldset></form><div className="space-y-3">{data.website.slots.slice().sort((a, b) => a.at.localeCompare(b.at)).map(slot => { const orders = data.website.orders.filter(r => r.slotId === slot.id && data.orders.some(o => o.id === r.orderId && o.status !== "cancelled")); return <article className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-3" key={slot.id}><p>{new Intl.DateTimeFormat("en-US", { timeZone: data.config.timezone, dateStyle: "medium", timeStyle: "short" }).format(new Date(slot.at))} · {orders.length}/{slot.capacity} orders · {slot.enabled ? "Published" : "Paused"}</p><button className="dd-secondary" disabled={disabled} onClick={() => void command("pickup.save", { ...slot, enabled: !slot.enabled })}>{slot.enabled ? "Pause new orders" : "Reopen pickup time"}</button></article>; })}</div></section>
  </div>;
}
