"use client";
import { useState } from "react";
import type { restaurantManagementData } from "@/lib/restaurant/management";
import type { ReportQuery } from "@/lib/restaurant/report-model";
import { shiftReportDate } from "@/lib/restaurant/report-model";
import { RestaurantServiceHours } from "./RestaurantServiceHours";
type Data = ReturnType<typeof restaurantManagementData>;
const money = (c: number | null) => c === null ? "Unknown" : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(c / 100);
const count = (n: number | null) => n === null ? "Unknown" : n.toFixed(1);
const percentage = (n: number | null) => n === null ? "No comparable baseline" : `${n >= 0 ? "+" : ""}${n.toFixed(1)}%`;
const labels = { dine_in: "Dine-in", takeaway: "Takeaway", online: "Online pickup" };
export function RestaurantSalesPatterns({ data, busy, canEditHours, onFilter, command }: { data: Data; busy: boolean; canEditHours: boolean; onFilter: (query: ReportQuery) => Promise<void>; command: (action: string, input: unknown) => Promise<boolean> }) {
  const report = data.financial!.report, [metric, setMetric] = useState<"sales" | "covers">("covers");
  const basis = report.query.basis, unit = basis === "open_hour" ? "open hour" : "open day";
  const rate = (d: typeof report.weekdays[number]) => metric === "sales" ? basis === "open_hour" ? d.salesPerHour : d.averageSales : basis === "open_hour" ? d.coversPerHour : d.averageCovers;
  const maximum = Math.max(0, ...report.weekdays.map(d => rate(d) ?? 0));
  const params = new URLSearchParams({ ...report.query, format: "csv" });
  return <div className="space-y-5" aria-label="Restaurant sales analysis"><section className="dd-card space-y-4"><h2 className="text-xl font-semibold">Compare service periods</h2><form key={JSON.stringify(report.query)} className="space-y-3" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void onFilter({ ...(f.get("from") ? { from: String(f.get("from")) } : {}), ...(f.get("to") ? { to: String(f.get("to")) } : {}), basis: String(f.get("basis")) as "open_hour" | "open_day" }); }}><fieldset disabled={busy} className="grid gap-3 text-sm sm:grid-cols-3"><label>First business date<input className="dd-input mt-1 w-full" type="date" name="from" defaultValue={report.query.from ?? ""} max={data.today}/></label><label>Last business date<input className="dd-input mt-1 w-full" type="date" name="to" defaultValue={report.query.to ?? ""} max={data.today}/></label><label>Comparison basis<select className="dd-input mt-1 w-full" name="basis" defaultValue={basis}><option value="open_hour">Per reviewed open hour</option><option value="open_day">Per reviewed open day</option></select></label><button className="dd-primary w-fit">Apply report filters</button><button className="dd-secondary w-fit" type="button" onClick={() => void onFilter({ from: shiftReportDate(data.today, -27), to: data.today, basis })}>Last 28 days</button><button className="dd-secondary w-fit" type="button" onClick={() => void onFilter({ basis })}>All recorded dates</button></fieldset></form><p className="text-sm">Business dates use {report.timezone}, starting at {String(report.businessDayStartHour).padStart(2, "0")}:00. Choose up to 366 days; blank dates show all recorded history. <a className="underline" href={`/api/restaurant/reports?${params}`}>Download service-day CSV</a></p><p className="text-sm" role="status">{report.observedOpenDays} reviewed open days · {report.recordedClosedDays} reviewed closed days · {report.period.daysMissingHours} open days missing opening time{report.period.unreviewedDays !== null ? ` · ${report.period.unreviewedDays} dates without a reviewed close` : ""}.</p>{report.previous && <><div className="overflow-auto"><table className="w-full text-left text-sm"><caption className="text-left">Selected period and the immediately preceding period of equal length</caption><thead><tr><th>Measure</th><th>{report.period.from} – {report.period.to}</th><th>{report.previous.from} – {report.previous.to}</th></tr></thead><tbody>{[
    ["Reviewed open days", report.period.openDays, report.previous.openDays], ["Dates without a close", report.period.unreviewedDays, report.previous.unreviewedDays], ["Recorded covers", report.period.covers, report.previous.covers], ["Sales before credits", money(report.period.sales), money(report.previous.sales)], ["Credits posted", money(report.period.credits), money(report.previous.credits)], ["Net sales", money(report.period.netSales), money(report.previous.netSales)], ["Food cost", money(report.period.foodCost), money(report.previous.foodCost)], [`Sales per ${unit}`, money(basis === "open_hour" ? report.period.salesPerHour : report.period.averageSales), money(basis === "open_hour" ? report.previous.salesPerHour : report.previous.averageSales)], [`Covers per ${unit}`, count(basis === "open_hour" ? report.period.coversPerHour : report.period.averageCovers), count(basis === "open_hour" ? report.previous.coversPerHour : report.previous.averageCovers)],
  ].map(row => <tr key={String(row[0])} className="border-t">{row.map((v, i) => <td key={i} className="py-2 pr-4">{v}</td>)}</tr>)}</tbody></table></div><p className="text-sm">Sales per {unit}: {percentage(report.comparison.salesPercent)} · Recorded covers per {unit}: {percentage(report.comparison.coversPercent)}. Comparisons need complete close coverage, at least three open days in each period and reviewed hours when using hourly rates. A zero prior rate has no percentage baseline. Periods may have different weekday mixes, holidays or seasonal conditions.</p></>}</section>
    <section className="dd-card space-y-4"><h2 className="text-xl font-semibold">Busy and quiet service days</h2><p>{report.guidance}</p><p className="text-sm">Sales exclude tax and tips and retain demand before credits. Recorded covers count parties/checks, including pickup quantities entered as covers; they are not unique customers. Missing dates are unknown. Per-hour rates use only days with reviewed opening time; a weekday needs all its observed hours and at least three open days to qualify for an hourly ranking.</p><label className="block text-sm">Chart measure<select className="dd-input ml-2" value={metric} onChange={e => setMetric(e.target.value as "sales" | "covers")}><option value="covers">Recorded covers</option><option value="sales">Sales</option></select></label><ul className="space-y-2" aria-label={`${metric === "sales" ? "Sales" : "Recorded covers"} per ${unit} by weekday`}>{report.weekdays.map(d => <li key={d.name} className="grid grid-cols-[6rem_1fr_7rem] items-center gap-3 text-sm"><span>{d.name}</span><div className="h-4 rounded bg-slate-100" aria-hidden="true"><div className={`h-4 rounded ${d.comparable ? "bg-emerald-600" : "bg-slate-400"}`} style={{ width: `${maximum ? (rate(d) ?? 0) / maximum * 100 : 0}%` }}/></div><span>{metric === "sales" ? money(rate(d)) : count(rate(d))}{!d.comparable ? " *" : ""}</span></li>)}</ul><p className="text-xs">* Insufficient observations or incomplete opening time for ranking. Zero is measured; unknown has no rate.</p><div className="overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th>Weekday</th><th>Open days</th><th>Days missing hours</th><th>Reviewed hours</th><th>Sales per day</th><th>Covers per day</th><th>Sales per hour</th><th>Covers per hour</th></tr></thead><tbody>{report.weekdays.map(d => <tr className="border-t" key={d.name}><td className="py-3 pr-3">{d.name}</td><td>{d.observedDays}</td><td>{d.daysMissingHours}</td><td>{d.daysWithHours ? count(d.openMinutes / 60) : "Unknown"}</td><td>{money(d.averageSales)}</td><td>{count(d.averageCovers)}</td><td>{money(d.salesPerHour)}</td><td>{count(d.coversPerHour)}</td></tr>)}</tbody></table></div>{report.busiestDays.length > 0 && <p>Highest sales per {unit} among comparable weekdays: <strong>{report.busiestDays.join(", ")}</strong>{report.busiestDays.length > 1 ? " (tied)" : ""}.</p>}</section>
    <RestaurantServiceHours closes={data.financial!.closes} history={data.financial!.serviceHours} disabled={busy || !canEditHours} command={command}/>
    <section className="dd-card space-y-4"><h2 className="text-xl font-semibold">Sales by channel</h2><p className="text-sm">Menu, channel and hourly totals follow original service dates and credits recorded through the chosen end date. Daily-close net sales follow credit posting dates, so these views can differ. {report.unclosedServiceDays} service dates in these totals still lack a reviewed close.</p><div className="overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th>Channel</th><th>Checks</th><th>Recorded covers</th><th>Net food sales</th><th>Average check</th></tr></thead><tbody>{report.channels.map(c => <tr className="border-t" key={c.channel}><td className="py-3">{labels[c.channel]}</td><td>{c.orders}</td><td>{c.covers}</td><td>{money(c.sales)}</td><td>{money(c.averageCheck)}</td></tr>)}</tbody></table></div></section>
    <section className="dd-card space-y-4"><h2 className="text-xl font-semibold">Menu sales</h2><div className="overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th>Item</th><th>Portions served</th><th>Net food sales</th></tr></thead><tbody>{report.items.map(i => <tr className="border-t" key={i.id}><td className="py-2">{i.name}</td><td>{i.quantity}</td><td>{money(i.sales)}</td></tr>)}</tbody></table></div>{!report.items.length && <p>No served menu items in this period.</p>}</section>
    <section className="dd-card space-y-4"><h2 className="text-xl font-semibold">Service by hour</h2><p className="text-sm">Net sales at original serving time in {report.timezone}. These clock-hour totals are not adjusted for opening time within each clock hour.</p><div className="grid gap-2 sm:grid-cols-6">{report.hours.filter(h => h.orders > 0).map(h => <div className="rounded border p-3" key={h.hour}><strong>{String(h.hour).padStart(2, "0")}:00</strong><p className="text-sm">{h.orders} checks<br/>{money(h.sales)}</p></div>)}</div></section>
    <section className="dd-card space-y-4"><h2 className="text-xl font-semibold">Review candidates for a limited special</h2><p className="text-sm">These candidates use current stock and current ingredient costs, regardless of the report dates. Contribution excludes labor, overhead, discounts and advertising. Review staffing and capacity before choosing an offer.</p>{report.specialCandidates.map(m => <article key={m.id} className="rounded border p-3"><h3 className="font-semibold">{m.name}</h3><p className="text-sm">Price {money(m.price)} · Food cost {money(m.estimatedFoodCost)} · Before-labor contribution {money(m.beforeLaborContribution)} · {m.available} portions available</p></article>)}<a className="underline" href="/restaurant/specials">Create a limited restaurant special</a></section>
  </div>;
}
