"use client";
import { useState } from "react";
import type { RestaurantClose } from "@/lib/restaurant/business-model";
import type { ServiceHoursReview } from "@/lib/restaurant/report-model";
type Command = (action: string, input: unknown) => Promise<boolean>;
const field = "dd-input mt-1 block w-full";
function Duration({ minutes }: { minutes?: number }) {
  return <div className="grid gap-3 sm:grid-cols-2"><label>Hours open<input className={field} type="number" name="hours" min="0" max="25" step="1" defaultValue={minutes === undefined ? "" : Math.floor(minutes / 60)} required/></label><label>Additional minutes<input className={field} type="number" name="minutes" min="0" max="59" step="1" defaultValue={(minutes ?? 0) % 60} required/></label></div>;
}
const duration = (form: FormData) => Number(form.get("hours")) * 60 + Number(form.get("minutes"));
const explanation = "Record actual time accepting orders across all channels. Add split services, exclude closed breaks and count overlapping service only once. Include overnight service in its business day. Use elapsed time when clocks change; this is not staff labor time.";
export function RestaurantCloseForm({ today, disabled, command }: { today: string; disabled: boolean; command: Command }) {
  const [operated, setOperated] = useState(true);
  return <form className="space-y-4 text-sm" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void command("close", { date: String(f.get("date")), operated, ...(operated ? { openMinutes: duration(f) } : {}), countedCash: Math.round(Number(f.get("counted")) * 100), note: String(f.get("note")), reviewed: true }); }}><fieldset disabled={disabled} className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><label>Close business date<input className={field} type="date" name="date" defaultValue={today} max={today} required/></label><label>Actual drawer cash counted<input className={field} type="number" name="counted" step="0.01" min="0" max="999999.99" required/></label></div><label className="flex gap-2"><input type="checkbox" checked={operated} onChange={e => setOperated(e.target.checked)}/>Open for service this day. Uncheck for a fully closed day.</label>{operated && <><Duration/><p>{explanation}</p></>}<label className="block">Count evidence and review notes<textarea className={field} name="note" minLength={3} maxLength={2000} required/></label><label className="flex gap-2"><input type="checkbox" required/>I reviewed the checks, tenders, transfers, cash count and opening time.</label><button className="dd-primary">Close and preserve this day</button></fieldset></form>;
}
export function RestaurantServiceHours({ closes, history, disabled, command }: { closes: RestaurantClose[]; history: ServiceHoursReview[]; disabled: boolean; command: Command }) {
  const [selected, setSelected] = useState("");
  const close = closes.find(c => c.id === selected && c.operated), reviews = history.filter(h => h.closeId === close?.id), latest = reviews.at(-1);
  return <details className="dd-card space-y-4"><summary className="cursor-pointer font-semibold">Review or correct opening time</summary><p className="text-sm">{explanation} This adds reviewed evidence while preserving the original close and all financial entries.</p><label className="block text-sm">Reviewed service day<select className={field} value={selected} onChange={e => setSelected(e.target.value)}><option value="">Choose an open day</option>{closes.filter(c => c.operated).slice().reverse().map(c => <option key={c.id} value={c.id}>{c.date}{history.some(h => h.closeId === c.id) ? " · time recorded" : " · opening time missing"}</option>)}</select></label>{close && <><form key={`${close.id}:${latest?.revision ?? 0}`} className="space-y-3 text-sm" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void command("hours.review", { closeId: close.id, revision: latest?.revision ?? 0, openMinutes: duration(f), evidence: String(f.get("evidence")), reviewed: true }); }}><fieldset disabled={disabled} className="space-y-3"><Duration minutes={latest?.openMinutes}/><label className="block">Opening-time evidence or correction reason<textarea className={field} name="evidence" minLength={3} maxLength={1000} required/></label><label className="flex gap-2"><input type="checkbox" required/>I verified the actual time open for this business day.</label><button className="dd-primary">Save reviewed opening time</button></fieldset></form><ol className="space-y-2 text-sm">{reviews.slice().reverse().map(h => <li key={h.id} className="rounded border p-3">Review {h.revision}: {Math.floor(h.openMinutes / 60)} hours {h.openMinutes % 60} minutes · {h.actor} · {h.at}<p>{h.evidence}</p></li>)}</ol></>}</details>;
}
