"use client";
import { useRef, useState, type ReactNode } from "react";
import { useRouter } from "next/navigation";
import type { ModuleRecord } from "@/lib/sdk/types";
import type { VinLookupReview } from "@/lib/vehicles/model";
const inputClass = "dd-input mt-1 block w-full";
const text = (f: FormData, key: string) => String(f.get(key) ?? "");
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block text-sm">{label}{children}</label>; }
export function VehicleVinLookup({ records: initial, clients, canEdit }: { records: ModuleRecord[]; clients: { id: string; title: string }[]; canEdit: boolean }) {
  const router = useRouter(), [saved, setSaved] = useState<ModuleRecord | null>(null), [target, setTarget] = useState(""), [vin, setVin] = useState(""), [year, setYear] = useState(""), [review, setReview] = useState<VinLookupReview | null>(null), [busy, setBusy] = useState(false), [notice, setNotice] = useState("");
  const records = saved ? [...initial.map(r => r.id === saved.id && r.updatedAt < saved.updatedAt ? saved : r), ...(!initial.some(r => r.id === saved.id) ? [saved] : [])] : initial;
  const requests = useRef(new Map<string, string>());
  async function lookup(form: HTMLFormElement) {
    const f = new FormData(form); setBusy(true); setNotice(""); setReview(null);
    try { const response = await fetch("/api/vehicles/vin", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "lookup", input: { vin, modelYear: year ? Number(year) : null, recordId: target || null, consent: f.has("consent") } }) }), result = await response.json(); if (!response.ok) throw new Error(result.error); setReview(result.review); }
    catch (e) { setNotice(e instanceof Error ? e.message : "Could not look up this VIN."); } finally { setBusy(false); }
  }
  async function apply(form: HTMLFormElement) {
    if (!review?.proof) return; const f = new FormData(form), details = { customer_id: text(f, "client"), registration: text(f, "registration"), odometer: text(f, "odometer") === "" ? null : Number(text(f, "odometer")), fleet_id: text(f, "fleet"), notes: text(f, "notes") }, payload = { proof: review.proof, details, reviewed: f.has("reviewed") }, key = JSON.stringify(payload), requestId = requests.current.get(key) ?? crypto.randomUUID(); requests.current.set(key, requestId); setBusy(true); setNotice("");
    try { const response = await fetch("/api/vehicles/vin", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "apply", input: { ...payload, requestId } }) }), result = await response.json(); if (!response.ok) throw new Error(result.error); const updated = result.record as ModuleRecord; setSaved(updated); setTarget(updated.id); setReview(null); setNotice("Saved the vehicle and reviewed VIN details. The review history is retained."); router.refresh(); }
    catch (e) { setNotice(e instanceof Error ? e.message : "Could not save the reviewed VIN."); } finally { setBusy(false); }
  }
  return <section className="dd-card mb-6 space-y-5"><h2 className="text-xl font-semibold">Look up and review a VIN</h2><button type="button" className="dd-secondary" disabled={busy} onClick={() => router.refresh()}>Refresh vehicles and clients</button><p className="text-sm">Use a complete 17-character VIN to check manufacturer-reported details through <a className="underline" href="https://vpic.nhtsa.dot.gov/api/" target="_blank" rel="noreferrer">NHTSA vPIC</a>. The request sends the VIN and optional model year. Customer names, plates, mileage and notes stay in this workspace.</p><p className="text-sm">Compare the result with the vehicle before saving. This lookup supplies specifications; it does not establish ownership, condition, service history or recall clearance. Older or incomplete identities can use the manual records form below.</p>{notice && <p role="status" className="rounded-lg border p-3">{notice}</p>}
    {canEdit && <form className="space-y-3" onSubmit={e => { e.preventDefault(); void lookup(e.currentTarget); }}><fieldset disabled={busy} className="space-y-3"><Field label="Vehicle to look up"><select className={inputClass} value={target} onChange={e => { const value = e.target.value, r = records.find(r => r.id === value); setTarget(value); setVin(String(r?.values.vin ?? "")); setYear(String(r?.values.year ?? "")); setReview(null); }}><option value="">Create a new vehicle from a reviewed lookup</option>{records.filter(r => !r.archived).map(r => <option key={r.id} value={r.id}>{String(r.values.vin ?? "")} · {String(r.values.make ?? "")} {String(r.values.model ?? "")}</option>)}</select></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="VIN for lookup"><input className={inputClass} value={vin} onChange={e => { setVin(e.target.value); setReview(null); }} minLength={17} maxLength={17} required autoComplete="off"/></Field><Field label="Known model year (optional)"><input className={inputClass} type="number" min={1980} max={2100} step={1} value={year} onChange={e => { setYear(e.target.value); setReview(null); }}/></Field></div><label className="flex gap-2 text-sm"><input type="checkbox" name="consent" required/>Send this VIN and optional model year to NHTSA for this lookup.</label><button className="dd-primary">Look up VIN</button></fieldset></form>}
    {review && <article className="space-y-3 rounded-lg border p-4"><h3 className="font-semibold">Lookup result for {review.result.vin}</h3><p>{review.result.year ?? "Year unavailable"} · {review.result.make || "Make unavailable"} · {review.result.model || "Model unavailable"}</p><dl className="grid gap-2 text-sm sm:grid-cols-2">{[["Manufacturer", review.result.manufacturer], ["Body", review.result.bodyClass], ["Cylinders", review.result.cylinders], ["Engine litres", review.result.displacementLitres], ["Fuel", review.result.fuel]].map(([label, value]) => <div key={label}><dt className="font-medium">{label}</dt><dd>{value || "Not supplied"}</dd></div>)}</dl><p className="text-sm">Provider response: {review.result.message}</p>{!review.result.canApply ? <p role="alert" className="rounded-lg bg-amber-50 p-3">The lookup has errors, incomplete details or a different model year. Nothing was applied. Check the VIN and year against the vehicle, or record independently verified details manually.</p> : <form key={review.proof} onSubmit={e => { e.preventDefault(); void apply(e.currentTarget); }} className="space-y-3"><fieldset disabled={busy || !canEdit} className="space-y-3"><p className="text-sm">Saving will use the VIN, make, model and year above. {review.target ? `Current record: ${review.target.values.year ?? ""} ${review.target.values.make ?? ""} ${review.target.values.model ?? ""}. Review the replacement and ownership details below.` : "Complete the client and vehicle details below."} This review expires in 15 minutes.</p><Field label="Service client for this vehicle"><select className={inputClass} name="client" defaultValue={String(review.target?.values.customer_id ?? "")} required><option value="">Choose service client</option>{clients.map(c => <option key={c.id} value={c.id}>{c.title}</option>)}</select></Field><a className="text-sm underline" href="/modules/service-clients" target="_blank" rel="noreferrer">Open service clients to add a client</a><Field label="Registration or plate"><input className={inputClass} name="registration" maxLength={100} defaultValue={String(review.target?.values.registration ?? "")}/></Field><Field label="Odometer reading"><input className={inputClass} name="odometer" type="number" min={0} max={10_000_000} step={1} defaultValue={String(review.target?.values.odometer ?? "")}/></Field><Field label="Fleet account reference (optional)"><input className={inputClass} name="fleet" maxLength={200} defaultValue={String(review.target?.values.fleet_id ?? "")}/></Field><Field label="Vehicle notes"><textarea className={inputClass} name="notes" maxLength={5000} defaultValue={String(review.target?.values.notes ?? "")}/></Field><label className="flex gap-2 text-sm"><input type="checkbox" name="reviewed" required/>I compared the VIN and decoded details with the vehicle and verified the client and vehicle information before saving.</label><button className="dd-primary">Save reviewed vehicle</button></fieldset></form>}</article>}
    <details>
      <summary className="cursor-pointer font-medium">Saved VIN review history</summary>
      <div className="mt-3 space-y-3">
        {records.filter(r => r.vinReviews?.length).map(r => {
          const last = r.vinReviews!.at(-1)!.result;
          const matches = String(r.values.vin ?? "").trim().toUpperCase() === last.vin && r.values.make === last.make && r.values.model === last.model && r.values.year === last.year;
          return <article key={r.id} className="rounded-lg border p-3 space-y-2">
            <h3 className="font-semibold">{String(r.values.vin)} · {r.archived ? "Archived" : "Active"}</h3>
            <p className="text-sm">{matches ? "Current identity matches the last reviewed lookup." : "Vehicle identity was manually changed after the last lookup. Review its current details."}</p>
            {r.vinReviews!.slice().reverse().map(h => <div className="border-t pt-2 text-sm" key={h.id}>
              <p>{h.result.provider} · Looked up {h.result.decodedAt} · Reviewed {h.reviewedAt} by {h.reviewedBy}</p>
              <p>{h.result.vin} · {h.result.year} {h.result.make} {h.result.model}</p>
              {h.appliedValues && <p>Client at review: {clients.find(c => c.id === h.appliedValues.customer_id)?.title ?? String(h.appliedValues.customer_id)} · Odometer {h.appliedValues.odometer === "" ? "not recorded" : String(h.appliedValues.odometer)} · Plate {String(h.appliedValues.registration || "not recorded")}</p>}
              {h.previousValues && <p>Previous record: {String(h.previousValues.vin ?? "")} · {String(h.previousValues.year ?? "")} {String(h.previousValues.make ?? "")} {String(h.previousValues.model ?? "")}</p>}
            </div>)}
          </article>;
        })}
        {!records.some(r => r.vinReviews?.length) && <p>No reviewed VIN lookups saved yet.</p>}
      </div>
    </details>
  </section>;
}
