// @vitest-environment node
import { afterEach,beforeEach,expect,it,vi } from "vitest";
import { mkdtempSync,rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { mapPipelineOrder,pipelineStage,isLate } from "./pipeline";
import { pullAmazonOrders } from "./client";
import { readAmazon,saveAmazon } from "./store";
let folder:string;
const raw={orderId:"111-2222222-3333333",createdTime:"2026-09-01T00:00:00Z",lastUpdatedTime:"2026-09-09T00:00:00Z",salesChannel:{marketplaceId:"ATVPDKIKX0DER",marketplaceName:"Amazon.com"},fulfillment:{fulfillmentStatus:"PARTIALLY_SHIPPED",fulfilledBy:"MERCHANT",shipByWindow:{latestDateTime:"2026-09-08T00:00:00Z"}},orderItems:[{orderItemId:"i1",quantityOrdered:3,product:{title:"Amba",sellerSku:"AMBA"},fulfillment:{quantityFulfilled:1,quantityUnfulfilled:2}}]};
beforeEach(()=>{folder=mkdtempSync(path.join(tmpdir(),"shuug-amazon-pipeline-"));vi.stubEnv("DEALDESK_DATA_DIR",folder);vi.stubGlobal("fetch",vi.fn());for(const [k,v] of Object.entries({CLIENT_ID:"id",CLIENT_SECRET:"secret",REFRESH_TOKEN:folder,MARKETPLACE_ID:"ATVPDKIKX0DER",REGION:"na"}))vi.stubEnv(`AMAZON_SP_${k}`,v);});afterEach(()=>{vi.unstubAllEnvs();vi.unstubAllGlobals();rmSync(folder,{recursive:true,force:true});});
it("preserves partial quantities and unknown payment/amounts without inventing paid status",()=>{const o=mapPipelineOrder(raw);expect(o).toMatchObject({stage:"partial",totalCents:null,currency:null,payments:[],items:[{quantity:3,shipped:1,unshipped:2}]});expect(isLate(o,Date.parse("2026-09-10"))).toBe(true);});
it("requires fully shipped status and all packages delivered before declaring delivery",()=>{expect(pipelineStage("PARTIALLY_SHIPPED",[{status:"DELIVERED"}])).toBe("partial");expect(pipelineStage("SHIPPED",[])).toBe("shipped");expect(pipelineStage("SHIPPED",[{status:"DELIVERED"},{status:"IN_TRANSIT"}])).toBe("shipped");expect(pipelineStage("SHIPPED",[{status:"DELIVERED"}])).toBe("delivered");expect(pipelineStage("FUTURE_STATUS",[])).toBe("exceptions");});
it("records status transitions and refuses older observations to roll a shipment back",()=>{const key="a".repeat(32),first=mapPipelineOrder(raw);saveAmazon(key,[first],{partial:false,after:"a",before:"b"});saveAmazon(key,[{...first,status:"SHIPPED",stage:"shipped",updatedAt:"2026-09-10T00:00:00Z"}],{partial:false,after:"a",before:"b"});saveAmazon(key,[first],{partial:false,after:"a",before:"b"});const saved=readAmazon(key);expect(saved.orders).toHaveLength(1);expect(saved.orders[0].stage).toBe("shipped");expect(saved.history).toHaveLength(2);});
it("uses the current API and follows pages with an unchanged updated-time window",async()=>{const fetch=vi.mocked(globalThis.fetch);fetch.mockResolvedValueOnce(Response.json({access_token:"access",expires_in:3600})).mockResolvedValueOnce(Response.json({orders:[raw],pagination:{nextToken:"next-page"}})).mockResolvedValueOnce(Response.json({orders:[{...raw,orderId:"222-3333333-4444444"}]}));const result=await pullAmazonOrders(30);expect(result.ok).toBe(true);expect(result.orders).toHaveLength(2);const a=new URL(String(fetch.mock.calls[1][0])),b=new URL(String(fetch.mock.calls[2][0]));expect(a.pathname).toBe("/orders/2026-01-01/orders");expect(b.searchParams.get("paginationToken")).toBe("next-page");expect(b.searchParams.get("lastUpdatedAfter")).toBe(a.searchParams.get("lastUpdatedAfter"));expect(a.searchParams.get("includedData")).toBe("FULFILLMENT,PACKAGES,PROCEEDS,PAYMENT");});
it("keeps completed pages when Amazon rate-limits the next page",async()=>{vi.mocked(fetch).mockResolvedValueOnce(Response.json({access_token:"access",expires_in:3600})).mockResolvedValueOnce(Response.json({orders:[raw],pagination:{nextToken:"resume-here"}})).mockResolvedValueOnce(Response.json({errors:[{message:"private-provider-debug"}]},{status:429}));const result=await pullAmazonOrders();expect(result.ok).toBe(false);expect(result.state?.partial).toBe(true);expect(result.state?.nextToken).toBe("resume-here");expect(result.orders).toHaveLength(1);expect(result.error).not.toContain("private-provider-debug");});
