import { fireEvent,render,screen,waitFor } from "@testing-library/react";
import { beforeEach,expect,it,vi } from "vitest";
import { SocialWorkspace } from "./SocialWorkspace";
import { socialAction } from "@/app/social/actions";
import { defaultBrand,PLATFORMS,type Platform,type SocialState } from "@/lib/social/model";
vi.mock("@/app/social/actions",()=>({socialAction:vi.fn()}));
beforeEach(()=>{vi.mocked(socialAction).mockReset();});
const state:SocialState={version:1,brand:defaultBrand(),brandRevision:1,accounts:[],snapshots:[],traffic:[],campaigns:[],assets:[],jobs:[]};
const data=()=>({state:structuredClone(state),signals:{start:"2026-08-13",end:"2026-09-09",orders:0,revenueCents:0,previousRevenueCents:0,estimatedOrders:0,demo:true,products:[],facts:["No traffic connected."],traffic:null},connections:{},creative:{gemini:false,openai:false}});
const help=Object.fromEntries(PLATFORMS.map(p=>[p,{setup:"Connect this platform",docs:"",oauth:false,competitors:false}])) as Record<Platform,{setup:string;docs:string;oauth:boolean;competitors:boolean}>;
function mount(){render(<SocialWorkspace initial={data()} help={help} models={{gemini:"fixture-gemini",openai:"fixture-openai"}} callbackUrl="http://localhost:3000/api/social/callback"/>);}
it("accepts multiple pasted social links and shows tracked profiles without invented metrics",async()=>{const result=data();result.state.accounts.push({id:"11111111-1111-4111-8111-111111111111",platform:"instagram",handle:"fixture",label:"fixture",profileUrl:"https://www.instagram.com/fixture/",role:"brand",method:"api",revision:1,disabled:false,createdAt:"2026-09-10T12:00:00Z"});vi.mocked(socialAction).mockResolvedValue({...result,ok:true,message:"1 profile added.",jobId:undefined});mount();fireEvent.change(screen.getByLabelText("Website or social profile URLs"),{target:{value:"instagram.com/fixture\ntiktok.com/@fixture"}});fireEvent.click(screen.getByRole("button",{name:"Track links"}));await waitFor(()=>expect(socialAction).toHaveBeenCalledWith("discover",{links:"instagram.com/fixture\ntiktok.com/@fixture",role:"brand"}));expect(await screen.findByText("Found · metrics not connected")).toBeVisible();expect(screen.getByLabelText("Website or social profile URLs")).toHaveValue("");});
it("supports a dragged social link and the competitor role",async()=>{vi.mocked(socialAction).mockResolvedValue({...data(),ok:true,message:"Competitor tracked.",jobId:undefined});mount();fireEvent.drop(screen.getByText("Drop a link. Start tracking."),{dataTransfer:{getData:(type:string)=>type==="text/uri-list"?"# browser link\nhttps://x.com/fixture":""}});expect(screen.getByLabelText("Website or social profile URLs")).toHaveValue("https://x.com/fixture");fireEvent.change(screen.getByLabelText("Track as"),{target:{value:"competitor"}});fireEvent.click(screen.getByRole("button",{name:"Track links"}));await waitFor(()=>expect(socialAction).toHaveBeenCalledWith("discover",{links:"https://x.com/fixture",role:"competitor"}));});
it("retains a failed URL so it can be corrected, and requires provider setup before image creation",async()=>{vi.mocked(socialAction).mockResolvedValue({ok:false,error:"Drop a profile link."});mount();fireEvent.change(screen.getByLabelText("Website or social profile URLs"),{target:{value:"instagram.com/p/123"}});fireEvent.click(screen.getByRole("button",{name:"Track links"}));expect(await screen.findByRole("alert")).toHaveTextContent("Drop a profile link.");expect(screen.getByLabelText("Website or social profile URLs")).toHaveValue("instagram.com/p/123");fireEvent.click(screen.getByRole("button",{name:"Creative studio"}));expect(screen.getByRole("button",{name:"Prepare image prompt"})).toBeDisabled();});
