"use client";
import { instantForLocal, localDateTime } from "@/lib/timeclock/zoned-time";
import { useRef, useState, type ReactNode } from "react";
import type { scheduleView } from "@/lib/timeclock/schedule";
type Data = ReturnType<typeof scheduleView>;
type Command = (action: string, input: unknown) => Promise<boolean>;
const inputClass = "dd-input mt-1 w-full";
const text = (f: FormData, key: string) => String(f.get(key) ?? "");
const money = (cents: number | null) => cents === null ? "Cost not established" : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(cents / 100);
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block text-sm">{label}{children}</label>; }
export function StaffSchedule({ initial, manager = false, canEdit = true }: { initial: Data; manager?: boolean; canEdit?: boolean }) {
  const [data, setData] = useState(initial), [busy, setBusy] = useState(false), [message, setMessage] = useState(""); const requests = useRef(new Map<string, string>()), endpoint = manager ? "/api/team/schedule" : "/api/workspace/me/schedule";
  const command: Command = async (action, input) => {
    const key = JSON.stringify({ action, input }), requestId = requests.current.get(key) ?? crypto.randomUUID(); requests.current.set(key, requestId); setBusy(true); setMessage("");
    try { const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ requestId, action, input }) }), result = await response.json(); if (!response.ok) throw new Error(result.error); setData(result.data); requests.current.delete(key); setMessage("Saved."); return true; } catch (e) { setMessage(e instanceof Error ? e.message : "Could not save. You can retry this action."); return false; } finally { setBusy(false); }
  };
  const fmt = (time: string | number) => new Intl.DateTimeFormat("en-US", { timeZone: data.timezone, dateStyle: "medium", timeStyle: "long" }).format(new Date(time));
  const disabled = busy || !canEdit, name = (id: string | null) => data.team.find(m => m.id === id)?.name ?? (id ? "Former team member" : "Unassigned");
  return <section id="shifts" className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-semibold">{manager ? "Published shifts and drafts" : "My shifts and time"}</h2><button className="dd-secondary" disabled={busy} onClick={async () => { setBusy(true); try { const r = await fetch(endpoint, { cache: "no-store" }); if (!r.ok) throw new Error("Could not refresh shifts."); setData(await r.json()); } catch (e) { setMessage(e instanceof Error ? e.message : "Refresh failed."); } finally { setBusy(false); } }}>Refresh shifts</button></div><p className="text-sm text-slate-600">Times are displayed and entered in {data.timezone}. When clocks move back, new draft times use the first occurrence; review the displayed offset before publishing. Published shifts appear in the assigned employee&apos;s My work area. Editing a published shift returns it to draft for review and publishing.</p>{message && <p role="status" className="rounded-lg border bg-white p-3">{message}</p>}
    {manager && <div className="dd-card"><h3 className="font-semibold">Add a shift</h3><ShiftForm data={data} command={command} disabled={disabled}/></div>}
    {!manager && data.openEntry && <form className="dd-card space-y-3" onSubmit={e => { e.preventDefault(); void command("clock.out", { breakMinutes: Number(text(new FormData(e.currentTarget), "break")) }); }}><p>You are clocked in since {fmt(data.openEntry.clockInMs)} · {data.openEntry.jobLabel}</p><Field label="Actual unpaid break minutes"><input className={inputClass} type="number" name="break" min="0" max="600" defaultValue="0" required/></Field><button className="dd-primary" disabled={disabled}>Clock out</button></form>}
    <div className="grid gap-4 lg:grid-cols-2">{data.shifts.slice().sort((a, b) => a.start.localeCompare(b.start)).map(shift => <article className="dd-card space-y-3" key={`${shift.id}:${shift.revision}`}><h3 className="font-semibold">{shift.role} · {shift.station}</h3><p>{manager ? `${name(shift.employeeId)} · ` : ""}{shift.status}{shift.acknowledgedAt ? " · Employee acknowledged" : ""}</p><p className="text-sm">{fmt(shift.start)} → {fmt(shift.end)}<br/>{(shift.scheduledMinutes / 60).toFixed(2)} planned hours · {shift.breakMinutes} minutes unpaid break</p>{shift.note && <p className="text-sm">{shift.note}</p>}{manager && <p className="text-sm">Planned base labor {money(shift.plannedCost)}<br/>Recorded completed hours {(shift.actualMinutes / 60).toFixed(2)}{shift.onClock ? " · Still clocked in" : ""} · Actual base labor {money(shift.actualCost)}</p>}
      {manager && shift.status !== "cancelled" && !shift.attendanceComplete && !shift.onClock && <div className="space-y-3"><details><summary className="cursor-pointer">Edit assignment and times</summary><ShiftForm shift={shift} data={data} command={command} disabled={disabled}/></details><div className="flex gap-2">{shift.status === "draft" && <button className="dd-primary" disabled={disabled} onClick={() => void command("shift.publish", { id: shift.id, revision: shift.revision })}>Publish shift</button>}<button className="dd-secondary" disabled={disabled} onClick={() => void command("shift.cancel", { id: shift.id, revision: shift.revision })}>Cancel shift</button></div></div>}
      {!manager && shift.status === "published" && <div className="flex flex-wrap gap-2">{!shift.acknowledgedAt && <button className="dd-secondary" disabled={disabled} onClick={() => void command("shift.acknowledge", { id: shift.id, revision: shift.revision })}>Acknowledge my shift</button>}{!data.openEntry && <button className="dd-primary" disabled={disabled} onClick={() => void command("clock.in", { shiftId: shift.id })}>Clock in for this shift</button>}</div>}
    </article>)}</div>{!data.shifts.length && <p className="text-sm">{manager ? "No shifts yet. Add assigned shifts or leave a position unassigned to show a coverage gap." : "No published shifts are assigned to you yet."}</p>}
    {manager && <p className="text-sm text-slate-600">Base labor estimates use the rate captured on each shift. They exclude overtime, premiums, payroll taxes and benefits. Missing rates and unfinished attendance remain unknown. Review payroll separately.</p>}
    <div className="dd-card space-y-4"><h3 className="font-semibold">{manager ? "Time-away requests" : "My time-away requests"}</h3>{!manager && <form className="grid gap-3 sm:grid-cols-2" onSubmit={e => { e.preventDefault(); try { const f = new FormData(e.currentTarget); void command("absence.request", { start: instantForLocal(text(f, "start"), data.timezone), end: instantForLocal(text(f, "end"), data.timezone), reason: text(f, "reason") }); } catch (e) { setMessage(e instanceof Error ? e.message : "Check the dates."); } }}><fieldset disabled={disabled} className="contents"><Field label="Time away starts"><input className={inputClass} name="start" type="datetime-local" required/></Field><Field label="Time away ends"><input className={inputClass} name="end" type="datetime-local" required/></Field><Field label="Reason for your manager"><input className={inputClass} name="reason" minLength={3} maxLength={500} required/></Field><button className="dd-primary w-fit self-end">Request time away</button></fieldset></form>}{data.absences.map(a => <div className="space-y-2 rounded-lg border p-3" key={a.id}><p>{manager ? `${name(a.employeeId)} · ` : ""}{a.status} · {fmt(a.start)} → {fmt(a.end)}</p><p className="text-sm">{a.reason}</p>{manager && a.status === "requested" && <div className="flex gap-2">{["approved", "declined"].map(status => <button className="dd-secondary" disabled={disabled} key={status} onClick={() => void command("absence.review", { id: a.id, revision: a.revision, status })}>{status === "approved" ? "Approve time away" : "Decline request"}</button>)}</div>}{!manager && ["requested", "approved"].includes(a.status) && <button className="dd-secondary" disabled={disabled} onClick={() => void command("absence.cancel", { id: a.id, revision: a.revision })}>Cancel my request</button>}</div>)}{!data.absences.length && <p className="text-sm">No requests recorded.</p>}</div>
    <div className="dd-card space-y-3"><h3 className="font-semibold">{manager ? "Recorded shift attendance" : "My recorded attendance"}</h3>{data.entries.slice().reverse().map(entry => <article className="rounded-lg border p-3 text-sm" key={entry.id}><p>{manager ? `${name(entry.employeeId)} · ` : ""}{entry.jobLabel ?? "Time clock"}</p><p>{fmt(entry.clockInMs)} → {entry.clockOutMs ? fmt(entry.clockOutMs) : "On clock"} · {entry.breakMinutes} unpaid break minutes</p>{entry.note && <p>{entry.note}</p>}{manager && <details className="mt-2"><summary className="cursor-pointer">Correct recorded time with a reason</summary><form className="mt-3 grid gap-3 sm:grid-cols-2" onSubmit={e => { e.preventDefault(); try { const f = new FormData(e.currentTarget); void command("attendance.correct", { id: entry.id, revision: entry.revision, clockIn: instantForLocal(text(f, "start"), data.timezone), clockOut: instantForLocal(text(f, "end"), data.timezone), breakMinutes: Number(text(f, "break")), reason: text(f, "reason") }); } catch (e) { setMessage(e instanceof Error ? e.message : "Check the times."); } }}><fieldset disabled={disabled} className="contents"><Field label="Correct clock-in"><input className={inputClass} type="datetime-local" name="start" defaultValue={localDateTime(entry.clockInMs, data.timezone)} required/></Field><Field label="Correct clock-out"><input className={inputClass} type="datetime-local" name="end" defaultValue={entry.clockOutMs ? localDateTime(entry.clockOutMs, data.timezone) : ""} required/></Field><Field label="Correct unpaid break minutes"><input className={inputClass} name="break" type="number" min="0" max="600" defaultValue={entry.breakMinutes} required/></Field><Field label="Correction evidence and reason"><input className={inputClass} name="reason" minLength={10} maxLength={1000} required/></Field><button className="dd-primary w-fit">Save reviewed correction</button></fieldset></form></details>}</article>)}{!data.entries.length && <p className="text-sm">No attendance recorded.</p>}</div>
    {manager && data.audit.length > 0 && <details className="dd-card"><summary className="cursor-pointer font-semibold">Recent schedule and attendance history</summary><ul className="mt-3 space-y-2 text-sm">{data.audit.map((a, i) => <li key={i}>{fmt(a.at)} · {a.actor} · {a.action} · {a.id}</li>)}</ul></details>}
  </section>;
}
function ShiftForm({ shift, data, command, disabled }: { shift?: Data["shifts"][number]; data: Data; command: Command; disabled: boolean }) {
  const [error, setError] = useState("");
  return <form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={async e => { e.preventDefault(); setError(""); const form = e.currentTarget, f = new FormData(form); try { const ok = await command("shift.save", { ...(shift ? { id: shift.id, revision: shift.revision } : {}), employeeId: text(f, "employee") || null, role: text(f, "role"), station: text(f, "station"), start: instantForLocal(text(f, "start"), data.timezone), end: instantForLocal(text(f, "end"), data.timezone), breakMinutes: Number(text(f, "break")), hourlyRate: text(f, "rate") === "" ? null : Math.round(Number(text(f, "rate")) * 100), note: text(f, "note") }); if (ok && !shift) form.reset(); } catch (e) { setError(e instanceof Error ? e.message : "Check the shift."); } }}><fieldset disabled={disabled} className="contents"><Field label="Employee"><select className={inputClass} name="employee" defaultValue={shift?.employeeId ?? ""}><option value="">Unassigned position</option>{data.team.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></Field><Field label="Role"><input className={inputClass} name="role" defaultValue={shift?.role} maxLength={80} required/></Field><Field label="Station or location"><input className={inputClass} name="station" defaultValue={shift?.station} maxLength={80} required/></Field><Field label="Hourly base labor rate ($, optional)"><input className={inputClass} name="rate" type="number" min="0" max="9999.99" step="0.01" defaultValue={shift?.hourlyRate == null ? "" : (shift.hourlyRate / 100).toFixed(2)}/></Field><Field label="Shift starts"><input className={inputClass} name="start" type="datetime-local" defaultValue={shift ? localDateTime(shift.start, data.timezone) : ""} required/></Field><Field label="Shift ends"><input className={inputClass} name="end" type="datetime-local" defaultValue={shift ? localDateTime(shift.end, data.timezone) : ""} required/></Field><Field label="Planned unpaid break minutes"><input className={inputClass} name="break" type="number" min="0" max="600" defaultValue={shift?.breakMinutes ?? 0} required/></Field><Field label="Instructions visible to the employee"><input className={inputClass} name="note" defaultValue={shift?.note} maxLength={1000}/></Field><button className="dd-primary w-fit">{shift ? "Save shift as draft" : "Add draft shift"}</button>{error && <p role="alert">{error}</p>}</fieldset></form>;
}
