import { z } from "zod";
import { saveSecrets,setting } from "../connections/vault";
import { readSocial,changeSocial } from "./store";
import type { Platform } from "./model";
export const credentialsSchema=z.object({accessToken:z.string().max(10000).optional(),refreshToken:z.string().max(10000).optional(),clientId:z.string().max(500).optional(),clientSecret:z.string().max(2000).optional(),apiKey:z.string().max(2000).optional(),objectId:z.string().max(200).optional(),version:z.string().max(20).optional()});
export type SocialCredentials=z.infer<typeof credentialsSchema>;
function key(id:string){if(id!=="ga4"&&id!=="creative")z.uuid().parse(id);return `SOCIAL_CONNECTION_${id.replaceAll("-","_").toUpperCase()}`;}
export function credentials(id:string):SocialCredentials {const raw=setting(key(id));return raw?credentialsSchema.parse(JSON.parse(raw)):{};}
export function saveCredentials(id:string,input:SocialCredentials,userChange=true){const parsed=credentialsSchema.parse(input),before=credentials(id),changedApp=(parsed.clientId&&parsed.clientId!==before.clientId)||(parsed.clientSecret&&parsed.clientSecret!==before.clientSecret);const next={...before,...(changedApp?{accessToken:"",refreshToken:""}:{}),...Object.fromEntries(Object.entries(parsed).filter(([,v])=>v!==""))};saveSecrets({[key(id)]:JSON.stringify(next)});if(userChange&&id!=="ga4"&&id!=="creative")changeSocial(s=>{const a=s.accounts.find(a=>a.id===id);if(!a)throw new Error("Account not found.");a.revision++;});}
export function disconnectSocial(id:string){saveSecrets({[key(id)]:""});if(id!=="ga4"&&id!=="creative")changeSocial(s=>{const a=s.accounts.find(a=>a.id===id);if(a)a.revision++;});}
export function connectionInfo(id:string){const c=credentials(id);return {hasToken:!!(c.accessToken||c.refreshToken),hasClient:!!(c.clientId&&c.clientSecret),hasApiKey:!!c.apiKey,objectId:c.objectId??"",version:c.version??"",clientIdSet:!!c.clientId};}
export function socialConnections(){return Object.fromEntries([...readSocial().accounts.map(a=>a.id),"ga4"].map(id=>[id,connectionInfo(id)]));}
export const PLATFORM_HELP:Record<Platform,{setup:string;docs:string;oauth:boolean;competitors:boolean}>={
  instagram:{setup:"Use an Instagram professional account connected to a Facebook Page. Enter its Instagram business ID and a token with instagram_basic, instagram_manage_insights and required Page permissions. Competitor lookup needs your authorized business ID plus the competitor's username.",docs:"https://developers.facebook.com/docs/instagram-platform/instagram-api-with-facebook-login/",oauth:false,competitors:true},
  facebook:{setup:"Enter the Facebook Page ID and its Page access token with pages_read_engagement. Other Pages may require approved public-content access.",docs:"https://developers.facebook.com/docs/pages-api/",oauth:false,competitors:false},
  tiktok:{setup:"Use an approved TikTok Login Kit + Display API app with user.info.basic, user.info.profile, user.info.stats and video.list scopes. Save the client key/secret, then sign in.",docs:"https://developers.tiktok.com/docs/en/display-api-get-started",oauth:true,competitors:false},
  youtube:{setup:"Enable YouTube Data API v3 in Google Cloud. Save your OAuth client ID/secret and sign in. For a public competitor channel, enter its channel ID and a Data API key.",docs:"https://developers.google.com/youtube/v3/docs",oauth:true,competitors:true},
  linkedin:{setup:"Enter the organization ID and an authorized Community Management access token with rw_organization_admin. Reporting is limited to organizations you administer. API version defaults to 202607.",docs:"https://learn.microsoft.com/en-us/linkedin/marketing/community-management/organizations/share-statistics",oauth:false,competitors:false},
  pinterest:{setup:"Use a Pinterest business account and an approved API app. Save its app ID/secret and sign in with user_accounts:read, boards:read and pins:read.",docs:"https://developers.pinterest.com/docs/getting-started/set-up-authentication-and-authorization/",oauth:true,competitors:false},
  x:{setup:"Enter the username and your X developer app's bearer token. Your API plan must permit user lookup and timeline reads; reads may consume paid API credits.",docs:"https://docs.x.com/x-api/users/lookup/quickstart/user-lookup",oauth:false,competitors:true},
  threads:{setup:"Enter a Threads user access token with threads_basic and threads_manage_insights. Authorized accounts only; use a report import for competitor comparisons.",docs:"https://developers.facebook.com/docs/threads/insights/",oauth:false,competitors:false},
  bluesky:{setup:"Enter the full public Bluesky handle, such as brand.bsky.social. Public profile and recent post counts do not require a token.",docs:"https://docs.bsky.app/docs/api/app-bsky-feed-get-author-feed",oauth:false,competitors:true},
  other:{setup:"Import the platform's exported metrics using the downloadable template. Every imported measurement keeps its source and observation date.",docs:"",oauth:false,competitors:false},
};
