// @vitest-environment node
import { afterEach,beforeEach,describe,expect,it,vi } from "vitest";
import { mkdtempSync,readFileSync,rmSync,writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { publicRequest } from "../connections/public-http";
import { discoverLink,normalizeLink,parseWebsite,saveDiscovery,socialProfile } from "./discovery";
import { addAccount,assetPath,campaignStatus,changeSocial,readSocial,saveBrand,saveCampaign,saveSnapshot,socialDirectory } from "./store";
import { analyzeSales,buildPlan,campaignDrafts } from "./planner";
import { emptyMetrics,type SocialSnapshot,type SocialAccount } from "./model";
import { campaignCalendar,campaignCsv,localToUtc } from "./export";
import { accountInsights } from "./insights";
import { importSnapshot } from "./import";
import { rowsToPosts } from "./import-parser";
import { credentials,saveCredentials } from "./connections";
import { beginSocialOAuth,finishSocialOAuth } from "./oauth";
import { accessToken } from "./tokens";
import { pullSocialAccount } from "./providers";
import { prepareCreative,runCreative,saveCreativeKey,storeImage } from "./creative";
vi.mock("../connections/public-http",()=>({publicRequest:vi.fn()}));
let dir:string;
beforeEach(()=>{dir=mkdtempSync(path.join(tmpdir(),"shuug-social-test-"));vi.stubEnv("DEALDESK_DATA_DIR",dir);vi.stubEnv("GEMINI_API_KEY","");vi.stubEnv("OPENAI_API_KEY","");vi.mocked(publicRequest).mockReset();});
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllGlobals();vi.unstubAllEnvs();rmSync(dir,{recursive:true,force:true});});
const profile=(platform:SocialAccount["platform"]="bluesky",role:SocialAccount["role"]="brand")=>addAccount({platform,role,handle:platform==="bluesky"?"fixture.bsky.social":"fixture",label:"Fixture",profileUrl:platform==="bluesky"?"https://bsky.app/profile/fixture.bsky.social":`https://www.${platform}.com/fixture`,method:"api"});
const snapshot=(accountId:string,at:string,followers:number|null):SocialSnapshot=>({id:randomUUID(),accountId,at,source:"import",followers,posts:[],period:null,periodMetrics:null,partial:false,warnings:[],sourceUrl:"https://example.com"});
const signals=()=>analyzeSales([],readSocial(),"2026-09-10",true);
const draft=()=>campaignDrafts(readSocial(),signals(),"2026-09-10",1)[0];
const png=Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aH1cAAAAASUVORK5CYII=","base64");

describe("drop links",()=>{
  it.each([["instagram.com/fixture/?igsh=a","instagram"],["facebook.com/profile.php?id=123","facebook"],["tiktok.com/@fixture","tiktok"],["youtube.com/@fixture","youtube"],["linkedin.com/company/fixture","linkedin"],["pinterest.com/fixture","pinterest"],["twitter.com/fixture","x"],["threads.net/@fixture","threads"],["bsky.app/profile/fixture.bsky.social","bluesky"]])("recognizes %s without credentials",(url,platform)=>{expect(socialProfile(url)?.platform).toBe(platform);});
  it("rejects lookalike hosts, sharing links, private hosts, credentials and individual posts",()=>{for(const url of ["instagram.com.evil.com/fixture","example.com/instagram.com/fixture","instagram.com/p/abc","facebook.com/sharer.php?u=test","x.com/intent/post","tiktok.com/@fixture/video/123","youtube.com/watch?v=abc"])expect(socialProfile(url)).toBeNull();for(const url of ["http://example.com","https://127.0.0.1","https://site.local","https://owner:secret@example.com","https://example.com:444"])expect(()=>normalizeLink(url)).toThrow();});
  it("discovers exact social anchors, structured sameAs and products without trusting page instructions",()=>{const parsed=parseWebsite(`<meta content="Fixture &amp; Co" property="og:site_name"><meta name="description" content="A real product"><a href="https://instagram.com/fixture">IG</a><a href="https://instagram.com.evil.com/fake">bad</a><a href="/about">About</a><script type="application/ld+json">{"@graph":[{"@type":"Organization","sameAs":["https://x.com/fixture"]},{"@type":"Product","name":"Fixture Sauce","url":"/products/sauce","image":"/sauce.png"}]}</script>`,"https://example.com");expect(parsed.name).toBe("Fixture & Co");expect(parsed.profiles.map(p=>p.platform)).toEqual(["instagram","x"]);expect(parsed.products[0].url).toBe("https://example.com/products/sauce");expect(parsed.pages).toEqual(["https://example.com/about"]);});
  it("saves a social URL immediately without scraping or claiming connected metrics; repeated drops dedupe",async()=>{const discovery=await discoverLink("instagram.com/fixture");expect(publicRequest).not.toHaveBeenCalled();expect(saveDiscovery(discovery,"brand").added).toHaveLength(1);expect(saveDiscovery(discovery,"brand").existing).toHaveLength(1);expect(readSocial().accounts).toHaveLength(1);expect(readSocial().snapshots).toHaveLength(0);expect(readSocial().brand.platforms).toEqual(["instagram"]);});
  it("safely follows redirects through publicRequest and rejects private redirect targets",async()=>{vi.mocked(publicRequest).mockResolvedValueOnce({status:301,body:"",location:"https://localhost/private"});await expect(discoverLink("example.com")).rejects.toThrow(/public/);expect(publicRequest).toHaveBeenCalledTimes(1);});
  it("reads an about page for missing social profiles while preserving source URLs",async()=>{vi.mocked(publicRequest).mockResolvedValueOnce({status:200,body:'<title>Fixture</title><a href="/about">About</a>'}).mockResolvedValueOnce({status:200,body:'<a href="https://threads.com/@fixture">Threads</a>'});const discovery=await discoverLink("example.com");expect(discovery.profiles[0].source).toBe("https://example.com/about");saveDiscovery(discovery,"brand");expect(readSocial().brand.website).toBe("https://example.com/");});
});
describe("plans, observations and history",()=>{
  it("plans without AI, preserves edits across repeated builds and adds tagged destinations",()=>{const s=readSocial();saveBrand({...s.brand,website:"https://example.com/shop"},s.brandRevision);expect(buildPlan(signals(),"2026-09-10",2)).toBe(6);const first=readSocial().campaigns[0];expect(first.fields.destination).toContain("utm_source=instagram");saveCampaign({...first.fields,title:"Owner's edited post"},first.id,first.revision);expect(buildPlan(signals(),"2026-09-10",2)).toBe(0);expect(readSocial().campaigns[0].fields.title).toBe("Owner's edited post");expect(readSocial().campaigns.every(c=>c.status==="draft")).toBe(true);});
  it("rejects stale changes and requires a real draft review path before recording publication",()=>{const c=saveCampaign({...draft().fields,format:"Text",objective:"Community"});expect(()=>saveCampaign(c.fields,c.id,99)).toThrow(/changed/);expect(()=>campaignStatus(c.id,1,"published","https://x.com/fixture/status/1")).toThrow(/ready/);campaignStatus(c.id,1,"ready");campaignStatus(c.id,2,"published","https://x.com/fixture/status/1");expect(readSocial().campaigns[0].history).toHaveLength(3);expect(()=>saveCampaign(c.fields,c.id,3)).toThrow(/Duplicate/);campaignStatus(c.id,3,"archived");expect(()=>campaignStatus(c.id,4,"ready")).toThrow(/Archived/);});
  it("requires artwork for image posts and rejects references to missing assets",()=>{const c=saveCampaign({...draft().fields,destination:"https://example.com"});expect(()=>campaignStatus(c.id,1,"ready")).toThrow(/artwork/);expect(()=>saveCampaign({...c.fields,assetIds:[randomUUID()]})).toThrow(/missing/);});
  it("uses observation date rather than import order; missing metrics stay unknown",()=>{const a=profile();saveSnapshot(snapshot(a.id,"2026-09-09T12:00:00Z",100),1);saveSnapshot(snapshot(a.id,"2026-09-01T12:00:00Z",90),1);const result=accountInsights(a,readSocial());expect(result.latest?.followers).toBe(100);expect(result.growth).toBe(10);expect(result.average).toBeNull();});
  it("validates imported values and deduplicates a reviewed report",()=>{const a=profile(),posts=rowsToPosts([{post_id:"1",post_url:"https://bsky.app/profile/fixture.bsky.social/post/1",published_at:"2026-09-01T12:00:00Z",likes:"",comments:"0",views:"1,200"}]);expect(posts[0].metrics).toEqual({...emptyMetrics(),comments:0,views:1200});const input={accountId:a.id,observedAt:"2026-09-09T12:00:00Z",followers:20,sourceUrl:a.profileUrl,posts};expect(saveSnapshot(importSnapshot(input),1)).toBe(true);expect(saveSnapshot(importSnapshot(input),1)).toBe(false);expect(()=>rowsToPosts([{post_id:"2",published_at:"yesterday",likes:"lots"}])).toThrow();});
  it("keeps unknown costs unknown and excludes cancellations from sales evidence",()=>{const base={id:"1",date:"2026-09-08",customer:"Fixture",channel:"online" as const,status:"paid",revenueCents:1000,costCents:null,estimated:false,products:[{id:"sauce",name:"Sauce",quantity:2,unit:"bottle",revenueCents:1000,costCents:null,estimated:false}]};const s=analyzeSales([base,{...base,id:"2",status:"cancelled"}],readSocial(),"2026-09-10",false);expect(s.orders).toBe(1);expect(s.revenueCents).toBe(1000);expect(s.products[0].profitCents).toBeNull();expect(s.traffic).toBeNull();});
  it("exports real timezone dates and escapes spreadsheet/calendar injections",()=>{const c=draft();c.fields.title="=EVIL\nBEGIN:VEVENT";expect(campaignCsv([c])).toContain("'=EVIL");const calendar=campaignCalendar([c]);expect(calendar.match(/^BEGIN:VEVENT$/gm)).toHaveLength(1);expect(calendar).toContain("\\nBEGIN:VEVENT");expect(localToUtc("2026-09-10","12:00","America/New_York")).toBe("20260910T160000Z");expect(localToUtc("2026-01-10","12:00","America/New_York")).toBe("20260110T170000Z");expect(()=>localToUtc("2026-03-08","02:30","America/New_York")).toThrow(/daylight/);});
  it("fails closed on corrupted history",()=>{writeFileSync(path.join(socialDirectory(),"workspace.json"),"broken");expect(()=>readSocial()).toThrow(/Restore/);});
});
describe("OAuth and platform adapters",()=>{
  it("rotates refresh tokens without invalidating the profile observation revision",async()=>{const a=profile("tiktok");saveCredentials(a.id,{clientId:"client",clientSecret:"fixture-secret",refreshToken:"old-refresh"});const current=readSocial().accounts[0],mock=vi.fn().mockResolvedValue(new Response(JSON.stringify({access_token:"fresh-access",refresh_token:"new-refresh",expires_in:3600})));vi.stubGlobal("fetch",mock);expect(await accessToken(current)).toBe("fresh-access");expect(credentials(a.id).refreshToken).toBe("new-refresh");expect(readSocial().accounts[0].revision).toBe(current.revision);expect(await accessToken(current)).toBe("fresh-access");expect(mock).toHaveBeenCalledTimes(1);expect(saveSnapshot(snapshot(a.id,new Date().toISOString(),10),current.revision)).toBe(true);});
  it("consumes OAuth state once and binds it to connection settings",async()=>{const a=profile("youtube");saveCredentials(a.id,{clientId:"client",clientSecret:"fixture-secret"});const first=beginSocialOAuth(a.id);saveCredentials(a.id,{clientId:"changed-client"});const mock=vi.fn();vi.stubGlobal("fetch",mock);await expect(finishSocialOAuth(first.state,"code")).rejects.toThrow(/changed/);expect(mock).not.toHaveBeenCalled();await expect(finishSocialOAuth(first.state,"code")).rejects.toThrow(/used/);});
  it("pulls Bluesky without credentials and preserves missing view counts",async()=>{const a=profile();const mock=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({handle:a.handle,followersCount:45}))).mockResolvedValueOnce(new Response(JSON.stringify({feed:[{post:{uri:"at://did:plc:fixture/app.bsky.feed.post/123",author:{handle:a.handle},record:{createdAt:"2026-09-01T12:00:00Z",text:"Fixture post"},likeCount:3,replyCount:2,repostCount:1}}]})));vi.stubGlobal("fetch",mock);const report=await pullSocialAccount(a);expect(report.followers).toBe(45);expect(report.posts[0].metrics.views).toBeNull();expect(report.posts[0].metrics.likes).toBe(3);expect(mock.mock.calls[0][1].headers.Authorization).toBeUndefined();});
  it("rejects a TikTok token for a different profile instead of misattributing its stats",async()=>{const a=profile("tiktok");saveCredentials(a.id,{accessToken:"fixture-token"});vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response(JSON.stringify({data:{user:{username:"someoneelse",follower_count:500}}}))));await expect(pullSocialAccount(a)).rejects.toThrow(/does not match/);});
  it("normalizes Meta timestamps and binds the Instagram business ID to the pasted username",async()=>{const a=profile("instagram");saveCredentials(a.id,{accessToken:"fixture-token",objectId:"123"});vi.stubGlobal("fetch",vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({username:"fixture",followers_count:20}))).mockResolvedValueOnce(new Response(JSON.stringify({data:[{id:"9",timestamp:"2026-09-01T12:00:00+0000",caption:"Fixture",like_count:2,comments_count:1}]}))));const report=await pullSocialAccount(a);expect(report.posts[0].publishedAt).toBe("2026-09-01T12:00:00.000Z");expect(report.posts[0].metrics.reach).toBeNull();});
});
describe("private artwork and billed request boundaries",()=>{
  it("retains private reference bytes and rejects fake image files",()=>{const asset=storeImage(png,"product.png");expect(readFileSync(assetPath(asset))).toEqual(png);expect(()=>storeImage(Buffer.from("<svg>pretend.png</svg>"),"fake.png")).toThrow();});
  it("prepares a no-package concept without references and permits only one provider submission",async()=>{const c=saveCampaign(draft().fields);saveCreativeKey("openai","fixture-only-openai-key");const job=prepareCreative(c.id,"openai","1:1");expect(job.prompt).toContain("do not invent a branded package");const mock=vi.fn().mockResolvedValue(new Response(JSON.stringify({data:[{b64_json:png.toString("base64")}]})));vi.stubGlobal("fetch",mock);const asset=await runCreative(job.id);expect(asset.kind).toBe("generated");expect(JSON.parse(mock.mock.calls[0][1].body).n).toBe(1);await expect(runCreative(job.id)).rejects.toThrow(/already submitted/);expect(mock).toHaveBeenCalledTimes(1);});
  it("sends reviewed references to Gemini and does not mark a campaign ready automatically",async()=>{const c=saveCampaign(draft().fields),asset=storeImage(png,"reference.png");changeSocial(s=>{s.brand.referenceAssetIds=[asset.id];s.brandRevision++;});saveCreativeKey("gemini","fixture-only-gemini-key");const job=prepareCreative(c.id,"gemini","4:5"),mock=vi.fn().mockResolvedValue(new Response(JSON.stringify({candidates:[{content:{parts:[{inlineData:{mimeType:"image/png",data:png.toString("base64")}}]}}]})));vi.stubGlobal("fetch",mock);await runCreative(job.id);const body=JSON.parse(mock.mock.calls[0][1].body);expect(body.contents[0].parts[1].inline_data.data).toBe(png.toString("base64"));expect(body.generationConfig.responseFormat.image.aspectRatio).toBe("4:5");expect(readSocial().campaigns[0].status).toBe("draft");});
  it("invalidates a prepared prompt after a brand edit and never retries an ambiguous provider failure",async()=>{const c=saveCampaign(draft().fields);saveCreativeKey("gemini","fixture-only-gemini-key");const job=prepareCreative(c.id,"gemini","1:1");changeSocial(s=>{s.brandRevision++;});const mock=vi.fn().mockRejectedValue(new TypeError("network"));vi.stubGlobal("fetch",mock);await expect(runCreative(job.id)).rejects.toThrow(/changed/);expect(mock).not.toHaveBeenCalled();const next=prepareCreative(c.id,"gemini","1:1");await expect(runCreative(next.id)).rejects.toThrow(/could not be confirmed/);await expect(runCreative(next.id)).rejects.toThrow(/already submitted/);expect(mock).toHaveBeenCalledTimes(1);});
});
