import { closeSync,mkdirSync,openSync,readFileSync,renameSync,unlinkSync,writeFileSync } from "node:fs";
import { createHash,randomUUID } from "node:crypto";
import path from "node:path";
import { z } from "zod";
import { dataDirectory } from "../connections/vault";
import { accountSchema,brandSchema,campaignFields,defaultBrand,type Brand,type CampaignFields,type CampaignStatus,type CreativeAsset,type SocialAccount,type SocialSnapshot,type SocialState,type TrafficReport } from "./model";
export function socialDirectory(){const dir=path.join(dataDirectory(),"social");mkdirSync(dir,{recursive:true,mode:0o700});return dir;}
function blank():SocialState{return {version:1,brand:defaultBrand(),brandRevision:1,accounts:[],snapshots:[],traffic:[],campaigns:[],assets:[],jobs:[]};}
export function readSocial():SocialState {
  try{const data=JSON.parse(readFileSync(path.join(socialDirectory(),"workspace.json"),"utf8"));if(data.version!==1||!["accounts","snapshots","traffic","campaigns","assets","jobs"].every(k=>Array.isArray(data[k])))throw new Error("Invalid social workspace");brandSchema.parse(data.brand);return data;}
  catch(e){if((e as NodeJS.ErrnoException).code==="ENOENT")return blank();throw new Error("Saved social marketing data could not be read. Restore its saved file before continuing.");}
}
/** Keep network work outside this synchronous, cross-process file lock. */
export function changeSocial<T>(fn:(state:SocialState)=>T):T {
  const file=path.join(socialDirectory(),"write.lock");let fd:number;
  try{fd=openSync(file,"wx",0o600);}catch(e){if((e as NodeJS.ErrnoException).code==="EEXIST")throw new Error("Another marketing change is being saved. Try again.");throw e;}
  try{const state=readSocial(),result=fn(state),temp=path.join(socialDirectory(),`${randomUUID()}.tmp`);writeFileSync(temp,JSON.stringify(state),{mode:0o600});renameSync(temp,path.join(socialDirectory(),"workspace.json"));return result;}finally{closeSync(fd);unlinkSync(file);}
}
export function saveBrand(brand:Brand,revision:number){return changeSocial(s=>{if(s.brandRevision!==revision)throw new Error("Your brand settings changed. Refresh before saving.");const valid=brandSchema.parse(brand);if(valid.referenceAssetIds.some(id=>!s.assets.some(a=>a.id===id)))throw new Error("A selected brand reference is missing.");s.brand=valid;s.brandRevision++;return s.brand;});}
export function addAccount(input:Pick<SocialAccount,"platform"|"label"|"handle"|"role"|"method"|"profileUrl">){return changeSocial(s=>{if(s.accounts.length>=100)throw new Error("This workspace supports up to 100 social profiles.");const prior=s.accounts.find(a=>!a.disabled&&a.platform===input.platform&&a.handle.toLowerCase()===input.handle.toLowerCase()&&a.role===input.role);if(prior)throw new Error("That profile is already tracked. Open its connection to update it.");const account=accountSchema.parse({...input,id:randomUUID(),revision:1,disabled:false,createdAt:new Date().toISOString()});s.accounts.push(account);return account;});}
export function saveSnapshot(snapshot:SocialSnapshot,accountRevision:number){return changeSocial(s=>{const account=s.accounts.find(a=>a.id===snapshot.accountId);if(!account||account.disabled||account.revision!==accountRevision)throw new Error("The social connection changed while refreshing. Refresh again.");if(snapshot.fingerprint&&s.snapshots.some(r=>r.accountId===snapshot.accountId&&r.fingerprint===snapshot.fingerprint))return false;s.snapshots.push(snapshot);return true;});}
export function saveTraffic(report:TrafficReport){return changeSocial(s=>{s.traffic.push(report);return report;});}
export function saveCampaign(fields:CampaignFields,id?:string,revision?:number){return changeSocial(s=>{
  const valid=campaignFields.parse(fields),now=new Date().toISOString();if(valid.assetIds.some(id=>!s.assets.some(a=>a.id===id)))throw new Error("An attached creative asset is missing.");let row=s.campaigns.find(c=>c.id===id);
  if(id&&!row)throw new Error("Campaign not found.");
  if(row){if(row.revision!==revision)throw new Error("This campaign changed. Reload before editing.");if(row.status==="published"||row.status==="archived")throw new Error("Duplicate this campaign to plan another post.");row.fields=valid;row.status="draft";row.revision++;row.updatedAt=now;}
  else{row={id:randomUUID(),revision:1,createdAt:now,updatedAt:now,status:"draft",fields:valid,history:[]};s.campaigns.push(row);}
  row.history.push({at:now,revision:row.revision,status:row.status,fields:structuredClone(row.fields)});return row;
});}
export function campaignStatus(id:string,revision:number,status:CampaignStatus,publishedUrl="") {return changeSocial(s=>{const row=s.campaigns.find(c=>c.id===id);if(!row||row.revision!==revision)throw new Error("This campaign changed. Refresh it first.");if(row.status==="archived")throw new Error("Archived posts stay in history. Duplicate to create a new draft.");if(status==="ready"){if(row.status!=="draft")throw new Error("Only a draft can be marked ready.");if(!row.fields.caption.trim())throw new Error("Add a caption before marking ready.");if(["Website visits","Sales"].includes(row.fields.objective)&&!row.fields.destination)throw new Error("Add a destination URL for this campaign.");if(["Photo","Carousel","Story"].includes(row.fields.format)&&!row.fields.assetIds.length)throw new Error("Attach reviewed artwork before marking this image post ready.");const limit=row.fields.platform==="x"?280:row.fields.platform==="bluesky"?300:row.fields.platform==="threads"?500:row.fields.platform==="instagram"?2200:6000;if([...row.fields.caption].length>limit)throw new Error(`Shorten this caption to ${limit} characters for this platform.`);}if(status==="published"&&row.status!=="ready")throw new Error("Review this post and mark it ready first.");if(row.status==="published"&&status!=="archived")throw new Error("Published records stay in history. Duplicate to make a new post.");if(status==="published"){const parsed=campaignFields.shape.publishedUrl.parse(publishedUrl);if(!parsed)throw new Error("Paste the live post URL to record publication.");row.fields.publishedUrl=parsed;}row.status=status;row.revision++;row.updatedAt=new Date().toISOString();row.history.push({at:row.updatedAt,revision:row.revision,status,fields:structuredClone(row.fields)});return row;});}
export function assetPath(asset:CreativeAsset){z.uuid().parse(asset.id);if(!["png","jpg","webp"].includes(asset.extension))throw new Error("Invalid creative file.");return path.join(socialDirectory(),`${asset.id}.${asset.extension}`);}
export function saveAsset(asset:CreativeAsset,bytes:Buffer){if(createHash("sha256").update(bytes).digest("hex")!==asset.hash)throw new Error("Creative checksum mismatch.");writeFileSync(assetPath(asset),bytes,{mode:0o600,flag:"wx"});try{return changeSocial(s=>{s.assets.push(asset);return asset;});}catch(e){unlinkSync(assetPath(asset));throw e;}}
export function checksum(value:string|Buffer){return createHash("sha256").update(value).digest("hex");}
