/** Pure capability definitions; safe to share with navigation and the client UI. */
export const packs = [
  { id: "crm", label: "CRM & contacts", tools: ["customers", "customer-imports", "pipeline", "contracts", "service-clients", "service-intake", "assessments"], profiles: [] },
  { id: "appointments", label: "Appointments & reservations", tools: ["service-booking", "service-resources", "service-capacity"], profiles: ["service"] },
  { id: "inventory", label: "Inventory", tools: ["operations", "costs", "traceability", "module:equipment-log"], profiles: ["product"] },
  { id: "jobs", label: "Projects & jobs", tools: ["service-catalog", "service-proposals", "service-agreements", "service-work", "service-resources", "service-mobile", "service-changes", "service-completion", "service-billing", "service-recurring", "service-profitability", "service-capacity", "service-rework", "service-renewals"], profiles: ["service"] },
  { id: "production", label: "Production & costing", tools: ["production", "costs", "traceability"], profiles: ["product"] },
  { id: "wholesale", label: "Wholesale", tools: ["orders", "products", "samples", "distribution", "visits", "territories", "delivery-routes"], profiles: ["product"] },
  { id: "product_sales", label: "Product sales & merchandise", tools: ["orders", "products", "amazon", "shopify"], profiles: ["product"] },
  { id: "donations", label: "Donations & funding", tools: ["nonprofit-donors", "nonprofit-donations", "nonprofit-pledges", "nonprofit-acknowledgments", "nonprofit-restrictions", "nonprofit-grants", "nonprofit-reimbursements", "nonprofit-funding", "nonprofit-campaigns", "nonprofit-events"], profiles: ["nonprofit"] },
  { id: "memberships", label: "Memberships", tools: ["nonprofit-memberships"], profiles: [] },
  { id: "time", label: "Payroll, shifts & time", tools: ["people", "timeclock", "worktrack", "performance", "service-time", "service-resources"], profiles: [] },
  { id: "accounting", label: "Accounting & payments", tools: ["finance", "accounting", "chart-of-accounts", "ledger", "balance-sheet", "sales-tax", "cashflow", "collections", "reconciliation", "payments", "expenses", "reports", "service-collections"], profiles: [] },
  { id: "purchasing", label: "Purchasing & suppliers", tools: ["invoice-audit", "expenses"], profiles: [] },
  { id: "marketing", label: "Marketing", tools: ["marketing", "google-ads", "amazon-marketing", "social", "module:customer-feedback"], profiles: [] },
  { id: "portal", label: "Customer portal", tools: ["service-portal"], profiles: ["service"] },
  { id: "programs", label: "Programs, participants & outcomes", tools: ["nonprofit-budgets", "nonprofit-enrollment", "nonprofit-participants", "nonprofit-sessions", "nonprofit-outcomes", "nonprofit-reporting", "nonprofit-events"], profiles: ["nonprofit"] },
  { id: "volunteers", label: "Volunteer coordination", tools: ["nonprofit-volunteers", "nonprofit-shifts"], profiles: ["nonprofit"] },
  { id: "governance", label: "Board & governance", tools: ["nonprofit-governance"], profiles: ["nonprofit"] },
  { id: "fleet", label: "Fleet & commercial accounts", tools: [], profiles: ["service"] },
  { id: "auto_repair", label: "Vehicles & auto repair", tools: [], profiles: ["service"] },
  { id: "restaurant", label: "Restaurant operations", tools: ["restaurant", "restaurant-orders", "restaurant-online", "restaurant-booking-rules", "restaurant-analysis"], profiles: ["product"] },
  { id: "childcare", label: "Childcare, classes & lessons", tools: ["childcare", "assessments"], profiles: ["service"] },
] as const;
export type PackId = typeof packs[number]["id"];
export interface IndustryQuestion { id: string; label: string; detail: string; default: boolean; pack?: PackId; connection?: "quickbooks" }
export interface IndustryTemplate { id: string; label: string; keywords: string; version: number; description: string; packs: PackId[]; profiles: ("product" | "service" | "nonprofit")[]; serviceTypes: ("field" | "professional" | "appointment" | "managed")[]; questions: IndustryQuestion[] }
const q = (id: string, label: string, pack: PackId, enabled = true, detail = "You can change this later."): IndustryQuestion => ({ id, label, pack, default: enabled, detail });
const accounting: IndustryQuestion = { id: "quickbooks", label: "Do you use QuickBooks?", default: false, connection: "quickbooks", detail: "We will include QuickBooks in your connection checklist. This does not authorize an account." };
const industry = (id: string, label: string, keywords: string, base: PackId[], questions: IndustryQuestion[], serviceTypes: IndustryTemplate["serviceTypes"] = ["field"], profiles: IndustryTemplate["profiles"] = ["service"]): IndustryTemplate => ({ id, label, keywords, description: `Start with the work a ${label.toLowerCase()} needs, then adjust any capability.`, version: 1, packs: base, profiles, serviceTypes, questions });
export const industries: IndustryTemplate[] = [
  industry("auto-repair", "Auto repair shop", "mechanic garage automotive vehicles fleet", ["crm", "jobs", "accounting", "auto_repair"], [q("appointments", "Do you schedule appointments?", "appointments"), q("parts", "Do you stock parts?", "inventory"), q("job-time", "Do technicians clock time against jobs?", "time"), accounting, q("electronic-estimates", "Do customers approve estimates electronically?", "portal"), q("fleet", "Do you serve fleet or commercial accounts?", "fleet", false, "Adds fleet accounts and commercial agreement records."), q("product-sales", "Do you also sell products over the counter?", "product_sales", false)]),
  industry("restaurant", "Restaurant", "cafe bar diner food kitchen catering", ["crm", "restaurant", "accounting", "purchasing"], [q("reservations", "Do you take reservations?", "appointments"), q("ingredients", "Do you track ingredient inventory?", "inventory"), q("food-cost", "Do you cost recipes and prepared food?", "production"), q("shifts", "Do staff work scheduled shifts?", "time"), accounting, q("catering", "Do you sell wholesale or catering orders?", "wholesale", false), q("promotions", "Do you run marketing campaigns?", "marketing", false)], [], ["product"]),
  industry("hvac", "HVAC company", "heating cooling air conditioning contractor", ["crm", "jobs", "accounting"], [q("dispatch", "Do you schedule customer visits?", "appointments"), q("parts", "Do you stock equipment or parts?", "inventory"), q("time", "Do technicians record job time?", "time"), accounting, q("approvals", "Should customers approve estimates online?", "portal"), q("products", "Do you sell equipment separately?", "product_sales", false)]),
  industry("landscaping", "Landscaper", "lawn garden grounds tree maintenance", ["crm", "jobs", "accounting"], [q("visits", "Do you schedule recurring visits?", "appointments"), q("supplies", "Do you track supplies and equipment?", "inventory"), q("crews", "Do crews record their time?", "time"), accounting, q("approvals", "Do customers approve work online?", "portal"), q("marketing", "Do you manage marketing campaigns?", "marketing", false)]),
  industry("wholesale", "Wholesale distributor", "bulk distribution warehouse b2b products", ["crm", "wholesale", "accounting", "purchasing"], [q("stock", "Do you hold inventory?", "inventory"), q("make", "Do you make or assemble products?", "production", false), q("staff", "Do warehouse staff record time?", "time"), accounting, q("retail", "Do you also sell directly to consumers?", "product_sales", false), q("marketing", "Do you manage marketing campaigns?", "marketing", false)], [], ["product"]),
  industry("agency", "Marketing agency", "professional consulting advertising design digital", ["crm", "jobs", "accounting", "marketing"], [q("meetings", "Do clients book appointments?", "appointments", false), q("time", "Do you bill or budget project time?", "time"), accounting, q("approval", "Do clients approve proposals online?", "portal"), q("purchasing", "Do you purchase services from subcontractors?", "purchasing"), q("products", "Do you also sell products?", "product_sales", false)], ["professional"]),
  industry("nonprofit", "Community nonprofit", "charity foundation community youth programs donations", ["crm", "donations", "programs", "governance", "accounting"], [q("volunteers", "Do volunteers deliver part of your work?", "volunteers"), q("members", "Do you have paid or renewing memberships?", "memberships", false), q("staff", "Do you track staff time?", "time"), accounting, q("merchandise", "Do you sell merchandise?", "product_sales", false), q("services", "Do you charge for services or projects?", "jobs", false), q("marketing", "Do you manage public outreach campaigns?", "marketing", true)], [], ["nonprofit"]),
  industry("gym", "Gym", "fitness club studio trainer classes", ["crm", "jobs", "appointments", "accounting"], [q("memberships", "Do you offer memberships?", "memberships"), q("staff", "Do trainers record time?", "time"), accounting, q("portal", "Should customers approve plans online?", "portal"), q("merchandise", "Do you sell merchandise or equipment?", "product_sales", false), q("marketing", "Do you run marketing campaigns?", "marketing", true)], ["appointment"]),
  industry("salon", "Salon", "hair beauty barber spa appointments", ["crm", "jobs", "appointments", "accounting"], [q("stock", "Do you stock supplies?", "inventory"), q("staff", "Do staff track shifts and hours?", "time"), accounting, q("products", "Do you sell products?", "product_sales", true), q("portal", "Should customers review plans online?", "portal", false), q("marketing", "Do you run marketing campaigns?", "marketing", true)], ["appointment"]),
  industry("construction", "Construction company", "builder contracting trades renovation", ["crm", "jobs", "accounting", "purchasing"], [q("schedule", "Do you schedule site visits and resources?", "appointments"), q("stock", "Do you hold materials or equipment?", "inventory"), q("time", "Do crews record project time?", "time"), accounting, q("approvals", "Do customers approve estimates and changes online?", "portal"), q("make", "Do you fabricate or assemble products?", "production", false)]),
  industry("home-daycare", "Home daycare", "childcare daycare babysitting preschool kids children in-home", ["crm", "childcare", "accounting"], [q("staff", "Do you have staff who clock hours?", "time", false), accounting, q("classes", "Do you also run classes or lessons (art, swim, music)?", "appointments", false), q("fundraising", "Do you run fundraising (PTO/PTA)?", "donations", false), q("updates", "Do you send parents updates and reminders?", "marketing", false), q("supplies", "Do you sell supplies or merchandise?", "product_sales", false)], ["managed"]),
  industry("school", "School / preschool", "school preschool kindergarten education classroom students teachers", ["crm", "childcare", "accounting"], [q("staff", "Do teachers and staff record hours?", "time"), accounting, q("programs", "Do you run structured programs and track outcomes?", "programs", false), q("fundraising", "Do you run PTO/PTA fundraising?", "donations", true), q("updates", "Do you send families updates and campaigns?", "marketing", true), q("supplies", "Do you sell uniforms or supplies?", "product_sales", false)], ["managed"]),
  industry("classes", "Classes & lessons", "art swim music dance tutoring lessons studio classes coaching", ["crm", "childcare", "appointments", "accounting"], [q("staff", "Do instructors record hours?", "time", false), accounting, q("memberships", "Do you sell memberships or class packages?", "memberships", false), q("marketing", "Do you run marketing campaigns?", "marketing", true), q("gear", "Do you sell products or gear?", "product_sales", false)], ["appointment"]),
];
export function packDefaultVisible(item: { id: string; group: string; capabilityPacks?: string[] }, selected: string[] | undefined | null): boolean {
  if (selected == null) return !item.capabilityPacks?.length;
  if (item.capabilityPacks?.length) return item.capabilityPacks.every(p => selected.includes(p));
  if (item.group === "Workspace" || (item.group === "Setup" && !item.id.startsWith("nonprofit-")) || item.id === "tasks" || item.id.startsWith("tracker:")) return true;
  return packs.some(p => selected.includes(p.id) && (p.tools as readonly string[]).includes(item.id));
}
