// @vitest-environment node
import { afterEach,beforeEach,expect,it,vi } from "vitest";
import { mkdtempSync,rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { matchColumns,mapCustomerRows,type ImportCustomer } from "./import-model";
import { previewCustomers,commitCustomers } from "./import";
import { importedArchive } from "./import-archive";
import { buildNewDeal,MemoryDealStore,type DealStore,type NewCustomerInput } from "../data/store";
import type { CustomerDeal } from "../data/model";
let folder:string;
beforeEach(()=>{folder=mkdtempSync(path.join(tmpdir(),"shuug-customer-import-"));vi.stubEnv("DEALDESK_DATA_DIR",folder);});afterEach(()=>{vi.unstubAllEnvs();rmSync(folder,{recursive:true,force:true});});
const customer:ImportCustomer={company:"Import Test Market",buyerName:"Test buyer",buyerEmail:"buyer@example.com",phone:"555-0100",billingAddress:"1 Example Street",shippingAddress:"1 Example Street",website:"https://example.com",region:"MA",accountOwner:"Owner",channel:"store",externalId:"42"};
function repo(initial:CustomerDeal[]=[]){const map=new Map(initial.map(d=>[d.customer.id,d]));return {durable:true,listCustomers:async()=>[...map.values()].map(d=>({id:d.customer.id,company:d.customer.company,buyerName:d.customer.buyerName})),getDeal:async(id:string)=>map.get(id)||null,createCustomer:vi.fn(async(input:NewCustomerInput,id?:string)=>{const key=id||"new";if(!map.has(key))map.set(key,buildNewDeal(key,input));return map.get(key)!;}),saveAgreement:vi.fn(),listOrders:async()=>[],getOrder:async()=>null,createOrder:vi.fn()} satisfies DealStore;}
it("recognizes common export columns and preserves phones and addresses",()=>{const rows=[{"Customer name":"Buyer Market","Email address":"buyer@example.com",Telephone:"0123",Address:"Street",Channel:"Bulk"}],mapping=matchColumns(Object.keys(rows[0]));expect(mapCustomerRows(rows,mapping,"store")[0]).toMatchObject({customer:{company:"Buyer Market",buyerEmail:"buyer@example.com",phone:"0123",billingAddress:"Street",shippingAddress:"Street",channel:"wholesale_bulk"},issue:""});});
it("accepts name-only contacts without fabricating an email and reports bad rows",()=>{const mapping={company:"Company",buyerEmail:"Email",channel:"Channel"},rows=mapCustomerRows([{Company:"A customer"},{Company:"Bad email",Email:"not an email"},{Company:"Bad channel",Channel:"anything"}],mapping,"store");expect(rows[0].customer?.buyerEmail).toBe("");expect(rows[1].issue).toBeTruthy();expect(rows[2].issue).toContain("Unknown sales channel");});
it("previews duplicates without writes, persists selected contacts, and deduplicates retries",async()=>{const store=repo(),preview=await previewCustomers([{index:0,customer,issue:""},{index:1,customer:{...customer},issue:""}],"QuickBooks","qbo:test-realm",store);expect(store.createCustomer).not.toHaveBeenCalled();expect(preview.rows[1].issue).toContain("Repeated");const result=await commitCustomers(preview.id,[0],store);expect(result.imported).toBe(1);expect(importedArchive().deals[0].customer).toMatchObject({phone:"555-0100",quickbooksCustomerId:"42"});expect(importedArchive().sources["qbo:test-realm:42"]).toBe(result.results[0].customerId);expect((await commitCustomers(preview.id,[0],store)).imported).toBe(0);expect(store.createCustomer).toHaveBeenCalledTimes(1);});
it("preserves existing pricing by skipping matching customers",async()=>{const existing=buildNewDeal("existing",{...customer,website:null,requiresPO:false,quickbooksCustomerId:null});existing.agreement.lines[0].unitPriceCents=12345;const store=repo([existing]),preview=await previewCustomers([{index:0,customer,issue:""}],"File","sheet",store);expect(preview.rows[0].duplicateId).toBe("existing");await commitCustomers(preview.id,[0],store);expect(store.createCustomer).not.toHaveBeenCalled();expect((await store.getDeal("existing"))?.agreement.lines[0].unitPriceCents).toBe(12345);});
it("uses stable import IDs to recover a committed account when the import receipt was interrupted",async()=>{const first=repo(),preview=await previewCustomers([{index:0,customer,issue:""}],"QuickBooks","qbo:company",first);const original=await commitCustomers(preview.id,[0],first);const archive=importedArchive();expect(archive.deals[0].customer.id).toMatch(/^import-/);const restarted=repo(archive.deals);const second=await previewCustomers([{index:0,customer,issue:""}],"QuickBooks","qbo:company",restarted);expect(second.rows[0].duplicateId).toBe(original.results[0].customerId);});
it("rehydrates imported profiles and changed pricing in a fresh local store",async()=>{const store=new MemoryDealStore(),p=await previewCustomers([{index:0,customer,issue:""}],"QuickBooks","qbo:restart",store);const done=await commitCustomers(p.id,[0],store),id=done.results[0].customerId!;const deal=(await store.getDeal(id))!;deal.agreement.lines[0].unitPriceCents=8800;await store.saveAgreement({agreement:deal.agreement,changedBy:"Owner",note:"New agreement"});const restored=await new MemoryDealStore().getDeal(id);expect(restored?.customer.phone).toBe("555-0100");expect(restored?.agreement.lines[0].unitPriceCents).toBe(8800);});
