"use client";
import { useEffect, useState } from "react";
import type { AppointmentOffer } from "@/lib/workspace/store";
type Data = { offers: AppointmentOffer[]; jobs: { id: string; title: string; client: string }[]; resources: { id: string; title: string }[] };
export function AppointmentAvailability() {
  const [data, setData] = useState<Data>({ offers: [], jobs: [], resources: [] }), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  const [job, setJob] = useState(""), [resource, setResource] = useState(""), [start, setStart] = useState(""), [end, setEnd] = useState(""), [buffer, setBuffer] = useState(0);
  useEffect(() => { let active = true; void fetch("/api/setup/appointments", { cache: "no-store" }).then(async r => { const v = await r.json(); if (!r.ok) throw new Error(v.error); if (active) setData(v); }).catch(e => { if (active) setMessage(e.message); }); return () => { active = false; }; }, []);
  async function command(action: string, input: unknown) {
    setBusy(true); setMessage("");
    try { const response = await fetch("/api/setup/appointments", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, input }) }), result = await response.json(); if (!response.ok) throw new Error(result.error);
      const updated = await fetch("/api/setup/appointments", { cache: "no-store" }); if (!updated.ok) throw new Error("Saved, but refresh failed. Reload the page."); setData(await updated.json()); setMessage(action === "publish" ? "Time published to the linked customer's booking page." : "Availability withdrawn.");
    } catch (e) { setMessage(e instanceof Error ? e.message : "Could not update availability."); } finally { setBusy(false); }
  }
  return <section className="rounded-xl border bg-white p-5"><h2 className="text-xl font-semibold">Publish service availability</h2><p className="mt-2 text-sm text-slate-600">Offer appointment times for agreed work. The agreement must be signed, any required deposit confirmed, and the staff member, room or equipment active. A customer’s booking reserves the resource and appears in Service → Booking.</p><form className="mt-4 grid gap-4 sm:grid-cols-2" onSubmit={e => { e.preventDefault(); void command("publish", { jobId: job, resourceId: resource, start: new Date(start).toISOString(), end: new Date(end).toISOString(), buffer }); }}><label className="text-sm">Work order<select className="dd-input mt-1 w-full" required value={job} onChange={e => setJob(e.target.value)}><option value="">Choose agreed work</option>{data.jobs.map(j => <option key={j.id} value={j.id}>{j.client} · {j.title}</option>)}</select></label><label className="text-sm">Available resource<select className="dd-input mt-1 w-full" required value={resource} onChange={e => setResource(e.target.value)}><option value="">Choose staff, equipment or room</option>{data.resources.map(r => <option key={r.id} value={r.id}>{r.title}</option>)}</select></label><label className="text-sm">Appointment start (your local time)<input type="datetime-local" required className="dd-input mt-1 w-full" value={start} onChange={e => setStart(e.target.value)}/></label><label className="text-sm">Appointment end (your local time)<input type="datetime-local" required className="dd-input mt-1 w-full" value={end} onChange={e => setEnd(e.target.value)}/></label><label className="text-sm">Preparation / travel buffer in minutes<input type="number" min={0} max={240} step={1} required className="dd-input mt-1 w-full" value={buffer} onChange={e => setBuffer(Number(e.target.value))}/></label><div className="self-end"><button disabled={busy} className="dd-primary">Publish appointment time</button></div></form>{message && <p className="mt-4 text-sm" role="status">{message}</p>}<p className="mt-4 text-sm text-slate-500">Customers can cancel a future appointment. Cancellation releases the resource; fees, agreements and refunds still follow your recorded terms.</p><ul className="mt-4 divide-y">{data.offers.filter(o => o.status !== "withdrawn").map(o => <li key={o.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div className="text-sm">{data.jobs.find(j => j.id === o.jobId)?.title ?? "Work order"}<br/>{new Date(o.start).toLocaleString()} → {new Date(o.end).toLocaleString()} · {o.status}</div>{o.status === "open" && <button disabled={busy} className="dd-secondary" onClick={() => void command("withdraw", { id: o.id })}>Withdraw time</button>}</li>)}</ul></section>;
}
