"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { addBusinessActivityAction, refreshBusinessHistoryAction } from "@/app/calendar/actions";
import { calendarDays, combineSummaries, emptySummary, summarizeHistory } from "@/lib/history/calculate";
import { moveDate, period } from "@/lib/history/dates";
import type { BusinessActivity, BusinessHistory } from "@/lib/history/model";
import { csvCell, dateOnly, money, signedAmount } from "@/lib/expenses/model";
import { downloadFile } from "./expenses/ExpensesWorkspace";
import { useSalesChannel } from "./WorkspaceShell";

const btn="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-medium text-slate-600 shadow-sm hover:bg-slate-50 disabled:opacity-40";
const primary="rounded-lg bg-[#2d4b3d] px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-900 disabled:opacity-50";
const field="mt-1.5 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm";
const dateLabel=(date:string,options:Intl.DateTimeFormatOptions)=>new Date(`${date}T12:00:00Z`).toLocaleDateString("en-US",{...options,timeZone:"UTC"});
const currency=(value:number|null)=>value===null?"Unknown":money(value);
function Metric({label,value,hint}:{label:string;value:string;hint:string}){return <div className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-[11px] font-medium text-slate-500">{label}</p><p className="mt-2 text-xl font-semibold tabular-nums tracking-tight text-slate-900">{value}</p><p className="mt-2 text-[11px] leading-4 text-slate-400">{hint}</p></div>;}

export function BusinessCalendar({initial,initialDate,initialView}:{initial:BusinessHistory;initialDate:string;initialView:"day"|"month"|"year"}) {
  const [data,setData]=useState(initial),[date,setDate]=useState(initialDate),[view,setView]=useState(initialView),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[adding,setAdding]=useState(false);
  const {channel}=useSalesChannel(),range=period(date,view),previous=period(moveDate(range.start,-1,view),view);
  const result=summarizeHistory(data,range.start,range.end,channel);
  const prior=summarizeHistory(data,previous.start,previous.end,channel).total,total=result.total;
  const month=period(date,"month"),monthDays=summarizeHistory(data,calendarDays(date)[0],calendarDays(date).at(-1)!,channel).days;
  const days=new Map(monthDays.map(d=>[d.date,d]));
  const selected=days.get(date)??emptySummary(date);
  const yearMonths=Array.from({length:12},(_,i)=>{const key=`${date.slice(0,4)}-${String(i+1).padStart(2,"0")}-01`;return combineSummaries(result.days.filter(d=>d.date.slice(0,7)===key.slice(0,7)),key);});
  const chart=view==="year"?yearMonths:result.days;
  const maxSales=Math.max(1,...chart.map(d=>d.salesCents)),delta=total.salesCents-prior.salesCents;
  const title=view==="year"?date.slice(0,4):dateLabel(date,view==="day"?{weekday:"long",month:"long",day:"numeric",year:"numeric"}:{month:"long",year:"numeric"});
  const matches=(c:string)=>channel==="all"||c===channel||c==="shared";
  const activities=data.activities.filter(a=>a.date===date&&matches(a.channel));
  const daySales=data.sales.filter(s=>s.date===date&&(channel==="all"||s.channel===channel));
  const dayExpenses=data.expenses.filter(r=>r.fields.date===date&&r.status!=="archived"&&matches(r.fields.channel));
  const selectedSales=data.sales.filter(s=>s.date>=range.start&&s.date<=range.end&&s.status!=="cancelled"&&(channel==="all"||s.channel===channel));
  const products=new Map<string,{name:string;revenue:number;cost:number;unknown:boolean;estimated:boolean;cases:number;bottles:number}>();
  for(const sale of selectedSales)for(const p of sale.products){const row=products.get(p.id)??{name:p.name,revenue:0,cost:0,unknown:false,estimated:false,cases:0,bottles:0};row.revenue+=p.revenueCents;row.cost+=p.costCents??0;row.unknown ||=p.costCents===null;row.estimated ||=p.estimated;if(p.unit==="case")row.cases+=p.quantity;else row.bottles+=p.quantity;products.set(p.id,row);}
  const otherCurrencies=data.expenses.filter(r=>r.status==="recorded"&&r.fields.currency!=="USD"&&r.fields.date>=range.start&&r.fields.date<=range.end&&matches(r.fields.channel));
  async function refresh(){setBusy(true);try{setData(await refreshBusinessHistoryAction());setNotice("Business history refreshed.");}catch{setNotice("History could not refresh. Try again.");}finally{setBusy(false);}}
  function navigate(next:string,nextView=view){if(!dateOnly.safeParse(next).success)return;setDate(next);setView(nextView);const url=new URL(window.location.href);url.searchParams.set("date",next);url.searchParams.set("view",nextView);window.history.replaceState(null,"",url.toString());}
  function exportPeriod(){const values=[["Date","Sales USD","Product costs USD","Operating expenses USD","Gross profit USD","Contribution USD","Gross margin %","Orders","Orders with estimated costs","Orders missing costs","Shared costs not allocated USD"],...result.days.map(d=>[d.date,d.salesCents/100,d.costCents/100,d.operatingCents/100,d.grossProfitCents===null?"Unknown":d.grossProfitCents/100,d.contributionCents===null?"Unknown":d.contributionCents/100,d.margin===null?"":(d.margin*100).toFixed(2),d.orders,d.estimatedOrders,d.missingCostOrders,d.sharedCents/100])];downloadFile(`business-${range.start}-to-${range.end}-${channel}.csv`,values.map(row=>row.map(csvCell).join(",")).join("\r\n"),"text/csv;charset=utf-8");}
  return <div className="space-y-5">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><p className="mb-1 text-xs font-medium uppercase tracking-widest text-slate-400">Your business, over time</p><h1 className="text-2xl font-bold tracking-tight">Business calendar</h1><p className="mt-2 text-sm text-slate-500">See what sold, what you spent, and what happened on any day.</p></div><div className="flex gap-2"><Link href="/expenses" className={btn}>Expenses & receipts</Link><button className={primary} onClick={()=>setAdding(true)}>+ Log activity</button></div></header>
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 bg-white p-3"><div className="flex items-center gap-2"><button className={btn} aria-label={`Previous ${view}`} disabled={!dateOnly.safeParse(moveDate(date,-1,view)).success} onClick={()=>navigate(moveDate(date,-1,view))}>←</button><button className={btn} onClick={()=>navigate(data.today)}>Today</button><button className={btn} aria-label={`Next ${view}`} disabled={!dateOnly.safeParse(moveDate(date,1,view)).success} onClick={()=>navigate(moveDate(date,1,view))}>→</button><p className="ml-2 text-sm font-semibold">{title}</p></div><div className="flex flex-wrap items-center gap-2"><label className="sr-only" htmlFor="calendar-date">Browse date</label><input id="calendar-date" aria-label="Browse date" className="rounded-lg border border-slate-200 px-2 py-1.5 text-xs" type="date" min="1900-01-01" max="2199-12-31" value={date} onChange={e=>navigate(e.target.value)}/><div className="flex rounded-lg bg-slate-100 p-1" aria-label="Calendar view">{(["day","month","year"] as const).map(v=><button key={v} aria-pressed={v===view} className={`rounded-md px-3 py-1.5 text-xs capitalize ${v===view?"bg-white font-semibold shadow-sm":"text-slate-500"}`} onClick={()=>navigate(date,v)}>{v}</button>)}</div><button className={btn} disabled={busy} onClick={()=>void refresh()}>Refresh</button><button className={btn} onClick={exportPeriod}>Export</button></div></div>
    {notice&&<p role="status" className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</p>}
    <div className="grid grid-cols-2 gap-3 xl:grid-cols-6">
      <Metric label="Product sales" value={money(total.salesCents)} hint={`${total.orders} orders · before freight`}/>
      <Metric label={total.estimatedOrders?"Est. product cost":"Product cost"} value={total.missingCostOrders?"Incomplete":money(total.costCents)} hint={`${total.estimatedOrders} orders use current catalog costs`}/>
      <Metric label={total.estimatedOrders?"Est. gross profit":"Gross profit"} value={currency(total.grossProfitCents)} hint="Sales minus product costs"/>
      <Metric label={total.estimatedOrders?"Est. gross margin":"Gross margin"} value={total.margin===null?"—":`${(total.margin*100).toFixed(1)}%`} hint="Gross profit divided by sales"/>
      <Metric label="Operating expenses" value={money(total.operatingCents)} hint="Reviewed USD receipts, less credits"/>
      <Metric label={total.estimatedOrders?"Est. contribution":"Contribution"} value={currency(total.contributionCents)} hint="Gross profit less operating expenses"/>
    </div>
    <div className="flex flex-wrap items-center justify-between gap-2 text-xs text-slate-500"><p><span className={delta>=0?"font-semibold text-emerald-700":"font-semibold text-rose-600"}>{delta>=0?"+":""}{money(delta)}</span> sales vs. full previous {view}{prior.salesCents>0?` (${delta>=0?"+":""}${(delta/prior.salesCents*100).toFixed(1)}%)`:" · no prior sales"}</p><p>Recorded order dates · USD · {data.timezone}</p></div>
    {total.missingCostOrders>0&&<p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">{total.missingCostOrders} orders have missing product costs. Their profit and margin are unknown.</p>}
    {channel!=="all"&&<p className="rounded-lg bg-slate-100 p-3 text-xs text-slate-600">Shared operating expenses: {money(total.sharedCents)}. These are shown separately and are not allocated to this channel. Choose All channels to include them in business contribution.</p>}
    {otherCurrencies.length>0&&<p className="rounded-lg bg-amber-50 p-3 text-xs text-amber-800">{otherCurrencies.length} recorded receipts use another currency and are excluded from USD totals. View their original amounts in Expenses & receipts.</p>}
    <div className={`grid items-start gap-5 ${view==="day"?"":"xl:grid-cols-[1.65fr_1fr]"}`}>
      {view!=="day"&&<section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
        <div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-100 p-4"><h2 className="font-semibold">{view==="year"?`${date.slice(0,4)} at a glance`:dateLabel(date,{month:"long",year:"numeric"})}</h2><p className="text-[10px] text-slate-400"><span className="text-emerald-700">● Sales</span> · <span className="text-amber-700">● Operating expenses</span></p></div>
        {view==="year"?<div className="grid gap-3 p-4 sm:grid-cols-3">{yearMonths.map(m=><button key={m.date} className="rounded-xl border border-slate-200 p-4 text-left hover:border-emerald-500 hover:bg-emerald-50/40" aria-label={`Open ${dateLabel(m.date,{month:"long",year:"numeric"})}`} onClick={()=>navigate(m.date,"month")}><p className="text-xs font-semibold">{dateLabel(m.date,{month:"long"})}</p><p className="mt-3 text-lg font-semibold text-emerald-800">{money(m.salesCents)}</p><p className="mt-1 text-[11px] text-slate-400">{m.orders} orders · {money(m.operatingCents)} expenses</p><div className="mt-3 h-1.5 rounded bg-slate-100"><div className="h-full rounded bg-emerald-600" style={{width:`${m.salesCents/maxSales*100}%`}}/></div></button>)}</div>:<>
          <div className="grid grid-cols-7 border-b border-slate-100 bg-slate-50/70">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(d=><span className="py-3 text-center text-[10px] font-semibold uppercase tracking-wide text-slate-400" key={d}>{d}</span>)}</div>
          <div className="grid grid-cols-7">{calendarDays(date).map(d=>{const s=days.get(d)??emptySummary(d),current=d===date;return <button key={d} aria-label={`View ${d}: ${money(s.salesCents)} sales, ${money(s.operatingCents)} operating expenses, ${s.activityCount} activities`} aria-pressed={current} onClick={()=>navigate(d)} className={`min-h-[94px] min-w-0 border-b border-r border-slate-100 p-1.5 text-left transition sm:min-h-[110px] sm:p-2 ${current?"relative bg-emerald-50 ring-2 ring-inset ring-emerald-600":d<month.start||d>month.end?"bg-slate-50/80 text-slate-400":"hover:bg-slate-50"}`}><span className={`inline-flex h-6 w-6 items-center justify-center rounded-full text-xs ${d===data.today?"bg-[#2d4b3d] font-semibold text-white":"font-medium"}`}>{Number(d.slice(-2))}</span>{s.orders>0&&<p className="mt-2 truncate text-[9px] font-semibold tabular-nums text-emerald-800 sm:text-[10px]" title={money(s.salesCents)}>{money(s.salesCents)}</p>}{s.operatingCents!==0&&<p className="mt-1 truncate text-[9px] tabular-nums text-amber-700 sm:text-[10px]" title={`${money(s.operatingCents)} expenses`}>{money(s.operatingCents)}</p>}{s.activityCount>0&&<p className="mt-1 truncate text-[9px] text-slate-400">{s.activityCount} activities</p>}</button>;})}</div>
        </>}
      </section>}
      <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs text-slate-400">Day details</p><h2 className="mt-1 font-semibold">{dateLabel(date,{weekday:"long",month:"short",day:"numeric"})}</h2></div>{view!=="day"&&<button className="text-xs font-semibold text-emerald-700" onClick={()=>navigate(date,"day")}>Expand day →</button>}</div>
        <div className="my-4 grid grid-cols-2 gap-3 rounded-lg bg-slate-50 p-3"><div><p className="text-[10px] text-slate-400">Sales</p><p className="mt-1 text-sm font-semibold">{money(selected.salesCents)}</p></div><div><p className="text-[10px] text-slate-400">{selected.estimatedOrders?"Est. contribution":"Contribution"}</p><p className="mt-1 text-sm font-semibold">{currency(selected.contributionCents)}</p></div></div>
        {daySales.length>0&&<div className="mb-5"><h3 className="mb-2 text-[10px] font-semibold uppercase tracking-widest text-slate-400">Orders & products sold</h3>{daySales.map(s=><details key={s.id} className="border-b border-slate-100 py-3"><summary className="cursor-pointer text-sm"><span className="font-medium">{s.customer}</span><span className="float-right ml-2 text-xs font-semibold">{s.status==="cancelled"?"Cancelled":money(s.revenueCents)}</span><p className="mt-1 text-[10px] text-slate-400">{s.id.slice(0,18)} · {s.channel} · {s.status}</p></summary><ul className="mt-3 space-y-2">{s.products.map((p,i)=><li key={i} className="rounded-lg bg-slate-50 p-3 text-xs"><p className="font-medium">{p.name} · {p.quantity} {p.unit}{p.quantity===1?"":"s"}</p><p className="mt-1 text-slate-500">Sales {money(p.revenueCents)} · {p.estimated?"est. cost":"cost"} {currency(p.costCents)} · {p.estimated?"est. gross profit":"gross profit"} {currency(p.costCents===null?null:p.revenueCents-p.costCents)}</p></li>)}</ul><p className="mt-2 text-[10px] text-slate-400">{s.status==="cancelled"?"Excluded from sales and margins.":"Recorded sales are not a confirmation of payment."}</p><Link className="mt-2 inline-block text-xs text-emerald-700" href="/orders">View orders →</Link></details>)}</div>}
        {dayExpenses.length>0&&<div className="mb-5"><h3 className="mb-2 text-[10px] font-semibold uppercase tracking-widest text-slate-400">Expenses & receipts</h3>{dayExpenses.map(r=><div key={r.id} className="border-b border-slate-100 py-3 text-xs"><div className="flex justify-between gap-3"><Link href="/expenses" className="font-semibold text-emerald-800">{r.fields.merchant||"Receipt awaiting review"}</Link><span>{r.fields.amountCents===null?"Unknown total":money(signedAmount(r.fields),r.fields.currency)}</span></div><p className="mt-1 text-slate-400">{r.status==="draft"?"Needs review · not counted":`${r.fields.category} · ${r.fields.treatment} · ${r.fields.paymentStatus}`} · {r.fields.channel}</p>{r.receipt&&<a className="mt-2 inline-block text-emerald-700" href={`/api/receipts/${r.id}?download=1`}>Original receipt ↗</a>}</div>)}</div>}
        <h3 className="mb-3 text-[10px] font-semibold uppercase tracking-widest text-slate-400">What happened / planned</h3><ol className="space-y-4">{activities.map(a=><li key={a.id} className="border-l-2 border-emerald-200 pl-3"><p className="text-[10px] font-medium text-slate-400">{a.kind}{a.source==="demo"?" · demo workspace":""}</p><Link href={a.href} className="mt-1 inline-block text-sm font-semibold text-slate-700">{a.title}</Link><p className="mt-1 whitespace-pre-wrap break-words text-xs leading-5 text-slate-500">{a.detail}</p></li>)}</ol>
        {!activities.length&&<p className="py-2 text-xs text-slate-400">No activities logged for this day.</p>}
        {!daySales.length&&!dayExpenses.length&&<p className="mt-4 text-xs text-slate-400">No orders or receipts recorded for this day.</p>}
        <button className="mt-5 text-xs font-semibold text-emerald-700" onClick={()=>setAdding(true)}>+ Add a visit, meeting or business note</button>
      </section>
    </div>
    <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold">Products sold · {title}</h2><Link href="/analytics" className="text-xs font-semibold text-emerald-700">Customer & channel reports →</Link></div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b text-slate-400">{["Product","Units sold","Sales","Product cost","Gross profit","Gross margin"].map(t=><th className="p-3 font-medium" key={t}>{t}</th>)}</tr></thead><tbody>{[...products.entries()].sort((a,b)=>b[1].revenue-a[1].revenue).map(([id,p])=><tr key={id} className="border-b border-slate-100 last:border-0"><td className="p-3 font-semibold">{p.name}{p.estimated&&<span className="mt-1 block text-[10px] font-normal text-amber-700">Cost estimated from current catalog</span>}</td><td className="p-3">{[p.cases?`${p.cases} cases`:"",p.bottles?`${p.bottles} bottles`:""].filter(Boolean).join(" + ")}</td><td className="p-3 tabular-nums">{money(p.revenue)}</td><td className="p-3 tabular-nums">{currency(p.unknown?null:p.cost)}</td><td className="p-3 tabular-nums">{currency(p.unknown?null:p.revenue-p.cost)}</td><td className="p-3">{p.unknown||!p.revenue?"—":`${((p.revenue-p.cost)/p.revenue*100).toFixed(1)}%`}</td></tr>)}</tbody></table></div>{!products.size&&<p className="py-6 text-center text-sm text-slate-400">No products sold in this period.</p>}</section>
    {view!=="day"&&<section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="mb-4 font-semibold">Sales through the {view}</h2><div className="flex h-40 items-end gap-1 overflow-x-auto" aria-label="Sales trend">{(view==="month"?Array.from({length:Number(month.end.slice(-2))},(_,i)=>{const key=`${date.slice(0,7)}-${String(i+1).padStart(2,"0")}`;return days.get(key)??emptySummary(key);}):yearMonths).map(d=><button key={d.date} className="flex h-full min-w-4 flex-1 flex-col items-center justify-end gap-2 rounded hover:bg-slate-50" aria-label={`${d.date}: ${money(d.salesCents)} sales`} title={`${d.date}: ${money(d.salesCents)} sales`} onClick={()=>navigate(d.date,view==="year"?"month":"day")}><span className="w-full max-w-10 rounded-t bg-emerald-600/80" style={{height:`${Math.max(1,d.salesCents/maxSales*115)}px`}}/><span className="text-[9px] text-slate-400">{view==="year"?dateLabel(d.date,{month:"short"}):Number(d.date.slice(-2))}</span></button>)}</div></section>}
    <details className="rounded-xl border border-slate-200 bg-white p-4 text-xs leading-6 text-slate-500"><summary className="cursor-pointer font-semibold text-slate-600">How these numbers are calculated & what history is included</summary><div className="mt-3 space-y-2"><p>Sales use recorded product subtotals on the order date. Cancelled orders are excluded. Freight, bank deposits, tax liabilities, marketplace fees and unrecorded refunds are not included. Contribution is a management view, not net income or available cash.</p><p>Product cost uses the saved order cost when available. Older orders use today’s catalog cost and are labeled estimated. Missing costs produce unknown profit. Operating expenses include recorded receipt totals, including entered tax, on the receipt date, whether paid or unpaid. Inventory, assets and transfers stay separate to avoid subtracting product cost twice. Expense refunds reduce expenses on their recorded date.</p><p>USD is the order workspace currency. Other receipt currencies remain in their original currency and are excluded here. Shared expenses count only in All channels; individual channel views show them separately.</p><p>{data.durableOrders?"Orders come from the connected workspace database.":"This local workspace includes seeded demo orders. Newly created local orders, their customer details and captured costs are saved to disk; older unsaved demo edits cannot be recovered."} Receipt files, expense versions and business journal entries are saved. The existing tasks, team notes, samples and shipment modules are demo data that can reset with the server. Activity cards show their current status, not a historical reconstruction of every change.</p><p>Amazon advertising reports and the separate Amazon shipping feed are not counted as sales here; this avoids double counting attributed advertising sales. Connectors do not backfill all historical sales automatically.</p></div></details>
    {adding&&<ActivityForm date={date} close={()=>setAdding(false)} saved={activity=>{setData(d=>({...d,activities:[activity,...d.activities]}));setAdding(false);setNotice("Business activity saved in your calendar history.");}}/>}
  </div>;
}

function ActivityForm({date,close,saved}:{date:string;close:()=>void;saved:(a:BusinessActivity)=>void}) {
  const [busy,setBusy]=useState(false),[error,setError]=useState("");
  const dialog=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const node=dialog.current;node?.showModal();return ()=>node?.close();},[]);
  return <dialog ref={dialog} aria-labelledby="activity-title" onCancel={e=>{e.preventDefault();if(!busy)close();}} className="m-auto max-h-[90vh] w-[calc(100%-2rem)] max-w-lg overflow-y-auto rounded-2xl border-0 bg-white p-0 shadow-xl backdrop:bg-slate-950/30"><section className="p-6"><div className="flex justify-between"><h2 id="activity-title" className="text-lg font-semibold">Log business activity</h2><button aria-label="Close activity form" disabled={busy} onClick={close}>✕</button></div><p className="mt-2 text-sm text-slate-500">Save what happened, or plan what’s next.</p>{error&&<p className="mt-3 text-sm text-rose-700" role="alert">{error}</p>}<form className="mt-5 space-y-4" onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);try{const result=await addBusinessActivityAction({title:String(form.get("title")),date:String(form.get("date")),detail:String(form.get("detail")),kind:String(form.get("kind")) as "Visit",channel:String(form.get("channel")) as "shared"});if(!result.ok)throw new Error(result.error);saved(result.activity);}catch(e){setError(e instanceof Error?e.message:"Activity could not save.");}finally{setBusy(false);}}}><fieldset disabled={busy} className="space-y-4"><label className="block text-xs text-slate-600">Title<input autoFocus className={field} name="title" required maxLength={180} placeholder="Met the buyer at Green Market"/></label><div className="grid grid-cols-2 gap-3"><label className="text-xs text-slate-600">Date<input name="date" className={field} type="date" required defaultValue={date} min="1900-01-01" max="2199-12-31"/></label><label className="text-xs text-slate-600">Activity type<select name="kind" className={field}>{["Visit","Call","Meeting","Delivery","Production","Business note"].map(k=><option key={k}>{k}</option>)}</select></label></div><label className="block text-xs text-slate-600">Channel<select name="channel" className={field}><option value="shared">Whole business</option><option value="bulk">Bulk</option><option value="stores">Stores</option><option value="online">Online</option></select></label><label className="block text-xs text-slate-600">Notes<textarea name="detail" rows={4} maxLength={5000} className={field} placeholder="Decisions, people you met, and what comes next…"/></label><div className="flex justify-end gap-2"><button type="button" className={btn} onClick={close}>Cancel</button><button type="submit" className={primary}>{busy?"Saving…":"Save activity"}</button></div></fieldset></form></section></dialog>;
}
