"use client";
import Link from "next/link";
import { useSalesChannel } from "./WorkspaceShell";
import { salesChannel, SALES_LABELS } from "@/lib/data/channels";
import type { CustomerDeal, Order } from "@/lib/data/model";
import { formatCents } from "@/lib/money";
export function BusinessHome({ deals, orders, durable, shopify, quickbooks }: { deals: CustomerDeal[]; orders: Order[]; durable:boolean; shopify:boolean; quickbooks:boolean }) {
  const {channel,setChannel} = useSalesChannel();
  const customers = deals.filter(d => channel === "all" || salesChannel(d.customer.channel) === channel);
  const ids = new Set(customers.map(d => d.customer.id));
  const selected = orders.filter(o => ids.has(o.customerId) && o.status !== "cancelled");
  const revenue = selected.reduce((n,o) => n + o.subtotalCents,0);
  const pending = selected.filter(o => o.status === "submitted");
  const company = (id:string) => deals.find(d => d.customer.id === id)?.customer.company || id;
  return <div className="space-y-6"><header className="flex flex-wrap items-center justify-between gap-4"><div><p className="dd-eyebrow">Your business at a glance</p><h1 className="mt-1 text-2xl font-bold tracking-tight">Let’s get to business.</h1><p className="mt-2 text-sm text-slate-500">Your buyers, orders and next moves. All in one place.</p></div><Link href="/customers?order=1" className="dd-primary">+ Create order</Link></header>
    {!durable && <div className="flex items-center gap-3 rounded-lg border border-amber-200/70 bg-amber-50/70 px-4 py-2.5 text-xs text-amber-900"><span className="h-1.5 w-1.5 rounded-full bg-amber-500"/><span>You’re exploring sample business data. Customer and order edits last for this server session.</span><Link href="/settings" className="ml-auto shrink-0 font-semibold underline">Set up your business</Link></div>}
    <section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[{label:"Sales recorded",value:formatCents(revenue),hint:`${SALES_LABELS[channel]} · all recorded orders`},{label:"Orders",value:String(selected.length),hint:"Excludes cancelled orders"},{label:"Active customers",value:String(customers.length),hint:"Accounts in this sales view"},{label:"To fulfill",value:String(pending.length),hint:pending.length ? "Orders ready for your team" : "You’re all caught up"}].map((m,i) => <div key={m.label} className="dd-card !p-4"><div className="flex items-center justify-between"><p className="text-xs font-medium text-slate-500">{m.label}</p><span className="text-xs text-slate-300">{["↗","▤","◎","✓"][i]}</span></div><p className="mt-3 text-2xl font-semibold tracking-tight tabular-nums">{m.value}</p><p className="mt-2 text-[11px] text-slate-400">{m.hint}</p></div>)}</section>
    <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1.7fr)_minmax(280px,1fr)]"><div className="space-y-5"><section className="dd-card"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">Your sales channels</h2><span className="text-[11px] text-slate-400">One catalog. One customer history.</span></div><div className="mt-5 grid gap-3 sm:grid-cols-3">{([{key:"bulk",label:"Bulk",detail:"Volume deals & distributors",icon:"▤",color:"bg-violet-50 text-violet-700"},{key:"stores",label:"Stores",detail:"Retail buyers & reorders",icon:"▥",color:"bg-amber-50 text-amber-700"},{key:"online",label:"Online",detail:"Direct sales & marketplaces",icon:"↗",color:"bg-emerald-50 text-emerald-700"}] as const).map(c => { const members=deals.filter(d=>salesChannel(d.customer.channel)===c.key), memberIds=new Set(members.map(d=>d.customer.id));const total=orders.filter(o=>o.status!=="cancelled"&&memberIds.has(o.customerId)).reduce((n,o)=>n+o.subtotalCents,0);return <button key={c.key} onClick={()=>setChannel(c.key)} className={`rounded-xl border p-4 text-left transition hover:border-slate-400 ${channel===c.key ? "border-emerald-400 ring-1 ring-emerald-100" : "border-slate-200"}`}><span className={`flex h-9 w-9 items-center justify-center rounded-lg text-lg ${c.color}`}>{c.icon}</span><p className="mt-3 text-sm font-semibold">{c.label}</p><p className="mt-1 text-[11px] leading-5 text-slate-400">{c.detail}</p><p className="mt-4 text-lg font-semibold tabular-nums">{formatCents(total)}</p><p className="mt-1 text-[11px] text-slate-400">{members.length} account(s)</p></button>;})}</div></section>
    <section className="dd-card !p-0"><div className="flex items-center justify-between p-5"><h2 className="text-sm font-semibold">Recent orders <span className="ml-1 font-normal text-slate-400">· {SALES_LABELS[channel]}</span></h2><Link href="/orders" className="text-xs font-medium text-emerald-700">View all →</Link></div>{selected.length ? <div className="overflow-x-auto"><table className="w-full min-w-[480px] text-left text-xs"><thead className="border-y border-slate-100 bg-slate-50/70 text-slate-400"><tr><th className="px-5 py-3 font-medium">Order / customer</th><th className="py-3 font-medium">Date</th><th className="py-3 font-medium">Status</th><th className="px-5 py-3 text-right font-medium">Total</th></tr></thead><tbody>{selected.slice(0,5).map(o=><tr key={o.id} className="border-b border-slate-100 last:border-0"><td className="px-5 py-4"><Link className="font-medium text-slate-800 hover:underline" href={`/customers/${o.customerId}/orders`}>{o.id}</Link><p className="mt-1 text-[11px] text-slate-400">{company(o.customerId)}</p></td><td className="text-slate-500">{o.createdAt.slice(0,10)}</td><td><span className={`rounded-md px-2 py-1 text-[10px] ${o.status==="fulfilled" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-800"}`}>{o.status==="fulfilled"?"Fulfilled":"To fulfill"}</span></td><td className="px-5 text-right font-medium tabular-nums">{formatCents(o.totalCents)}</td></tr>)}</tbody></table></div>:<div className="px-5 pb-8 pt-4 text-center"><p className="text-sm font-medium">Your first {channel==="all"?"":SALES_LABELS[channel].toLowerCase()+" "}order starts here.</p><p className="mt-2 text-xs text-slate-400">Add a buyer, confirm their pricing and create an order.</p><Link className="dd-button mt-4" href="/customers/new">Add a customer</Link></div>}</section>
    <section className="relative overflow-hidden rounded-xl border border-[#d4ddca] bg-[#e9eedf] p-5"><div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-wider text-[#6a7a55]"><span>✦</span> A clearer path to growth</div><h2 className="mt-3 text-lg font-semibold tracking-tight text-[#2e3b25]">Find your edge before you buy the click.</h2><p className="mt-2 max-w-xl text-xs leading-6 text-[#69735f]">Compare Shuug with competing brands, spot a stronger offer, and test ad costs against your actual product margins.</p><Link href="/ads" className="dd-primary mt-4">Explore your market →</Link></section></div>
    <div className="space-y-5"><section className="dd-card"><h2 className="text-sm font-semibold">Make yourself at home</h2><p className="mt-1 text-xs text-slate-400">A few simple steps to bring it together.</p><div className="mt-5 space-y-5">{[{n:"1",title:"Bring in your buyers",body:"Add a customer and their sales channel.",href:"/customers/new",done:durable&&deals.length>0},{n:"2",title:"Make your first deal",body:"Set case pricing, terms and order minimums.",href:customers[0]?`/customers/${customers[0].customer.id}`:"/customers/new",done:false},{n:"3",title:"Connect your online store",body:"Link Shopify to your accounting workflow.",href:"/settings",done:shopify},{n:"4",title:"Bring your books along",body:"Connect QuickBooks for invoicing.",href:"/settings",done:quickbooks}].map(s=><Link key={s.n} href={s.href} className="group flex gap-3"><span className={`mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full border text-[10px] font-medium ${s.done?"border-emerald-100 bg-emerald-50 text-emerald-700":"border-slate-200 text-slate-400"}`}>{s.done?"✓":s.n}</span><div><p className="text-xs font-semibold group-hover:text-emerald-700">{s.title}</p><p className="mt-1 text-[11px] leading-5 text-slate-400">{s.body}</p></div><span className="ml-auto mt-1 text-slate-300">›</span></Link>)}</div></section>
    <section className="dd-card"><h2 className="text-sm font-semibold">Your business, connected</h2><div className="mt-4 space-y-4">{[{name:"Shopify",initial:"S",detail:"Online selling",ready:shopify},{name:"QuickBooks",initial:"qb",detail:"Books & invoices",ready:quickbooks}].map(c=><Link key={c.name} href="/settings" className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-lg border border-slate-200 text-xs font-bold text-emerald-700">{c.initial}</span><div><p className="text-xs font-semibold">{c.name}</p><p className="mt-1 text-[11px] text-slate-400">{c.detail}</p></div><span className={`ml-auto text-[10px] ${c.ready?"text-emerald-700":"text-slate-400"}`}>{c.ready?"Configured":"Set up →"}</span></Link>)}</div></section>
    <section className="rounded-xl border border-dashed border-slate-300 p-5"><p className="text-sm font-medium">Need a hand?</p><p className="mt-2 text-xs leading-6 text-slate-500">Ask about your top customers, order trends or the next deal to focus on.</p><Link href="/copilot" className="mt-3 inline-block text-xs font-semibold text-emerald-700">Ask your assistant →</Link></section></div></div>
  </div>;
}
