"use client";
import Link from "next/link";
import { useEffect,useRef,useState } from "react";
import type { ConnectionSummary,ConnectionId } from "@/lib/connections/catalog";
import { saveConnectionAction,testConnectionAction,disconnectConnectionAction,createAutomationTokenAction } from "@/app/settings/connections";
const INFO:Record<ConnectionId,{initial:string;color:string;description:string;link:string;fields:{key:string;label:string;hint?:string;secret?:boolean;optional?:boolean}[]}>= {
  slack:{initial:"#",color:"bg-purple-100 text-purple-800",description:"Send request references to the channel selected in your Slack app. Reading conversations and choosing other channels are not supported.",link:"https://docs.slack.dev/messaging/sending-messages-using-incoming-webhooks/",fields:[{key:"SLACK_WEBHOOK_URL",label:"Slack incoming webhook URL",secret:true,hint:"In your Slack app, enable Incoming Webhooks and add a webhook for the intended channel."}]},
  stripe:{initial:"S",color:"bg-indigo-100 text-indigo-800",description:"Use hosted Stripe Checkout for supported order payments. The connection check only reads account access.",link:"https://dashboard.stripe.com/apikeys",fields:[{key:"STRIPE_SECRET_KEY",label:"Stripe secret key",secret:true,hint:"Start with a test key. A live key permits real payments when you explicitly create checkout sessions."},{key:"STRIPE_WEBHOOK_SECRET",label:"Website payment webhook signing secret",secret:true,hint:"Register /api/website/stripe/webhook in Stripe, then paste its whsec_ signing secret."}]},
  amazonads:{initial:"a+",color:"bg-amber-100 text-amber-900",description:"Build Sponsored Products campaigns, launch reviewed ads and measure results.",link:"https://advertising.amazon.com/about-api",fields:[{key:"AMAZON_ADS_CLIENT_ID",label:"Amazon Ads app client ID",hint:"Your Login with Amazon app must have approved Amazon Ads API access."},{key:"AMAZON_ADS_CLIENT_SECRET",label:"App client secret",secret:true},{key:"AMAZON_ADS_REGION",label:"Advertising region",hint:"na = North America, eu = Europe, fe = Far East. Default: na",optional:true},{key:"AMAZON_ADS_REFRESH_TOKEN",label:"Existing Ads refresh token",hint:"Optional alternative to Sign in to Amazon Ads. Selling Partner tokens do not grant Ads access.",secret:true,optional:true}]},
  amazon:{initial:"a",color:"bg-amber-100 text-amber-900",description:"Track Amazon products and orders through fulfillment, packages and shipping.",link:"https://sellercentral.amazon.com/apps/manage",fields:[{key:"AMAZON_SP_CLIENT_ID",label:"Selling Partner app client ID"},{key:"AMAZON_SP_CLIENT_SECRET",label:"App client secret",secret:true},{key:"AMAZON_SP_REFRESH_TOKEN",label:"Seller authorization refresh token",secret:true},{key:"AMAZON_SP_MARKETPLACE_ID",label:"Marketplace ID",hint:"For Amazon.com: ATVPDKIKX0DER"},{key:"AMAZON_SP_REGION",label:"Region",hint:"na = North America, eu = Europe, fe = Far East. Default: na",optional:true}]},
  shopify:{initial:"S",color:"bg-lime-100 text-lime-800",description:"Connect your online store, customers and orders.",link:"https://dev.shopify.com/dashboard",fields:[{key:"SHOPIFY_STORE_DOMAIN",label:"Your Shopify store",hint:"your-store.myshopify.com"},{key:"SHOPIFY_CLIENT_ID",label:"App client ID",hint:"From your Shopify Dev Dashboard"},{key:"SHOPIFY_CLIENT_SECRET",label:"App client secret",secret:true},{key:"SHOPIFY_ADMIN_TOKEN",label:"Existing Admin API access token",secret:true,optional:true,hint:"Optional alternative for an existing custom app"}]},
  quickbooks:{initial:"qb",color:"bg-green-100 text-green-800",description:"Link your company for accounting and invoices.",link:"https://developer.intuit.com/app/developer/dashboard",fields:[{key:"QBO_CLIENT_ID",label:"App client ID",hint:"From your Intuit developer app"},{key:"QBO_CLIENT_SECRET",label:"App client secret",secret:true}]},
  maps:{initial:"↗",color:"bg-sky-100 text-sky-800",description:"Find buyers nearby and plan the order of your visits.",link:"https://console.cloud.google.com/google/maps-apis/credentials",fields:[{key:"GOOGLE_MAPS_SERVER_KEY",label:"Places & Routes API key",secret:true,hint:"Enable Places API (New) and Routes API for this server key."},{key:"GOOGLE_MAPS_BROWSER_KEY",label:"Map display key",secret:true,hint:"Enable Maps JavaScript API. Restrict this browser key to your app’s website address."}]},
  zapier:{initial:"z",color:"bg-orange-100 text-orange-800",description:"Send saved prospects to your Zaps and other business tools.",link:"https://zapier.com/app/zaps",fields:[{key:"ZAPIER_WEBHOOK_URL",label:"Zapier Catch Hook URL",secret:true,hint:"Create a Zap → Webhooks by Zapier → Catch Hook, then paste its URL."}]},
  custom:{initial:"{}",color:"bg-violet-100 text-violet-800",description:"Connect an HTTPS API or webhook with an optional bearer token.",link:"",fields:[{key:"CUSTOM_API_NAME",label:"Connection name",hint:"For example: Warehouse or CRM"},{key:"CUSTOM_API_URL",label:"HTTPS API endpoint",hint:"Test uses GET. Enabled prospect events use POST to the same URL.",secret:true},{key:"CUSTOM_API_TOKEN",label:"Bearer access token",secret:true,optional:true}]},
  googleads:{initial:"G",color:"bg-blue-100 text-blue-800",description:"Get keyword costs, review campaigns and see your results.",link:"https://developers.google.com/google-ads/api/docs/get-started/introduction",fields:[{key:"GOOGLE_ADS_CUSTOMER_ID",label:"Advertising account ID",hint:"10 digits; use a USD client account"},{key:"GOOGLE_ADS_DEVELOPER_TOKEN",label:"Developer token",secret:true},{key:"GOOGLE_ADS_CLIENT_ID",label:"OAuth client ID"},{key:"GOOGLE_ADS_CLIENT_SECRET",label:"OAuth client secret",secret:true},{key:"GOOGLE_ADS_REFRESH_TOKEN",label:"OAuth refresh token",secret:true},{key:"GOOGLE_ADS_LOGIN_CUSTOMER_ID",label:"Manager account ID",optional:true}]},
  research:{initial:"✦",color:"bg-teal-100 text-teal-800",description:"Discover competitor websites with live market searches.",link:"https://api-dashboard.search.brave.com/",fields:[{key:"BRAVE_SEARCH_API_KEY",label:"Brave Search API key",secret:true}]},
};
export function ConnectionWizard({initial,baseUrl}: {initial:ConnectionSummary[];baseUrl:string}) {
  const [connections,setConnections]=useState(initial),[active,setActive]=useState<ConnectionId|null>(null),[step,setStep]=useState(0),[values,setValues]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[ok,setOk]=useState(false),[inboundToken,setInboundToken]=useState("");
  const dialog=useRef<HTMLDialogElement>(null);
  useEffect(()=>{if(active){dialog.current?.showModal();}else dialog.current?.close();},[active]);
  const selected=connections.find(c=>c.id===active),info=active?INFO[active]:null;
  function open(id:ConnectionId){setActive(id);setStep(0);setValues({...connections.find(c=>c.id===id)?.publicValues});setMessage("");setOk(false);}
  async function perform(work:()=>Promise<{ok:boolean;message:string;connections?:ConnectionSummary[]}>,next?:number){if(busy)return;setBusy(true);setMessage("");try{const result=await work();setMessage(result.message);setOk(result.ok);if(result.connections)setConnections(result.connections);if(result.ok&&next!==undefined)setStep(next);}catch{setOk(false);setMessage("The request did not finish. Try again.");}finally{setBusy(false);}}
  return <><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{connections.map(c=><section key={c.id} id={c.id==="googleads"?"marketing":c.id} className="dd-card flex flex-col"><div className="flex items-center justify-between"><span className={`flex h-10 w-10 items-center justify-center rounded-xl font-bold ${INFO[c.id].color}`}>{INFO[c.id].initial}</span><span className={`rounded-full px-2.5 py-1 text-[10px] font-medium ${c.connected?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500"}`}>{c.connected?c.id==="maps"?"Places verified":"Connected":c.configured?"Ready to check":"Not connected"}</span></div><h2 className="mt-4 font-semibold">{c.label}</h2><p className="mt-2 flex-1 text-xs leading-6 text-slate-500">{INFO[c.id].description}</p><button className={`${c.connected?"dd-button":"dd-primary"} mt-5 w-full`} onClick={()=>open(c.id)}>{c.connected?"Manage connection":"Connect "+c.label}</button></section>)}</div>
    <section className="dd-card mt-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Bring leads in from any tool</h2><p className="mt-1 text-sm text-slate-500">Use Zapier, Make or your own API client to add prospects to Store finder.</p></div><button className="dd-button" disabled={busy} onClick={()=>void perform(async()=>{const r=await createAutomationTokenAction();if(r.ok&&r.token)setInboundToken(r.token);return r;})}>{inboundToken?"Rotate inbound token":"Create inbound API token"}</button></div><details className="mt-4 text-xs text-slate-500"><summary className="cursor-pointer font-medium">API endpoint & example</summary><p className="mt-3 break-all font-mono">POST {baseUrl}/api/automation/events</p><p className="mt-2">Send a unique Idempotency-Key with each request and Authorization: Bearer YOUR_TOKEN.</p><pre className="mt-3 overflow-x-auto rounded-lg bg-slate-50 p-3 text-[11px]">{JSON.stringify({type:"prospect.create",data:{name:"A real buyer’s store",address:"Street, city, state",phone:"",decisionMaker:"",email:"",notes:"Lead from our signup form"}},null,2)}</pre><p className="mt-2 leading-6">The API supports prospect creation. For other applications, connect an API endpoint or map fields through Zapier. localhost is reachable only on this computer; hosted inbound automation needs your authenticated HTTPS deployment.</p></details>{inboundToken&&<label className="mt-4 block text-xs font-medium">Your new inbound token · copy and store securely<input className="dd-input mt-2 font-mono text-xs" readOnly value={inboundToken} onFocus={e=>e.target.select()}/></label>}{!active&&message&&<p role="status" className="mt-3 text-sm text-slate-600">{message}</p>}</section>
    <dialog ref={dialog} onCancel={()=>{if(!busy)setActive(null);}} className="fixed inset-0 m-auto max-h-[90vh] w-[min(680px,calc(100%_-_2rem))] overflow-y-auto rounded-2xl border border-slate-200 bg-white p-0 text-slate-900 shadow-2xl backdrop:bg-slate-900/35" aria-labelledby="connection-title">
      {active&&selected&&info&&<><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><p className="dd-eyebrow">Connection wizard</p><h2 id="connection-title" className="mt-1 text-lg font-semibold">{selected.label}</h2></div><button aria-label="Close connection wizard" disabled={busy} className="rounded p-2 text-lg text-slate-400" onClick={()=>setActive(null)}>×</button></div><div className="p-5"><div className="mb-6 flex gap-2">{["1 · Details","2 · Connect","3 · Ready"].map((label,i)=><span key={label} className={`flex-1 rounded-lg py-2 text-center text-xs font-medium ${step===i?"bg-emerald-50 text-emerald-800":"bg-slate-50 text-slate-400"}`}>{label}</span>)}</div>
      {step===0&&<form onSubmit={e=>{e.preventDefault();void perform(()=>saveConnectionAction(active,values),1);}}><p className="mb-5 text-sm leading-6 text-slate-500">{active==="shopify"||active==="quickbooks"||active==="amazonads"?"Add your app credentials once. Then sign in with your provider and approve this business connection.":info.description} Existing secrets are kept when you leave their fields blank.</p><div className="space-y-4">{info.fields.map(f=><label key={f.key} className="block text-xs font-medium">{f.label}{f.optional&&<span className="ml-1 font-normal text-slate-400">(optional)</span>}<input className="dd-input mt-1.5" type={f.secret?"password":"text"} autoComplete="off" spellCheck={false} value={values[f.key]||""} placeholder={selected.fields[f.key]?"Saved securely · leave blank to keep":""} onChange={e=>setValues(p=>({...p,[f.key]:e.target.value}))}/>{f.hint&&<span className="mt-1 block text-[11px] font-normal leading-5 text-slate-400">{f.hint}</span>}</label>)}</div>
        {active==="quickbooks"&&<label className="mt-4 block text-xs font-medium">QuickBooks company type<select className="dd-input mt-1" value={values.QBO_ENVIRONMENT||"sandbox"} onChange={e=>setValues(p=>({...p,QBO_ENVIRONMENT:e.target.value}))}><option value="sandbox">Test company (sandbox)</option><option value="production">My real company (production)</option></select></label>}
        {(active==="shopify"||active==="quickbooks"||active==="amazonads")&&<div className="mt-4 rounded-lg bg-slate-50 p-3"><p className="text-xs font-medium">Add this redirect URL in your provider’s app settings</p><input readOnly className="mt-2 w-full bg-transparent font-mono text-[11px] text-slate-500" value={`${baseUrl}/api/${active==="amazonads"?"amazon-ads":active}/callback`} onFocus={e=>e.target.select()}/></div>}
        {(active==="zapier"||active==="custom")&&<label className="mt-5 flex items-start gap-2 text-xs leading-5"><input className="mt-1" type="checkbox" checked={values[active==="zapier"?"ZAPIER_EVENTS_ENABLED":"CUSTOM_EVENTS_ENABLED"]==="true"} onChange={e=>setValues(p=>({...p,[active==="zapier"?"ZAPIER_EVENTS_ENABLED":"CUSTOM_EVENTS_ENABLED"]:String(e.target.checked)}))}/><span>Send a prospect.saved event when I save a lead. Includes the Place ID and details I enter; provider data stays in the map workspace.</span></label>}
        {active==="googleads"&&<label className="mt-5 flex items-start gap-2 text-xs leading-5"><input type="checkbox" className="mt-1" checked={values.GOOGLE_ADS_ENABLE_CAMPAIGN_PUSH==="true"} onChange={e=>setValues(p=>({...p,GOOGLE_ADS_ENABLE_CAMPAIGN_PUSH:String(e.target.checked)}))}/><span>Allow reviewed campaigns to be created paused. I will enable campaigns in Google Ads when ready.</span></label>}
        {info.link&&<a href={info.link} target="_blank" rel="noreferrer" className="mt-4 inline-block text-xs text-emerald-700 underline">Open {selected.label} setup ↗</a>}<div className="mt-6 flex justify-between gap-3">{selected.configured?<button type="button" className="text-xs font-medium text-rose-700" disabled={busy} onClick={()=>void perform(()=>disconnectConnectionAction(active),0)}>Disconnect from workspace</button>:<span/>}<button className="dd-primary" disabled={busy}>{busy?"Saving…":"Save & continue →"}</button></div></form>}
      {step===1&&<div><h3 className="font-semibold">{active==="shopify"||active==="quickbooks"||active==="amazonads"?"Approve the connection":"Check everything is working"}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{active==="shopify"?"Sign in to Shopify, review the requested app permissions, and return here after approval. If you supplied an existing token, use Check connection.":active==="quickbooks"?"Choose your QuickBooks company and approve accounting access. You’ll return here when the connection is saved.":active==="amazonads"?"Sign in to Amazon to authorize campaign management. Amazon must approve your app for the Ads API first. Choose the advertising account inside Amazon Marketing after sign-in.":active==="zapier"?"Keep your Zap trigger listening. We’ll send a clearly labeled test event so you can map its fields.":active==="maps"?"We’ll verify Places access with a small business search. Google bills Places searches and route optimization to your Maps project.":"We’ll make a request with your saved credentials and show the result."}</p><div className="mt-5 flex flex-wrap gap-3">{(active==="shopify"||active==="quickbooks"||active==="amazonads")&&<a className="dd-primary" href={`/api/${active==="amazonads"?"amazon-ads":active}/connect`}>Sign in to {selected.label} →</a>}<button className="dd-button" disabled={busy} onClick={()=>void perform(()=>testConnectionAction(active),2)}>{busy?"Checking…":active==="slack"?"Send Slack test message":active==="zapier"?"Send test event":"Check connection"}</button></div><button className="mt-5 text-xs text-slate-500 underline" onClick={()=>setStep(0)}>← Edit details</button></div>}
      {step===2&&<div className="py-5 text-center"><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-emerald-50 text-2xl text-emerald-700">✓</span><h3 className="mt-4 text-lg font-semibold">{selected.label} is ready</h3><p className="mt-3 text-sm text-slate-500">{message}</p><div className="mt-5 flex justify-center gap-3"><button className="dd-button" onClick={()=>setActive(null)}>Done</button><Link className="dd-primary" href={active==="amazonads"?"/amazon-marketing":active==="amazon"?"/amazon":active==="maps"?"/visits":active==="googleads"||active==="research"?"/ads":"/settings#order-sync"} onClick={()=>setActive(null)}>Continue to workspace →</Link></div></div>}
      {message&&step!==2&&<p role="status" className={`mt-4 rounded-lg p-3 text-sm ${ok?"bg-emerald-50 text-emerald-800":"bg-rose-50 text-rose-800"}`}>{message}</p>}</div></>}
    </dialog>
  </>;
}
