"use client";
import Link from "next/link";
import { useState,useTransition } from "react";
import { useRouter } from "next/navigation";
import { customerFields,customerLabels,matchColumns,type ImportPreview } from "@/lib/customers/import-model";
import { previewFileCustomersAction,previewQuickBooksCustomersAction,commitCustomersAction } from "@/app/customers/import/actions";

export function CustomerImport({quickbooksConnected}:{quickbooksConnected:boolean}){
  const router=useRouter(),[pending,start]=useTransition(),[reading,setReading]=useState(false),[message,setMessage]=useState(""),[channel,setChannel]=useState("store"),[preview,setPreview]=useState<ImportPreview|null>(null),[selected,setSelected]=useState<number[]>([]),[mapping,setMapping]=useState<Record<string,string>>({}),[sheets,setSheets]=useState<{name:string;rows:Record<string,string>[];headers:string[]}[]>([]),[sheet,setSheet]=useState(0),[show,setShow]=useState(100),[done,setDone]=useState(false);
  const active=sheets[sheet];
  async function load(file:File|undefined){if(!file)return;setReading(true);setMessage("");setPreview(null);setDone(false);setSheets([]);try{
    if(file.size>5_000_000)throw new Error("Choose a file smaller than 5 MB.");if(!/\.(xlsx|xls|csv|tsv)$/i.test(file.name))throw new Error("Choose an Excel, CSV or TSV file.");
    const XLSX=await import("xlsx"),book=XLSX.read(await file.arrayBuffer(),{type:"array",sheetRows:5002,cellFormula:false,cellHTML:false,cellDates:false});
    if(book.SheetNames.length>30)throw new Error("Choose a workbook with up to 30 sheets, or export the customer sheet as CSV.");
    const data=book.SheetNames.map(name=>{const grid=XLSX.utils.sheet_to_json<string[]>(book.Sheets[name],{header:1,defval:"",raw:false,blankrows:false});if(grid.length>5001)throw new Error("This sheet has more than 5,000 rows. Split it into smaller files.");const headers=(grid[0]||[]).map((h,i)=>String(h||`Column ${i+1}`).trim());if(headers.length>60||new Set(headers).size!==headers.length)throw new Error("Use up to 60 uniquely named columns in the first row.");return {name,headers,rows:grid.slice(1).map(values=>Object.fromEntries(headers.map((h,i)=>[h,String(values[i]??"")])))};}).filter(s=>s.rows.length);
    if(!data.length)throw new Error("No customer rows found. Put column names in the first row.");setSheets(data);setSheet(0);setMapping(matchColumns(data[0].headers));
  }catch(e){setMessage(e instanceof Error?e.message:"The file could not be opened.");}finally{setReading(false);}}
  function review(qbo=false){start(async()=>{setMessage("");setDone(false);try{const r=qbo?await previewQuickBooksCustomersAction(channel):await previewFileCustomersAction(active.rows,mapping,channel);if(r.ok){setPreview(r.result);setSelected(r.result.rows.filter(r=>!r.issue&&r.customer).map(r=>r.index));}else setMessage(r.error);}catch{setMessage("The preview could not be loaded. Your customers have not changed.");}});}
  function commit(){if(!preview)return;start(async()=>{try{const r=await commitCustomersAction(preview.id,selected);if(r.ok){setDone(true);setMessage(`${r.result.imported} customers imported. ${r.result.skipped} rows skipped. ${r.result.results.filter(x=>!x.customerId).slice(0,3).map(x=>`Row ${x.index+2}: ${x.message}`).join(" ")}`);router.refresh();}else setMessage(r.error);}catch{setMessage("The request was interrupted. Retry this reviewed import; saved customers will be skipped.");}});}
  function template(){const a=document.createElement("a"),url=URL.createObjectURL(new Blob(["Company,Contact name,Email,Phone,Billing address,Shipping address,Website,Region,Account owner,Sales channel\r\n"],{type:"text/csv"}));a.href=url;a.download="customer-import-template.csv";a.click();URL.revokeObjectURL(url);}
  const busy=pending||reading;
  return <div><Link href="/customers" className="text-xs text-slate-500">← Customers</Link><h1 className="mt-4 text-3xl font-semibold tracking-tight">Import your customers</h1><p className="mt-2 text-sm text-slate-500">Bring your contacts together. Review every import before adding accounts and their standard catalog pricing.</p><div className="my-6 flex flex-wrap gap-2">{["1 · Choose a source","2 · Match columns","3 · Review & import"].map((x,i)=><span key={x} className={`rounded-lg px-4 py-2 text-xs ${i===(preview?2:active?1:0)?"bg-emerald-100 text-emerald-900":"bg-white text-slate-400"}`}>{x}</span>)}</div>
    {message&&<p role="status" className="mb-5 rounded-lg border border-slate-200 bg-white p-4 text-sm">{message}{done&&<Link href="/customers" className="ml-3 font-semibold text-emerald-700 underline">View customers →</Link>}</p>}
    {!preview&&<><label className="mb-5 block max-w-xs text-xs font-medium">Default sales channel<select className="dd-input mt-1" value={channel} onChange={e=>setChannel(e.target.value)}><option value="wholesale_bulk">Bulk</option><option value="store">Stores</option><option value="online">Online</option></select></label><div className="grid gap-5 md:grid-cols-2"><section className="dd-card"><h2 className="font-semibold">From QuickBooks</h2><p className="mt-2 text-sm leading-6 text-slate-500">Load your customer list, including contact names, emails, phone numbers and addresses. Your QuickBooks records stay unchanged.</p>{quickbooksConnected?<button className="dd-primary mt-5" disabled={busy} onClick={()=>review(true)}>{pending?"Loading customers…":"Preview QuickBooks customers"}</button>:<Link className="dd-primary mt-5 inline-block" href="/settings">Connect QuickBooks</Link>}</section><section className="dd-card"><h2 className="font-semibold">From a spreadsheet</h2><p className="mt-2 text-sm leading-6 text-slate-500">Excel (.xlsx or .xls), CSV and TSV. Choose a sheet and match your column names. Up to 5,000 rows per file.</p><input className="mt-4 block w-full text-xs file:mr-3 file:rounded-lg file:border file:border-slate-200 file:bg-white file:px-3 file:py-2" aria-label="Choose customer spreadsheet" disabled={busy} type="file" accept=".xlsx,.xls,.csv,.tsv" onChange={e=>void load(e.target.files?.[0])}/><button className="mt-4 text-xs font-medium text-emerald-700 underline" onClick={template}>Download a blank column template</button></section></div>
    {active&&<section className="dd-card mt-6"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">Match your columns</h2><label className="text-xs">Sheet<select className="dd-input mt-1" value={sheet} onChange={e=>{const i=Number(e.target.value);setSheet(i);setMapping(matchColumns(sheets[i].headers));}}>{sheets.map((s,i)=><option value={i} key={i}>{s.name} · {s.rows.length} rows</option>)}</select></label></div><p className="mt-2 text-xs text-slate-500">Company / customer name is required. Other details can be blank and added later.</p><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{customerFields.map(f=><label key={f} className="text-xs font-medium">{customerLabels[f]}<select className="dd-input mt-1" value={mapping[f]||""} onChange={e=>setMapping({...mapping,[f]:e.target.value})}><option value="">{f==="channel"?"Use default channel":"Not in this sheet"}</option>{active.headers.map(h=><option key={h}>{h}</option>)}</select>{mapping[f]&&<span className="mt-1 block truncate font-normal text-slate-400">Example: {active.rows[0][mapping[f]]||"Blank"}</span>}</label>)}</div><button className="dd-primary mt-5" disabled={busy||!mapping.company} onClick={()=>review()}>{pending?"Preparing preview…":"Review customers →"}</button></section>}</>}
    {preview&&<section className="dd-card"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Review {preview.count} rows from {preview.source}</h2><p className="mt-1 text-xs text-slate-500">{selected.length} selected · {preview.rows.filter(r=>r.issue).length} need attention or match existing customers. Existing details and pricing will not be overwritten.</p></div><button className="dd-button" disabled={busy} onClick={()=>{setPreview(null);setDone(false);}}>Start another import</button></div><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b border-slate-200"><th className="p-3"><input aria-label="Select all eligible customers" type="checkbox" disabled={done||busy} checked={!!selected.length&&selected.length===preview.rows.filter(r=>!r.issue&&r.customer).length} onChange={e=>setSelected(e.target.checked?preview.rows.filter(r=>!r.issue&&r.customer).map(r=>r.index):[])}/></th>{["Customer","Contact","Email / phone","Result"].map(t=><th key={t} className="p-3 font-medium">{t}</th>)}</tr></thead><tbody>{preview.rows.slice(0,show).map(r=><tr key={r.index} className="border-b border-slate-100"><td className="p-3"><input aria-label={`Import row ${r.index+2}`} type="checkbox" disabled={!!r.issue||done||busy} checked={selected.includes(r.index)} onChange={e=>setSelected(s=>e.target.checked?[...s,r.index]:s.filter(i=>i!==r.index))}/></td><td className="p-3 font-medium">{r.customer?.company||`Row ${r.index+2}`}</td><td className="p-3">{r.customer?.buyerName||"—"}</td><td className="p-3">{r.customer?.buyerEmail||"No email"}<p className="mt-1 text-slate-400">{r.customer?.phone}</p></td><td className={`max-w-sm p-3 ${r.issue?"text-amber-800":"text-emerald-700"}`}>{r.issue||"Ready"}{r.duplicateId&&<Link className="ml-2 underline" href={`/customers/${r.duplicateId}`}>View existing</Link>}</td></tr>)}</tbody></table></div>{show<preview.count&&<button className="dd-button mt-3" onClick={()=>setShow(show+100)}>Show 100 more rows</button>}<div className="mt-5 flex flex-wrap items-center justify-between gap-3"><p className="max-w-xl text-xs leading-5 text-slate-500">Imported customer profiles are archived on this server and survive restarts. Phone numbers and source IDs are retained. Import does not subscribe contacts to marketing.</p><button className="dd-primary" disabled={busy||done||!selected.length} onClick={commit}>{pending?"Importing…":`Import ${selected.length} customers`}</button></div></section>}
  </div>;
}
