"use client";
import { useState } from "react";
import type { CustomerAccount } from "@/lib/customer-access/accounts";
import { AppointmentAvailability } from "./AppointmentAvailability";
export type CustomerSetupData = { accounts: CustomerAccount[]; settings: { enabled: boolean; pricing: boolean; ordering: boolean; orderStatus: boolean; servicePortal: boolean; booking: boolean }; customers: { id: string; company: string }[]; clients: { id: string; title: string }[] };
export function CustomerAccessSetup({ initial, baseUrl }: { initial: CustomerSetupData; baseUrl: string }) {
  const [data, setData] = useState(initial), [settings, setSettings] = useState(initial.settings), [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [invitation, setInvitation] = useState("");
  const [name, setName] = useState(""), [email, setEmail] = useState(""), [customerId, setCustomerId] = useState(""), [clientId, setClientId] = useState("");
  async function command(action: string, input: unknown) {
    setBusy(true); setMessage(""); setInvitation("");
    try {
      const response = await fetch("/api/setup/customers", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, input }) }), result = await response.json(); if (!response.ok) throw new Error(result.error);
      if (result.url) setInvitation(result.url);
      if (action === "create") { setName(""); setEmail(""); setMessage("Customer account created. Create a setup link below and share it privately after verifying the recipient."); }
      else if (action === "settings") setMessage("Website customer capabilities saved.");
      else if (action === "enable") setMessage("Account access updated; previous sessions and setup links have been revoked.");
      const state = await fetch("/api/setup/customers", { cache: "no-store" }); if (!state.ok) throw new Error("Saved, but could not refresh the account list. Reload this page."); setData(await state.json());
    } catch (e) { setMessage(e instanceof Error ? e.message : "Could not update customer access."); } finally { setBusy(false); }
  }
  return <div className="space-y-6"><section className="rounded-xl border bg-white p-5"><h2 className="text-xl font-semibold">Website capabilities</h2><p className="mt-2 text-sm text-slate-600">Customers sign in with their own account and see only linked business records. Choose which customer actions are available.</p><div className="my-4 grid gap-3 sm:grid-cols-2">{([["enabled", "Enable customer sign-in"], ["pricing", "Show customer-specific prices"], ["ordering", "Allow wholesale orders"], ["orderStatus", "Show order history and status"], ["servicePortal", "Show proposals, work, appointments and invoices"], ["booking", "Allow customers to book published appointment times"]] as const).map(([key, label]) => <label key={key} className="flex gap-2 text-sm"><input type="checkbox" checked={settings[key]} onChange={e => setSettings(s => ({ ...s, [key]: e.target.checked }))}/>{label}</label>)}</div><button className="dd-primary" disabled={busy} onClick={() => void command("settings", settings)}>Save customer capabilities</button><p className="mt-4 text-sm"><a className="underline" href={`${baseUrl}/api/website/customer`} target="_blank" rel="noreferrer">Open customer sign-in</a></p></section>
    <AppointmentAvailability/>
    <section className="rounded-xl border bg-white p-5"><h2 className="text-xl font-semibold">Invite a customer</h2><p className="mt-2 text-sm text-slate-600">Select the exact customer or service client this person may access. You can link both for an organization that buys products and services.</p><form className="mt-4 grid gap-4 sm:grid-cols-2" onSubmit={e => { e.preventDefault(); void command("create", { name, email, customerId: customerId || null, clientId: clientId || null }); }}><label className="text-sm">Customer name<input className="dd-input mt-1 w-full" value={name} onChange={e => setName(e.target.value)} required maxLength={100}/></label><label className="text-sm">Customer email<input type="email" className="dd-input mt-1 w-full" value={email} onChange={e => setEmail(e.target.value)} required maxLength={160}/></label><label className="text-sm">Product customer<select className="dd-input mt-1 w-full" value={customerId} onChange={e => setCustomerId(e.target.value)}><option value="">No product account</option>{data.customers.map(c => <option key={c.id} value={c.id}>{c.company}</option>)}</select></label><label className="text-sm">Service client<select className="dd-input mt-1 w-full" value={clientId} onChange={e => setClientId(e.target.value)}><option value="">No service account</option>{data.clients.map(c => <option key={c.id} value={c.id}>{c.title}</option>)}</select></label><button className="dd-primary w-fit" disabled={busy || (!customerId && !clientId)}>Create customer account</button></form></section>
    {message && <p role="status" className="rounded-lg border p-4 text-sm">{message}</p>}{invitation && <section className="rounded-xl border border-emerald-300 bg-emerald-50 p-5"><label className="text-sm font-semibold">Private account setup link<input className="dd-input mt-2 w-full" readOnly value={invitation} onFocus={e => e.target.select()}/></label><p className="mt-2 text-sm">This single-use link expires in 48 hours. Share it privately with the verified customer. Previous passwords, sessions and setup links have been revoked.</p></section>}
    <section className="rounded-xl border bg-white p-5"><h2 className="text-xl font-semibold">Customer accounts</h2>{!data.accounts.length && <p className="mt-3 text-sm">No customer accounts yet.</p>}{data.accounts.map(a => <article key={a.id} className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t pt-4"><div><h3 className="font-medium">{a.name}</h3><p className="text-sm text-slate-500">{a.email} · {a.status}</p><p className="text-xs text-slate-500">{data.customers.find(c => c.id === a.customerId)?.company ?? ""}{a.customerId && a.clientId ? " · " : ""}{data.clients.find(c => c.id === a.clientId)?.title ?? ""}</p></div><div className="flex gap-2"><button className="dd-secondary" disabled={busy || a.status === "disabled"} onClick={() => void command("invite", { id: a.id })}>{a.status === "active" ? "Reset password with a new link" : "Create setup link"}</button><button className="dd-secondary" disabled={busy} onClick={() => void command("enable", { id: a.id, enabled: a.status === "disabled" })}>{a.status === "disabled" ? "Enable account" : "Disable account"}</button></div></article>)}</section>
  </div>;
}
