"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { EmployeeAccount } from "@/lib/auth/employees";
export interface EmployeeAccountsState { configured: boolean; accounts: (EmployeeAccount & { role: string })[]; members: { id: string; name: string; email: string }[]; roles: string[]; loginUrl: string }
const field = "mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm";
export function EmployeeAccounts({ initial }: { initial: EmployeeAccountsState }) {
  const [state, setState] = useState(initial), [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [invite, setInvite] = useState("");
  const [memberId, setMemberId] = useState(""), [name, setName] = useState(""), [email, setEmail] = useState(""), [role, setRole] = useState("Employee"), [password, setPassword] = useState("");
  const router = useRouter();
  async function change(input: unknown) {
    setBusy(true); setMessage(""); setInvite("");
    try { const response = await fetch("/api/workspace/employees", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }); const result = await response.json();
      if (!response.ok) throw new Error(result.error ?? "Could not update access.");
      setState(result); setInvite(result.inviteUrl ?? ""); setMessage(result.inviteUrl ? "Setup link created. Share it directly with this employee." : "Access updated."); router.refresh(); return true;
    } catch (error) { setMessage(error instanceof Error ? error.message : "Connection interrupted. Reload and check the account before retrying."); return false; } finally { setBusy(false); }
  }
  return <div className="space-y-6"><header><p className="dd-eyebrow">Team · Access</p><h1 className="mt-2 text-2xl font-bold">Employee accounts</h1><p className="mt-2 text-sm text-slate-600">Give each employee their own sign-in, assigned tasks, private notes and AI roadmap. Roles grant access to additional shared business sections.</p></header>
    {message && <p role="status" className="rounded-lg border bg-amber-50 p-3 text-sm">{message}</p>}
    {!state.configured ? <form className="max-w-xl space-y-4 rounded-xl border bg-white p-5" onSubmit={async e => { e.preventDefault(); if (await change({ action: "setup", password })) setPassword(""); }}><h2 className="font-semibold">Secure your owner login first</h2><p className="text-sm text-slate-600">This turns on sign-in for the whole workspace, including this computer. You remain signed in as the owner.</p><label className="block text-sm">Your new owner password<input className={field} type="password" autoComplete="new-password" required minLength={14} maxLength={200} value={password} onChange={e => setPassword(e.target.value)}/></label><button className="dd-primary" disabled={busy}>Save owner password</button></form> : <>
    <div className="rounded-xl border bg-white p-5"><p className="text-sm font-semibold">Employee sign-in address</p><a className="mt-2 block break-all text-sm text-emerald-800 underline" href={state.loginUrl}>{state.loginUrl}</a><p className="mt-2 text-sm text-slate-500">For access from other computers, deploy the app with your HTTPS address configured as APP_BASE_URL.</p></div>
    {invite && <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-5"><label className="text-sm font-semibold">Private setup link · expires in 48 hours<input aria-label="Employee setup link" readOnly className={field} value={invite} onFocus={e => e.target.select()}/></label><button type="button" className="mt-3 rounded-lg border bg-white px-3 py-2 text-sm" onClick={async () => { try { await navigator.clipboard.writeText(invite); setMessage("Setup link copied."); } catch { setMessage("Select and copy the setup link above."); } }}>Copy setup link</button><p className="mt-2 text-sm">The employee chooses their own password. No email has been sent.</p></div>}
    <form className="space-y-4 rounded-xl border bg-white p-5" onSubmit={async e => { e.preventDefault(); if (await change({ action: "create", ...(memberId ? { memberId } : {}), name, email, role })) { setName(""); setEmail(""); setMemberId(""); } }}><h2 className="font-semibold">Add employee login</h2><div className="grid gap-4 md:grid-cols-2"><label className="text-sm">Team member<select className={field} value={memberId} onChange={e => { setMemberId(e.target.value); const member = state.members.find(m => m.id === e.target.value); setName(member?.name ?? ""); setEmail(member?.email ?? ""); }}><option value="">Create a new team member</option>{state.members.filter(m => !state.accounts.some(a => a.memberId === m.id)).map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label className="text-sm">Access role<select className={field} value={role} onChange={e => setRole(e.target.value)}>{state.roles.map(r => <option key={r}>{r}</option>)}</select></label><label className="text-sm">Full name<input className={field} required maxLength={100} value={name} onChange={e => setName(e.target.value)}/></label><label className="text-sm">Sign-in email<input className={field} type="email" required maxLength={160} value={email} onChange={e => setEmail(e.target.value)}/></label></div><p className="text-xs text-slate-500">Employee starts with personal work only. Broader roles can access the shared sections enabled in Roles &amp; access.</p><button className="dd-primary" disabled={busy}>Create account &amp; setup link</button></form>
    <ul className="space-y-3">{state.accounts.map(a => <li key={a.id} className="flex flex-wrap items-center gap-4 rounded-xl border bg-white p-5"><div className="min-w-48 flex-1"><h2 className="font-semibold">{a.name}</h2><p className="text-sm text-slate-500">{a.email} · {a.status}</p><p className="mt-1 text-xs text-slate-500">{a.lastLogin ? `Last sign-in: ${new Date(a.lastLogin).toLocaleString()}` : "Has not signed in yet"}</p></div><label className="text-sm">Role<select aria-label={`Role for ${a.name}`} className={field} disabled={busy} value={a.role === "Owner" ? "Employee" : a.role} onChange={e => void change({ action: "role", id: a.id, role: e.target.value })}>{state.roles.map(r => <option key={r}>{r}</option>)}</select></label><div className="flex flex-wrap gap-2">{a.status !== "disabled" && <button disabled={busy} className="rounded-lg border px-3 py-2 text-sm" onClick={() => { if (a.status !== "active" || window.confirm(`Reset ${a.name}'s password and sign them out on all devices?`)) void change({ action: "invite", id: a.id }); }}>{a.status === "active" ? "Reset password" : "New setup link"}</button>}<button disabled={busy} className="rounded-lg border px-3 py-2 text-sm" onClick={() => { if (a.status === "disabled" || window.confirm(`Disable ${a.name}'s login and end all their sessions?`)) void change({ action: a.status === "disabled" ? "enable" : "disable", id: a.id }); }}>{a.status === "disabled" ? "Enable login" : "Disable login"}</button></div><details className="w-full"><summary className="cursor-pointer text-sm text-emerald-800">Edit account details</summary><form className="mt-3 grid gap-3 sm:grid-cols-3" onSubmit={async e => { e.preventDefault(); const values = new FormData(e.currentTarget); await change({ action: "profile", id: a.id, name: String(values.get("name")), email: String(values.get("email")) }); }}><label className="text-sm">Full name<input name="name" required maxLength={100} defaultValue={a.name} className={field}/></label><label className="text-sm">Sign-in email<input name="email" type="email" required maxLength={160} defaultValue={a.email} className={field}/></label><button disabled={busy} className="mt-auto rounded-lg border px-3 py-2 text-sm">Save details</button><p className="text-xs text-slate-500 sm:col-span-3">Changing the email signs this employee out. Create a new setup link afterward.</p></form></details></li>)}</ul>
    {!state.accounts.length && <p className="text-sm text-slate-500">Add your first employee above. Their account stays inactive until they set a password.</p>}</>}
  </div>;
}
