"use client";
import Link from "next/link";
import { useEffect, useRef, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { FEATURES, TEMPLATES } from "@/lib/features/catalog";
import { fieldTypes, type Field, type FeatureState, type TrackerDefinition } from "@/lib/features/model";
import { activateToolAction, createTrackerAction, setToolVisibilityAction } from "@/app/features/actions";
import { TemplatePreview } from "./TemplatePreview";
const typeLabels={text:"Text",notes:"Long notes",number:"Number",money:"Amount (USD)",date:"Date",select:"Choices",checkbox:"Checkbox"};
const blank=(name=""):TrackerDefinition=>({name,description:"",fields:[{id:"title",label:"Name",type:"text",required:true,options:[]},{id:"notes",label:"Notes",type:"notes",required:false,options:[]}]});
export function FeatureLibrary({initial,initialName}:{initial:FeatureState;initialName?:string}) {
  const router=useRouter(), [pending,start]=useTransition(),[search,setSearch]=useState(""),[filter,setFilter]=useState("All");
  const [message,setMessage]=useState(""),[builder,setBuilder]=useState<TrackerDefinition|null>(initialName?blank(initialName):null),[requestId,setRequestId]=useState("");
  const [choicesText,setChoicesText]=useState<Record<string,string>>({});
  const [previewTemplate,setPreviewTemplate]=useState<(typeof TEMPLATES)[number]|null>(null),previewDialog=useRef<HTMLDialogElement>(null),builderRef=useRef<HTMLElement>(null);
  useEffect(()=>{if(previewTemplate)previewDialog.current?.showModal();else previewDialog.current?.close();},[previewTemplate]);
  const builderOpen=!!builder;
  useEffect(()=>{if(builderOpen)builderRef.current?.scrollIntoView?.({behavior:"smooth",block:"start"});},[builderOpen]);
  const matches=(name:string,description:string,category:string)=>`${name} ${description}`.toLowerCase().includes(search.toLowerCase())&&(filter==="All"||filter===category);
  function begin(def:TrackerDefinition) {setBuilder(structuredClone(def));setRequestId(crypto.randomUUID());setChoicesText(Object.fromEntries(def.fields.map(f=>[f.id,f.options.join(", ")])));setMessage("");}
  function activate(id:string,type:"feature"|"template") {start(async()=>{try{const r=await activateToolAction(id,type);setMessage(r.ok?r.result.answer:r.error);if(r.ok)router.refresh();}catch{setMessage("Connection interrupted. Try again to reopen the same tool.");}});}
  function visibility(id:string,type:"feature"|"tracker",enabled:boolean) {start(async()=>{try{const r=await setToolVisibilityAction(id,type,enabled);setMessage(r.ok?enabled?"Added to your tools.":"Hidden from your tools. Saved records are kept.":r.error);if(r.ok)router.refresh();}catch{setMessage("The change could not be saved. Try again.");}});}
  function updateField(index:number,patch:Partial<Field>) {setBuilder(b=>b?{...b,fields:b.fields.map((f,i)=>i===index?{...f,...patch}:f)}:b);}
  function create() {if(!builder)return;const id=requestId||crypto.randomUUID();setRequestId(id);start(async()=>{try{const r=await createTrackerAction(builder,id);if(r.ok){router.push(`/trackers/${r.result.tracker.id}`);router.refresh();}else setMessage(r.error);}catch{setMessage("Save interrupted. Retry to recover the same tracker.");}});}
  return <div><header className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><p className="dd-eyebrow">Make room for what you need</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Tools for your business</h1><p className="mt-2 text-sm text-slate-600">Add a ready-made tool or create a tracker with your own fields. Keep your workspace simple.</p></div><button className="dd-primary" onClick={()=>begin(blank())}>+ Create a tracker</button></header>
    {message&&<p role="status" className="mb-5 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm leading-6 text-emerald-950">{message}</p>}
    {builder&&<section ref={builderRef} className="dd-card mb-6 scroll-mt-20 border-emerald-200" aria-label="Tracker builder"><div className="flex justify-between gap-3"><div><p className="dd-eyebrow">Tracker builder</p><h2 className="mt-1 text-xl font-semibold">A place to track your work</h2></div><button className="dd-button" disabled={pending} onClick={()=>setBuilder(null)}>Close</button></div><form onSubmit={e=>{e.preventDefault();create();}}><fieldset disabled={pending} className="mt-4"><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-medium">Tracker name<input className="dd-input mt-1" required minLength={2} maxLength={70} value={builder.name} onChange={e=>setBuilder({...builder,name:e.target.value})}/></label><label className="text-xs font-medium">What is it for?<input className="dd-input mt-1" maxLength={240} value={builder.description} onChange={e=>setBuilder({...builder,description:e.target.value})}/></label></div><p className="my-4 text-xs text-slate-500">Each record includes its sales channel. Add the other details you want to keep.</p>
      <div className="space-y-3">{builder.fields.map((f,i)=><div key={f.id} className="grid items-start gap-3 rounded-lg border border-slate-200 bg-slate-50/60 p-3 sm:grid-cols-[1fr_180px_auto_auto]"><label className="text-xs">Field name<input aria-label={`Field ${i+1} name`} className="dd-input mt-1" maxLength={60} required value={f.label} onChange={e=>updateField(i,{label:e.target.value})}/></label><label className="text-xs">Type<select className="dd-input mt-1" value={f.type} onChange={e=>updateField(i,{type:e.target.value as Field["type"]})}>{fieldTypes.map(t=><option key={t} value={t}>{typeLabels[t]}</option>)}</select></label><label className="mt-6 flex items-center gap-2 text-xs"><input type="checkbox" checked={f.required} onChange={e=>updateField(i,{required:e.target.checked})}/>Required</label><button type="button" aria-label={`Remove ${f.label||`field ${i+1}`}`} className="mt-4 rounded-lg p-2 text-slate-500 hover:bg-white" disabled={builder.fields.length===1} onClick={()=>setBuilder({...builder,fields:builder.fields.filter((_,n)=>n!==i)})}>×</button>{f.type==="select"&&<label className="text-xs sm:col-span-4">Choices, separated by commas<input className="dd-input mt-1" required value={choicesText[f.id]??f.options.join(", ")} onChange={e=>{setChoicesText({...choicesText,[f.id]:e.target.value});updateField(i,{options:e.target.value.split(",").map(s=>s.trim()).filter(Boolean)});}} placeholder="Requested, In progress, Done"/></label>}</div>)}</div>
      <div className="mt-4 flex flex-wrap items-center justify-between gap-3"><button type="button" className="dd-button" disabled={builder.fields.length>=16} onClick={()=>setBuilder({...builder,fields:[...builder.fields,{id:`field_${crypto.randomUUID().slice(0,8)}`,label:"",type:"text",required:false,options:[]}]})}>+ Add field</button><button className="dd-primary">{pending?"Saving…":"Create tracker"}</button></div><p className="mt-3 text-xs text-slate-500">Your tracker stores records locally. It does not send messages, issue refunds, or update connected accounts.</p></fieldset></form></section>}
    {initial.trackers.length>0&&<section className="mb-7"><h2 className="mb-3 text-base font-semibold">Your trackers</h2><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{initial.trackers.map(t=><div key={t.id} className="dd-card flex items-center justify-between gap-3"><div><Link href={`/trackers/${t.id}`} className="text-sm font-semibold text-emerald-800 hover:underline">{t.name} ↗</Link><p className="mt-1 text-xs text-slate-500">{t.fields.length} fields · {t.enabled?"In your sidebar":"Hidden · records kept"}</p></div><button disabled={pending} onClick={()=>visibility(t.id,"tracker",!t.enabled)} className="dd-button">{t.enabled?"Hide":"Show"}</button></div>)}</div></section>}
    <div className="mb-5 flex flex-wrap items-center gap-3"><input aria-label="Search tools and templates" className="dd-input max-w-sm" placeholder="Search tools and templates" value={search} onChange={e=>setSearch(e.target.value)}/><div className="flex flex-wrap gap-1" role="group" aria-label="Tool category">{["All","Sales","Operations","Marketing","Money"].map(c=><button key={c} aria-pressed={filter===c} onClick={()=>setFilter(c)} className={`rounded-lg px-3 py-2 text-xs ${filter===c?"bg-slate-800 text-white":"text-slate-600 hover:bg-white"}`}>{c}</button>)}</div></div>
    <h2 className="mb-3 text-base font-semibold">Tracker templates <span className="ml-2 text-xs font-normal text-slate-400">Saved records · no connection needed</span></h2><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{TEMPLATES.filter(t=>matches(t.name,t.description,t.category)).map(t=>{const saved=initial.trackers.find(x=>x.templateId===t.id);return <article key={t.id} className="dd-card flex flex-col"><p className="dd-eyebrow">{t.category}</p><h3 className="mt-2 font-semibold">{t.name}</h3><p className="mb-3 mt-2 text-xs leading-5 text-slate-500">{t.description}</p><p className="mb-4 text-[11px] text-slate-400">{t.fields.map(f=>f.label).slice(0,4).join(" · ")} + more</p><div className="mt-auto flex flex-wrap gap-2"><button className="dd-button" onClick={()=>setPreviewTemplate(t)}>Preview</button>{saved?.enabled?<Link href={`/trackers/${saved.id}`} className="dd-primary">Open tracker</Link>:<button className="dd-primary" disabled={pending} onClick={()=>activate(t.id,"template")}>{saved?"Show tracker":"Use template"}</button>}<button className="dd-button" onClick={()=>begin({name:`${t.name} — custom`,description:t.description,fields:t.fields})}>Customize</button></div></article>;})}</div>
    <h2 className="mb-3 mt-8 text-base font-semibold">Business tools</h2><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{FEATURES.filter(f=>matches(f.name,f.description,f.category)).map(f=>{const enabled=f.core||initial.enabled.includes(f.id);return <article className="dd-card flex flex-col" key={f.id}><div className="flex justify-between gap-2"><p className="dd-eyebrow">{f.category}</p><span className="text-[10px] text-slate-400">{f.core?"Included":enabled?"Added":"Optional"}</span></div><h3 className="mt-2 font-semibold">{f.name}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{f.description}</p>{f.requirement&&<p className="mt-3 rounded-lg bg-amber-50 p-2 text-[11px] leading-5 text-amber-900">{f.requirement}</p>}<div className="mt-auto flex gap-2 pt-4">{enabled?<Link href={f.href} className="dd-button">Open tool ↗</Link>:<button disabled={pending} className="dd-primary" onClick={()=>activate(f.id,"feature")}>Add tool</button>}{enabled&&!f.core&&<button className="dd-button" disabled={pending} onClick={()=>visibility(f.id,"feature",false)}>Hide</button>}</div></article>;})}</div>
    {!FEATURES.some(f=>matches(f.name,f.description,f.category))&&!TEMPLATES.some(t=>matches(t.name,t.description,t.category))&&<p className="dd-card text-sm text-slate-500">No matching tools. Create a custom tracker above to keep the records you need.</p>}
    <section id="how-it-works" className="mt-8 rounded-xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold">From a request to a working tool</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[{title:"1. Say what you need",body:"Ask the assistant or browse the library. Both use the same tools."},{title:"2. Match a tool",body:"A recognized request selects an existing tool or template. Unclear requests show choices."},{title:"3. Make it yours",body:"Templates open immediately. Custom trackers let you review fields before saving."},{title:"4. Keep working",body:"Your tool appears in the sidebar. Add records, filter by channel and export your data."}].map(s=><div key={s.title} className="rounded-lg bg-[#f1f4ef] p-4"><h3 className="text-sm font-semibold text-emerald-950">{s.title}</h3><p className="mt-2 text-xs leading-5 text-slate-600">{s.body}</p></div>)}</div><p className="mt-4 text-xs leading-5 text-slate-500">The assistant uses built-in rules. It can configure supported tools and trackers; a brand-new integration or calculation still needs development. Hiding a tool keeps its data.</p></section>
    {initial.activity.length>0&&<section className="mt-7"><h2 className="mb-3 text-base font-semibold">Recent changes</h2><div className="dd-card divide-y divide-slate-100">{initial.activity.slice(0,12).map(a=><div key={a.id} className="flex flex-wrap items-center justify-between gap-2 py-2 text-xs"><Link href={a.href} className="text-slate-700 hover:underline">{a.label} <span className="text-slate-400">· {a.action}</span></Link><time dateTime={a.at} className="text-slate-400">{a.at.slice(0,16).replace("T"," ")} UTC</time></div>)}</div></section>}
    <dialog ref={previewDialog} onCancel={()=>setPreviewTemplate(null)} onClick={e=>{if(e.target===e.currentTarget)setPreviewTemplate(null);}} className="fixed inset-0 m-auto max-h-[90vh] w-[min(1000px,calc(100%_-_2rem))] overflow-y-auto rounded-2xl border border-slate-200 bg-white p-0 text-slate-900 shadow-2xl backdrop:bg-slate-900/40" aria-labelledby="template-preview-title">{previewTemplate&&<TemplatePreview template={previewTemplate} onClose={()=>setPreviewTemplate(null)} onUse={()=>{activate(previewTemplate.id,"template");setPreviewTemplate(null);}} onCustomize={()=>{begin({name:`${previewTemplate.name} — custom`,description:previewTemplate.description,fields:previewTemplate.fields});setPreviewTemplate(null);}}/>}</dialog>
  </div>;
}
