"use client";
import Link from "next/link";
import { useEffect, useState, type ReactNode } from "react";
import type { ConnectionSummary } from "@/lib/connections/catalog";
import type { Branding } from "@/lib/branding/store";
import { ConnectionWizard } from "./ConnectionWizard";
import { IndustrySetup } from "./IndustrySetup";
import { formKinds, formLabels, type Form, type WorkflowInput } from "@/lib/getting-started/model";
import type { setupState } from "@/lib/getting-started/store";
type State = ReturnType<typeof setupState>;
type Test = { testId: string; steps: string[]; message: string };
const field = "dd-input mt-1 w-full";
const emptyForm = { title: "", kind: "contact" as Form["kind"], origins: [] as string[], enabled: false };
const blankWorkflow = (formId = ""): WorkflowInput => ({ name: "Website follow-up", formId, taskTitle: "Follow up on website request", assigneeId: null, priority: "medium", channels: [] });
export function GettingStarted({ initial, connections, branding, members, baseUrl, configuration }: { initial: State; connections: ConnectionSummary[]; branding: Branding; members: { id: string; name: string }[]; baseUrl: string; configuration: ReactNode }) {
  const [state, setState] = useState(initial), [tab, setTab] = useState(branding.industrySetup ? "connect" : "industry"), [busy, setBusy] = useState(false), [notice, setNotice] = useState("");
  const [form, setForm] = useState<Omit<Form, "id" | "revision" | "createdAt"> & Partial<Pick<Form, "id" | "revision">>>(emptyForm), [origins, setOrigins] = useState(""), [site, setSite] = useState("wordpress");
  const [workflow, setWorkflow] = useState<WorkflowInput>(() => blankWorkflow(initial.forms[0]?.id)), [test, setTest] = useState<Test | null>(null), [request, setRequest] = useState(""), [unsupported, setUnsupported] = useState<string[]>([]);
  const [selected, setSelected] = useState(initial.forms[0]?.id ?? "");
  useEffect(() => { const update = () => { const hash = window.location.hash.slice(1); if (["industry", "connect", "configure", "attach", "automate"].includes(hash)) setTab(hash); }; update(); window.addEventListener("hashchange", update); return () => window.removeEventListener("hashchange", update); }, []);
  async function api(action: string, input: unknown) { const response = await fetch("/api/setup", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, input }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Could not save changes."); return data; }
  async function refresh() { const response = await fetch("/api/setup", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setState(data); }
  async function perform(action: () => Promise<void>) { if (busy) return; setBusy(true); setNotice(""); try { await action(); } catch (e) { setNotice(e instanceof Error ? e.message : "Could not complete this request."); } finally { setBusy(false); } }
  function changeWorkflow(patch: Partial<WorkflowInput>) { setWorkflow(w => ({ ...w, ...patch })); setTest(null); }
  function chooseTab(next: string) { setTab(next); window.history.pushState(null, "", `#${next}`); setNotice(""); }
  const chosen = state.forms.find(f => f.id === selected);
  const embedUrl = chosen ? `${baseUrl}/api/website/forms/${chosen.id}` : "";
  const embed = chosen ? `<iframe src="${embedUrl}" title="${chosen.title.replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;').replaceAll('>', '&gt;')}" width="100%" height="740" style="border:0" loading="lazy"></iframe>` : "";
  const stepLabels = [{ id: "connect", label: "Connect", detail: "Keep the tools you use" }, { id: "configure", label: "Configure", detail: `${branding.organizationTypes.length} workspace profiles` }, { id: "attach", label: "Attach", detail: `${state.forms.filter(f => f.enabled).length} published forms` }, { id: "automate", label: "Automate", detail: `${state.workflows.filter(w => w.enabled).length} active workflows` }];
  const availableKinds = formKinds.filter(k => !["quote", "booking", "wholesale", "volunteer"].includes(k) || branding.organizationTypes.includes(k === "wholesale" ? "product" : k === "volunteer" ? "nonprofit" : "service"));
  return <div>
    <button type="button" className="mb-4 text-sm text-emerald-700 underline" onClick={() => chooseTab("industry")}>{branding.industrySetup ? `Industry: ${branding.industrySetup.templateName} · change or customize` : "Start with your business type"}</button>
    <nav aria-label="Getting started" className="mb-6 grid grid-cols-2 gap-3 lg:grid-cols-4">{stepLabels.map((step, i) => <button key={step.id} className={`rounded-xl border p-4 text-left ${tab === step.id ? "border-emerald-700 bg-emerald-50" : "border-slate-200 bg-white"}`} aria-current={tab === step.id ? "step" : undefined} onClick={() => chooseTab(step.id)}><span className="font-semibold">{i + 1}. {step.label}</span><span className="mt-1 block text-xs text-slate-500">{step.detail}</span></button>)}</nav>
    <p role="status" aria-live="polite" className="mb-4 text-sm text-slate-700">{busy ? "Working…" : notice}</p>
    {tab === "industry" && <IndustrySetup initial={branding.industrySetup} onApplied={() => { chooseTab("connect"); setNotice("Your workspace is configured. Connect the tools you already use."); }}/>}
    {tab === "connect" && <section><h2 className="text-xl font-semibold">What do you already use?</h2><p className="mb-5 mt-2 text-sm text-slate-600">Connect only the tools you need. Each card explains what becomes available. App credentials and provider permissions may require the person who manages that account.</p>
      <ConnectionWizard initial={connections} baseUrl={baseUrl}/>
      <div className="mt-6 grid gap-4 md:grid-cols-2"><article className="dd-card"><h3 className="font-semibold">WordPress, Wix &amp; Squarespace</h3><p className="my-3 text-sm text-slate-600">Keep your public website. Add a request form using a link or an embed. WordPress adds public form shortcodes, customer account links, and an employee workspace.</p><button className="dd-button" onClick={() => chooseTab("attach")}>Choose what to attach</button></article><article className="dd-card"><h3 className="font-semibold">Google Workspace &amp; Microsoft 365</h3><p className="my-3 text-sm text-slate-600">Use provider forwarding or Zapier for supported events. Native mailbox sign-in and two-way calendar synchronization are not included in this release.</p><Link className="text-sm text-emerald-700 underline" href="/settings#zapier">Set up Zapier</Link></article></div>
      <button className="dd-primary mt-6" onClick={() => chooseTab("configure")}>Continue to workspace configuration</button>
    </section>}
    {tab === "configure" && <section><div className="mb-5 flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-semibold">Make this your organization’s workspace</h2><p className="mt-2 text-sm text-slate-600">Combine profiles, set your brand, and choose visible tools. Save a reusable template for your next client.</p></div><div className="flex gap-3"><Link className="dd-button" href="/admin/users">Employee accounts</Link><Link className="dd-button" href="/admin">Roles &amp; permissions</Link></div></div>{configuration}<button className="dd-primary mt-6" onClick={() => chooseTab("attach")}>Continue to website attachments</button></section>}
    {tab === "attach" && <section><h2 className="text-xl font-semibold">Add Shuug to your existing website</h2><p className="mb-5 mt-2 text-sm text-slate-600">Forms collect requests for your team to review. They do not confirm appointments, take payments or grant customer access.</p>
      <div className="grid gap-5 lg:grid-cols-2"><form className="dd-card space-y-4" onSubmit={e => { e.preventDefault(); void perform(async () => { const result = await api("form.save", { ...form, origins: origins.split(/\n|,/).map(v => v.trim()).filter(Boolean) }); setForm({ id: result.form.id, revision: result.form.revision, title: result.form.title, kind: result.form.kind, origins: result.form.origins, enabled: result.form.enabled }); setSelected(result.form.id); if (!workflow.formId) changeWorkflow({ formId: result.form.id }); await refresh(); setNotice(result.form.enabled ? "Form published. Copy its embed or link." : "Draft saved. Preview it before publishing."); }); }}>
        <h3 className="font-semibold">{form.id ? "Edit website form" : "Create a website form"}</h3><label className="block text-sm">Form title<input className={field} value={form.title} required maxLength={100} onChange={e => setForm(f => ({ ...f, title: e.target.value }))}/></label><label className="block text-sm">Request type<select className={field} value={form.kind} onChange={e => setForm(f => ({ ...f, kind: e.target.value as Form["kind"] }))}>{[...new Set([...availableKinds, form.kind])].map(k => <option value={k} key={k}>{formLabels[k]}</option>)}</select></label>
        <label className="block text-sm">Websites allowed to embed this form<textarea className={field} value={origins} placeholder="https://www.example.org" onChange={e => setOrigins(e.target.value)}/><span className="mt-1 block text-xs text-slate-500">One exact HTTPS origin per line. Include your live domain and any required editor/frame origin. Leave blank to use the hosted link only.</span></label>
        <label className="flex gap-2 text-sm"><input type="checkbox" checked={form.enabled} onChange={e => setForm(f => ({ ...f, enabled: e.target.checked }))}/>Publish and accept requests</label><div className="flex gap-3"><button className="dd-primary" disabled={busy}>Save form</button>{form.id && <button className="dd-button" type="button" onClick={() => { setForm(emptyForm); setOrigins(""); }}>New form</button>}</div>
      </form>
      <article className="dd-card space-y-4"><h3 className="font-semibold">Attach it</h3><label className="block text-sm">Website platform<select className={field} value={site} onChange={e => setSite(e.target.value)}>{["wordpress", "wix", "squarespace", "shopify", "other"].map(s => <option key={s} value={s}>{s === "other" ? "Another website / copy embed" : s[0].toUpperCase() + s.slice(1)}</option>)}</select></label>
        <p className="text-sm"><a className="text-emerald-700 underline" href="/setup/customers">Configure customer login, booking, prices, wholesale ordering and order status</a></p><p className="text-sm"><a className="text-emerald-700 underline" href="/setup/payments">Configure invoice payments and donations</a></p><p className="text-sm"><a className="text-emerald-700 underline" href="/restaurant/manage?tab=website">Configure restaurant menu and pickup ordering</a></p><p className="text-sm"><a className="text-emerald-700 underline" href="/restaurant/reservations">Configure restaurant table reservations and booking hours</a></p>
        {site === "wordpress" && <p className="text-sm leading-6"><a className="text-emerald-700 underline" href="/api/setup/wordpress">Download the WordPress plugin</a>. Upload under Plugins → Add New, save the backend origin, and choose website capabilities in Business → Connection. Add the generated shortcodes to your pages. Employees can use <code>[shuug_workspace]</code>.</p>}
        {site === "wix" && <p className="text-sm leading-6">In Wix, add an Embed HTML element and paste the code below. Add the site’s embed/editor origins above if needed. Your Shuug backend must use HTTPS.</p>}
        {site === "squarespace" && <p className="text-sm leading-6">Add a Code block, choose HTML and paste the iframe. Your Squarespace plan must permit iframe code. The hosted link works when embeds are unavailable.</p>}
        {site === "shopify" && <p className="text-sm leading-6">Add a Custom Liquid section to your theme and paste the iframe, or link to the hosted form. This collects requests; configure commerce synchronization separately in Connections.</p>}
        <label className="block text-sm">Saved form<select className={field} value={selected} onChange={e => setSelected(e.target.value)}><option value="">Choose a form</option>{state.forms.map(f => <option value={f.id} key={f.id}>{f.title} · {f.enabled ? "Published" : "Draft"}</option>)}</select></label>
        {chosen && <><p className="text-sm">{chosen.enabled ? "Published and accepting requests." : "Draft: publish before sharing."}</p><textarea aria-label="Website embed code" className={`${field} min-h-32 font-mono text-xs`} readOnly value={embed}/><div className="flex flex-wrap gap-3"><button className="dd-button" disabled={busy} onClick={() => void perform(async () => { await navigator.clipboard.writeText(embed); setNotice("Embed copied."); })}>Copy embed</button><button className="dd-button" onClick={() => void perform(async () => { await navigator.clipboard.writeText(embedUrl); setNotice("Hosted link copied."); })}>Copy hosted link</button><a className="dd-button" href={`${embedUrl}${chosen.enabled ? "" : "?preview=1"}`} target="_blank" rel="noreferrer">{chosen.enabled ? "Open form" : "Preview draft"}</a><button className="dd-button" onClick={() => { setForm({ id: chosen.id, revision: chosen.revision, title: chosen.title, kind: chosen.kind, origins: chosen.origins, enabled: chosen.enabled }); setOrigins(chosen.origins.join("\n")); }}>Edit form</button></div></>}
      </article></div>
      <div className="dd-card mt-5"><h3 className="font-semibold">Customer access and payments</h3><p className="mt-2 text-sm text-slate-600">Issue a private client link from the service workspace, or create a supported Stripe Checkout link from Billing. Each link belongs to its customer or payment.</p><div className="mt-3 flex gap-4"><Link className="text-sm text-emerald-700 underline" href="/modules/service-portal">Client portal</Link><Link className="text-sm text-emerald-700 underline" href="/billing">Payment links</Link></div></div>
      <div className="mt-6 flex items-center justify-between"><h3 className="font-semibold">Incoming website requests</h3><button className="dd-button" disabled={busy} onClick={() => void perform(refresh)}>Refresh requests</button></div><div className="mt-3 space-y-3">{!state.submissions.length && <p className="text-sm text-slate-500">Published forms will send requests here. Add an automation to create and assign follow-up tasks.</p>}{state.submissions.map(s => <article className="dd-card" key={s.id}><div className="flex flex-wrap justify-between gap-3"><h4 className="font-semibold">{s.name} · {s.formTitle}</h4><span className="text-xs">{s.status} · {s.createdAt.slice(0, 10)}</span></div><p className="mt-1 text-sm">{s.email}</p><p className="my-3 whitespace-pre-wrap text-sm text-slate-600">{s.message}</p>{s.records?.some(r => r.kind === "inquiry") && <p className="my-2 text-sm"><Link className="text-emerald-700 underline" href="/modules/service-intake">Review this request in Service inquiries</Link></p>}{s.records?.some(r => r.kind === "volunteer") && <p className="my-2 text-sm"><Link className="text-emerald-700 underline" href="/modules/nonprofit-volunteers">Review volunteer signup and onboarding</Link></p>}{s.status === "new" && <button className="dd-button" disabled={busy} onClick={() => void perform(async () => { await api("request.review", { id: s.id }); await refresh(); })}>Mark reviewed</button>}</article>)}</div>
      <button className="dd-primary mt-6" onClick={() => chooseTab("automate")}>Automate request follow-up</button>
    </section>}
    {tab === "automate" && <section><h2 className="text-xl font-semibold">Describe the follow-up you want</h2><p className="mt-2 text-sm text-slate-600">This workflow handles website requests: create an assigned task, then optionally send a reference to Slack or Zapier. Inventory reservation, accounting posting and order triggers need additional workflows.</p>
      <div className="mt-5 grid gap-5 lg:grid-cols-2"><div className="dd-card space-y-4"><label className="block text-sm">When this form receives a request<select className={field} value={workflow.formId} onChange={e => changeWorkflow({ formId: e.target.value })}><option value="">Choose a saved form</option>{state.forms.map(f => <option key={f.id} value={f.id}>{f.title}</option>)}</select></label><label className="block text-sm">What should happen?<textarea className={`${field} min-h-28`} maxLength={3000} value={request} placeholder="Create a high-priority follow-up task and notify our connected Slack channel." onChange={e => setRequest(e.target.value)}/></label><button className="dd-button" disabled={busy || !workflow.formId || request.trim().length < 10} onClick={() => void perform(async () => { const draft = await api("workflow.draft", { request, formId: workflow.formId }); setWorkflow(draft.workflow); setUnsupported(draft.unsupported); setTest(null); setNotice("AI draft ready. Review every step and select an assignee."); })}>Draft with AI</button><p className="text-xs text-slate-500">AI uses your configured provider. You can also edit the workflow directly.</p>{unsupported.length > 0 && <div className="rounded-lg bg-amber-50 p-3 text-sm"><p className="font-semibold">These requested steps are not supported:</p><ul className="list-disc pl-5">{unsupported.map((step, i) => <li key={i}>{step}</li>)}</ul><button className="mt-3 underline" onClick={() => { setUnsupported([]); setTest(null); setNotice("Review and test the supported subset below."); }}>Continue with only the supported steps</button></div>}</div>
      <form className="dd-card space-y-4" onSubmit={e => { e.preventDefault(); void perform(async () => { const result = await api("workflow.test", workflow); setTest(result); setNotice(result.message); }); }}><label className="block text-sm">Workflow name<input className={field} value={workflow.name} maxLength={100} required onChange={e => changeWorkflow({ name: e.target.value })}/></label><label className="block text-sm">Task instruction<input className={field} value={workflow.taskTitle} maxLength={100} required onChange={e => changeWorkflow({ taskTitle: e.target.value })}/></label><label className="block text-sm">Assign follow-up to<select className={field} value={workflow.assigneeId ?? ""} onChange={e => changeWorkflow({ assigneeId: e.target.value || null })}><option value="">Shared team queue</option>{members.map(m => <option value={m.id} key={m.id}>{m.name}</option>)}</select></label><label className="block text-sm">Priority<select className={field} value={workflow.priority} onChange={e => changeWorkflow({ priority: e.target.value as WorkflowInput["priority"] })}>{["low", "medium", "high"].map(p => <option key={p}>{p}</option>)}</select></label><fieldset><legend className="mb-2 text-sm">Optional delivery after the task is created</legend>{(["slack", "zapier"] as const).map(channel => <label key={channel} className="mb-2 flex gap-2 text-sm"><input type="checkbox" checked={workflow.channels.includes(channel)} onChange={e => changeWorkflow({ channels: e.target.checked ? [...workflow.channels, channel] : workflow.channels.filter(c => c !== channel) })}/>{channel === "slack" ? "Send a reference to the connected Slack channel" : "Send a reference to Zapier"}</label>)}</fieldset><p className="text-xs text-slate-500">Only the request reference, type, timestamp and owner workspace link leave Shuug. Contact details stay inside the workspace. External delivery requires the workflow worker.</p><button className="dd-primary" disabled={busy || !workflow.formId || unsupported.length > 0}>Test workflow without sending</button></form></div>
      {test && <article className="dd-card mt-5"><h3 className="font-semibold">Review the tested workflow</h3><ol className="my-4 flex flex-col gap-3 md:flex-row">{test.steps.map((step, i) => <li key={i} className="flex-1 rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-sm"><span className="block font-semibold">Step {i + 1}</span>{step}</li>)}</ol><p className="mb-4 text-sm">{test.message}</p><button className="dd-primary" disabled={busy} onClick={() => void perform(async () => { await api("workflow.enable", { workflow, testId: test.testId }); setTest(null); await refresh(); setNotice("Workflow enabled for new requests. Existing requests are unchanged."); })}>{workflow.channels.length ? "Enable workflow and future external deliveries" : "Enable workflow"}</button></article>}
      <div className="mt-6 flex justify-between gap-3"><h3 className="font-semibold">Workflows and run history</h3><button className="dd-button" disabled={busy} onClick={() => void perform(refresh)}>Refresh runs</button></div><div className="mt-3 space-y-3">{state.workflows.map(w => <article className="dd-card flex flex-wrap justify-between gap-3" key={w.id}><div><h4 className="font-semibold">{w.name}</h4><p className="text-xs text-slate-500">{w.enabled ? "Enabled for new requests" : "Paused"}</p></div>{w.enabled ? <button className="dd-button" disabled={busy} onClick={() => void perform(async () => { await api("workflow.pause", { id: w.id }); await refresh(); })}>Pause workflow</button> : <button className="dd-button" onClick={() => { setWorkflow({ name: w.name, formId: w.formId, taskTitle: w.taskTitle, assigneeId: w.assigneeId, priority: w.priority, channels: w.channels }); setTest(null); setNotice("Review and test this workflow to enable a new version."); }}>Review a new version</button>}</article>)}{state.runs.map(r => <article className="rounded-lg border bg-white p-3 text-sm" key={r.id}><strong>{r.workflowName} · {r.action}</strong><p>{r.status} · {r.detail}</p></article>)}</div><p className="mt-5 text-sm text-slate-500">Queued external steps wait for the workflow worker. Unconfirmed delivery requires review and is never retried automatically. <Link href="/automation" className="text-emerald-700 underline">Open existing business alert rules</Link>.</p>
    </section>}
  </div>;
}
