"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { industries, packs, type PackId } from "@/lib/industry/catalog";
import { assembleIndustry, type IndustrySetup as Configuration } from "@/lib/industry/model";
import type { previewIndustry } from "@/lib/industry/service";
export function IndustrySetup({ initial, onApplied }: { initial?: Configuration | null; onApplied: () => void }) {
  const router = useRouter(), [query, setQuery] = useState("");
  const defaults = initial ? assembleIndustry({ industryId: initial.industryId, answers: initial.answers, templateName: initial.templateName, revision: initial.revision }).setup.packs : [];
  const [id, setId] = useState(initial?.industryId ?? ""), [answers, setAnswers] = useState<Record<string, boolean>>(initial?.answers ?? {}), [added, setAdded] = useState<PackId[]>(initial?.packs.filter(p => !defaults.includes(p)) ?? []), [removed, setRemoved] = useState<PackId[]>(defaults.filter(p => !initial?.packs.includes(p)));
  const [name, setName] = useState(initial?.templateName ?? ""), [revision, setRevision] = useState(initial?.revision ?? 1), [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [preview, setPreview] = useState<ReturnType<typeof previewIndustry> | null>(null);
  const template = industries.find(i => i.id === id);
  const input = { industryId: id, answers, addedPacks: added, removedPacks: removed, templateName: name, revision };
  const selectedPacks = template && name.trim() ? assembleIndustry(input).setup.packs : [];
  function invalidate() { setPreview(null); setMessage(""); }
  function choose(next: string) { const entry = industries.find(i => i.id === next)!; setId(next); setAnswers({}); setAdded([]); setRemoved([]); setName(entry.label); setRevision(1); invalidate(); }
  async function command(apply: boolean) { setBusy(true); setMessage(""); try { const response = await fetch("/api/setup/industry", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ input, ...(apply && preview ? { apply: true, currentDigest: preview.currentDigest, proposedDigest: preview.proposedDigest } : { apply: false }) }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); if (apply) { router.refresh(); onApplied(); } else setPreview(result); } catch (e) { setMessage(e instanceof Error ? e.message : "Could not configure the workspace."); } finally { setBusy(false); } }
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-7"><h2 className="text-2xl font-semibold">What do you run?</h2><p className="mt-2 text-sm text-slate-600">Choose a starting point. Answer a few questions, then keep only the capabilities your organization needs.</p>
    <label className="mt-5 block text-sm font-medium">Find your business type<input type="search" className="dd-input mt-2 w-full" value={query} placeholder="Mechanic, restaurant, nonprofit…" onChange={e => setQuery(e.target.value)}/></label>
    <div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{industries.filter(i => `${i.label} ${i.keywords}`.toLowerCase().includes(query.toLowerCase().trim())).map(i => <button key={i.id} type="button" aria-pressed={id === i.id} className={`rounded-lg border px-4 py-3 text-left text-sm ${id === i.id ? "border-emerald-700 bg-emerald-50 font-semibold" : "border-slate-200"}`} onClick={() => choose(i.id)}>{i.label}</button>)}</div>
    {!industries.some(i => `${i.label} ${i.keywords}`.toLowerCase().includes(query.toLowerCase().trim())) && <p className="mt-3 text-sm">Choose the closest type, then customize its capabilities below.</p>}
    {template && <><fieldset className="mt-6 grid gap-3 md:grid-cols-2"><legend className="mb-3 font-semibold">A few questions about your {template.label.toLowerCase()}</legend>{template.questions.map(question => <label key={question.id} className="flex items-start gap-3 rounded-lg border p-3 text-sm"><input type="checkbox" checked={answers[question.id] ?? question.default} className="mt-1 accent-emerald-700" onChange={e => { setAnswers(a => ({ ...a, [question.id]: e.target.checked })); if (question.pack) { setAdded(a => a.filter(p => p !== question.pack)); setRemoved(a => a.filter(p => p !== question.pack)); } invalidate(); }}/><span>{question.label}<span className="mt-1 block text-xs text-slate-500">{question.detail}</span></span></label>)}</fieldset>
      <details className="mt-5 rounded-xl border p-4"><summary className="cursor-pointer font-semibold">Customize capability packs · {selectedPacks.length} selected</summary><p className="my-3 text-sm text-slate-500">Add merchandise to a nonprofit, product sales to a mechanic, or wholesale to a restaurant. Individual tool switches remain available in Branding.</p><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{packs.map(pack => <label key={pack.id} className="flex gap-2 text-sm"><input type="checkbox" checked={selectedPacks.includes(pack.id)} disabled={selectedPacks.length === 1 && selectedPacks.includes(pack.id)} onChange={e => { setAdded(a => e.target.checked ? [...new Set([...a, pack.id])] : a.filter(p => p !== pack.id)); setRemoved(a => e.target.checked ? a.filter(p => p !== pack.id) : [...new Set([...a, pack.id])]); invalidate(); }}/>{pack.label}</label>)}</div></details>
      <div className="mt-5 grid gap-3 sm:grid-cols-[1fr_130px]"><label className="text-sm">Reusable template name<input className="dd-input mt-1 w-full" required maxLength={120} value={name} onChange={e => { setName(e.target.value); invalidate(); }}/></label><label className="text-sm">Template revision<input className="dd-input mt-1 w-full" type="number" min={1} max={10000} value={revision} onChange={e => { setRevision(Math.max(1, Math.min(10000, Number(e.target.value) || 1))); invalidate(); }}/></label></div>
      <button className="dd-primary mt-5" disabled={busy || !name.trim()} onClick={() => void command(false)}>{busy ? "Preparing…" : "Preview my workspace"}</button>
    </>}
    {preview && <article className="mt-6 rounded-xl border border-emerald-200 bg-emerald-50/40 p-5"><h3 className="font-semibold">{preview.setup.templateName} — v{preview.setup.revision}</h3><p className="mt-2 text-sm">{preview.shown.length} tools shown · {preview.hidden.length} hidden. This applies the template’s visibility defaults; your records and employee permissions remain in place.</p><div className="mt-4 grid gap-4 md:grid-cols-2"><div><h4 className="text-sm font-semibold">Your workspace</h4><ul className="mt-2 max-h-64 list-disc overflow-auto pl-5 text-sm">{preview.shown.map(item => <li key={item.id}>{item.label} <span className="text-xs text-slate-500">· {item.group}</span></li>)}</ul></div><details><summary className="cursor-pointer text-sm font-semibold">Hidden by this template</summary><ul className="mt-2 max-h-64 list-disc overflow-auto pl-5 text-sm">{preview.hidden.map(item => <li key={item.id}>{item.label}</li>)}</ul></details></div>{preview.connections.length > 0 && <p className="mt-4 text-sm">Next connection: QuickBooks. You will authorize your own account in Connect.</p>}<button className="dd-primary mt-5" disabled={busy} onClick={() => void command(true)}>Apply this workspace</button></article>}
    {message && <p role="status" className="mt-4 text-sm text-rose-700">{message}</p>}
  </section>;
}
