"use client";
import Link from "next/link";
import { useState } from "react";
import type { WorkspaceUser } from "@/lib/auth/identity";
import type { Task, TaskStatus } from "@/lib/tasks/store";
const statuses: Record<TaskStatus, string> = { todo: "To do", in_progress: "In progress", review: "Ready for review", done: "Done" };
const field = "mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm";
export function MyWork({ user, initialTasks }: { user: WorkspaceUser; initialTasks: Task[] }) {
  const [tasks, setTasks] = useState(initialTasks), [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  const [title, setTitle] = useState(""), [dueDate, setDueDate] = useState(""), [priority, setPriority] = useState("medium"), [goal, setGoal] = useState("");
  const [currentPassword, setCurrentPassword] = useState(""), [password, setPassword] = useState(""), [confirm, setConfirm] = useState("");
  async function update(input: unknown) {
    setBusy(true); setMessage("");
    try { const response = await fetch("/api/workspace/me", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }); const result = await response.json();
      if (!response.ok) throw new Error(result.error ?? "Could not save your work.");
      if (result.signInRequired) { window.location.replace(new URL("/api/auth/login", window.location.origin).href); return true; }
      setTasks(result.tasks); setMessage("Saved."); return true;
    } catch (error) { setMessage(error instanceof Error ? error.message : "Connection interrupted. Refresh to check your work."); return false; } finally { setBusy(false); }
  }
  const open = tasks.filter(t => t.status !== "done"), agenda = open.filter(t => t.dueDate).sort((a, b) => a.dueDate!.localeCompare(b.dueDate!));
  return <div className="max-w-6xl space-y-6"><header className="flex flex-wrap items-center justify-between gap-4"><div><p className="dd-eyebrow">Your employee workspace</p><h1 className="mt-2 text-2xl font-bold">My work</h1><p className="mt-2 text-sm text-slate-600">Welcome, {user.name}. Your assignments, deadlines, notes and plans are here.</p></div><form method="post" action="/api/auth/logout"><button className="rounded-lg border bg-white px-4 py-2 text-sm">Sign out</button></form></header>
    <div className="grid gap-4 sm:grid-cols-3"><div className="rounded-xl border bg-white p-5"><p className="text-sm text-slate-500">Open assignments</p><p className="mt-2 text-3xl font-bold">{open.length}</p></div><Link href="/notes" className="rounded-xl border bg-white p-5"><h2 className="font-semibold">My notes</h2><p className="mt-2 text-sm text-slate-500">Create a private note and discuss it with AI →</p></Link><Link href="/copilot?tab=roadmap" className="rounded-xl border bg-white p-5"><h2 className="font-semibold">My roadmap</h2><p className="mt-2 text-sm text-slate-500">Plan your goals and track the next steps →</p></Link></div>
    {message && <p role="status" className="rounded-lg border bg-amber-50 p-3 text-sm">{message}</p>}
    <section className="space-y-4"><h2 className="text-lg font-semibold">Assigned to me</h2><ul className="space-y-3">{tasks.map(task => <li key={task.id} className="flex flex-wrap items-center gap-4 rounded-xl border bg-white p-4"><div className="min-w-48 flex-1"><h3 className="font-semibold">{task.title}</h3><p className="mt-1 text-xs text-slate-500">{task.priority} priority{task.dueDate ? ` · Due ${task.dueDate}` : ""}{task.goal ? ` · ${task.goal}` : ""}</p>{/^Website request [a-f0-9-]{36}$/.test(task.goal ?? "") && <a className="mt-2 inline-block text-sm text-emerald-700 underline" href={`/api/website/requests/${task.goal!.slice(16)}`} target="_blank" rel="noreferrer">Open assigned request</a>}</div><label className="text-sm">Status<select aria-label={`Status for ${task.title}`} className={field} disabled={busy} value={task.status} onChange={e => void update({ action: "status", id: task.id, status: e.target.value })}>{Object.entries(statuses).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></li>)}</ul>{!tasks.length && <p className="text-sm text-slate-500">No assignments yet. Add a task below, or ask your manager to assign work to your team member account.</p>}</section>
    <form className="space-y-4 rounded-xl border bg-white p-5" onSubmit={async e => { e.preventDefault(); if (await update({ action: "task", title, priority, dueDate: dueDate || null, goal: goal || null })) { setTitle(""); setGoal(""); setDueDate(""); } }}><h2 className="font-semibold">Add a task for myself</h2><label className="block text-sm">Task<input required maxLength={140} className={field} value={title} onChange={e => setTitle(e.target.value)}/></label><div className="grid gap-4 sm:grid-cols-3"><label className="text-sm">Due date<input type="date" className={field} value={dueDate} onChange={e => setDueDate(e.target.value)}/></label><label className="text-sm">Priority<select className={field} value={priority} onChange={e => setPriority(e.target.value)}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label><label className="text-sm">Goal<input maxLength={120} className={field} value={goal} onChange={e => setGoal(e.target.value)}/></label></div><button disabled={busy} className="dd-primary">Add my task</button></form>
    <section id="agenda" className="rounded-xl border bg-white p-5"><h2 className="font-semibold">My upcoming deadlines</h2><ul className="mt-3 space-y-2 text-sm">{agenda.map(task => <li key={task.id}><time className="mr-3 font-medium">{task.dueDate}</time>{task.title}</li>)}</ul>{!agenda.length && <p className="mt-2 text-sm text-slate-500">Your open tasks have no due dates.</p>}</section>
    <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">My account</h2><p className="mt-2 text-sm">{user.name} · {user.email} · {user.role}</p><p className="mt-2 text-sm text-slate-500">Your owner manages your name, sign-in email and access role.</p><details className="mt-4"><summary className="cursor-pointer text-sm font-semibold">Change my password</summary><form className="mt-4 max-w-md space-y-3" onSubmit={async e => { e.preventDefault(); if (password !== confirm) { setMessage("The new passwords do not match."); return; } await update({ action: "password", currentPassword, password }); }}><label className="block text-sm">Current password<input type="password" autoComplete="current-password" required maxLength={200} className={field} value={currentPassword} onChange={e => setCurrentPassword(e.target.value)}/></label><label className="block text-sm">New password<input type="password" autoComplete="new-password" required minLength={14} maxLength={200} className={field} value={password} onChange={e => setPassword(e.target.value)}/></label><label className="block text-sm">Confirm new password<input type="password" autoComplete="new-password" required minLength={14} maxLength={200} className={field} value={confirm} onChange={e => setConfirm(e.target.value)}/></label><p className="text-xs text-slate-500">Changing your password signs you out on all devices.</p><button disabled={busy} className="dd-primary">Save password &amp; sign out</button></form></details></section>
  </div>;
}
