"use client";
import { useState, useTransition } from "react";
import { portalLinkAction } from "@/app/modules/portal-actions";
export function PortalLinks({ clients }: { clients: { id: string; title: string }[] }) {
  const [client, setClient] = useState(""), [url, setUrl] = useState(""), [message, setMessage] = useState("");
  const [grants, setGrants] = useState<{ id: string; clientId: string; expires: number; revoked: number }[]>([]), [pending, start] = useTransition();
  function run(clientId?: string, revokeId?: string) { start(async () => { try { const result = await portalLinkAction(clientId, revokeId); if (!result.ok) throw new Error(result.error); setGrants(result.grants); setUrl(result.url ?? ""); setMessage(result.url ? "Private link created. Share it directly with this client; it expires in seven days." : "Portal access updated."); } catch (e) { setMessage(e instanceof Error ? e.message : "Request failed."); } }); }
  return <section className="space-y-3 rounded-xl border bg-white p-5"><h2 className="font-semibold">Client portal access</h2><p className="text-sm text-slate-500">Clients can review proposals, accept completed work, and see appointments and invoice balances. Each private link opens only that client’s records.</p><div className="flex flex-wrap gap-2"><select aria-label="Client for portal link" className="rounded-lg border px-3 py-2 text-sm" value={client} onChange={e => setClient(e.target.value)}><option value="">Select a client</option>{clients.map(c => <option key={c.id} value={c.id}>{c.title}</option>)}</select><button disabled={!client || pending} className="rounded-lg bg-emerald-800 px-3 py-2 text-sm font-semibold text-white disabled:opacity-40" onClick={() => run(client)}>Create private link</button><button disabled={pending} className="rounded-lg border px-3 py-2 text-sm" onClick={() => run()}>Manage existing links</button></div>{message && <p role="status" className="text-sm">{message}</p>}{url && <input aria-label="Private client portal link" readOnly value={url} onFocus={e => e.target.select()} className="w-full rounded-lg border px-3 py-2 text-xs"/>}<ul className="space-y-2 text-sm">{grants.map(g => <li key={g.id} className="flex justify-between gap-2 border-t pt-2"><span>{clients.find(c => c.id === g.clientId)?.title ?? "Client"} · {g.revoked ? "Revoked" : `Expires ${new Date(g.expires).toLocaleDateString()}`}</span>{!g.revoked && <button disabled={pending} onClick={() => run(undefined, g.id)} className="text-red-700">Revoke access</button>}</li>)}</ul></section>;
}
