"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { evaluateCampaign, evaluateKeyword, type KeywordInput, type PpcVerdict } from "@/lib/ppc/economics";
import { buildCampaignPlan, type GeneratedAds, type CampaignPlan } from "@/lib/ppc/plan";
import { formatCents } from "@/lib/money";
import type { Sku } from "@/lib/data/model";
import { MARKETS, publicWebsite, type Market } from "@/lib/ppc/market";
import type { KeywordMetric } from "@/lib/ppc/google-ads-map";
import type { AccountResult, PushResult } from "@/lib/ppc/google-ads";
import { generateAdsAction, pullCpcAction, validateCampaignAction, launchAction, accountPerformanceAction } from "@/app/ads/actions";
import { CompetitorResearch, downloadText } from "./CompetitorResearch";
interface KwRow { keyword: string; cpc: string; searches: string; source: string; metric?: KeywordMetric; market: Market }
const SEED: KwRow[] = [
  { keyword: "wholesale hot sauce", cpc: "2.40", searches: "1900", source: "Example", market: "US" },
  { keyword: "bulk hot sauce distributor", cpc: "3.10", searches: "720", source: "Example", market: "US" },
  { keyword: "hot sauce for retailers", cpc: "1.80", searches: "480", source: "Example", market: "US" },
  { keyword: "buy hot sauce by the case", cpc: "2.00", searches: "390", source: "Example", market: "US" },
];
const STYLES: Record<PpcVerdict, string> = { worth: "bg-emerald-100 text-emerald-800", marginal: "bg-amber-100 text-amber-900", skip: "bg-rose-100 text-rose-700" };
const VERDICTS: Record<PpcVerdict, string> = { worth: "Worth testing", marginal: "Break-even", skip: "Too expensive" };
const TABS = ["Competitors", "Keyword opportunities", "Campaign builder", "Results"];
const amount = (value: string) => /^\d+(\.\d{1,2})?$/.test(value) ? Math.round(Number(value) * 100) : null;
const metricRow = (m: KeywordMetric, market: Market, fetchedAt: string): KwRow => ({ keyword: m.keyword, cpc: m.cpcCents === null ? "" : (m.cpcCents / 100).toFixed(2), searches: m.monthlySearches === null ? "" : String(m.monthlySearches), source: `Google · ${fetchedAt.slice(0,10)}`, metric: m, market });
function assets(lines: string[], limit: number) { return lines.map(text => ({ text, chars: text.length, withinLimit: text.length <= limit })); }

export function PpcPlanner({ skus, googleConfigured, aiConfigured, searchConfigured, pushEnabled }: { skus: Sku[]; googleConfigured: boolean; aiConfigured: boolean; searchConfigured: boolean; pushEnabled: boolean }) {
  const [tab, setTab] = useState(0);
  const [skuId, setSkuId] = useState(skus[0]?.id ?? "");
  const sku = skus.find(s => s.id === skuId) ?? skus[0];
  const [market, setMarket] = useState<Market>("US");
  const [cases, setCases] = useState("1"), [ctr, setCtr] = useState("5"), [cvr, setCvr] = useState("2");
  const [share, setShare] = useState("25");
  const [rows, setRows] = useState<KwRow[]>(SEED);
  const [website, setWebsite] = useState("");
  const [operation, setOperation] = useState("");
  const [message, setMessage] = useState("");
  const [ads, setAds] = useState<GeneratedAds | null>(null);
  const [dailyBudget, setDailyBudget] = useState("10.00"), [maxCpc, setMaxCpc] = useState("");
  const [finalUrl, setFinalUrl] = useState("https://shuug.co/collections/wholesale");
  const [negatives, setNegatives] = useState("recipe, recipes, jobs, free, private label");
  const [campaignName, setCampaignName] = useState("");
  const [review, setReview] = useState<(PushResult & { signature: string }) | null>(null);
  const [pushed, setPushed] = useState<PushResult | null>(null);
  const [performance, setPerformance] = useState<AccountResult | null>(null);
  const gpPerCase = sku ? sku.standardPriceCents - sku.costPerCaseCents : 0;
  const validAssumptions = /^\d+$/.test(cases) && Number(cases) > 0 && Number(cases) <= 10000 && Number(cvr) > 0 && Number(cvr) <= 100 && Number(ctr) > 0 && Number(ctr) <= 100 && Number(share) > 0 && Number(share) <= 100;
  const assumptions = { ctr: Number(ctr) / 100 || .05, conversionRate: Number(cvr) / 100 || .02, valuePerConversionCents: gpPerCase * Number(cases) };
  const breakEven = validAssumptions ? Math.round(assumptions.valuePerConversionCents * assumptions.conversionRate) : 0;
  function asKeyword(r: KwRow): KeywordInput | null {
    const cpc = amount(r.cpc), searches = Number(r.searches);
    if (!r.keyword.trim() || cpc === null || cpc <= 0 || !/^\d+$/.test(r.searches) || !Number.isSafeInteger(searches) || searches > 1e9 || r.market !== market || !validAssumptions) return null;
    return { keyword: r.keyword.trim(), cpcCents: cpc, monthlySearches: Math.round(searches * Number(share) / 100) };
  }
  const validKeywords = rows.flatMap(r => { const k = asKeyword(r); return k ? [k] : []; });
  const econ = evaluateCampaign(validKeywords, validAssumptions ? assumptions : { ctr: .05, conversionRate: .02, valuePerConversionCents: 0 });
  const basePlan = buildCampaignPlan(sku?.name || "Shuug", econ);
  const plan: CampaignPlan = { ...basePlan, campaignName: campaignName || basePlan.campaignName, dailyBudgetCents: amount(dailyBudget) ?? 0, maxCpcCents: amount(maxCpc) ?? Math.max(1, Math.round(breakEven * .8)), finalUrl, market, negativeKeywords: negatives.split(",").map(s => s.trim()).filter(Boolean) };
  const signature = JSON.stringify({ plan, ads });
  const currentReview = review?.signature === signature && review.ok && review.reviewId ? review : null;
  const canReview = !!ads?.ok && plan.keywords.length > 0 && plan.dailyBudgetCents > 0 && plan.maxCpcCents > 0 && !!publicWebsite(finalUrl) && validAssumptions;
  const busy = !!operation;
  const totals = useMemo(() => (performance?.campaigns ?? []).reduce((sum,c) => ({ spend: sum.spend + c.spendCents, clicks: sum.clicks + c.clicks, conversions: sum.conversions + c.conversions }), { spend: 0, clicks: 0, conversions: 0 }), [performance]);
  async function run(name: string, fn: () => Promise<void>) { if (busy) return; setOperation(name); setMessage(""); try { await fn(); } catch { setMessage("The request did not complete. Try again; a submitted campaign will not be duplicated."); } finally { setOperation(""); } }
  function updateRow(i: number, patch: Partial<KwRow>) { setRows(p => p.map((r,j) => j === i ? { ...r, ...patch, metric: undefined, source: "Your input", market } : r)); setPushed(null); }
  function useKeywords(keywords: string[], domain?: string) {
    setRows(p => { const known = new Set(p.map(r => r.keyword.toLowerCase())); return [...p, ...keywords.filter(k => !known.has(k.toLowerCase())).map(keyword => ({ keyword, cpc: "", searches: "", source: "Research idea", market }))].slice(0, 50); });
    setWebsite(domain || ""); setTab(1); setMessage("Research keywords added. Pull Google metrics or enter your own estimates to evaluate them.");
  }
  function pull(historical: boolean) { void run("metrics", async () => {
    const seeds = rows.map(r => r.keyword.trim()).filter(Boolean).slice(0,20);
    const res = await pullCpcAction(seeds, market, !historical && website ? website : undefined, historical);
    if (!res.ok) { setMessage(res.error || "Google metrics could not be loaded."); return; }
    if (!res.keywords.length) { setMessage("Google returned no metrics for this selection. Your existing keywords are unchanged."); return; }
    const incoming = res.keywords.map(m => metricRow(m, market, res.fetchedAt || ""));
    // Historical metrics group close variants; don't duplicate their shared volume.
    if (historical) {
      const returned = new Set(res.keywords.flatMap(k => [k.keyword, ...k.closeVariants]).map(k => k.toLowerCase()));
      const missing = rows.filter(r => !returned.has(r.keyword.toLowerCase())).map(r => ({ ...r, cpc: "", searches: "", metric: undefined, source: "No Google data", market }));
      setRows([...incoming, ...missing].slice(0,50));
    } else setRows(incoming.slice(0,50));
    setMessage(`Updated ${incoming.length} keywords from Google Keyword Planner · ${MARKETS[market].label} · USD. These are historical estimates, not guaranteed prices.`);
  }); }
  function starterCopy() {
    setAds({ ok: true, headlines: assets([`Shuug ${sku.name}`.slice(0,30), "Sauces For Your Store", "Explore Shuug Wholesale", "Amba, Zhoug & Harissa"],30), descriptions: assets(["Explore Shuug sauces for your store. Browse the range and request wholesale details.", "Bring Amba, Zhoug and Harissa to your shelves. Discover wholesale options from Shuug."],90) });
    setPushed(null); setMessage("Starter copy is ready to edit. Review all claims and your landing page before submitting.");
  }
  function exportDraft() { downloadText("shuug-campaign-draft.json", JSON.stringify({ plan, ads, assumptions, modeledVisibilityPercent: Number(share), keywords: rows, exportedAt: new Date().toISOString() }, null, 2), "application/json"); }
  return <div className="space-y-5">
    <section className="flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap items-center gap-2"><span className="text-sm text-slate-500">Plan for</span><select aria-label="Product" className="dd-input !w-auto" value={skuId} onChange={e => { setSkuId(e.target.value); setAds(null); setReview(null); setPushed(null); }}>{skus.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select><select aria-label="Target market" className="dd-input !w-auto" value={market} onChange={e => { setMarket(e.target.value as Market); setReview(null); }}>{Object.entries(MARKETS).map(([k,v]) => <option key={k} value={k}>{v.label}</option>)}</select></div><Link className="dd-button" href="/settings#marketing">{googleConfigured ? "Manage connections" : "Connect Google Ads"}</Link></section>
    <div className="grid gap-3 sm:grid-cols-3"><div className="dd-card !py-4"><p className="dd-eyebrow">Product gross profit / case</p><p className="mt-1 text-2xl font-semibold tracking-tight">{formatCents(gpPerCase)}</p><p className="mt-1 text-xs text-slate-500">Catalog price less landed cost · USD</p></div><div className="dd-card !py-4"><p className="dd-eyebrow">Your break-even click cost</p><p className="mt-1 text-2xl font-semibold tracking-tight">{validAssumptions ? formatCents(breakEven) : "—"}</p><p className="mt-1 text-xs text-slate-500">{cases} case(s) / order · {cvr}% conversion assumption</p></div><div className="dd-card !py-4"><p className="dd-eyebrow">Campaign status</p><p className="mt-1 text-2xl font-semibold tracking-tight">{pushed?.ok ? "Created · paused" : "Planning"}</p><p className="mt-1 text-xs text-slate-500">{pushed?.ok ? "Review in Google Ads before enabling" : "Research, compare, then test a small campaign"}</p></div></div>
    <div role="tablist" aria-label="Marketing workspace" className="flex gap-1 overflow-x-auto border-b border-slate-200">{TABS.map((t,i) => <button id={`marketing-tab-${i}`} role="tab" aria-selected={tab === i} aria-controls={`marketing-panel-${i}`} key={t} onClick={() => { setTab(i); setMessage(""); }} className={`whitespace-nowrap border-b-2 px-4 py-3 text-sm font-medium ${tab === i ? "border-emerald-700 text-emerald-800" : "border-transparent text-slate-500 hover:text-slate-900"}`}>{t}</button>)}</div>
    {message && <p role="status" className="rounded-lg border border-slate-200 bg-white px-4 py-3 text-sm text-slate-700">{message}</p>}
    <div role="tabpanel" id="marketing-panel-0" aria-labelledby="marketing-tab-0" hidden={tab !== 0}><CompetitorResearch market={market} product={sku.name} searchConfigured={searchConfigured} onKeywords={useKeywords} /></div>
    {tab === 1 && <div role="tabpanel" id="marketing-panel-1" aria-labelledby="marketing-tab-1" className="space-y-5">
      <section className="dd-card"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">Will the numbers work?</h2><p className="mt-1 text-sm text-slate-500">A wholesale buyer may order multiple cases. Model the first order before paying for clicks.</p></div><button className="dd-button" onClick={() => setCases("10")}>Try a 10-case order</button></div><div className="mt-4 grid gap-4 sm:grid-cols-4">{[{ label: "Cases per first order", value: cases, set: setCases, hint: "Your assumption" },{ label: "Clicks → orders (%)", value: cvr, set: setCvr, hint: "Conversion rate" },{ label: "Impressions → clicks (%)", value: ctr, set: setCtr, hint: "Click-through rate" },{ label: "Search visibility (%)", value: share, set: setShare, hint: "Modeled share of searches" }].map(f => <label key={f.label} className="text-xs font-medium text-slate-600">{f.label}<input className="dd-input mt-1" type="number" min="0" value={f.value} onChange={e => f.set(e.target.value)} /><span className="mt-1 block font-normal text-slate-400">{f.hint}</span></label>)}</div>{!validAssumptions && <p role="alert" className="mt-3 text-sm text-rose-700">Use 1–10,000 cases and percentages above 0 and at most 100.</p>}<p className="mt-4 text-xs leading-5 text-slate-500">Gross-profit model before fulfillment overhead, discounts and taxes. Repeat purchases are excluded. Demand can overlap between close keyword variants.</p></section>
      <section className="dd-card"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Keyword opportunities</h2><p className="mt-1 text-sm text-slate-500">Spend only where your order margin can support it.</p></div><div className="flex gap-2"><button className="dd-button" disabled={busy || !rows.length} onClick={() => pull(true)}>{operation === "metrics" ? "Pulling metrics…" : "Update keyword costs"}</button><button className="dd-primary" disabled={busy || !rows.length} onClick={() => pull(false)}>Discover keywords</button></div></div>
      <label className="mt-4 block text-xs font-medium text-slate-600">Use a competitor website to discover related ideas (optional)<input className="dd-input mt-1 max-w-lg" placeholder="https://competitor.com" value={website} onChange={e => setWebsite(e.target.value)} /></label>
      {rows.some(r => r.source === "Example") && <div className="mt-4 flex flex-wrap justify-between gap-2 rounded-lg bg-amber-50 px-3 py-2 text-xs text-amber-900"><span>Starting costs and search volumes are examples. Replace them with Google metrics or your own data.</span><button className="font-semibold underline" onClick={() => setRows(p => p.map(r => r.source === "Example" ? { ...r, cpc: "", searches: "", source: "Your input" } : r))}>Clear example numbers</button></div>}
      <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[820px] text-left text-sm"><thead className="border-b border-slate-200 text-xs text-slate-500"><tr><th className="py-3 font-medium">Keyword / source</th><th className="px-2 font-medium">CPC · USD</th><th className="px-2 font-medium">Searches / mo</th><th className="px-2 font-medium">Cost / order</th><th className="px-2 font-medium">Profit / order</th><th className="px-2 font-medium">Decision</th><th><span className="sr-only">Remove</span></th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map((r,i) => { const kw = asKeyword(r), e = kw ? evaluateKeyword(kw, assumptions) : null; return <tr key={i}>
        <td className="w-[32%] py-3 pr-3"><input aria-label={`Keyword ${i+1}`} className="dd-input" value={r.keyword} maxLength={80} onChange={ev => updateRow(i,{keyword:ev.target.value})} /><p className="mt-1 text-[11px] text-slate-400">{r.source} · {r.market}{r.metric && ` · ${r.metric.cpcBasis === "historical_average" ? "Historical avg CPC" : r.metric.cpcBasis === "bid_proxy" ? "Bid-range proxy" : "CPC unavailable"}`}</p>{r.metric?.lowBidCents !== null && r.metric?.lowBidCents !== undefined && <p className="text-[11px] text-slate-400">Top bids {formatCents(r.metric.lowBidCents)}–{r.metric.highBidCents === null ? "?" : formatCents(r.metric.highBidCents)} · {r.metric.competition.toLowerCase()} competition</p>}</td>
        <td className="px-2"><input aria-label={`CPC for ${r.keyword || i+1}`} className="dd-input !w-24 text-right" value={r.cpc} placeholder="Unknown" inputMode="decimal" onChange={ev => updateRow(i,{cpc:ev.target.value})} /></td><td className="px-2"><input aria-label={`Monthly searches for ${r.keyword || i+1}`} className="dd-input !w-24 text-right" value={r.searches} placeholder="Unknown" inputMode="numeric" onChange={ev => updateRow(i,{searches:ev.target.value})} /></td><td className="px-2 tabular-nums">{e ? formatCents(e.cpaCents) : "—"}</td><td className={`px-2 tabular-nums ${e && e.profitPerConversionCents < 0 ? "text-rose-700" : "text-emerald-700"}`}>{e ? formatCents(e.profitPerConversionCents) : "—"}</td><td className="px-2">{e ? <span className={`whitespace-nowrap rounded-full px-2 py-1 text-[11px] font-medium ${STYLES[e.verdict]}`}>{VERDICTS[e.verdict]}</span> : <span className="text-xs text-slate-400">{r.market !== market ? "Different market" : "Needs data"}</span>}</td><td><button aria-label={`Remove ${r.keyword || "keyword"}`} onClick={() => setRows(p => p.filter((_,j) => j !== i))} className="p-2 text-lg text-slate-400 hover:text-rose-700">×</button></td>
      </tr>; })}</tbody></table></div><button className="mt-3 text-sm font-medium text-emerald-700" disabled={rows.length >= 50} onClick={() => setRows(p => [...p,{keyword:"",cpc:"",searches:"",source:"Your input",market}])}>+ Add keyword</button>
      <div className="mt-5 grid grid-cols-2 gap-4 border-t border-slate-100 pt-4 sm:grid-cols-4">{[{label:"Modeled ad spend / mo",value:formatCents(econ.totalMonthlySpendCents)},{label:"Modeled gross profit / mo",value:formatCents(econ.totalMonthlyGrossProfitCents)},{label:"After-ad profit / mo",value:formatCents(econ.totalMonthlyNetCents)},{label:"Keywords to test",value:String(plan.keywords.length)}].map(m => <div key={m.label}><p className="text-xs text-slate-500">{m.label}</p><p className="mt-1 text-lg font-semibold tabular-nums">{m.value}</p></div>)}</div><p className="mt-3 text-xs text-slate-400">Scenario for {validKeywords.length} complete keywords at {share}% visibility. This is not an estimate of any competitor’s total spend.</p><div className="mt-4 flex justify-end"><button className="dd-primary" onClick={() => setTab(2)}>Build a campaign →</button></div></section>
    </div>}
    {tab === 2 && <div role="tabpanel" id="marketing-panel-2" aria-labelledby="marketing-tab-2" className="space-y-5">
      <section className="dd-card"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">Start with a campaign you can review</h2><p className="mt-1 text-sm text-slate-500">Phrase-match Search campaign · {MARKETS[market].label} · English · created paused</p></div><button className="dd-button" onClick={exportDraft}>Export draft</button></div>
        <div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-medium">Campaign name<input className="dd-input mt-1" value={campaignName || basePlan.campaignName} maxLength={100} onChange={e => setCampaignName(e.target.value)} /></label><label className="text-xs font-medium">Where should buyers land?<input className="dd-input mt-1" value={finalUrl} onChange={e => setFinalUrl(e.target.value)} placeholder="https://your-store.com/wholesale" /></label><label className="text-xs font-medium">Average daily budget · USD<input className="dd-input mt-1" value={dailyBudget} onChange={e => setDailyBudget(e.target.value)} inputMode="decimal" /></label><label className="text-xs font-medium">Maximum cost per click · USD<input className="dd-input mt-1" value={maxCpc || (Math.max(1,Math.round(breakEven*.8))/100).toFixed(2)} onChange={e => setMaxCpc(e.target.value)} inputMode="decimal" /></label></div><p className="mt-3 text-xs leading-5 text-slate-500">Google treats this as an average daily budget and may spend more on individual days after you enable the campaign. Your CPC cap is set separately.</p>
        <div className="mt-5"><h3 className="text-sm font-medium">Keywords in this draft ({plan.keywords.length})</h3>{plan.keywords.length ? <div className="mt-2 flex flex-wrap gap-2">{plan.keywords.map(k => <span className="dd-badge" key={k}>“{k}”</span>)}</div> : <p className="mt-2 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">No keywords currently cover their acquisition cost. Update keyword data or order assumptions before creating a campaign. <button className="font-semibold underline" onClick={() => setTab(1)}>Review the numbers</button></p>}</div><label className="mt-4 block text-xs font-medium">Negative keywords · separate with commas<textarea className="dd-input mt-1" value={negatives} onChange={e => setNegatives(e.target.value)} /></label>
      </section>
      <section className="dd-card"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Write the ad</h2><p className="mt-1 text-sm text-slate-500">Start with editable copy, or ask AI for variations.</p></div><div className="flex gap-2"><button className="dd-button" onClick={starterCopy}>Use starter copy</button><button className="dd-primary" disabled={busy || !aiConfigured || !plan.keywords.length} onClick={() => void run("copy",async () => { const result = await generateAdsAction(sku.name,plan.keywords.slice(0,20)); setAds(result); if (!result.ok) setMessage(result.error || "Could not generate copy."); })}>{operation === "copy" ? "Writing…" : "Write with AI"}</button></div></div>
      {ads?.ok && <div className="mt-5 grid gap-5 md:grid-cols-2">{(["headlines","descriptions"] as const).map(section => { const limit = section === "headlines" ? 30 : 90; return <div key={section}><h3 className="mb-3 text-xs font-semibold uppercase tracking-wide text-slate-500">{section} · up to {limit} characters</h3><div className="space-y-3">{ads[section].map((a,i) => <label className="block" key={i}><span className="sr-only">{section} {i+1}</span><textarea rows={section === "headlines" ? 1 : 2} className="dd-input" value={a.text} onChange={e => setAds(p => p ? { ...p,[section]:p[section].map((old,j) => j === i ? assets([e.target.value],limit)[0] : old) } : p)} /><span className={`block text-right text-[11px] ${a.text.length > limit ? "text-rose-700" : "text-slate-400"}`}>{a.text.length}/{limit}</span></label>)}</div></div>; })}</div>}
      </section>
      <section className="dd-card"><h2 className="font-semibold">Review, then create</h2><p className="mt-1 text-sm leading-6 text-slate-500">First Google validates the full draft without creating anything. Then you can create that exact version, paused. Changes to the draft require another validation.</p><div className="mt-4 flex flex-wrap gap-3"><button className="dd-button" disabled={busy || !canReview || !googleConfigured} onClick={() => void run("validate", async () => { const result = await validateCampaignAction(plan,ads!); setReview({...result,signature}); setMessage(result.message); })}>{operation === "validate" ? "Validating…" : "1. Validate with Google"}</button><button className="dd-primary" disabled={busy || !currentReview || !pushEnabled || !!pushed?.ok} onClick={() => void run("create",async () => { const result = await launchAction(currentReview!.reviewId!); setPushed(result); setMessage(result.message); })}>{operation === "create" ? "Creating…" : "2. Create paused campaign"}</button></div>{currentReview?.account && <p className="mt-3 text-sm text-emerald-700">Validated for {currentReview.account.name} · account {currentReview.account.id} · {currentReview.account.currency}. Review expires after 15 minutes.</p>}{(!googleConfigured || !pushEnabled) && <p className="mt-3 text-xs text-slate-500">{!googleConfigured ? "Connect Google Ads to validate." : "Campaign creation is disabled in connection settings."} <Link className="text-emerald-700 underline" href="/settings#marketing">View connection settings</Link></p>}{pushed?.campaignResourceName && <p className="mt-3 text-sm"><a href="https://ads.google.com/" target="_blank" rel="noreferrer" className="text-emerald-700 underline">Review campaign in Google Ads ↗</a></p>}</section>
    </div>}
    {tab === 3 && <div role="tabpanel" id="marketing-panel-3" aria-labelledby="marketing-tab-3" className="dd-card"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-semibold">Your advertising results</h2><p className="mt-1 text-sm text-slate-500">Actual account performance for the last 30 days, excluding today, in the account’s time zone.</p></div><button className="dd-primary" disabled={busy} onClick={() => void run("results",async () => { const r = await accountPerformanceAction(); setPerformance(r); if(!r.ok) setMessage(r.error || "Unable to load results."); })}>{operation === "results" ? "Loading…" : "Refresh from Google"}</button></div>{performance?.ok && performance.account ? <><p className="mt-4 text-xs text-slate-500">{performance.account.name} · {performance.account.currency} · {performance.account.timeZone} · retrieved {performance.fetchedAt?.slice(0,10)}</p><div className="mt-4 grid grid-cols-3 gap-4">{[{label:"Ad spend",value:new Intl.NumberFormat("en-US",{style:"currency",currency:performance.account.currency}).format(totals.spend/100)},{label:"Clicks",value:totals.clicks.toLocaleString()},{label:"Reported conversions",value:totals.conversions.toLocaleString()}].map(m => <div key={m.label}><p className="text-xs text-slate-500">{m.label}</p><p className="mt-1 text-2xl font-semibold">{m.value}</p></div>)}</div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[500px] text-left text-sm"><thead><tr className="border-b border-slate-200 text-slate-500"><th className="py-3">Campaign</th><th>Status</th><th>Spend</th><th>Clicks</th><th>Conversions</th></tr></thead><tbody>{performance.campaigns?.map((c,i) => <tr key={i} className="border-b border-slate-100"><td className="py-3">{c.name}</td><td>{c.status.toLowerCase()}</td><td>{new Intl.NumberFormat("en-US",{style:"currency",currency:performance.account!.currency}).format(c.spendCents/100)}</td><td>{c.clicks}</td><td>{c.conversions}</td></tr>)}</tbody></table></div>{!performance.campaigns?.length && <p className="py-6 text-sm text-slate-500">No campaign activity reported for this period.</p>}<p className="mt-3 text-xs text-slate-400">Up to 100 campaigns by spend. Conversions follow your Google tracking configuration and are not automatically verified wholesale orders.</p></> : <div className="py-14 text-center"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-xl bg-emerald-50 text-2xl text-emerald-700">↗</div><h3 className="mt-4 font-semibold">See what your campaigns actually earn</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">Connect your advertising account to bring in spend, clicks and reported conversions. Your account totals will appear here.</p><Link href="/settings#marketing" className="dd-button mt-5">Set up Google Ads</Link></div>}</div>}
  </div>;
}
