"use client";
import { useState, useTransition } from "react";
import type { Note } from "@/lib/notes/store";
import type { Plan, PlanningThread, Roadmap } from "@/lib/planning/model";
import { organizationOptions, type OrganizationType } from "@/lib/navigation/catalog";
import { chatPlanningAction, saveRoadmapAction } from "@/app/copilot/planning-actions";
const field = "mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm";
const button = "rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold disabled:opacity-40";
export function RoadmapWorkspace({ notes, initialThreads, initialRoadmaps, selectedNote, profiles, provider }: { notes: Note[]; initialThreads: PlanningThread[]; initialRoadmaps: Roadmap[]; selectedNote?: string; profiles: OrganizationType[]; provider: string }) {
  const [threads, setThreads] = useState(initialThreads), [roadmaps, setRoadmaps] = useState(initialRoadmaps);
  const [thread, setThread] = useState<PlanningThread | null>(null), [roadmap, setRoadmap] = useState<Roadmap | null>(null);
  const [plan, setPlan] = useState<Plan | null>(null), [goal, setGoal] = useState(""), [jobRole, setJobRole] = useState("");
  const [profile, setProfile] = useState<PlanningThread["profile"]>(notes.find(n => n.id === selectedNote)?.profile ?? (profiles.length === 1 ? profiles[0] : "all"));
  const [noteIds, setNoteIds] = useState<string[]>(selectedNote && notes.some(n => n.id === selectedNote) ? [selectedNote] : []);
  const [message, setMessage] = useState(""), [notice, setNotice] = useState(""), [pending, startTransition] = useTransition();
  function openThread(value: PlanningThread) { setThread(value); setRoadmap(null); setPlan(value.draft); setProfile(value.profile); setGoal(value.goal); setJobRole(value.jobRole); setNoteIds(value.noteIds); setNotice(""); }
  function openRoadmap(value: Roadmap) { setThread(null); setRoadmap(value); setPlan(value.plan); setProfile(value.profile); setNoteIds(value.noteIds); setNotice(""); }
  function newConversation() { setThread(null); setRoadmap(null); setPlan(null); setMessage(""); setNotice(""); }
  function save() { if (!plan) return; startTransition(async () => {
    try { const result = await saveRoadmapAction({ ...(roadmap ? { id: roadmap.id, revision: roadmap.revision } : {}), profile, noteIds, plan });
      if (!result.ok) { setNotice(result.error); return; }
      setRoadmap(result.roadmap); setRoadmaps([result.roadmap, ...roadmaps.filter(r => r.id !== result.roadmap.id)]); setNotice("Roadmap and progress saved.");
    } catch { setNotice("Connection interrupted. Reload to check the saved roadmap."); }
  }); }
  function updateStep(index: number, patch: Partial<Plan["steps"][number]>) { if (plan) setPlan({ ...plan, steps: plan.steps.map((step, i) => i === index ? { ...step, ...patch } : step) }); }
  return <div className="max-w-7xl space-y-5"><header><h1 className="text-2xl font-bold">My roadmap</h1><p className="mt-2 text-sm leading-6 text-slate-600">Talk through your notes, define what your job needs to accomplish, and save an actionable plan.</p><p className="mt-1 text-xs text-slate-500">AI provider: {provider}. Only selected notes are included. Review proposed steps before saving.</p></header>
    <div className="flex flex-wrap gap-3"><button onClick={newConversation} className={button} disabled={pending}>New conversation</button><select aria-label="Open conversation" value={thread?.id ?? ""} onChange={e => { const t = threads.find(t => t.id === e.target.value); if (t) openThread(t); }} className="rounded-lg border px-3 py-2 text-sm"><option value="">Previous conversations</option>{threads.map(t => <option key={t.id} value={t.id}>{t.goal || t.messages[0]?.content.slice(0, 70)}</option>)}</select><select aria-label="Open saved roadmap" value={roadmap?.id ?? ""} onChange={e => { const r = roadmaps.find(r => r.id === e.target.value); if (r) openRoadmap(r); }} className="rounded-lg border px-3 py-2 text-sm"><option value="">Saved roadmaps</option>{roadmaps.map(r => <option key={r.id} value={r.id}>{r.plan.title}</option>)}</select></div>
    {notice && <p role="status" className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm">{notice}</p>}
    <div className="grid items-start gap-5 lg:grid-cols-2"><section className="space-y-4 rounded-xl border bg-white p-5">
      <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">My job / role<input value={jobRole} maxLength={200} onChange={e => setJobRole(e.target.value)} className={field}/></label><label className="text-sm">Workspace profile<select disabled={Boolean(thread) || pending} value={profile} onChange={e => { setProfile(e.target.value as PlanningThread["profile"]); setNoteIds([]); }} className={field}><option value="all">Shared across profiles</option>{organizationOptions.filter(p => profiles.includes(p.id)).map(p => <option key={p.id} value={p.id}>{p.label}</option>)}</select></label></div>
      <label className="block text-sm">What I need to accomplish<textarea value={goal} maxLength={2000} rows={2} onChange={e => setGoal(e.target.value)} className={field}/></label>
      <fieldset><legend className="text-sm font-medium">Notes to discuss · up to 8</legend><div className="mt-2 max-h-44 space-y-2 overflow-auto">{notes.filter(n => profile === "all" || n.profile === "all" || n.profile === profile).map(n => <label key={n.id} className="flex gap-2 text-sm"><input type="checkbox" disabled={Boolean(thread) || pending || (!noteIds.includes(n.id) && noteIds.length >= 8)} checked={noteIds.includes(n.id)} onChange={() => setNoteIds(noteIds.includes(n.id) ? noteIds.filter(id => id !== n.id) : [...noteIds, n.id])}/>{n.title || n.body.slice(0, 70)}</label>)}{!notes.length && <p className="text-xs text-slate-500">Create a note under Notes, or start with your goal here.</p>}</div></fieldset>
      <div aria-live="polite" className="max-h-[480px] space-y-3 overflow-auto">{thread?.messages.map((m, i) => <div key={i} className={`rounded-xl p-3 text-sm leading-6 ${m.role === "user" ? "bg-slate-100" : "border border-emerald-100 bg-emerald-50/40"}`}><p className="mb-1 text-xs font-semibold text-slate-500">{m.role === "user" ? "You" : "Assistant"}</p><p className="whitespace-pre-wrap">{m.content}</p></div>)}{pending && <p className="text-sm text-slate-500">Working…</p>}</div>
      <form onSubmit={e => { e.preventDefault(); startTransition(async () => {
        try { const result = await chatPlanningAction({ ...(thread ? { id: thread.id, revision: thread.revision } : {}), goal, jobRole, profile, noteIds, message });
          if (!result.ok) { setNotice(result.error); return; }
          setThread(result.thread); setThreads([result.thread, ...threads.filter(t => t.id !== result.thread.id)]); setPlan(result.thread.draft); setRoadmap(null); setMessage(""); setNotice("AI proposal ready. Review the plan and save it when it matches your work.");
        } catch { setNotice("AI connection interrupted. Your saved notes and roadmap are unchanged."); }
      }); }}><label className="block text-sm">Discuss your notes or ask for a roadmap<textarea value={message} required maxLength={4000} rows={3} onChange={e => setMessage(e.target.value)} placeholder="Use my notes to map the steps I need to complete this week." className={field}/></label><div className="mt-3 flex flex-wrap gap-2"><button disabled={pending || !message.trim()} className={`${button} bg-emerald-800 text-white`}>Talk to AI</button><button type="button" disabled={pending} className={button} onClick={() => { setRoadmap(null); setPlan({ title: "My work roadmap", outcome: goal || "Complete my work priorities", steps: [{ title: "First step", detail: "", milestone: "Getting started", due: "", status: "todo" }] }); }}>Create a plan manually</button></div></form>
    </section>
    {plan ? <section className="space-y-4 rounded-xl border bg-white p-5"><label className="block text-sm font-semibold">Roadmap title<input value={plan.title} maxLength={200} onChange={e => setPlan({ ...plan, title: e.target.value })} className={field}/></label><label className="block text-sm">Outcome<textarea value={plan.outcome} maxLength={2000} rows={2} onChange={e => setPlan({ ...plan, outcome: e.target.value })} className={field}/></label><p className="text-sm text-slate-500">{plan.steps.filter(s => s.status === "done").length} of {plan.steps.length} steps complete · {roadmap ? `Saved revision ${roadmap.revision}` : "Unsaved proposal"}</p>
      <ol className="space-y-4 border-l-2 border-emerald-200 pl-4">{plan.steps.map((step, index) => <li key={index} className="space-y-2 rounded-lg bg-slate-50 p-3"><div className="flex gap-2"><span className="pt-3 text-sm font-semibold text-emerald-800">{index + 1}</span><input aria-label={`Step ${index + 1} title`} value={step.title} maxLength={200} onChange={e => updateStep(index, { title: e.target.value })} className={field}/></div><input aria-label={`Step ${index + 1} milestone`} placeholder="Milestone" value={step.milestone} maxLength={200} onChange={e => updateStep(index, { milestone: e.target.value })} className={field}/><textarea aria-label={`Step ${index + 1} details`} value={step.detail} maxLength={2000} onChange={e => updateStep(index, { detail: e.target.value })} className={field}/><div className="flex gap-2"><input aria-label={`Step ${index + 1} due date`} type="date" value={step.due} onChange={e => updateStep(index, { due: e.target.value })} className={field}/><select aria-label={`Step ${index + 1} status`} value={step.status} onChange={e => updateStep(index, { status: e.target.value as Plan["steps"][number]["status"] })} className={field}><option value="todo">To do</option><option value="in_progress">In progress</option><option value="done">Done</option></select></div><button disabled={plan.steps.length <= 1} onClick={() => setPlan({ ...plan, steps: plan.steps.filter((_, i) => i !== index) })} className="text-xs text-slate-500 disabled:opacity-30">Remove step</button></li>)}</ol>
      <div className="flex flex-wrap gap-2"><button disabled={plan.steps.length >= 20} className={button} onClick={() => setPlan({ ...plan, steps: [...plan.steps, { title: "Next step", detail: "", milestone: "", due: "", status: "todo" }] })}>Add step</button><button disabled={pending} onClick={save} className={`${button} bg-emerald-800 text-white`}>Save roadmap & progress</button></div>
    </section> : <div className="rounded-xl border border-dashed p-6 text-sm leading-6 text-slate-500">Your roadmap appears here. Ask the assistant to map your work, open a saved plan, or create a plan manually.</div>}
    </div>
  </div>;
}
