"use client";
import Link from "next/link";
import { useEffect,useRef,useState,useTransition } from "react";
import { useSalesChannel } from "./WorkspaceShell";
import { pullAmazonAction } from "@/app/amazon/actions";
import { STAGES,isLate,type PipelineOrder } from "@/lib/amazon/pipeline";
import type { AmazonState } from "@/lib/amazon/store";
function amount(cents:number|null,currency:string|null){if(cents===null||!currency)return "Not reported";try{return new Intl.NumberFormat("en-US",{style:"currency",currency}).format(cents/100);}catch{return `${(cents/100).toFixed(2)} ${currency}`;}}
function date(value:string|null){if(!value)return "Not provided";const d=new Date(value);return Number.isFinite(d.getTime())?d.toLocaleString():"Not provided";}
export function ShippingPipeline({initial,configured}:{initial:AmazonState|null;configured:boolean}){
  const {channel}=useSalesChannel(),[state,setState]=useState(initial),[pending,start]=useTransition(),[query,setQuery]=useState(""),[fulfiller,setFulfiller]=useState("all"),[late,setLate]=useState(false),[message,setMessage]=useState(""),[selected,setSelected]=useState<string|null>(null),[days,setDays]=useState(30),[auto,setAuto]=useState(false);
  const orders=(state?.orders||[]).filter(o=>(channel==="all"||channel==="online")&&(fulfiller==="all"||o.fulfilledBy===fulfiller)&&(!late||isLate(o))&&`${o.orderId} ${o.items.map(i=>i.title+" "+i.sku).join(" ")}`.toLowerCase().includes(query.toLowerCase()));
  const current=state?.orders.find(o=>o.orderId===selected);
  function sync(continuation=false){start(async()=>{try{const r=await pullAmazonAction(days,continuation);if(r.state)setState(r.state);setMessage(r.ok?(r.state?.partial?"Saved this batch. Continue syncing to load the remaining pages.":"Amazon orders refreshed."):r.error||"Sync failed. Previously saved orders are still available.");}catch{setMessage("The connection was interrupted. Your last saved orders are still available.");}});}
  useEffect(()=>{if(!auto||!configured)return;const timer=setInterval(()=>{if(!pending&&document.visibilityState==="visible"){start(async()=>{try{const r=await pullAmazonAction(days,!!state?.nextToken);if(r.state)setState(r.state);if(!r.ok)setMessage(r.error||"Automatic refresh did not complete.");}catch{setMessage("Automatic refresh did not complete.");}});}},300000);return ()=>clearInterval(timer);},[auto,configured,days,pending,state?.nextToken]);
  return <div><header className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><p className="dd-eyebrow">Online · Amazon</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Shipping pipeline</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">See each order, the products inside it and the next fulfillment step. Amazon updates remain the source of truth.</p></div><div className="flex flex-wrap gap-2"><Link className="dd-button" href="/settings">Amazon connection</Link><button className="dd-primary" disabled={!configured||pending} onClick={()=>sync()}>{pending?"Syncing…":"Refresh Amazon orders"}</button></div></header>
    {!configured&&<div className="dd-card mb-5"><h2 className="font-semibold">Connect your Amazon seller account</h2><p className="mt-2 text-sm text-slate-500">Use the Amazon wizard in Settings to add your Selling Partner credentials and check access. Your live order pipeline will appear here.</p><Link className="dd-primary mt-4 inline-block" href="/settings">Connect Amazon →</Link></div>}
    {message&&<p role="status" className="mb-4 rounded-lg border border-slate-200 bg-white p-4 text-sm">{message}</p>}
    <div className="dd-card mb-5"><div className="flex flex-wrap items-end gap-4"><label className="text-xs font-medium">Search orders or products<input className="dd-input mt-1" placeholder="Order ID, product or SKU" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="text-xs font-medium">Fulfillment<select className="dd-input mt-1" value={fulfiller} onChange={e=>setFulfiller(e.target.value)}><option value="all">Amazon & merchant</option><option value="AMAZON">Amazon (FBA)</option><option value="MERCHANT">Our team (FBM)</option></select></label><label className="text-xs font-medium">Refresh orders updated in<select className="dd-input mt-1" disabled={pending} value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option><option value={365}>Last year</option></select></label><label className="flex items-center gap-2 py-2 text-xs"><input type="checkbox" checked={late} onChange={e=>setLate(e.target.checked)}/>Past ship-by date</label></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 pt-3"><p className="text-[11px] text-slate-400">Last saved refresh: {date(state?.syncedAt||null)} · {state?.orders.length||0} saved orders · Changing the lookback preserves older saved orders.</p><label className="flex items-center gap-2 text-xs text-slate-500"><input type="checkbox" disabled={!configured} checked={auto} onChange={e=>setAuto(e.target.checked)}/>Refresh every 5 minutes while this page is visible</label></div>{state?.nextToken&&<button className="dd-button mt-3" disabled={pending} onClick={()=>sync(true)}>Continue remaining Amazon pages →</button>}</div>
    {channel!=="all"&&channel!=="online"&&<p className="mb-4 text-sm text-slate-500">Amazon belongs to Online. Select Online or All channels in the sales view to see these orders.</p>}
    <div className="overflow-x-auto pb-4"><div className="grid min-w-[1500px] grid-cols-6 gap-3">{STAGES.map(stage=>{const rows=orders.filter(o=>o.stage===stage.id);return <section key={stage.id} className="min-h-[280px] rounded-xl border border-slate-200 bg-[#ecefea] p-3" aria-label={stage.label}><div className="mb-4 flex items-center justify-between gap-2"><h2 className="text-xs font-semibold text-slate-700">{stage.label}</h2><span className="rounded bg-white px-2 py-1 text-xs text-slate-500">{rows.length}</span></div><div className="space-y-3">{rows.map(o=><button key={o.orderId} onClick={()=>setSelected(o.orderId)} className={`w-full rounded-lg border bg-white p-3 text-left shadow-sm ${isLate(o)?"border-rose-300":"border-slate-200 hover:border-emerald-500"}`}><p className="font-mono text-[11px] font-medium">{o.orderId}</p><p className="mt-2 text-xs font-semibold leading-5">{o.items.slice(0,2).map(i=>`${i.quantity} × ${i.title}`).join(" · ")||"Product details pending"}</p>{o.items.length>2&&<p className="mt-1 text-[10px] text-slate-400">+ {o.items.length-2} more products</p>}<div className="mt-3 flex justify-between gap-2 text-[10px] text-slate-400"><span>{o.fulfilledBy==="AMAZON"?"Amazon FBA":o.fulfilledBy==="MERCHANT"?"Our team FBM":"Fulfillment unknown"}</span><span>{amount(o.totalCents,o.currency)}</span></div><p className="mt-2 text-[10px] text-slate-500">Payment: {o.payments.length?"execution reported":"not reported"}</p>{o.shipBy&&["ready","partial"].includes(o.stage)&&<p className={`mt-2 text-[10px] ${isLate(o)?"font-semibold text-rose-700":"text-slate-500"}`}>{isLate(o)?"Past ship-by":"Ship by"} · {date(o.shipBy)}</p>}</button>)}{!rows.length&&<p className="py-10 text-center text-xs text-slate-400">No orders at this stage</p>}</div></section>;})}</div></div>
    <p className="mt-2 text-xs leading-6 text-slate-500">Payment execution details are shown when Amazon supplies them. They do not confirm your bank payout. Missing amounts and payment status stay unknown. Delivered status requires every reported package to be delivered on a fully shipped order; package tracking is available for supported merchant-fulfilled orders.</p>
    {current&&<OrderDetails order={current} history={state?.history.filter(h=>h.orderId===current.orderId)||[]} close={()=>setSelected(null)}/>}
  </div>;
}
function OrderDetails({order:o,history,close}:{order:PipelineOrder;history:NonNullable<AmazonState>["history"];close:()=>void}){
  const dialog=useRef<HTMLDialogElement>(null);
  useEffect(()=>{dialog.current?.showModal();},[o.orderId]);
  return <dialog ref={dialog} onCancel={close} aria-label={`Order ${o.orderId}`} className="fixed inset-y-0 left-auto right-0 m-0 h-dvh max-h-dvh w-full max-w-2xl overflow-y-auto border-0 bg-white p-6 text-slate-900 shadow-2xl backdrop:bg-slate-900/30"><div className="flex justify-between gap-3"><div><p className="dd-eyebrow">Amazon order</p><h2 className="mt-2 text-xl font-semibold">{o.orderId}</h2></div><button aria-label="Close order details" className="dd-button" onClick={close}>×</button></div><div className="my-5 grid grid-cols-2 gap-4 rounded-xl bg-slate-50 p-4 text-xs"><p>Status<span className="mt-1 block font-semibold">{o.status}</span></p><p>Fulfilled by<span className="mt-1 block font-semibold">{o.fulfilledBy}</span></p><p>Ordered<span className="mt-1 block text-slate-500">{date(o.createdAt)}</span></p><p>Amazon last updated<span className="mt-1 block text-slate-500">{date(o.updatedAt)}</span></p><p>Ship by<span className="mt-1 block text-slate-500">{date(o.shipBy)}</span></p><p>Deliver by<span className="mt-1 block text-slate-500">{date(o.deliverBy)}</span></p></div>
    <h3 className="font-semibold">Products in this order</h3><table className="my-3 w-full text-left text-xs"><thead><tr className="border-b border-slate-200"><th className="py-3">Product</th><th>Ordered</th><th>Shipped</th><th>Remaining</th></tr></thead><tbody>{o.items.map(i=><tr key={i.id} className="border-b border-slate-100"><td className="py-3 pr-3">{i.title}<p className="mt-1 text-slate-400">{i.sku}</p></td><td>{i.quantity}</td><td>{i.shipped??"Unknown"}</td><td>{i.unshipped??"Unknown"}</td></tr>)}</tbody></table>
    <h3 className="mt-6 font-semibold">Packages & tracking</h3>{o.packages.length?o.packages.map(p=><div key={p.id} className="mt-3 rounded-lg border border-slate-200 p-3 text-xs"><p className="font-semibold">{p.carrier} · {p.status}</p><p className="mt-2 select-all font-mono">{p.tracking||"Tracking number not reported"}</p><p className="mt-2 text-slate-500">{p.detail.replaceAll("_"," ")}</p></div>):<p className="mt-2 text-xs text-slate-500">Amazon has not returned package details for this order. FBA package data may be unavailable through this API.</p>}
    <h3 className="mt-6 font-semibold">Payment information</h3>{o.payments.length?o.payments.map((p,i)=><p key={i} className="mt-2 text-xs">{p.method} · {amount(p.amountCents,p.currency)} <span className="text-slate-400">· execution reported by Amazon</span></p>):<p className="mt-2 text-xs text-slate-500">No payment execution returned. This order has not been labeled paid.</p>}
    <h3 className="mt-6 font-semibold">Changes observed here</h3><p className="mt-1 text-[11px] text-slate-400">Recorded during our refreshes, starting with the first import.</p><ol className="mt-3 space-y-3">{history.map((h,i)=><li key={i} className="border-l-2 border-emerald-200 pl-3 text-xs"><p>{h.from?`${h.from} → ${h.to}`:`First seen: ${h.to}`}</p><time className="mt-1 block text-slate-400">{date(h.at)}</time></li>)}</ol></dialog>;
}
