"use client";
import Link from "next/link";
import { useEffect,useRef,useState } from "react";
import type { Place } from "@/lib/visits/model";
import { decodePolyline } from "@/lib/visits/polyline";
interface MapInstance {fitBounds:(bounds:unknown,padding?:number)=>void;panTo:(point:{lat:number;lng:number})=>void;setZoom:(zoom:number)=>void}
interface MarkerInstance {map:MapInstance|null;addListener:(type:string,fn:()=>void)=>{remove:()=>void}}
interface MapsLibrary {Map:new(el:HTMLElement,options:Record<string,unknown>)=>MapInstance;LatLngBounds:new()=>{extend:(point:{lat:number;lng:number})=>void};marker:{AdvancedMarkerElement:new(options:Record<string,unknown>)=>MarkerInstance};Polyline:new(options:Record<string,unknown>)=>{setMap:(map:MapInstance|null)=>void}}
declare global {interface Window {google?:{maps:MapsLibrary};__shuugMapsReady?:()=>void;gm_authFailure?:()=>void}}
let loader:Promise<MapsLibrary>|null=null,loadedKey="";
function loadMaps(key:string){if(loader&&loadedKey!==key)return Promise.reject(new Error("Reload the page after changing your map display key."));if(loader)return loader;loadedKey=key;loader=new Promise<MapsLibrary>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error("The map could not load. Check your browser key, website restrictions and network.")),20000);window.__shuugMapsReady=()=>{clearTimeout(timer);if(window.google)resolve(window.google.maps);else reject(new Error("Google Maps did not initialize."));};window.gm_authFailure=()=>{clearTimeout(timer);reject(new Error("Google rejected the map display key. Check its website and Maps JavaScript API restrictions."));};const script=document.createElement("script");script.src=`https://maps.googleapis.com/maps/api/js?${new URLSearchParams({key,v:"weekly",libraries:"marker",loading:"async",callback:"__shuugMapsReady"})}`;script.async=true;script.onerror=()=>{clearTimeout(timer);reject(new Error("Could not load Google Maps."));};document.head.append(script);});return loader;}
export function StoreMap({apiKey,places,selectedId,onSelect,routeOrder=[],polyline=""}:{apiKey:string;places:Place[];selectedId:string|null;onSelect:(id:string)=>void;routeOrder?:string[];polyline?:string}){
  const host=useRef<HTMLDivElement>(null),map=useRef<MapInstance|null>(null),maps=useRef<MapsLibrary|null>(null),[ready,setReady]=useState(false),[error,setError]=useState("");const selectRef=useRef(onSelect);useEffect(()=>{selectRef.current=onSelect;},[onSelect]);
  useEffect(()=>{if(!apiKey||!host.current)return;let active=true;loadMaps(apiKey).then(lib=>{if(!active||!host.current)return;maps.current=lib;map.current=new lib.Map(host.current,{center:{lat:42.1015,lng:-72.5898},zoom:10,mapId:"DEMO_MAP_ID",mapTypeControl:false,streetViewControl:false,fullscreenControl:true});setReady(true);window.gm_authFailure=()=>setError("Google rejected the display key. Check its website restrictions in Connections.");}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;map.current=null;};},[apiKey]);
  useEffect(()=>{if(!ready||!maps.current||!map.current)return;const lib=maps.current,bounds=new lib.LatLngBounds(),listeners:{remove:()=>void}[]=[];const markers=places.map(p=>{const number=routeOrder.indexOf(p.id);const pin=document.createElement("div");pin.textContent=number>=0?String(number+1):"●";pin.style.cssText=`background:${p.id===selectedId?"#d97706":number>=0?"#315744":"#ffffff"};color:${p.id===selectedId||number>=0?"white":"#315744"};border:2px solid #315744;border-radius:50%;width:30px;height:30px;display:flex;align-items:center;justify-content:center;font:600 12px system-ui;box-shadow:0 2px 5px #0003;`;const marker=new lib.marker.AdvancedMarkerElement({map:map.current,position:{lat:p.lat,lng:p.lng},title:p.name,content:pin});listeners.push(marker.addListener("click",()=>selectRef.current(p.id)));bounds.extend({lat:p.lat,lng:p.lng});return marker;});if(places.length>1)map.current.fitBounds(bounds,50);else if(places[0]){map.current.panTo({lat:places[0].lat,lng:places[0].lng});map.current.setZoom(14);}let line:{setMap:(m:MapInstance|null)=>void}|undefined;try{if(polyline)line=new lib.Polyline({map:map.current,path:decodePolyline(polyline),strokeColor:"#315744",strokeWeight:5,strokeOpacity:.85});}catch{/* Route list remains usable if geometry is absent. */}return()=>{markers.forEach(m=>m.map=null);listeners.forEach(l=>l.remove());line?.setMap(null);};},[ready,places,selectedId,routeOrder,polyline]);
  return <div className="relative h-[520px] overflow-hidden rounded-xl border border-slate-200 bg-[#e8eddf]"><div ref={host} className="h-full w-full" aria-label="Google map of business search results"/>{(!apiKey||error)&&<div className="absolute inset-0 flex flex-col items-center justify-center bg-[#eef0e8] px-8 text-center"><svg width="80" height="80" viewBox="0 0 80 80" fill="none" aria-hidden><path d="m7 21 22-8 22 8 22-8v47l-22 8-22-8-22 8V21Z" stroke="#9cae95" strokeWidth="2"/><path d="M29 13v47M51 21v47" stroke="#9cae95" strokeWidth="2"/><path d="M51 26c0 9-11 19-11 19S29 35 29 26a11 11 0 1 1 22 0Z" fill="#426747"/><circle cx="40" cy="26" r="4" fill="#eef0e8"/></svg><h3 className="mt-5 text-lg font-semibold text-[#354d32]">{error?"Map connection needs attention":"Your next buyer is out there."}</h3><p className="mt-3 max-w-sm text-sm leading-6 text-[#74826a]">{error||"Connect Google Maps to search real businesses, see their phone numbers and put your visit list on the map."}</p><Link href="/settings" className="dd-primary mt-5">Set up Google Maps →</Link></div>}{apiKey&&!error&&!ready&&<div className="absolute inset-0 flex items-center justify-center text-sm text-slate-500">Loading your map…</div>}</div>;
}
