"use client";
import { useState } from "react";
import type { TrackerTemplate } from "@/lib/features/catalog";
const sample:Record<string,string>={company:"Example Market",buyer:"Example buyer",owner:"Your team",product:"Amba sauce",quantity:"2",task:"Follow up with buyer",campaign:"Autumn tasting",offer:"In-store product tasting",supplier:"Example supplier",reference:"PO-EXAMPLE",order:"Example order",batch:"LOT-EXAMPLE",rep:"Example rep",phone:"Phone number",next_action:"Call the buyer",reason:"Damaged case",carrier:"Your carrier",tracking:"Tracking reference",notes:"Your team's notes go here."};
export function TemplatePreview({template:t,onClose,onUse,onCustomize}:{template:TrackerTemplate;onClose:()=>void;onUse:()=>void;onCustomize:()=>void}){
  const [tab,setTab]=useState<"table"|"form">("table");
  const value=(f:TrackerTemplate["fields"][number])=>f.type==="select"?f.options[0]:f.type==="date"?"2026-10-01":f.type==="money"?"$25.00":f.type==="number"?"2":f.type==="checkbox"?"No":sample[f.id]||"Example detail";
  return <><header className="sticky top-0 z-10 flex items-start justify-between gap-4 border-b border-slate-200 bg-white p-5"><div><p className="dd-eyebrow">Template preview · example data</p><h2 id="template-preview-title" className="mt-2 text-xl font-semibold">{t.name}</h2><p className="mt-2 text-sm text-slate-500">{t.description}</p></div><button aria-label="Close template preview" className="dd-button" onClick={onClose}>×</button></header><div className="p-5"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div className="flex rounded-lg bg-slate-100 p-1" role="group" aria-label="Preview view"><button aria-pressed={tab==="table"} className={`rounded-md px-4 py-2 text-xs ${tab==="table"?"bg-white shadow-sm":"text-slate-500"}`} onClick={()=>setTab("table")}>Records table</button><button aria-pressed={tab==="form"} className={`rounded-md px-4 py-2 text-xs ${tab==="form"?"bg-white shadow-sm":"text-slate-500"}`} onClick={()=>setTab("form")}>Entry form</button></div><span className="text-xs text-slate-500">{t.fields.length} fields · Bulk / Stores / Online</span></div>
    {tab==="table"?<div className="overflow-x-auto rounded-lg border border-slate-200"><table className="w-full text-left text-xs"><thead className="bg-slate-50"><tr><th className="whitespace-nowrap p-3 font-medium">Channel</th>{t.fields.map(f=><th className="whitespace-nowrap p-3 font-medium" key={f.id}>{f.label}</th>)}</tr></thead><tbody>{["Stores","Bulk","Online"].map((channel,i)=><tr key={channel} className="border-t border-slate-100"><td className="p-3"><span className={`mr-2 inline-block h-2 w-2 rounded-full ${i===0?"bg-amber-400":i===1?"bg-violet-400":"bg-emerald-400"}`}/>{channel}</td>{t.fields.map(f=><td className="whitespace-nowrap p-3 text-slate-500" key={f.id}>{f.type==="select"?f.options[i%f.options.length]:value(f)}</td>)}</tr>)}</tbody></table></div>:<div className="grid gap-4 rounded-xl border border-slate-200 bg-slate-50/40 p-5 sm:grid-cols-2 lg:grid-cols-3"><label className="text-xs font-medium">Sales channel<select aria-label="Preview sales channel" className="dd-input mt-1" defaultValue="Stores"><option>Bulk</option><option>Stores</option><option>Online</option></select></label>{t.fields.map(f=><label className={`text-xs font-medium ${f.type==="notes"?"sm:col-span-2":""}`} key={f.id}>{f.label}{f.required&&" *"}{f.type==="select"?<select className="dd-input mt-1" defaultValue={f.options[0]}>{f.options.map(o=><option key={o}>{o}</option>)}</select>:f.type==="notes"?<textarea className="dd-input mt-1" rows={3} placeholder={value(f)}/>:f.type==="checkbox"?<input className="ml-3" type="checkbox"/>:<input className="dd-input mt-1" type={f.type==="date"?"date":f.type==="number"||f.type==="money"?"number":"text"} placeholder={value(f)} step={f.type==="money"?"0.01":"any"}/>}</label>)}</div>}
    <p className="mt-4 text-xs leading-5 text-slate-500">This is an interactive preview with fictional examples. Typing here does not save records or create a tracker. Use template starts an empty tracker or reopens your existing one with its saved records.</p></div><footer className="sticky bottom-0 flex flex-wrap justify-end gap-2 border-t border-slate-200 bg-white p-4"><button className="dd-button" onClick={onClose}>Back to templates</button><button className="dd-button" onClick={onCustomize}>Customize fields</button><button className="dd-primary" onClick={onUse}>Use template</button></footer></>;
}
