"use client";
import Link from "next/link";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { useSalesChannel } from "./WorkspaceShell";
import type { Tracker, TrackerRecord, Cell, TrackerChannel } from "@/lib/features/model";
import { displayCell, recordsCsv } from "@/lib/features/export";
import { archiveTrackerRecordAction, saveTrackerRecordAction, setToolVisibilityAction } from "@/app/features/actions";
type Draft={id:string;revision:number;channel:TrackerChannel;values:Record<string,Cell>};
export function TrackerWorkspace({initial}:{initial:Tracker}) {
  const router=useRouter(),{channel}=useSalesChannel(),[tracker,setTracker]=useState(initial),[search,setSearch]=useState(""),[archived,setArchived]=useState(false),[status,setStatus]=useState("");
  const [draft,setDraft]=useState<Draft|null>(null),[message,setMessage]=useState(""),[pending,start]=useTransition();
  const statusField=tracker.fields.find(f=>f.id==="status"&&f.type==="select"),moneyField=tracker.fields.find(f=>f.type==="money");
  const rows=tracker.records.filter(r=>r.archived===archived&&(channel==="all"||r.channel===channel)&&(!status||!statusField||r.values[statusField.id]===status)&&Object.values(r.values).join(" ").toLowerCase().includes(search.toLowerCase()));
  function edit(record?:TrackerRecord) {
    setMessage("");setDraft(record?{id:record.id,revision:record.revision,channel:record.channel,values:{...record.values}}:{id:crypto.randomUUID(),revision:0,channel:channel==="all"?"stores":channel,values:Object.fromEntries(tracker.fields.filter(f=>f.type==="checkbox"||f.type==="select").map(f=>[f.id,f.type==="checkbox"?false:f.options[0]]))});
  }
  function save() {
    if(!draft)return;
    const values={...draft.values};
    for(const f of tracker.fields)if((f.type==="number"||f.type==="money")&&values[f.id]!==undefined&&values[f.id]!=="")values[f.id]=Number(values[f.id]);
    start(async()=>{try{const r=await saveTrackerRecordAction(tracker.id,{...draft,values});if(r.ok){setTracker(r.result);setDraft(null);setMessage("Record saved.");router.refresh();}else setMessage(r.error);}catch{setMessage("Save interrupted. Retry to save this same record.");}});
  }
  function archive(record:TrackerRecord) {
    start(async()=>{try{const r=await archiveTrackerRecordAction(tracker.id,record.id,record.revision,!record.archived);if(r.ok){setTracker(r.result);setMessage(record.archived?"Record restored.":"Record archived. You can restore it from Archived.");router.refresh();}else setMessage(r.error);}catch{setMessage("The record could not be changed. Reload before trying again.");}});
  }
  function exportData() {
    const url=URL.createObjectURL(new Blob(["\uFEFF",recordsCsv(tracker.fields,rows)],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`${tracker.name.replace(/[^a-z0-9]/gi,"-").toLowerCase()}.csv`;a.click();URL.revokeObjectURL(url);
  }
  return <div><Link href="/features" className="text-xs text-slate-500 hover:underline">← Tools & trackers</Link><header className="mb-6 mt-4 flex flex-wrap items-start justify-between gap-4"><div><p className="dd-eyebrow">Your tracker</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{tracker.name}</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">{tracker.description||"Keep the records your business needs in one place."}</p></div><div className="flex gap-2"><button className="dd-button" onClick={exportData} disabled={!rows.length}>Export CSV</button><button className="dd-primary" disabled={pending} onClick={()=>edit()}>+ Add record</button></div></header>
    {!tracker.enabled&&<div className="mb-4 flex flex-wrap items-center justify-between gap-3 rounded-lg bg-amber-50 px-4 py-3 text-sm text-amber-900"><p>This tracker is hidden from the sidebar. Your records are still saved.</p><button className="dd-button" disabled={pending} onClick={()=>start(async()=>{try{const r=await setToolVisibilityAction(tracker.id,"tracker",true);if(r.ok){setTracker({...tracker,enabled:true});router.refresh();}else setMessage(r.error);}catch{setMessage("The sidebar could not be updated. Try again.");}})}>Show in sidebar</button></div>}
    {message&&<p role="status" className="mb-4 rounded-lg border border-slate-200 bg-white px-4 py-3 text-sm">{message}</p>}
    {draft&&<section className="dd-card mb-6 border-emerald-200" aria-label="Record editor"><div className="mb-4 flex items-center justify-between"><h2 className="font-semibold">{draft.revision?"Edit record":"New record"}</h2><button disabled={pending} className="dd-button" onClick={()=>setDraft(null)}>Cancel</button></div><form onSubmit={e=>{e.preventDefault();save();}}><fieldset disabled={pending} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><label className="text-xs font-medium">Sales channel<select className="dd-input mt-1" value={draft.channel} onChange={e=>setDraft({...draft,channel:e.target.value as TrackerChannel})}><option value="bulk">Bulk</option><option value="stores">Stores</option><option value="online">Online</option></select></label>{tracker.fields.map(f=><label className={`text-xs font-medium ${f.type==="notes"?"sm:col-span-2":""}`} key={f.id}>{f.label}{f.required&&<span className="ml-1 text-emerald-700">*</span>}{f.type==="checkbox"?<span className="mt-3 flex items-center gap-2"><input type="checkbox" checked={draft.values[f.id]===true} onChange={e=>setDraft({...draft,values:{...draft.values,[f.id]:e.target.checked}})}/><span className="font-normal">{draft.values[f.id]?"Yes":"No"}</span></span>:f.type==="select"?<select className="dd-input mt-1" required={f.required} value={String(draft.values[f.id]??"")} onChange={e=>setDraft({...draft,values:{...draft.values,[f.id]:e.target.value}})}><option value="">Choose…</option>{f.options.map(o=><option key={o}>{o}</option>)}</select>:f.type==="notes"?<textarea rows={3} className="dd-input mt-1" maxLength={4000} required={f.required} value={String(draft.values[f.id]??"")} onChange={e=>setDraft({...draft,values:{...draft.values,[f.id]:e.target.value}})}/>:<input className="dd-input mt-1" required={f.required} maxLength={500} type={f.type==="date"?"date":f.type==="number"||f.type==="money"?"number":"text"} step={f.type==="money"?"0.01":"any"} value={String(draft.values[f.id]??"")} onChange={e=>setDraft({...draft,values:{...draft.values,[f.id]:e.target.value}})}/>}</label>)}<div className="flex items-end sm:col-span-2 lg:col-span-3"><button className="dd-primary">{pending?"Saving…":"Save record"}</button></div></fieldset></form></section>}
    <div className="mb-4 grid gap-4 sm:grid-cols-3"><div className="dd-card"><p className="dd-eyebrow">Showing</p><p className="mt-2 text-2xl font-semibold">{rows.length}<span className="ml-2 text-xs font-normal text-slate-500">{archived?"archived":"active"} records</span></p></div><div className="dd-card"><p className="dd-eyebrow">Sales view</p><p className="mt-2 text-lg font-semibold capitalize">{channel==="all"?"All channels":channel}</p></div>{moneyField&&<div className="dd-card"><p className="dd-eyebrow">{moneyField.label} · showing</p><p className="mt-2 text-2xl font-semibold">{displayCell(moneyField,rows.reduce((n,r)=>n+(typeof r.values[moneyField.id]==="number"?Math.round((r.values[moneyField.id] as number)*100):0),0)/100)}</p><p className="mt-1 text-[11px] text-slate-400">Sum of entered amounts</p></div>}</div>
    <section className="dd-card overflow-hidden p-0"><div className="flex flex-wrap items-center gap-3 border-b border-slate-200 p-4"><input aria-label="Search tracker records" className="dd-input max-w-xs" placeholder="Search records" value={search} onChange={e=>setSearch(e.target.value)}/>{statusField&&<select aria-label="Filter by status" className="dd-input max-w-[200px]" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{statusField.options.map(o=><option key={o}>{o}</option>)}</select>}<div className="ml-auto flex gap-1"><button aria-pressed={!archived} onClick={()=>setArchived(false)} className={`dd-button ${!archived?"bg-slate-100":""}`}>Active</button><button aria-pressed={archived} onClick={()=>setArchived(true)} className={`dd-button ${archived?"bg-slate-100":""}`}>Archived</button></div></div>
      {!rows.length?<div className="px-5 py-16 text-center"><h2 className="text-lg font-semibold">{tracker.records.length?"No matching records":"Your tracker is ready"}</h2><p className="mt-2 text-sm text-slate-500">{tracker.records.length?"Change the search, status or channel to see more records.":"Add your first record. It will stay saved when you leave this page."}</p>{!tracker.records.length&&<button className="dd-primary mt-5" onClick={()=>edit()}>+ Add first record</button>}</div>:<div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-slate-50"><tr><th className="whitespace-nowrap px-4 py-3 font-medium text-slate-500">Channel</th>{tracker.fields.map(f=><th key={f.id} className="whitespace-nowrap px-4 py-3 font-medium text-slate-500">{f.label}</th>)}<th className="px-4 py-3"><span className="sr-only">Actions</span></th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-slate-100 hover:bg-slate-50/50"><td className="px-4 py-3 capitalize"><span className={`mr-2 inline-block h-2 w-2 rounded-full ${r.channel==="bulk"?"bg-violet-400":r.channel==="stores"?"bg-amber-400":"bg-emerald-400"}`}/>{r.channel}</td>{tracker.fields.map(f=><td key={f.id} className="max-w-[300px] whitespace-pre-wrap break-words px-4 py-3 text-slate-600">{displayCell(f,r.values[f.id])||"—"}</td>)}<td className="px-4 py-3"><div className="flex gap-2"><button className="dd-button" disabled={pending} onClick={()=>edit(r)}>Edit</button><button className="dd-button" disabled={pending} onClick={()=>archive(r)}>{r.archived?"Restore":"Archive"}</button></div></td></tr>)}</tbody></table></div>}
    </section><p className="mt-4 text-xs text-slate-400">Records are saved in this workspace. CSV exports include the current search, channel, status and archive filters.</p>
  </div>;
}
