"use client";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { CATEGORIES,STATUS_LABELS,type Place,type Prospect,type VisitState,type RoutePlan } from "@/lib/visits/model";
import { navigationLinks } from "@/lib/visits/navigation";
import { searchPlacesAction,refreshPlacesAction,saveProspectAction,updateProspectAction,saveVisitListAction,optimizeVisitListAction,convertProspectAction,reloadVisitsAction } from "@/app/visits/actions";
import { StoreMap } from "./StoreMap";
import { downloadText } from "./CompetitorResearch";
export function VisitPlanner({initial,browserKey,placesConfigured}:{initial:VisitState;browserKey:string;placesConfigured:boolean}) {
  const [state,setState]=useState(initial),[tab,setTab]=useState<"search"|"saved"|"route">("search"),[category,setCategory]=useState("deli"),[area,setArea]=useState("Springfield, MA"),[searchTerm,setSearchTerm]=useState("");
  const [results,setResults]=useState<Place[]>([]),[placeCache,setPlaceCache]=useState<Record<string,Place>>({}),[selectedPlace,setSelectedPlace]=useState<string|null>(null),[nextPage,setNextPage]=useState<string|undefined>(),[lastQuery,setLastQuery]=useState("");
  const [busy,setBusy]=useState(""),[message,setMessage]=useState(""),[savedFilter,setSavedFilter]=useState("all"),[savedSearch,setSavedSearch]=useState("");
  const [editId,setEditId]=useState<string|null>(null),[edit,setEdit]=useState<Partial<Prospect>>({});
  const [manual,setManual]=useState(false),[manualName,setManualName]=useState(""),[manualAddress,setManualAddress]=useState(""),[manualPhone,setManualPhone]=useState("");
  const [routeIds,setRouteIds]=useState<string[]>([]),[start,setStart]=useState(""),[roundTrip,setRoundTrip]=useState(true),[listName,setListName]=useState("My first visit list"),[listId,setListId]=useState<string|null>(null),[route,setRoute]=useState<(RoutePlan&{signature:string})|null>(null);
  const [started,setStarted]=useState(false);
  useEffect(()=>{if(!placesConfigured)return;let live=true;const ids=initial.prospects.flatMap(p=>p.placeId?[p.placeId]:[]).slice(0,20);if(!ids.length)return;void refreshPlacesAction(ids).then(r=>{if(!live)return;setPlaceCache(Object.fromEntries(r.places.map(p=>[p.id,p])));if(r.error)setMessage(r.error);}).catch(()=>{if(live)setMessage("Live business details could not load. Your saved notes are available.");});return()=>{live=false;};},[initial,placesConfigured]);
  const details=(p:Prospect)=>p.placeId?placeCache[p.placeId]:undefined;
  const name=(p:Prospect)=>p.name||details(p)?.name||"Saved Google business";
  const address=(p:Prospect)=>p.address||details(p)?.address||"Address needs refresh";
  const phone=(p:Prospect)=>p.phone||details(p)?.phone||"";
  const stops=routeIds.flatMap(id=>{const p=state.prospects.find(p=>p.id===id);return p?[p]:[];});
  const routeSignature=JSON.stringify({ids:routeIds,start,roundTrip});
  const validRoute=route?.signature===routeSignature?route:null;
  const routePlaceIds=useMemo(()=>routeIds.flatMap(id=>{const p=state.prospects.find(p=>p.id===id);return p?.placeId?[p.placeId]:[];}),[routeIds,state]);
  const mapPlaces=useMemo(()=>{const selected=tab==="search"?results:tab==="route"?routeIds.flatMap(id=>{const p=state.prospects.find(p=>p.id===id);return p?.placeId&&placeCache[p.placeId]?[placeCache[p.placeId]]:[];}):state.prospects.flatMap(p=>p.placeId&&placeCache[p.placeId]?[placeCache[p.placeId]]:[]);return [...new Map(selected.map(p=>[p.id,p])).values()];},[tab,results,routeIds,state,placeCache]);
  const visibleSaved=state.prospects.filter(p=>(savedFilter==="all"||p.status===savedFilter)&&`${name(p)} ${address(p)} ${p.decisionMaker} ${p.notes}`.toLowerCase().includes(savedSearch.toLowerCase()));
  async function run(label:string,fn:()=>Promise<void>){if(busy)return;setBusy(label);setMessage("");try{await fn();}catch{setMessage("The request did not finish. Your saved lists are still available; refresh before retrying a save.");}finally{setBusy("");}}
  function search(more=false){void run("search",async()=>{const query=more?lastQuery:`${searchTerm.trim()||CATEGORIES.find(c=>c.id===category)?.query||"grocery stores"} in ${area.trim()}`;if(!area.trim()){setMessage("Enter a city, ZIP code or neighborhood.");return;}const r=await searchPlacesAction(query,more?nextPage:undefined);setStarted(true);if(!r.ok){setMessage(r.error||"Search failed.");return;}setResults(p=>more?[...new Map([...p,...r.places].map(x=>[x.id,x])).values()]:r.places);setPlaceCache(p=>({...p,...Object.fromEntries(r.places.map(p=>[p.id,p]))}));setLastQuery(query);setNextPage(r.nextPageToken);if(!r.places.length)setMessage("No businesses found. Try another category or nearby town.");else setSelectedPlace(r.places[0].id);});}
  function openProspect(p:Prospect){setEditId(p.id);setEdit({name:p.name,address:p.address,phone:p.phone,decisionMaker:p.decisionMaker,role:p.role,email:p.email,notes:p.notes,status:p.status,nextVisit:p.nextVisit});if(p.placeId)setSelectedPlace(p.placeId);}
  function savePlace(p:Place,addToRoute=false){void run("save",async()=>{const r=await saveProspectAction({placeId:p.id});if(!r.ok||!r.state){setMessage(r.error||"Could not save this lead.");return;}setState(r.state);if(addToRoute&&r.prospectId)setRouteIds(ids=>ids.includes(r.prospectId!)?ids:[...ids,r.prospectId!].slice(0,20));setMessage(r.delivery?.some(d=>!d.ok)?"Prospect saved. An automation delivery failed; check Connections.":addToRoute?"Saved and added to your visit list.":"Prospect saved. Add the decision-maker’s name and follow-up details when you know them.");});}
  function addStop(id:string){setRouteIds(p=>p.includes(id)?p:[...p,id].slice(0,20));setMessage(routeIds.length>=20?"A driving route supports up to 20 visits. Save another list for the rest.":"Added to this visit list.");}
  function moveStop(i:number,delta:number){setRouteIds(ids=>{const next=[...ids],j=i+delta;if(j<0||j>=next.length)return ids;[next[i],next[j]]=[next[j],next[i]];return next;});}
  function saveList(){void run("list",async()=>{const id=listId||crypto.randomUUID(),r=await saveVisitListAction({id,name:listName,prospectIds:routeIds,startAddress:start,returnToStart:roundTrip,updatedAt:new Date().toISOString()},state.revision);if(r.ok&&r.state){setState(r.state);setListId(id);setMessage("Visit list saved. Your stops and order will be here next time.");}else setMessage(r.error||"List could not be saved.");});}
  function optimize(){void run("route",async()=>{const r=await optimizeVisitListAction(start,routeIds,roundTrip);if(r.ok&&r.route){setRouteIds(r.route.orderedIds);setRoute({...r.route,signature:JSON.stringify({ids:r.route.orderedIds,start,roundTrip})});setMessage("Google optimized the stop order using driving routes. Save the list to keep this order.");}else setMessage(r.error||"Route could not be calculated.");});}
  function exportNotes(){const csv=(s:string)=>`"${(/^[=+\-@]/.test(s)?"'":"")+s.replace(/"/g,'""')}"`;const rows=[['Order','Your business name','Your address','Your phone','Decision maker','Role','Email','Status','Notes','Google Place ID'],...stops.map((p,i)=>[String(i+1),p.name,p.address,p.phone,p.decisionMaker,p.role,p.email,STATUS_LABELS[p.status],p.notes,p.placeId||""])];downloadText("visit-list-notes.csv",rows.map(r=>r.map(csv).join(",")).join("\n"),"text/csv");}
  const links=navigationLinks(start,stops.map(p=>({name:name(p),address:p.address||details(p)?.address||"",placeId:p.placeId})),roundTrip);
  const selectedProspect=state.prospects.find(p=>p.id===editId);
  return <div className="space-y-5"><header className="flex flex-wrap items-center justify-between gap-4"><div><p className="dd-eyebrow">Find your next retail buyer</p><h1 className="mt-1 text-2xl font-bold tracking-tight">Store finder & visits</h1><p className="mt-2 text-sm text-slate-500">Find the right businesses. Meet the right people. Make every trip count.</p></div><div className="flex gap-2"><button className="dd-button" onClick={()=>setManual(!manual)}>+ Add a business</button><button className="dd-primary" onClick={()=>setTab("route")}>My visit list <span className="rounded bg-white/15 px-1.5">{routeIds.length}</span></button></div></header>
    <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex gap-1 rounded-lg bg-slate-200/50 p-1" role="tablist" aria-label="Store finder views">{([{id:"search",label:"Discover businesses"},{id:"saved",label:`Saved prospects (${state.prospects.length})`},{id:"route",label:"Plan visits"}] as const).map(t=><button key={t.id} role="tab" aria-selected={tab===t.id} onClick={()=>setTab(t.id)} className={`rounded-md px-3 py-2 text-xs font-semibold ${tab===t.id?"bg-white text-slate-900 shadow-sm":"text-slate-500"}`}>{t.label}</button>)}</div><span className="text-xs text-slate-400">{placesConfigured?"Google Places connected":"Live business search needs Google Maps"}</span></div>
    {message&&<p role="status" className="rounded-lg border border-slate-200 bg-white p-3 text-sm text-slate-700">{message}<button className="ml-3 text-xs text-emerald-700 underline" disabled={!!busy} onClick={()=>void run("refresh",async()=>{const r=await reloadVisitsAction();if(r.ok&&r.state)setState(r.state);else setMessage(r.error||"Could not refresh.");})}>Refresh saved data</button></p>}
    {manual&&<form className="dd-card" onSubmit={e=>{e.preventDefault();void run("manual",async()=>{const r=await saveProspectAction({name:manualName,address:manualAddress,phone:manualPhone});if(r.ok&&r.state){setState(r.state);setManual(false);setManualName("");setManualAddress("");setManualPhone("");setTab("saved");setMessage("Business saved to your prospect list.");}else setMessage(r.error||"Could not save.");});}}><h2 className="text-sm font-semibold">Add a business you know</h2><div className="mt-4 grid gap-3 sm:grid-cols-3">{[{label:"Business name",value:manualName,set:setManualName},{label:"Street address",value:manualAddress,set:setManualAddress},{label:"Business phone",value:manualPhone,set:setManualPhone}].map(f=><label key={f.label} className="text-xs font-medium">{f.label}<input className="dd-input mt-1" value={f.value} onChange={e=>f.set(e.target.value)} required={f.label==="Business name"}/></label>)}</div><button className="dd-primary mt-4" disabled={!!busy}>Save business</button></form>}
    {tab==="search"&&<section className="dd-card"><form onSubmit={e=>{e.preventDefault();search();}}><div className="grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><label className="text-xs font-medium">Search around<input className="dd-input mt-1" value={area} onChange={e=>setArea(e.target.value)} placeholder="City, ZIP or neighborhood" maxLength={160}/></label><label className="text-xs font-medium">Business or specialty (optional)<input className="dd-input mt-1" value={searchTerm} onChange={e=>setSearchTerm(e.target.value)} placeholder="Mediterranean deli, natural foods…" maxLength={120}/></label><button disabled={!!busy} className="dd-primary self-end !py-2.5">{busy==="search"?"Searching…":"Search Google Places"}</button></div><div className="mt-4 flex flex-wrap gap-2">{CATEGORIES.map(c=><button type="button" key={c.id} onClick={()=>{setCategory(c.id);setSearchTerm("");}} aria-pressed={category===c.id&&!searchTerm} className={`rounded-full border px-3 py-1.5 text-xs font-medium ${category===c.id&&!searchTerm?"border-emerald-300 bg-emerald-50 text-emerald-800":"border-slate-200 text-slate-500 hover:border-slate-400"}`}>{c.label}</button>)}</div></form></section>}
    <div className="grid items-start gap-5 xl:grid-cols-[minmax(310px,.8fr)_minmax(0,1.2fr)]"><section className="space-y-3">
      {tab==="search"&&<><div className="flex justify-between text-xs"><span className="font-medium text-slate-600">{results.length?`${results.length} businesses` : "Discover places to stock Shuug"}</span>{results.length>0&&<span className="text-slate-400">Google Maps</span>}</div><div className="max-h-[670px] space-y-3 overflow-y-auto pr-1">{results.map(p=>{const saved=state.prospects.find(s=>s.placeId===p.id);return <article key={p.id} className={`dd-card !p-4 ${selectedPlace===p.id?"!border-emerald-400":""}`}><button className="text-left" onClick={()=>setSelectedPlace(p.id)}><h3 className="text-sm font-semibold">{p.name}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{p.address}</p></button><div className="mt-2 flex flex-wrap items-center gap-3 text-xs">{p.phone?<a className="font-medium text-emerald-700" href={`tel:${p.phone.replace(/[^+\d]/g,"")}`}>{p.phone}</a>:<span className="text-slate-400">Phone not listed</span>}{p.website&&<a href={p.website} target="_blank" rel="noreferrer" className="text-slate-500 underline">Website ↗</a>}<a className="text-slate-500 underline" target="_blank" rel="noreferrer" href={p.mapsUrl}>Google Maps ↗</a></div>{p.businessStatus!=="OPERATIONAL"&&<p className="mt-2 text-[11px] text-amber-700">Business status: {p.businessStatus.toLowerCase().replace(/_/g," ")}</p>}{p.hours.length>0&&<details className="mt-2 text-[11px] text-slate-400"><summary className="cursor-pointer">Business hours</summary><ul className="mt-1 leading-5">{p.hours.map(h=><li key={h}>{h}</li>)}</ul></details>}<div className="mt-3 flex gap-2"><button className="dd-button flex-1" disabled={!!busy} onClick={()=>saved?openProspect(saved):savePlace(p)}>{saved?"Edit buyer notes":"Save prospect"}</button><button className="dd-primary flex-1" disabled={!!busy||routeIds.length>=20||!!saved&&routeIds.includes(saved.id)} onClick={()=>saved?addStop(saved.id):savePlace(p,true)}>{saved&&routeIds.includes(saved.id)?"In visit list":"+ Add to visits"}</button></div></article>;})}{!results.length&&<div className="dd-card py-10 text-center"><span className="text-3xl text-emerald-700">⌖</span><h3 className="mt-3 text-sm font-semibold">{started?"Try a nearby area":"Start with a neighborhood"}</h3><p className="mt-2 text-xs leading-6 text-slate-500">Search delis, supermarkets, independent stores and restaurants. Save the ones that fit your products.</p><p className="mt-4 text-[11px] leading-5 text-slate-400">Public business numbers come from Google. Decision-makers are recorded by you after a call or visit.</p></div>}</div>{nextPage&&<button className="dd-button w-full" disabled={!!busy} onClick={()=>search(true)}>Load more businesses</button>}</>}
      {tab==="saved"&&<><div className="flex gap-2"><input className="dd-input" aria-label="Search saved prospects" placeholder="Search buyers or notes…" value={savedSearch} onChange={e=>setSavedSearch(e.target.value)}/><select className="dd-input !w-auto" aria-label="Prospect status" value={savedFilter} onChange={e=>setSavedFilter(e.target.value)}><option value="all">All statuses</option>{Object.entries(STATUS_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div><button className="text-left text-xs text-emerald-700 underline" disabled={!!busy} onClick={()=>void run("details",async()=>{const ids=visibleSaved.flatMap(p=>p.placeId?[p.placeId]:[]).slice(0,20),r=await refreshPlacesAction(ids);setPlaceCache(p=>({...p,...Object.fromEntries(r.places.map(p=>[p.id,p]))}));setMessage(r.error||`Refreshed ${r.places.length} Google business records.`);})}>Refresh Google details for up to 20 visible businesses</button><div className="max-h-[640px] space-y-3 overflow-y-auto pr-1">{visibleSaved.map(p=><article key={p.id} className="dd-card !p-4"><div className="flex items-start justify-between gap-2"><button className="text-left" onClick={()=>openProspect(p)}><h3 className="text-sm font-semibold">{name(p)}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{address(p)}</p></button><span className="dd-badge shrink-0">{STATUS_LABELS[p.status]}</span></div>{phone(p)&&<a href={`tel:${phone(p).replace(/[^+\d]/g,"")}`} className="mt-2 block text-xs font-medium text-emerald-700">{phone(p)}</a>}<p className="mt-2 text-xs text-slate-500">Buyer: {p.decisionMaker||"Not identified yet"}{p.role&&` · ${p.role}`}</p>{p.nextVisit&&<p className="mt-1 text-xs text-slate-400">Next visit: {p.nextVisit.replace("T"," ")}</p>}<div className="mt-3 flex gap-2"><button className="dd-button flex-1" onClick={()=>openProspect(p)}>Contact & notes</button><button className="dd-primary flex-1" disabled={routeIds.includes(p.id)||routeIds.length>=20} onClick={()=>addStop(p.id)}>{routeIds.includes(p.id)?"In visit list":"+ Add to visits"}</button></div></article>)}</div>{!visibleSaved.length&&<div className="dd-card py-10 text-center"><p className="text-sm font-semibold">Your future buyers will be here.</p><p className="mt-2 text-xs leading-6 text-slate-500">Save businesses from the map, add one manually or send prospects from Zapier.</p></div>}</>}
      {tab==="route"&&<><section className="dd-card !p-4"><div className="flex justify-between"><h2 className="text-sm font-semibold">Plan your day</h2><button className="text-xs text-emerald-700 underline" onClick={()=>{setListId(null);setListName("New visit list");setRouteIds([]);setRoute(null);}}>New list</button></div>{state.lists.length>0&&<label className="mt-3 block text-xs">Open a saved list<select className="dd-input mt-1" value={listId||""} onChange={e=>{const l=state.lists.find(l=>l.id===e.target.value);if(l){setListId(l.id);setListName(l.name);setRouteIds(l.prospectIds);setStart(l.startAddress);setRoundTrip(l.returnToStart);setRoute(null);}}}><option value="">Choose a list…</option>{state.lists.map(l=><option key={l.id} value={l.id}>{l.name} · {l.prospectIds.length} stops</option>)}</select></label>}<label className="mt-3 block text-xs font-medium">List name<input className="dd-input mt-1" value={listName} onChange={e=>setListName(e.target.value)} maxLength={120}/></label><label className="mt-3 block text-xs font-medium">Starting address<input className="dd-input mt-1" value={start} onChange={e=>setStart(e.target.value)} placeholder="Your office, warehouse or home" maxLength={300}/></label><label className="mt-3 flex gap-2 text-xs text-slate-600"><input type="checkbox" checked={roundTrip} onChange={e=>setRoundTrip(e.target.checked)}/>Return to the starting address</label><p className="mt-2 text-[11px] leading-5 text-slate-400">{roundTrip?"Google can rearrange all visits and return you to the start.":"The final stop stays fixed; Google optimizes the visits before it."} Up to 20 visits per driving route.</p><div className="mt-4 flex gap-2"><button className="dd-primary flex-1" disabled={!!busy||!start.trim()||!stops.length} onClick={optimize}>{busy==="route"?"Finding best order…":"Optimize driving order"}</button><button className="dd-button" disabled={!!busy||!listName.trim()} onClick={saveList}>Save list</button></div></section>
      <div className="max-h-[590px] space-y-2 overflow-y-auto pr-1">{stops.map((p,i)=><article key={p.id} className="dd-card !p-3"><div className="flex items-start gap-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[#315744] text-xs font-semibold text-white">{i+1}</span><div className="min-w-0 flex-1"><button className="text-left text-sm font-semibold" onClick={()=>openProspect(p)}>{name(p)}</button><p className="mt-1 text-xs leading-5 text-slate-500">{address(p)}</p>{phone(p)&&<a className="mt-1 block text-xs font-medium text-emerald-700" href={`tel:${phone(p).replace(/[^+\d]/g,"")}`}>{phone(p)}</a>}<p className="mt-1 text-[11px] text-slate-400">{p.decisionMaker?`Ask for ${p.decisionMaker}`:"Ask who handles purchasing"}</p>{validRoute?.legs[i]&&<p className="mt-2 text-[11px] font-medium text-emerald-700">About {Math.ceil(validRoute.legs[i].durationSeconds/60)} min driving from previous stop</p>}</div><div className="flex flex-col"><button className="p-1 text-xs text-slate-500 disabled:opacity-25" aria-label={`Move ${name(p)} earlier`} disabled={i===0} onClick={()=>moveStop(i,-1)}>↑</button><button className="p-1 text-xs text-slate-500 disabled:opacity-25" aria-label={`Move ${name(p)} later`} disabled={i===stops.length-1} onClick={()=>moveStop(i,1)}>↓</button><button className="p-1 text-xs text-slate-400" aria-label={`Remove ${name(p)} from route`} onClick={()=>setRouteIds(ids=>ids.filter(id=>id!==p.id))}>×</button></div></div></article>)}</div>{!stops.length&&<div className="dd-card py-8 text-center"><h3 className="text-sm font-semibold">Where do you want to go?</h3><p className="mt-2 text-xs leading-6 text-slate-500">Add businesses from search results or your saved prospects, then put them in visit order.</p><button className="dd-button mt-4" onClick={()=>setTab(state.prospects.length?"saved":"search")}>Choose businesses</button></div>}</>}
    </section><section className="space-y-4 xl:sticky xl:top-20"><StoreMap apiKey={browserKey} places={mapPlaces} selectedId={selectedPlace} onSelect={id=>{setSelectedPlace(id);const p=state.prospects.find(p=>p.placeId===id);if(p&&tab!=="search")openProspect(p);}} routeOrder={routePlaceIds} polyline={validRoute?.polyline}/>
      {tab==="route"&&stops.length>0&&<section className="dd-card"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-sm font-semibold">{validRoute?"Your route is ready":"Your visit order"}</h2><p className="mt-1 text-xs text-slate-500">{validRoute?`${(validRoute.distanceMeters/1609.344).toFixed(1)} miles · about ${Math.ceil(validRoute.durationSeconds/60)} minutes driving · Google Routes`:"Manually ordered. Optimize to calculate driving time and distance."}</p></div><button className="dd-button" onClick={exportNotes}>Export contact notes</button></div><p className="mt-3 text-[11px] leading-5 text-slate-400">Driving time excludes meetings, parking and breaks. Check opening hours before leaving. Navigation opens in batches of four visits for mobile compatibility.</p>{start.trim()&&<div className="mt-4 flex flex-wrap gap-2">{links.map(l=><a className="dd-primary" key={l.label} href={l.url} target="_blank" rel="noreferrer">Navigate {l.label.toLowerCase()} ↗</a>)}</div>}</section>}
      <p className="text-[11px] leading-5 text-slate-400">Business search and map data: Google Maps. Availability and contact information can change. Your prospect notes and named lists are saved on this server.</p>
    </section></div>
    {selectedProspect&&<section className="dd-card" id="buyer-notes"><div className="flex items-center justify-between gap-3"><div><p className="dd-eyebrow">Buyer relationship</p><h2 className="mt-1 font-semibold">{name(selectedProspect)}</h2></div><button aria-label="Close buyer notes" className="p-2 text-lg text-slate-400" onClick={()=>setEditId(null)}>×</button></div><p className="mt-2 text-xs leading-6 text-slate-500">Record the details you verify. Google provides business listings; a buyer’s name and direct contact come from your conversations.</p><form className="mt-4" onSubmit={e=>{e.preventDefault();void run("notes",async()=>{const r=await updateProspectAction(selectedProspect.id,edit,state.revision);if(r.ok&&r.state){setState(r.state);setMessage("Buyer notes saved.");}else setMessage(r.error||"Could not save notes.");});}}><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[{key:"name",label:"Business name · your record"},{key:"address",label:"Verified street address"},{key:"phone",label:"Verified business phone"},{key:"decisionMaker",label:"Decision-maker’s name"},{key:"role",label:"Role / title"},{key:"email",label:"Buyer email"}].map(f=><label key={f.key} className="text-xs font-medium">{f.label}<input className="dd-input mt-1" value={String(edit[f.key as keyof Prospect]||"")} onChange={e=>setEdit(p=>({...p,[f.key]:e.target.value}))}/></label>)}<label className="text-xs font-medium">Relationship status<select className="dd-input mt-1" value={edit.status||"new"} onChange={e=>setEdit(p=>({...p,status:e.target.value as Prospect["status"]}))}>{Object.entries(STATUS_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="text-xs font-medium">Next visit or follow-up<input className="dd-input mt-1" type="datetime-local" value={edit.nextVisit||""} onChange={e=>setEdit(p=>({...p,nextVisit:e.target.value}))}/></label></div><label className="mt-4 block text-xs font-medium">Visit notes<textarea className="dd-input mt-1 min-h-24" placeholder="Who places orders? Best time to visit? Samples requested? Next step?" maxLength={3000} value={edit.notes||""} onChange={e=>setEdit(p=>({...p,notes:e.target.value}))}/></label><div className="mt-4 flex flex-wrap gap-3"><button className="dd-primary" disabled={!!busy}>Save buyer notes</button>{selectedProspect.customerId?<Link className="dd-button" href={`/customers/${selectedProspect.customerId}`}>Open customer account →</Link>:<button className="dd-button" type="button" disabled={!!busy} onClick={()=>void run("customer",async()=>{const r=await convertProspectAction(selectedProspect.id);if(r.ok&&r.state){setState(r.state);setMessage("Customer account created. You can now set pricing and take an order.");}else setMessage(r.error||"Save verified contact details first.");})}>Create customer from saved details</button>}</div></form></section>}
  </div>;
}
