// @vitest-environment node
import { afterEach,beforeEach,describe,it,expect,vi } from "vitest";
import { mkdtemp,rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { randomUUID } from "node:crypto";
import path from "node:path";
import { GoogleAdsClient,validateCampaign,pushCampaignToGoogleAds,pullKeywordIdeas,type GoogleAdsConfig } from "./google-ads";
import { campaignOperations,validatedDraft } from "./campaign";
import type { CampaignPlan,GeneratedAds } from "./plan";
const config=():GoogleAdsConfig=>({developerToken:"private-developer",clientId:randomUUID(),clientSecret:"private-client",refreshToken:"private-refresh",customerId:"1234567890",loginCustomerId:"9876543210",apiVersion:"v25"});
const response=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status});
const plan:CampaignPlan={campaignName:"Shuug test",dailyBudgetCents:1000,maxCpcCents:72,finalUrl:"https://shuug.co/collections/wholesale",market:"US",keywords:["wholesale hot sauce"],skipKeywords:[],negativeKeywords:["recipes"]};
const asset=(text:string)=>({text,chars:1,withinLimit:true});
const ads:GeneratedAds={ok:true,headlines:["Shuug Wholesale","Sauces For Your Store","Explore Our Sauces"].map(asset),descriptions:["Discover Shuug sauces for your store.","Explore our wholesale range and request details."].map(asset)};
let folder="";
beforeEach(async()=>{folder=await mkdtemp(path.join(tmpdir(),"dealdesk-api-test-"));vi.stubEnv("DEALDESK_DATA_DIR",folder);vi.stubEnv("GOOGLE_ADS_LEDGER_DIR",path.join(folder,"reviews"));const c=config();for(const [key,value] of Object.entries({DEVELOPER_TOKEN:c.developerToken,CLIENT_ID:c.clientId,CLIENT_SECRET:c.clientSecret,REFRESH_TOKEN:c.refreshToken,CUSTOMER_ID:c.customerId,LOGIN_CUSTOMER_ID:c.loginCustomerId!,API_VERSION:c.apiVersion,ENABLE_CAMPAIGN_PUSH:"true"}))vi.stubEnv(`GOOGLE_ADS_${key}`,value);});
afterEach(async()=>{vi.unstubAllGlobals();vi.unstubAllEnvs();await rm(folder,{recursive:true,force:true});});
describe("Google Ads REST contract",()=>{
  it("shares OAuth refresh and sends the account and manager headers",async()=>{const calls:{url:string;init?:RequestInit}[]=[];const transport=vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{calls.push({url:String(input),init});return String(input).includes("oauth2")?response({access_token:"access",expires_in:3600}):response({ok:true});});const client=new GoogleAdsClient(config(),transport);await Promise.all([client.request("/googleAds:search",{}),client.request("/googleAds:search",{})]);expect(calls.filter(c=>c.url.includes("oauth2"))).toHaveLength(1);const api=calls.find(c=>c.url.includes("googleads.googleapis"))!;expect(api.url).toContain("/v25/customers/1234567890/");expect(api.init?.headers).toMatchObject({"login-customer-id":"9876543210",Authorization:"Bearer access"});});
  it("refreshes once on 401 and never loops",async()=>{const transport=vi.fn(async(input:RequestInfo|URL)=>String(input).includes("oauth2")?response({access_token:randomUUID()}):response({},401));await expect(new GoogleAdsClient(config(),transport).request("/googleAds:search",{})).rejects.toThrow("401");expect(transport).toHaveBeenCalledTimes(4);});
  it("does not retry an uncertain mutation or expose raw provider errors",async()=>{const transport=vi.fn(async(input:RequestInfo|URL)=>String(input).includes("oauth2")?response({access_token:"token"}):response({error:{message:"private-refresh private-developer"}},503));await expect(new GoogleAdsClient(config(),transport).request("/googleAds:mutate",{},true)).rejects.toThrow("Google Ads 503");expect(transport).toHaveBeenCalledTimes(2);});
  it("uses historical metrics with country, language and requested average CPC",async()=>{let body:Record<string,unknown>={};vi.stubGlobal("fetch",vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{const url=String(input);if(url.includes("oauth2"))return response({access_token:"token"});if(url.endsWith("/googleAds:search"))return response({results:[{customer:{id:"1234567890",currencyCode:"USD"}}]});body=JSON.parse(String(init?.body));expect(url).toContain(":generateKeywordHistoricalMetrics");return response({results:[{text:"hot sauce",keywordMetrics:{averageCpcMicros:"2400000",avgMonthlySearches:"1000"}}]});}));const r=await pullKeywordIdeas(["hot sauce"],"CA",undefined,true);expect(r.ok).toBe(true);expect(body).toMatchObject({geoTargetConstants:["geoTargetConstants/2124"],language:"languageConstants/1000",historicalMetricsOptions:{includeAverageCpc:true},keywordPlanNetwork:"GOOGLE_SEARCH"});expect(r.keywords[0]).toMatchObject({cpcCents:240,cpcBasis:"historical_average"});});
  it("refuses to mix a non-USD account with USD product margins",async()=>{vi.stubGlobal("fetch",vi.fn(async(input:RequestInfo|URL)=>String(input).includes("oauth2")?response({access_token:"x"}):response({results:[{customer:{id:"1234567890",currencyCode:"CAD"}}]})));const r=await pullKeywordIdeas(["sauce"]);expect(r.ok).toBe(false);expect(r.error).toContain("CAD");});
});
describe("reviewed campaign creation",()=>{
  it("builds an atomic paused campaign with bids, landing URL and targeting",()=>{const operations=campaignOperations("1234567890",validatedDraft(plan,ads),"abcdef00-0000-4000-8000-000000000000");const json=JSON.stringify(operations);expect(json).toContain('"amountMicros":"10000000"');expect(json).toContain('"cpcBidMicros":"720000"');expect(json).toContain('"finalUrls":["https://shuug.co/collections/wholesale"]');expect(json).toContain('"geoTargetConstant":"geoTargetConstants/2840"');expect(json).toContain('"targetSearchNetwork":false');const campaign=operations.find(o=>"campaignOperation" in o),group=operations.find(o=>"adGroupOperation" in o);expect(campaign && "campaignOperation" in campaign && campaign.campaignOperation?.create.status).toBe("PAUSED");expect(group && "adGroupOperation" in group && group.adGroupOperation?.create.status).toBe("PAUSED");});
  it("checks actual copy and blocks invalid URLs and conflicting negatives",()=>{expect(()=>validatedDraft(plan,{...ads,headlines:[asset("x".repeat(31)),...ads.headlines]})).toThrow();expect(()=>validatedDraft({...plan,finalUrl:"https://127.0.0.1/"},ads)).toThrow();expect(()=>validatedDraft({...plan,negativeKeywords:["hot sauce"]},ads)).toThrow("conflicts");});
  it("validates without creating and consumes the exact saved snapshot once",async()=>{const mutations:Record<string,unknown>[]=[];vi.stubGlobal("fetch",vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{const url=String(input);if(url.includes("oauth2"))return response({access_token:"x"});if(url.endsWith(":search"))return response({results:[{customer:{id:"1234567890",currencyCode:"USD"}}]});const body=JSON.parse(String(init?.body));mutations.push(body);return body.validateOnly?response({}):response({mutateOperationResponses:[{campaignResult:{resourceName:"customers/1234567890/campaigns/777"}}]});}));const review=await validateCampaign(plan,ads);expect(review.ok).toBe(true);expect(mutations).toHaveLength(1);expect(mutations[0]).toMatchObject({validateOnly:true,partialFailure:false});const first=await pushCampaignToGoogleAds(review.reviewId!);const retry=await pushCampaignToGoogleAds(review.reviewId!);expect(first.ok).toBe(true);expect(retry).toEqual(first);expect(mutations).toHaveLength(2);expect(mutations[1].mutateOperations).toEqual(mutations[0].mutateOperations);});
  it("keeps a persistent no-replay receipt when a mutation times out",async()=>{let mutations=0;vi.stubGlobal("fetch",vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{if(String(input).includes("oauth2"))return response({access_token:"x"});if(String(input).endsWith(":search"))return response({results:[{customer:{id:"1234567890",currencyCode:"USD"}}]});if(JSON.parse(String(init?.body)).validateOnly)return response({});mutations++;throw new Error("timeout");}));const review=await validateCampaign(plan,ads);const first=await pushCampaignToGoogleAds(review.reviewId!);expect(first.ok).toBe(false);await pushCampaignToGoogleAds(review.reviewId!);expect(mutations).toBe(1);});
});
