import { randomUUID } from "node:crypto";
import { addRecord } from "../src/lib/sdk/records";
import { moduleById } from "../src/lib/sdk/registry";
import { listBusinessRecords } from "../src/lib/workspace/store";
import type { BusinessRecord, FieldValue } from "../src/lib/workspace/model";
import { createPortalGrant } from "../src/lib/workspace/portal";
import { inspectionFixtureDefinition, tinyInspectionPhoto } from "../src/lib/auto-repair/inspection-fixture";
import { inspectionRows } from "../src/lib/auto-repair/inspection-state";
import { workspaceDatabase } from "../src/lib/workspace/database";
function assert(v: unknown, message: string): asserts v { if (!v) throw new Error(message); }
export async function inspectionHttpCheck(base: string, ownerCookie: string) {
  assert(process.env.DEALDESK_DATA_DIR?.includes("shuug-http-check-"), "Inspection HTTP acceptance requires the disposable workspace.");
  const request = (route: string, body?: unknown, cookie = ownerCookie, origin = base) => fetch(base + route, { method: body === undefined ? "GET" : "POST", headers: { Cookie: cookie, Origin: origin, "Content-Type": "application/json" }, ...(body === undefined ? {} : { body: JSON.stringify(body) }), redirect: "manual", signal: AbortSignal.timeout(20000) });
  const json = async (route: string, body?: unknown, cookie = ownerCookie) => { const response = await request(route, body, cookie), result = await response.json(); assert(response.ok, result.error ?? `Inspection HTTP failed: ${route}`); return result; };
  const postForm = (route: string, form: Record<string, string>, cookie = "") => fetch(base + route, { method: "POST", headers: { Cookie: cookie, Origin: base, "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams(form), redirect: "manual" });
  const password = `Synthetic-inspection-${randomUUID()}`;
  async function employee(name: string, email: string) {
    const created = await json("/api/workspace/employees", { action: "create", name, email, role: "Employee" }), account = created.accounts.find((a: { email: string }) => a.email === email); assert(account, "Inspection employee creation failed.");
    const page = await fetch(created.inviteUrl), html = await page.text(), csrf = html.match(/name="csrf" value="([a-f0-9]+)"/)?.[1]; assert(csrf, "Employee activation CSRF missing.");
    const activated = await postForm("/api/auth/activate", { token: new URL(created.inviteUrl).searchParams.get("token")!, csrf, password, confirm: password }, page.headers.getSetCookie().map(c => c.split(";")[0]).join("; ")); assert(activated.ok, "Could not activate inspection employee.");
    const login = await fetch(base + "/api/auth/login"), loginHtml = await login.text(), nonce = loginHtml.match(/name="csrf" value="([a-f0-9]+)"/)?.[1]; assert(nonce, "Employee login CSRF missing."); const signed = await postForm("/api/auth/login", { csrf: nonce, email, password }, login.headers.getSetCookie().map(c => c.split(";")[0]).join("; ")), cookie = signed.headers.getSetCookie().find(c => c.startsWith("dd_session="))?.split(";")[0]; assert(signed.status === 303 && cookie, "Inspection employee login failed."); return { ...account, cookie };
  }
  const alpha = await employee("Inspection technician Alpha", "inspection-alpha@example.test"), beta = await employee("Inspection technician Beta", "inspection-beta@example.test");
  const industry = { industryId: "auto-repair", answers: {}, addedPacks: [], templateName: "HTTP inspection workshop", revision: 1 }, preview = await json("/api/setup/industry", { apply: false, input: industry }); await json("/api/setup/industry", { apply: true, input: industry, currentDigest: preview.currentDigest, proposedDigest: preview.proposedDigest });
  const recordCommand = async (command: string, input: unknown): Promise<BusinessRecord> => (await json("/api/workspace/records", { command, input })).record;
  const create = (kind: string, fields: Record<string, FieldValue>) => recordCommand("save", { kind, title: `HTTP inspection ${kind}`, currency: "USD", fields, requestId: randomUUID() });
  const go = (r: BusinessRecord, target: string) => recordCommand("transition", { id: r.id, revision: r.revision, target, commandId: randomUUID() });
  const client = await create("client", { email: "inspection-customer@example.test", notes: "PRIVATE-INSPECTION-CLIENT" }), vehicle = addRecord("vehicles", moduleById("vehicles")!.fields, { customer_id: client.id, vin: "1HGCM82633A004352", make: "Honda", model: "Accord", year: 2003 });
  const proposal = await go(await go(await create("proposal", { client: client.id, scope: "Inspect vehicle", exclusions: "Repairs require a separate agreed scope", amount: 10000, expires: "2099-01-01", acceptedBy: "Synthetic customer", evidence: "Synthetic diagnostic approval" }), "sent"), "accepted"), agreement = await go(await create("agreement", { client: client.id, proposal: proposal.id, terms: "Diagnostic visit only", deposit: 0, signedBy: "Synthetic customer", evidence: "Synthetic agreement" }), "signed");
  let job = await create("job", { client: client.id, agreement: agreement.id, instructions: "Inspect vehicle and report findings", requiredChecks: "Workshop check", completedChecks: "Workshop check", acceptedBy: "Synthetic customer", evidence: "Synthetic completion evidence", budget: 5000 }); const resource = await go(await create("resource", { category: "staff", weeklyHours: 40 }), "active"); await go(await create("booking", { job: job.id, resource: resource.id, start: "2026-09-21T10:00:00Z", end: "2026-09-21T12:00:00Z" }), "scheduled"); job = await go(job, "scheduled");
  const manage = "/api/auto-repair/inspections", personal = "/api/workspace/me/inspections";
  const cmd = async (action: string, input: unknown, cookie = ownerCookie, self = false, requestId = randomUUID()) => json(self ? personal : manage, { requestId, action, input }, cookie);
  const tpl = await cmd("template.save", { definition: inspectionFixtureDefinition(), shareInTemplates: true }); await cmd("template.publish", { id: tpl.result.id, revision: 1, reviewed: true, review: "Synthetic reviewed checklist" });
  const assigned = await cmd("inspection.assign", { title: "HTTP private vehicle inspection", vehicleId: vehicle.id, jobId: job.id, templateId: tpl.result.id, technicianId: alpha.memberId, instructions: "Inspect the pads and lights" }); const id = assigned.result.id;
  const read = async () => (await json(personal, undefined, alpha.cookie)).inspections.find((i: { id: string }) => i.id === id);
  assert((await request(manage, undefined, alpha.cookie)).status === 403, "Employee read the manager inspection workspace."); assert((await json(personal, undefined, beta.cookie)).inspections.length === 0, "Another employee saw private inspections.");
  assert((await request(personal, { requestId: randomUUID(), action: "inspection.start", input: { id, revision: 1 } }, beta.cookie)).status === 400, "Another technician started this inspection."); assert((await request(personal, { requestId: randomUUID(), action: "inspection.start", input: { id, revision: 1 } }, alpha.cookie, "https://foreign.test")).status === 403, "Foreign origin started work.");
  const starts = await Promise.all([0, 1].map(() => request(personal, { requestId: randomUUID(), action: "inspection.start", input: { id, revision: 1 } }, alpha.cookie))); assert(starts.filter(r => r.ok).length === 1 && starts.filter(r => r.status === 400).length === 1, "Concurrent starts duplicated work timers.");
  const view = await fetch(base + "/me", { headers: { Cookie: alpha.cookie } }), html = await view.text(); assert(view.ok && html.includes("My vehicle inspections") && html.includes("HTTP private vehicle inspection") && html.includes("Pause inspection timer") && !html.includes("PRIVATE-INSPECTION-CLIENT"), "Employee page did not render the assigned inspection safely.");
  const upload = await cmd("inspection.photo", { id, revision: (await read()).revision, key: "brakes", name: "Synthetic pad.png", mime: "image/png", data: tinyInspectionPhoto }, alpha.cookie, true); const photoId = upload.data.inspections.find((i: { id: string }) => i.id === id).photos[0].id;
  const photoRoute = `/api/auto-repair/inspections/photo/${photoId}`; assert((await request(photoRoute, undefined, alpha.cookie)).ok && (await request(photoRoute, undefined, beta.cookie)).status === 404 && (await request(photoRoute, undefined, "")).status === 404, "Inspection photo ownership failed.");
  await cmd("inspection.save", { id, revision: (await read()).revision, odometer: 50000, odometerUnit: "miles", staffNotes: "PRIVATE-TECHNICIAN-NOTES", customerSummary: "Public vehicle findings", findings: [{ key: "brakes", outcome: "attention", measurement: "3", observation: "Uneven wear observed", recommendation: "Discuss replacement with customer" }, { key: "lights", outcome: "pass", measurement: "", observation: "Functional check", recommendation: "" }] }, alpha.cookie, true); await cmd("inspection.pause", { id, revision: (await read()).revision }, alpha.cookie, true);
  await cmd("inspection.time.correct", { id, revision: (await read()).revision, minutes: 15, reason: "Synthetic reviewed time correction for deterministic cost acceptance" }); await cmd("inspection.submit", { id, revision: (await read()).revision, confirmed: true }, alpha.cookie, true);
  job = listBusinessRecords(["job"]).find(j => j.id === job.id)!; assert((await request("/api/workspace/records", { command: "transition", input: { id: job.id, revision: job.revision, target: "completed", commandId: randomUUID() } })).status === 400, "A pending inspection did not block job completion.");
  const grant = createPortalGrant(client.id); assert(!(await (await fetch(`${base}/api/portal/${grant.token}`)).text()).includes("Public vehicle findings"), "Unreviewed inspection reached the customer.");
  const reviewInput = { id, revision: (await read()).revision, reviewed: true, review: "PRIVATE-MANAGER-REVIEW", hourlyCost: 3000, shareWithCustomer: true, dispositions: [{ key: "brakes", disposition: "deferred", evidence: "PRIVATE documented follow-up agreement" }] };
  const reviews = await Promise.all([0, 1].map(() => request(manage, { requestId: randomUUID(), action: "inspection.review", input: reviewInput }))); assert(reviews.filter(r => r.ok).length === 1 && reviews.filter(r => r.status === 400).length === 1, "Concurrent reviewers duplicated the inspection cost.");
  const entries = listBusinessRecords(["time_entry"]).filter(r => r.computed?.inspectionId === id); assert(entries.length === 1 && entries[0].status === "approved" && entries[0].fields.minutes === 15 && entries[0].fields.cost === 750, "Reviewed inspection did not create one costed time entry.");
  const report = await fetch(`${base}/api/portal/${grant.token}`), reportHtml = await report.text(); assert(report.ok && reportHtml.includes("Vehicle inspection reports") && reportHtml.includes("Uneven wear observed") && reportHtml.includes(photoId) && !reportHtml.includes("PRIVATE"), "Private customer report leaked staff data or omitted findings/photos."); assert((await fetch(`${base}/api/portal/${grant.token}/inspection-photo/${photoId}`)).ok, "Authorized portal photo failed.");
  const customer = (await json("/api/setup/customers", { action: "create", input: { name: "Inspection customer", email: "inspection-customer-login@example.test", customerId: null, clientId: client.id } })).account, invite = await json("/api/setup/customers", { action: "invite", input: { id: customer.id } }); assert((await postForm("/api/website/customer", { action: "activate", invite: new URL(invite.url).searchParams.get("invite")!, password, confirmation: password })).ok, "Inspection customer activation failed.");
  const login = await postForm("/api/website/customer", { action: "login", email: customer.email, password }), customerCookie = login.headers.getSetCookie().find(c => c.startsWith("shuug_customer="))?.split(";")[0]; assert(customerCookie, "Inspection customer login failed."); const dashboard = await request("/api/website/customer", undefined, customerCookie), dashboardHtml = await dashboard.text(); assert(dashboard.ok && dashboardHtml.includes("Vehicle inspection reports") && !dashboardHtml.includes("PRIVATE") && dashboard.headers.get("content-security-policy")?.includes("img-src 'self'"), "Customer login did not show a private photo-enabled report."); assert((await request(`/api/website/customer/inspection-photo/${photoId}`, undefined, customerCookie)).ok, "Customer account photo failed.");
  job = await go(job, "completed"); job = await go(job, "accepted"); const invoice = await go(await create("invoice", { job: job.id, method: "fixed", amount: 10000, description: "Agreed diagnostic service" }), "issued"); assert(invoice.fields.amount === 10000, "Inspection labor cost changed the customer's agreed bill.");
  await cmd("inspection.share", { id, revision: (await read()).revision, shareWithCustomer: false }); assert((await request(`/api/website/customer/inspection-photo/${photoId}`, undefined, customerCookie)).status === 404, "Withdrawing report sharing did not revoke photo access.");
  const template = await json("/api/workspace/template"); assert(template.version === 4 && template.autoRepairInspections.length === 1 && template.autoRepairPricing.length === 1 && !JSON.stringify(template).includes("PRIVATE") && !JSON.stringify(template).includes(vehicle.id), "Combined checklist/pricing template export failed privacy or format checks.");
  const managerPage = await request("/m/vehicle-inspections"), managerHtml = await managerPage.text(); assert(managerPage.ok && managerHtml.includes('aria-label="Vehicle inspection management"'), `Installed manager inspection controls did not render (HTTP ${managerPage.status}; headings: ${managerHtml.match(/<h[12][^>]*>[^<]*/g)?.slice(0, 8).join(" | ") ?? "none"}).`);
  await json("/api/workspace/employees", { action: "disable", id: alpha.id }); assert((await request(personal, undefined, alpha.cookie)).status === 403, "Disabled technician retained inspection access.");
  const restaurant = { industryId: "restaurant", answers: {}, addedPacks: [], templateName: "HTTP restaurant", revision: 1 }, next = await json("/api/setup/industry", { apply: false, input: restaurant }); await json("/api/setup/industry", { apply: true, input: restaurant, currentDigest: next.currentDigest, proposedDigest: next.proposedDigest }); const hidden = await request("/m/vehicle-inspections"); assert(!(await hidden.text()).includes('aria-label="Vehicle inspection management"'), "Restaurant profile exposed mechanic management controls."); assert(workspaceDatabase(db => inspectionRows(db).some(i => i.id === id)), "Profile change discarded inspection history.");
  console.log(JSON.stringify({ ok: true, inspections: ["active employee assignment and isolated My work", "concurrent timer start", "measurements and protected photo evidence", "reviewed time correction", "pending inspection blocks job completion", "competing reviews → one costed time entry", "private grant and customer-login reports/photos", "sharing withdrawal and employee revocation", "original-price invoice", "format-4 pricing/checklist template and profile isolation"], laborCostCents: 750, externalActions: "None; synthetic evidence only" }));
}
