import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { listManualEntries, chartOfAccounts } from "../src/lib/accounting/journal-store";
import { trialBalance } from "../src/lib/accounting/ledger";
/** Called only by workspace-smoke in its disposable, credential-free workspace. */
export async function journalHttpCheck(base: string, ownerCookie: string, staffCookie: string) {
  const req = (route: string, init: RequestInit = {}, cookie = ownerCookie) => fetch(base + route, { ...init, redirect: "manual", signal: AbortSignal.timeout(20000), headers: { cookie, ...init.headers } });
  const post = (payload: unknown, cookie = ownerCookie, origin = base) => req("/api/accounting/journal", { method: "POST", headers: { Origin: origin, "Content-Type": "application/json" }, body: JSON.stringify(payload) }, cookie);
  const account = { requestId: randomUUID(), action: "account.save", input: { number: 7100, revision: 0, name: "Synthetic installed expense", classification: "expense", parentNumber: 6000, active: true, reviewed: true } };
  const accountPost = (payload: unknown, cookie = ownerCookie) => req("/api/accounting/accounts", { method: "POST", headers: { Origin: base, "Content-Type": "application/json" }, body: JSON.stringify(payload) }, cookie);
  assert.equal((await accountPost(account, staffCookie)).status, 403);
  assert.equal((await req("/api/accounting/accounts", {}, staffCookie)).status, 403);
  const accountSaves = await Promise.all([accountPost(account), accountPost(account)]); for (const r of accountSaves) assert.equal(r.status, 200);
  assert.deepEqual(await accountSaves[0].json(), await accountSaves[1].json());
  assert.equal(chartOfAccounts().accounts.filter(a => a.number === 7100).length, 1);
  assert.equal((await accountPost({ ...account, requestId: randomUUID(), input: { ...account.input, name: "Stale create" } })).status, 400);
  const command = { requestId: randomUUID(), action: "journal.post", input: { date: "2026-09-10", memo: "Synthetic installed journal", reviewed: true, lines: [{ accountNumber: 1000, debitCents: 4567, creditCents: 0 }, { accountNumber: 7100, debitCents: 0, creditCents: 4567 }] } };
  assert.equal((await post(command, ownerCookie, "https://foreign.invalid")).status, 403);
  assert.equal((await post(command, staffCookie)).status, 403);
  assert.equal((await req("/api/accounting/journal", {}, staffCookie)).status, 403);
  assert.equal((await req("/api/v1/accounting-journal", {}, staffCookie)).status, 403);
  const attempts = await Promise.all([post(command), post(command), post(command)]);
  for (const response of attempts) assert.equal(response.status, 200);
  const outcomes = await Promise.all(attempts.map(r => r.json())); assert.deepEqual(outcomes[0], outcomes[1]); assert.deepEqual(outcomes[0], outcomes[2]);
  const id = outcomes[0].result.id;
  assert.equal(listManualEntries().filter(e => e.id === id).length, 1, "Installed server and separate CLI process must read the same durable journal.");
  assert.equal((await post({ ...command, input: { ...command.input, date: "2026-02-30" } })).status, 400);
  const reverse = { requestId: randomUUID(), action: "journal.reverse", input: { id, revision: 1, date: "2026-09-11", reason: "Synthetic installed correction", reviewed: true } };
  const competing = await Promise.all([post(reverse), post({ ...reverse, requestId: randomUUID() })]);
  assert.deepEqual(competing.map(r => r.status).sort(), [200, 400], "Competing reversals must not both post.");
  const get = await req("/api/accounting/journal"); assert.equal(get.headers.get("cache-control"), "private, no-store");
  const history = await get.json(); const original = history.entries.find((e: { id: string }) => e.id === id);
  const reversal = history.entries.find((e: { manual: { reversesId: string } }) => e.manual.reversesId === id);
  assert.ok(reversal); assert.equal(original.manual.reversedById, reversal.id); assert.match(original.manual.actor, /owner/i);
  assert.deepEqual(original.lines, command.input.lines); assert.equal(trialBalance([original, reversal], chartOfAccounts().accounts).totalDebitCents, 0);
  const page = await req("/ledger"), html = await page.text(); assert.equal(page.status, 200);
  assert.ok(html.includes("Recorded reversal") && html.includes("Synthetic installed correction") && html.includes("Original entry"));
  const chart = await req("/ledger/accounts"), chartHtml = await chart.text(); assert.equal(chart.status, 200);
  assert.ok(chartHtml.includes("Synthetic installed expense") && chartHtml.includes("Other current asset") && chartHtml.includes("New account"));
  assert.equal((await accountPost({ ...account, requestId: randomUUID(), input: { ...account.input, revision: 1, classification: "income", parentNumber: null } })).status, 400);
  const inactive = { ...account, requestId: randomUUID(), input: { ...account.input, revision: 1, active: false } };
  assert.equal((await accountPost(inactive)).status, 200);
  assert.equal((await post({ ...command, requestId: randomUUID() })).status, 400);
  const books = await req("/books"), bookHtml = await books.text(); assert.equal(books.status, 200);
  assert.ok(bookHtml.includes("QuickBooks manual coverage") && bookHtml.includes("Document fields and layout") && bookHtml.includes("Payroll processing"));
  assert.ok(!bookHtml.includes("% ready"));
  const catalog = await (await req("/api/v1/accounting-manual")).json();
  assert.equal(new Set(catalog.data.requirements.map((r: { chapter: number }) => r.chapter)).size, 20);
  console.log("Installed journal: authenticated posting, concurrent retries, one reviewed reversal, durable cross-process history, classified custom accounts, inactive posting restrictions, role/origin checks and all 20 manual chapters passed.");
}
