import { randomUUID } from "node:crypto";
import type { specialManagementData } from "../src/lib/restaurant/special-management";
import type { restaurantManagementData } from "../src/lib/restaurant/management";
function assert(value: unknown, message: string): asserts value { if (!value) throw new Error(message); }
export async function restaurantSpecialHttpCheck(base: string, cookie: string, employeeCookie: string, fixture: { menu: string; ingredient: string; supplier: string; today: string; pickup: string }) {
  assert(process.env.DEALDESK_DATA_DIR?.includes("shuug-http-check-"), "Specials acceptance requires disposable fixture data.");
  const request = (path: string, body?: unknown, token = cookie) => fetch(base + path, { method: body === undefined ? "GET" : "POST", headers: { Cookie: token, Origin: base, "Content-Type": "application/json" }, ...(body === undefined ? {} : { body: JSON.stringify(body) }), signal: AbortSignal.timeout(20000) });
  const command = async (action: string, input: unknown, requestId = randomUUID()) => { const response = await request("/api/restaurant/business", { action, input, requestId }), result = await response.json(); assert(response.ok, result.error ?? `Special ${action} failed`); return result.result as { id: string }; };
  const read = async (): Promise<ReturnType<typeof restaurantManagementData>> => (await request("/api/restaurant/business")).json();
  await command("receive", { supplierId: fixture.supplier, invoiceReference: "HTTP-SPECIAL-STOCK", date: fixture.today, purchaseId: null, lines: [{ ingredientId: fixture.ingredient, quantity: 200, cost: 200, expires: null }] });
  const special = await command("special.save", { name: "HTTP limited bowl offer", code: "HTTP10", description: "Synthetic ten percent rice bowl offer.", startDate: fixture.today, endDate: fixture.today, weekdays: [0, 1, 2, 3, 4, 5, 6], startTime: "00:00", endTime: "00:00", overnight: true, channels: ["online"], menuIds: [fixture.menu], discountBasisPoints: 1000, minimumFoodContribution: 500, maxOrders: 1, maxOrdersPerDate: 1, discountBudget: 100, advertisingBudget: 100 });
  const blocked = await request("/api/restaurant/business", { requestId: randomUUID(), action: "special.publish", input: { id: special.id, revision: 1, reviewed: true } }, employeeCookie); assert(blocked.status === 403, "Restricted employee published a discount.");
  await command("special.publish", { id: special.id, revision: 1, reviewed: true });
  const pickupSlot = (await read()).website.slots.find(s => s.id === fixture.pickup); assert(pickupSlot, "Special pickup slot missing");
  await command("pickup.save", { id: pickupSlot.id, revision: pickupSlot.revision, at: pickupSlot.at, capacity: 20, enabled: true });
  const publicPath = "/api/website/restaurant", field = (html: string, name: string) => { const value = html.match(new RegExp(`name="${name}" value="([^"]+)"`))?.[1]; assert(value, `Special ${name} field missing`); return value; };
  const post = (body: Record<string, string>) => fetch(base + publicPath, { method: "POST", headers: { Origin: base, "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams(body), signal: AbortSignal.timeout(20000) });
  const review = async () => { const page = await fetch(base + publicPath + "?special=HTTP10"), html = await page.text(); assert(page.ok && html.includes('value="HTTP10"'), "Public offer path did not prefill the code."); const result = await post({ action: "review", proof: field(html, "proof"), specialCode: "HTTP10", slotId: fixture.pickup, name: "HTTP special guest", phone: "555-0100", consent: "yes", "menu.0": fixture.menu, "qty.0": "1" }), reviewed = await result.text(); assert(result.ok && reviewed.includes("Discount USD 1.00") && reviewed.includes("Total due at pickup USD 9.90"), "Special review lost its discount or net tax."); return field(reviewed, "quote"); };
  const a = await review(), b = await review(), race = await Promise.all([a, b].map(quote => post({ action: "submit", quote, confirmed: "yes" })));
  assert(race.filter(r => r.ok).length === 1 && race.filter(r => r.status === 400).length === 1, "Competing requests exceeded the special order/budget limit.");
  assert((await race.find(r => r.status === 400)!.text()).includes("special has reached"), "The competition failed for a reason other than the offer limits.");
  const accepted = (await read()).orders.find(o => o.special?.id === special.id); assert(accepted && accepted.total === 990, "Accepted special order missing");
  await command("special.pause", { id: special.id, revision: 2 });
  const current = async () => { const order = (await read()).orders.find(o => o.id === accepted.id); assert(order, "Special check missing"); return order; };
  await command("order.allergens", { id: accepted.id, revision: accepted.revision, reviewed: true });
  for (const status of ["cooking", "ready"]) { const response = await request("/api/restaurant/service", { action: "ticket.status", input: { id: accepted.ticketId, status } }); assert(response.ok, "Special kitchen step failed"); }
  await command("order.serve", { id: accepted.id, revision: (await current()).revision }); await command("tender", { id: accepted.id, revision: (await current()).revision, amount: 990, tip: 0, method: "cash", reference: "HTTP-SPECIAL-CASH", received: true }); await command("order.close", { id: accepted.id, revision: (await current()).revision });
  const spendRequest = randomUUID(), spend = { id: special.id, date: fixture.today, amount: 100, provider: "Synthetic newspaper", reference: "HTTP-SPECIAL-AD", evidence: "Synthetic verified advertising bank payment", paid: true }; await command("special.spend", spend, spendRequest); await command("special.spend", spend, spendRequest);
  const report: ReturnType<typeof specialManagementData> = await (await request("/api/restaurant/specials")).json(); const result = report.specials.find(s => s.id === special.id); assert(result && result.servedOrders === 1 && result.discount === 100 && result.sales === 900 && result.foodCost === 100 && result.advertising === 100 && result.beforeLaborContribution === 700 && result.spend.length === 1, "Campaign results do not match actual sales, food and advertising evidence.");
  const page = await request("/restaurant/specials"), html = await page.text(); assert(page.ok && html.includes("HTTP limited bowl offer") && html.includes("Recorded offer results"), "Installed campaign page did not render saved results."); const ledger = await request("/ledger"); assert(ledger.ok && (await ledger.text()).includes("Special advertising: HTTP10"), "Shared ledger did not include the recorded advertising expense."); assert((await request("/api/restaurant/specials", undefined, employeeCookie)).status === 403, "Restricted employee opened campaign records.");
  console.log(JSON.stringify({ ok: true, specials: ["draft → owner publication → public code/review", "concurrent discount budget and order cap", "accepted price survives pause", "kitchen → discounted tax/payment", "verified advertising journal and retry", "campaign results and installed screen", "employee restrictions"], externalAdvertising: "No advertisement was bought or sent" }));
}
