import { restaurantPrepHttpCheck } from "./restaurant-prep-http-check";
import { restaurantReportHttpCheck } from "./restaurant-report-http-check";
import { restaurantModifierHttpCheck } from "./restaurant-modifier-http-check";
import { restaurantCreditHttpCheck } from "./restaurant-credit-http-check";
import { restaurantStocktakeHttpCheck } from "./restaurant-stocktake-http-check";
import { restaurantSpecialHttpCheck } from "./restaurant-special-http-check";
import { restaurantDiningHttpCheck } from "./restaurant-dining-http-check";
import { randomUUID } from "node:crypto";
import { restaurantBusinessSnapshot } from "../src/lib/restaurant/business";
import type { restaurantManagementData } from "../src/lib/restaurant/management";
function assert(value: unknown, message: string): asserts value { if (!value) throw new Error(message); }
export async function restaurantBusinessHttpCheck(base: string, ownerCookie: string, employeeCookie: string, backendToken: string) {
  assert(process.env.DEALDESK_DATA_DIR?.includes("shuug-http-check-"), "Restaurant acceptance requires the disposable fixture workspace.");
  const request = (route: string, body?: unknown, cookie = ownerCookie) => fetch(base + route, { method: body === undefined ? "GET" : "POST", headers: { Cookie: cookie, Origin: base, "Content-Type": "application/json" }, ...(body === undefined ? {} : { body: JSON.stringify(body) }), redirect: "manual", signal: AbortSignal.timeout(20000) });
  async function command(action: string, input: unknown, requestId: string = randomUUID()) { const r = await request("/api/restaurant/business", { action, input, requestId }), v = await r.json(); assert(r.ok, v.error ?? `Restaurant ${action} failed`); return v.result as { id: string }; }
  const read = async (): Promise<ReturnType<typeof restaurantManagementData>> => { const r = await request("/api/restaurant/business"); assert(r.ok, "Restaurant data failed"); return r.json(); };
  const check = async (id: string) => { const order = (await read()).orders.find(o => o.id === id); assert(order, "Restaurant check missing"); return order; };
  const offset = new Date().getUTCHours() - 12, timezone = `Etc/GMT${offset >= 0 ? "+" : "-"}${Math.abs(offset)}`;
  await command("configure", { name: "HTTP Kitchen", timezone, businessDayStartHour: 0, taxBasisPoints: 1000, taxReviewed: true });
  const diningVisit = await restaurantDiningHttpCheck(base, ownerCookie, employeeCookie);
  const supplier = (await command("supplier.save", { name: "HTTP Supply", email: "supplier@example.test", phone: "", active: true })).id;
  const ingredient = (await command("ingredient.save", { name: "HTTP rice", unit: "g", reorderAt: 100, targetStock: 1000, supplierId: supplier, active: true })).id;
  const today = (await read()).today;
  const receipt = (await command("receive", { supplierId: supplier, invoiceReference: "HTTP-SUP-1", date: today, purchaseId: null, lines: [{ ingredientId: ingredient, quantity: 300, cost: 300, expires: null }] })).id;
  const menu = (await command("menu.save", { name: "HTTP rice bowl", category: "Main", price: 1000, station: "Line", description: "Synthetic rice bowl", allergens: "Kitchen-reviewed fixture", recipe: [{ ingredientId: ingredient, quantity: 100 }], active: true })).id;
  const create = async (ref: string, qty: number) => (await command("order.create", { ref, channel: ref === "HTTP-CHECK-1" ? "dine_in" : "takeaway", guest: "Synthetic HTTP guest", covers: 1, reservationId: ref === "HTTP-CHECK-1" ? diningVisit : null, server: "HTTP server", note: "Synthetic acceptance", lines: [{ menuId: menu, qty }] })).id;
  const first = await create("HTTP-CHECK-1", 2), fireId = randomUUID(), fireInput = { id: first, revision: (await check(first)).revision, allergensReviewed: true };
  await command("order.fire", fireInput, fireId); await command("order.fire", fireInput, fireId);
  assert((await read()).ingredients.find(i => i.id === ingredient)?.available === 100, "Retry deducted stock twice.");
  // Competing requests through separate HTTP connections must share stock.
  const a = await create("HTTP-RACE-A", 1), b = await create("HTTP-RACE-B", 1);
  const race = await Promise.all([a, b].map(id => request("/api/restaurant/business", { requestId: randomUUID(), action: "order.fire", input: { id, revision: 1, allergensReviewed: true } })));
  assert(race.filter(r => r.ok).length === 1 && race.filter(r => r.status === 400).length === 1, "Last portion was accepted twice.");
  for (const id of [a, b]) await command("order.cancel", { id, revision: (await check(id)).revision, reason: "Synthetic race complete before cooking" });
  const floor = await (await request("/api/restaurant/service")).json(); const visit = floor.reservations.find((r: { id: string }) => r.id === diningVisit);
  const premature = await request("/api/restaurant/dining", { requestId: randomUUID(), action: "visit.status", input: { id: diningVisit, revision: visit.revision, status: "completed" } }); assert(premature.status === 400, "Floor released a table with an open priced check.");
  const o = await check(first);
  const service = async (action: string, input: unknown) => { const r = await request("/api/restaurant/service", { action, input }); assert(r.ok, `Kitchen ${action} failed`); };
  for (const status of ["cooking", "ready"]) await service("ticket.status", { id: o.ticketId, status });
  const shortcut = await request("/api/restaurant/service", { action: "ticket.status", input: { id: o.ticketId, status: "served" } }); assert(shortcut.status === 400, "Kitchen bypassed the priced sale posting.");
  await command("tender", { id: first, revision: (await check(first)).revision, method: "cash", amount: 1000, tip: 100, reference: "HTTP-CASH-1", received: true });
  await command("order.serve", { id: first, revision: (await check(first)).revision });
  await command("tender", { id: first, revision: (await check(first)).revision, method: "external_card", amount: 1200, tip: 0, reference: "HTTP-CARD-1", received: true });
  await command("order.close", { id: first, revision: (await check(first)).revision });
  const released = await request("/api/restaurant/dining", { requestId: randomUUID(), action: "visit.status", input: { id: diningVisit, revision: visit.revision, status: "completed" } }); assert(released.ok, "Paid check did not allow table release.");
  await command("website.configure", { revision: 1, enabled: true, origins: [], instructions: "Synthetic restaurant pickup counter. Payment at pickup." });
  const pickup = (await command("pickup.save", { at: new Date(Date.now() + 3600000).toISOString(), capacity: 2, enabled: true })).id;
  const storefront = await fetch(base + "/api/website/restaurant"), menuHtml = await storefront.text();
  const proof = menuHtml.match(/name="proof" value="([^"]+)"/)?.[1]; assert(storefront.ok && proof && menuHtml.includes("HTTP rice bowl") && !menuHtml.includes("remainingCost"), "Public pickup menu missing or leaked stock costs.");
  const websitePost = (body: Record<string, string>) => fetch(base + "/api/website/restaurant", { method: "POST", headers: { Origin: base, "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams(body), redirect: "manual" });
  const reviewed = await websitePost({ action: "review", proof, slotId: pickup, name: "HTTP online guest", phone: "555-0100", email: "", note: "Synthetic dietary review", consent: "yes", "menu.0": menu, "qty.0": "1" }), reviewHtml = await reviewed.text();
  const quote = reviewHtml.match(/name="quote" value="([^"]+)"/)?.[1]; assert(reviewed.ok && quote && reviewHtml.includes("USD 11.00"), "Pickup review did not show the server price and tax.");
  let receiptToken = "";
  for (let attempt = 0; attempt < 2; attempt++) { const r = await websitePost({ action: "submit", quote, confirmed: "yes" }), html = await r.text(); assert(r.ok && html.includes("awaiting kitchen review"), "Pickup submission or its retry failed."); const token = html.match(/href="\/api\/website\/restaurant\?receipt=([^"]+)"/)?.[1]; assert(token, "Private pickup receipt link missing"); receiptToken = decodeURIComponent(token); }
  const online = (await read()).orders.filter(o => o.channel === "online"); assert(online.length === 1 && (await read()).ingredients[0].available === 0, "Online retry duplicated an order or stock deduction.");
  const onlineOrder = online[0]; const earlyCook = await request("/api/restaurant/service", { action: "ticket.status", input: { id: onlineOrder.ticketId, status: "cooking" } }); assert(earlyCook.status === 400, "Online order bypassed kitchen dietary review.");
  await command("order.allergens", { id: onlineOrder.id, revision: onlineOrder.revision, reviewed: true });
  for (const status of ["cooking", "ready"]) await service("ticket.status", { id: onlineOrder.ticketId, status });
  await command("order.serve", { id: onlineOrder.id, revision: (await check(onlineOrder.id)).revision });
  await command("tender", { id: onlineOrder.id, revision: (await check(onlineOrder.id)).revision, method: "cash", amount: 1100, tip: 0, reference: "HTTP-PICKUP-CASH", received: true });
  await command("order.close", { id: onlineOrder.id, revision: (await check(onlineOrder.id)).revision });
  await command("bill.pay", { id: receipt, amount: 300, reference: "HTTP-SUPPLIER-BANK-1", paid: true });
  await command("tips.pay", { amount: 100, method: "cash", reference: "HTTP-TIPS-1", evidence: "Synthetic staff tip receipt", confirmed: true });
  await command("processor.settle", { amount: 1200, fees: 30, reference: "HTTP-SETTLEMENT-1", evidence: "Synthetic 1170 net bank receipt", confirmed: true });
  await restaurantSpecialHttpCheck(base, ownerCookie, employeeCookie, { menu, ingredient, supplier, today, pickup });
  await restaurantStocktakeHttpCheck(base, ownerCookie, employeeCookie, { ingredient, supplier, today });
  await restaurantCreditHttpCheck(base, ownerCookie, employeeCookie, { first, menu, onlineId: onlineOrder.id, receiptToken });
  const modifiers = await restaurantModifierHttpCheck(base, ownerCookie, employeeCookie, today);
  const prep = await restaurantPrepHttpCheck(base, ownerCookie, employeeCookie, backendToken, today);
  await command("close", { date: today, operated: true, openMinutes: 480, countedCash: 2570 + modifiers.cash + prep.cash, note: "Synthetic counted cash short by 10", reviewed: true });
  const data = await read(); assert(data.financial?.closes[0].sales === 3000 + modifiers.netSales + prep.netSales && data.financial.closes[0].foodCost === 400 + modifiers.foodCost + prep.foodCost && data.financial.closes[0].variance === -10, "Daily close does not match the service-day evidence.");
  await restaurantReportHttpCheck(base, ownerCookie, employeeCookie, data.financial.closes[0]);
  assert(data.financial.journals.every(j => j.lines.reduce((t, l) => t + l.debitCents - l.creditCents, 0) === 0), "Restaurant posted an unbalanced journal.");
  assert(restaurantBusinessSnapshot().orders.find(o => o.id === first)?.status === "closed", "The second process cannot see the committed check.");
  const page = await request("/restaurant/manage?tab=orders"), html = await page.text(); assert(page.ok && html.includes("HTTP-CHECK-1") && html.includes("HTTP rice bowl"), "Installed operations screen failed to render saved checks.");
  const ledger = await request("/ledger"); assert(ledger.ok && (await ledger.text()).includes("Restaurant sale: HTTP-CHECK-1"), "Shared ledger did not render the restaurant journal.");
  const denied = await request("/api/restaurant/business", undefined, employeeCookie); assert(denied.status === 403, "Restricted employee opened restaurant accounting.");
  console.log(JSON.stringify({ ok: true, restaurant: ["receiving and recipe costing", "server-priced check", "online menu → review → order → dietary review → kitchen → payment", "concurrent last-stock protection", "retry protection", "kitchen readiness and sale posting", "split tenders and tips", "supplier payment and processor fee", "cash count and balanced shared ledger", "installed screen and cross-process persistence", "employee restriction"], externalPayments: "synthetic evidence only; no provider was called" }));
}
