// @vitest-environment node
import { beforeEach,afterEach,it,expect,vi } from "vitest";
import { mkdtemp,rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { mapPlace,searchPlaces,optimizeRoute } from "./google";
import { navigationLinks } from "./navigation";
import { decodePolyline } from "./polyline";
let dir="";beforeEach(async()=>{dir=await mkdtemp(path.join(tmpdir(),"dealdesk-maps-"));vi.stubEnv("DEALDESK_DATA_DIR",dir);vi.stubEnv("GOOGLE_MAPS_SERVER_KEY","secret-maps-key");});afterEach(async()=>{vi.unstubAllGlobals();vi.unstubAllEnvs();await rm(dir,{recursive:true,force:true});});
it("keeps unlisted contact information unknown",()=>{const p=mapPlace({id:"ChIJ_test123",displayName:{text:"Deli"},location:{latitude:42,longitude:-72}});expect(p?.phone).toBeNull();expect(p?.website).toBeNull();expect(p?.mapsUrl).toContain("query_place_id=ChIJ_test123");expect(mapPlace({id:"x"})).toBeNull();});
it("uses a field mask for business phones and sends the search page token",async()=>{const transport=vi.fn(async(_url:unknown,init?:RequestInit)=>{expect(init?.headers).toMatchObject({"X-Goog-Api-Key":"secret-maps-key"});expect((init?.headers as Record<string,string>)["X-Goog-FieldMask"]).toContain("places.nationalPhoneNumber");expect(JSON.parse(String(init?.body))).toMatchObject({textQuery:"delis in Springfield MA",pageToken:"next",pageSize:20});return new Response(JSON.stringify({places:[],nextPageToken:"page2"}));});vi.stubGlobal("fetch",transport);expect(await searchPlaces("delis in Springfield MA","next")).toMatchObject({places:[],nextPageToken:"page2"});});
const stops=[0,1,2].map(i=>({id:`00000000-0000-4000-8000-00000000000${i}`,placeId:`ChIJ_test${i}`,address:""}));
it("maps Google's optimized indices back to the correct saved prospects",async()=>{vi.stubGlobal("fetch",vi.fn(async(_url:unknown,init?:RequestInit)=>{const body=JSON.parse(String(init?.body));expect(body.origin).toEqual({address:"10 Main St, Springfield MA"});expect(body.destination).toEqual(body.origin);expect(body.optimizeWaypointOrder).toBe(true);return new Response(JSON.stringify({routes:[{optimizedIntermediateWaypointIndex:[2,0,1],duration:"1800s",distanceMeters:12345,legs:[],polyline:{encodedPolyline:""}}]}));}));const r=await optimizeRoute("10 Main St, Springfield MA",stops,true);expect(r.orderedIds).toEqual([stops[2].id,stops[0].id,stops[1].id]);expect(r.durationSeconds).toBe(1800);});
it("fails closed when Google returns a duplicate/incomplete permutation",async()=>{vi.stubGlobal("fetch",vi.fn(async()=>new Response(JSON.stringify({routes:[{optimizedIntermediateWaypointIndex:[0,0,1],duration:"30s",distanceMeters:20}]}))));await expect(optimizeRoute("10 Main St",stops,true)).rejects.toThrow("incomplete stop order");});
it("keeps the final visit fixed for a one-way route",async()=>{vi.stubGlobal("fetch",vi.fn(async(_url:unknown,init?:RequestInit)=>{expect(JSON.parse(String(init?.body)).destination).toEqual({placeId:stops[2].placeId});return new Response(JSON.stringify({routes:[{optimizedIntermediateWaypointIndex:[1,0],duration:"20s",distanceMeters:100}]}));}));expect((await optimizeRoute("Start street",stops,false)).orderedIds).toEqual([stops[1].id,stops[0].id,stops[2].id]);});
it("splits navigation into mobile-compatible batches without losing visits",()=>{const links=navigationLinks("Start",Array.from({length:9},(_,i)=>({name:`Shop ${i}`,address:`${i} Main St`,placeId:`ChIJ_${i}`})),true);expect(links).toHaveLength(4);expect(new URL(links[0].url).searchParams.get("waypoint_place_ids")).toBe("ChIJ_0|ChIJ_1|ChIJ_2");expect(new URL(links[1].url).searchParams.get("origin")).toBe("3 Main St");expect(links[3].label).toBe("Return to start");});
it("decodes route geometry and rejects truncated data",()=>{expect(decodePolyline('_p~iF~ps|U_ulLnnqC_mqNvxq`@')).toEqual([{lat:38.5,lng:-120.2},{lat:40.7,lng:-120.95},{lat:43.252,lng:-126.453}]);expect(()=>decodePolyline('_')).toThrow();});
