import { z } from "zod";
const time = z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/), date = z.iso.date(), id = z.uuid();
export const serviceWindowInput = z.object({ start: time, end: time, overnight: z.boolean() }).strict();
export const diningSettingsInput = z.object({ revision: z.number().int().positive(), enabled: z.boolean(), tableIds: z.array(id).max(200), origins: z.array(z.string().max(250)).max(8), instructions: z.string().trim().min(10).max(2000), turnMinutes: z.number().int().min(15).max(360), bufferMinutes: z.number().int().min(0).max(120), intervalMinutes: z.enum(["15", "30", "60"]), leadMinutes: z.number().int().min(0).max(1440), horizonDays: z.number().int().min(1).max(180), maxPartySize: z.number().int().min(1).max(50), maxArrivingCovers: z.number().int().min(1).max(500), changeLeadMinutes: z.number().int().min(0).max(10080), weekly: z.array(serviceWindowInput.extend({ weekday: z.number().int().min(0).max(6) })).max(21), exceptions: z.array(z.object({ date, windows: z.array(serviceWindowInput).max(3) }).strict()).max(366) }).strict();
export type DiningSettings = z.infer<typeof diningSettingsInput>;
export interface DiningState { settings: DiningSettings; commands: Record<string, { request: string; result: { id: string } }>; audit: { at: string; actor: string; action: string; id: string; before?: unknown }[] }
export const emptyDining = (): DiningState => ({ settings: { revision: 1, enabled: false, tableIds: [], origins: [], instructions: "Contact the restaurant if your plans change or you need assistance with your visit.", turnMinutes: 90, bufferMinutes: 15, intervalMinutes: "15", leadMinutes: 30, horizonDays: 60, maxPartySize: 8, maxArrivingCovers: 30, changeLeadMinutes: 60, weekly: [], exceptions: [] }, commands: {}, audit: [] });
export const diningCommandSchema = z.object({ requestId: id, action: z.enum(["settings.save", "reservation.save", "visit.arrive", "visit.quote", "visit.status", "visit.table"]), input: z.record(z.string(), z.unknown()) }).strict();
export const reservationSaveInput = z.object({ id: id.optional(), revision: z.number().int().positive().optional(), name: z.string().trim().min(1).max(120), phone: z.string().trim().max(40), email: z.union([z.email().max(160), z.literal("")]), notes: z.string().trim().max(500), partySize: z.number().int().min(1).max(50), dateISO: date, time, occurrence: z.enum(["first", "second"]).default("first"), tableId: id.nullable(), walkIn: z.boolean(), quotedWaitMinutes: z.number().int().min(0).max(240).nullable(), host: z.string().trim().max(100) }).strict();
export const diningVisitInput = z.object({ id, revision: z.number().int().positive() }).strict();
export const visitQuoteInput = diningVisitInput.extend({ quotedWaitMinutes: z.number().int().min(0).max(240), host: z.string().trim().min(1).max(100) });
export const visitStatusInput = diningVisitInput.extend({ status: z.enum(["requested", "confirmed", "waiting", "seated", "completed", "cancelled", "no-show"]) });
export const visitTableInput = diningVisitInput.extend({ tableId: id.nullable() });
export const publicDiningInput = z.object({ name: z.string().trim().min(1).max(120), phone: z.string().trim().min(5).max(40), email: z.union([z.email().max(160), z.literal("")]), notes: z.string().trim().max(500), partySize: z.number().int().min(1).max(50), startAt: z.iso.datetime({ offset: true }), consent: z.literal(true) }).strict();
export function diningCatalog() { return Object.entries({ "settings.save": diningSettingsInput, "reservation.save": reservationSaveInput, "visit.arrive": diningVisitInput, "visit.quote": visitQuoteInput, "visit.status": visitStatusInput, "visit.table": visitTableInput }).map(([action, schema]) => ({ action, inputSchema: z.toJSONSchema(schema) })); }
