import { z } from "zod";
const id = z.uuid(), cents = z.number().int().min(0).max(99_999_999), time = z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/);
export const specialCodeInput = z.string().trim().toUpperCase().max(30).regex(/^[A-Z0-9-]*$/).default("");
export const specialInput = z.object({ id: id.optional(), revision: z.number().int().positive().optional(), name: z.string().trim().min(1).max(100), code: specialCodeInput.refine(v => v.length >= 3, "Use a special code of at least three characters."), description: z.string().trim().min(10).max(1000), startDate: z.iso.date(), endDate: z.iso.date(), weekdays: z.array(z.number().int().min(0).max(6)).min(1).max(7), startTime: time, endTime: time, overnight: z.boolean(), channels: z.array(z.enum(["dine_in", "takeaway", "online"])).min(1).max(3), menuIds: z.array(id).min(1).max(100), discountBasisPoints: z.number().int().min(1).max(9000), minimumFoodContribution: cents, maxOrders: z.number().int().min(1).max(100000), maxOrdersPerDate: z.number().int().min(1).max(10000), discountBudget: cents.positive(), advertisingBudget: cents }).strict();
export const specialVersionInput = z.object({ id, revision: z.number().int().positive() }).strict();
export const specialPublishInput = specialVersionInput.extend({ reviewed: z.literal(true) }).strict();
export const specialSpendInput = z.object({ id, date: z.iso.date(), amount: cents.positive(), provider: z.string().trim().min(1).max(80), reference: z.string().trim().min(1).max(100), evidence: z.string().trim().min(3).max(1000), overrunReason: z.string().trim().max(1000).default(""), paid: z.literal(true) }).strict();
export type RestaurantSpecial = Omit<z.infer<typeof specialInput>, "id" | "revision"> & { id: string; revision: number; status: "draft" | "active" | "paused" | "archived"; publishedAt: string | null; timezone: string | null; createdAt: string; publishedBy: string | null };
export interface SpecialSpend { id: string; specialId: string; date: string; amount: number; provider: string; reference: string; evidence: string; overrunReason: string; actor: string; at: string }
export interface SpecialUse { id: string; revision: number; code: string; name: string; serviceDate: string; reviewedAt: string; minimumFoodContribution: number; menuIds: string[] }
