import type { SectionKey } from "../permissions/model";

export type FieldType = "text" | "long" | "email" | "date" | "datetime" | "money" | "number" | "boolean" | "select" | "ref";
export interface Field { key: string; label: string; type: FieldType; required?: boolean; options?: string[]; kinds?: string[] }
export interface RecordDefinition {
  kind: string; label: string; section: SectionKey; profile: "service" | "nonprofit";
  module: string; fields: Field[]; states: string[]; transitions: Record<string, string[]>;
}
const f = (key: string, label: string, type: FieldType = "text", required = false): Field => ({ key, label, type, required });
const ref = (key: string, label: string, kinds: string[], required = true): Field => ({ key, label, type: "ref", kinds, required });
const choice = (key: string, label: string, options: string[], required = true): Field => ({ key, label, type: "select", options, required });
const money = (key = "amount", label = "Amount"): Field => f(key, label, "money", true);
const evidence = f("evidence", "Evidence / document references", "long");
const owner = f("owner", "Responsible person");
const due = f("due", "Due date", "date");
const notes = f("notes", "Notes", "long");
const dates = [f("start", "Starts", "datetime", true), f("end", "Ends", "datetime", true)];
const client = ref("client", "Client", ["client"]);
const job = ref("job", "Work order", ["job"]);
const donor = ref("donor", "Donor", ["donor"]);
const program = ref("program", "Program", ["program"]);
const participant = ref("participant", "Participant", ["participant"]);

function def(kind: string, label: string, module: string, section: SectionKey, fields: Field[], states = ["draft", "active", "closed"], transitions?: Record<string, string[]>): RecordDefinition {
  return { kind, label, module, section, profile: module.startsWith("service-") ? "service" : "nonprofit", fields,
    states, transitions: transitions ?? Object.fromEntries(states.map((s, i) => [s, i < states.length - 1 ? [states[i + 1]] : []])) };
}

/** Separate record contracts and completion rules, sharing only storage and form infrastructure. */
export const recordDefinitions: RecordDefinition[] = [
  def("donor", "Donor / supporter", "nonprofit-donors", "fundraising", [choice("category", "Type", ["individual", "household", "company", "foundation"]), f("email", "Email", "email"), f("phone", "Phone"), f("address", "Address", "long"), ref("household", "Household / related supporter", ["donor"], false), choice("contactPreference", "Contact preference", ["email", "phone", "mail", "do_not_contact"]), owner, notes]),
  def("donation", "Donation", "nonprofit-donations", "fundraising", [donor, money(), choice("giftType", "Gift type", ["cash", "noncash"]), ref("pledge", "Pledge installment", ["pledge"], false), ref("campaign", "Campaign", ["campaign"], false), ref("fund", "Restricted fund", ["fund"], false), f("goodsDescription", "Noncash property / goods or services description", "long"), f("benefitValue", "Goods or services value", "money"), evidence, notes], ["draft", "recorded", "cancelled"], { draft: ["recorded", "cancelled"], recorded: [], cancelled: [] }),
  def("gift_schedule", "Recurring gift schedule", "nonprofit-donations", "fundraising", [donor, money(), choice("frequency", "Frequency", ["monthly", "quarterly", "annual"]), due, f("providerReference", "Payment provider subscription reference"), evidence], ["draft", "active", "paused", "cancelled"], { draft: ["active", "cancelled"], active: ["paused", "cancelled"], paused: ["active", "cancelled"], cancelled: [] }),
  def("gift_payment", "Donation payment / refund", "nonprofit-donations", "fundraising", [ref("donation", "Donation", ["donation"]), money(), choice("direction", "Entry", ["receipt", "refund"]), f("reference", "Unique bank / processor transaction reference", "text", true), f("paidOn", "Payment date", "date", true), evidence], ["draft", "confirmed", "reconciled"], { draft: ["confirmed"], confirmed: ["reconciled"], reconciled: [] }),
  def("pledge", "Pledge installment", "nonprofit-pledges", "fundraising", [donor, money(), due, ref("campaign", "Campaign", ["campaign"], false), evidence, notes], ["draft", "committed", "cancelled"], { draft: ["committed", "cancelled"], committed: ["cancelled"], cancelled: [] }),
  def("acknowledgment", "Donation acknowledgment", "nonprofit-acknowledgments", "fundraising", [ref("donation", "Donation", ["donation"]), f("template", "Reviewed acknowledgment text", "long", true), f("reviewer", "Template reviewer", "text", true), ref("corrects", "Corrects acknowledgment", ["acknowledgment"], false), f("deliveryReference", "Delivery evidence / tracking reference"), evidence], ["draft", "reviewed", "delivered"], { draft: ["reviewed"], reviewed: ["delivered"], delivered: [] }),
  def("fund", "Restricted fund", "nonprofit-restrictions", "money", [f("purpose", "Permitted purpose", "long", true), f("conditions", "Conditions and reviewed allocation rules", "long", true), f("startsOn", "Available from", "date"), f("endsOn", "Available until", "date"), evidence, owner]),
  def("allocation", "Funding allocation", "nonprofit-restrictions", "money", [ref("fund", "Fund", ["fund"]), program, money(), f("rationale", "Compliance with fund conditions", "long", true), f("reviewer", "Reviewer", "text", true), evidence], ["draft", "approved"], { draft: ["approved"], approved: [] }),
  def("grant", "Incoming grant", "nonprofit-grants", "fundraising", [ref("funder", "Funder", ["donor"]), money("award", "Award requested / awarded"), due, f("reportDue", "Report due", "date"), ref("fund", "Restricted fund", ["fund"], false), f("agreement", "Award agreement / conditions", "long"), evidence, owner], ["draft", "submitted", "awarded", "declined", "closed"], { draft: ["submitted"], submitted: ["awarded", "declined"], awarded: ["closed"], declined: [], closed: [] }),
  def("grant_payment", "Grant receipt", "nonprofit-funding", "money", [ref("grant", "Grant", ["grant"]), money(), f("reference", "Unique bank transaction reference", "text", true), f("paidOn", "Payment date", "date", true), evidence], ["draft", "confirmed", "reconciled"]),
  def("claim", "Reimbursement claim", "nonprofit-reimbursements", "money", [ref("grant", "Grant", ["grant"]), ref("cost", "Approved program cost", ["program_cost"]), money(), due, f("rejectionReason", "Correction requested", "long"), evidence], ["draft", "submitted", "approved", "rejected", "paid"], { draft: ["submitted"], submitted: ["approved", "rejected"], rejected: ["draft"], approved: ["paid"], paid: [] }),
  def("program", "Program budget", "nonprofit-budgets", "programs", [money("budget", "Approved budget"), f("capacity", "Participant capacity", "number", true), f("allocationMethod", "Shared cost allocation method", "long"), owner, notes]),
  def("program_cost", "Program cost", "nonprofit-budgets", "programs", [program, money(), choice("costType", "Cost category", ["direct", "staff_time", "shared"]), f("allocationMethod", "Allocation method", "long", true), f("reviewer", "Cost reviewer", "text", true), evidence, due], ["draft", "approved", "paid"]),
  def("campaign", "Fundraising campaign", "nonprofit-campaigns", "fundraising", [money("goal", "Fundraising goal"), money("cost", "Campaign costs"), due, owner, f("appeal", "Appeal / outreach plan", "long"), notes]),
  def("volunteer", "Volunteer", "nonprofit-volunteers", "volunteers", [f("email", "Email", "email"), f("skills", "Skills and interests", "long"), f("availability", "Availability", "long"), f("training", "Completed training", "long"), f("onboardingComplete", "Required checks and documents reviewed", "boolean", true), evidence, owner], ["draft", "approved", "inactive"], { draft: ["approved"], approved: ["inactive"], inactive: ["draft"] }),
  def("shift", "Volunteer shift assignment", "nonprofit-shifts", "volunteers", [ref("volunteer", "Volunteer", ["volunteer"], false), ...dates, f("location", "Location", "text", true), f("hours", "Verified hours", "number"), f("verifier", "Hours verified by"), evidence], ["draft", "assigned", "checked_in", "verified", "cancelled"], { draft: ["assigned", "cancelled"], assigned: ["checked_in", "cancelled"], checked_in: ["verified"], verified: [], cancelled: [] }),
  def("participant", "Participant", "nonprofit-participants", "programs", [f("email", "Contact email", "email"), owner, f("contact", "Authorized contact instructions", "long"), notes]),
  def("service_record", "Participant service record", "nonprofit-participants", "programs", [participant, program, f("servedOn", "Service date", "date", true), f("service", "Service delivered", "long", true), owner, evidence], ["draft", "reviewed"]),
  def("enrollment", "Program application", "nonprofit-enrollment", "programs", [participant, program, f("eligibility", "Eligibility review and required documents", "long", true), f("reviewer", "Eligibility reviewer", "text", true), f("referral", "Referral / waitlist notes", "long"), evidence], ["draft", "reviewed", "enrolled", "waitlisted", "declined", "completed"], { draft: ["reviewed"], reviewed: ["enrolled", "waitlisted", "declined"], waitlisted: ["enrolled", "declined"], enrolled: ["completed"], declined: [], completed: [] }),
  def("session", "Program session", "nonprofit-sessions", "programs", [program, ...dates, f("location", "Room / location", "text", true), owner, f("capacity", "Capacity", "number", true)], ["draft", "scheduled", "completed", "cancelled"], { draft: ["scheduled", "cancelled"], scheduled: ["completed", "cancelled"], completed: [], cancelled: [] }),
  def("attendance", "Session attendance", "nonprofit-sessions", "programs", [ref("session", "Session", ["session"]), participant, notes], ["draft", "present", "absent"], { draft: ["present", "absent"], present: [], absent: [] }),
  def("outcome", "Outcome measure", "nonprofit-outcomes", "programs", [program, participant, f("measure", "Measure and unit", "text", true), f("baseline", "Baseline result", "text", true), f("result", "Follow-up result", "text", true), f("measuredOn", "Measurement date", "date", true), evidence, f("reviewer", "Reviewer", "text", true)], ["draft", "reviewed"]),
  def("report", "Program / funder report", "nonprofit-reporting", "programs", [program, ref("grant", "Grant", ["grant"], false), f("periodStart", "Period begins", "date", true), f("periodEnd", "Period ends", "date", true), due, f("narrative", "Report narrative", "long", true), f("reviewer", "Report reviewer", "text", true), f("submissionReference", "Submission evidence")], ["draft", "reviewed", "submitted"]),
  def("event", "Fundraising event", "nonprofit-events", "fundraising", [...dates, f("location", "Location"), f("capacity", "Capacity", "number", true), money("cost", "Event costs"), owner]),
  def("registration", "Event registration / sponsorship", "nonprofit-events", "fundraising", [ref("event", "Event", ["event"]), donor, choice("category", "Entry type", ["ticket_purchase", "sponsorship_purchase", "free_registration"]), money(), f("paymentReference", "Payment evidence"), f("attended", "Attended", "boolean")], ["draft", "confirmed", "cancelled"], { draft: ["confirmed", "cancelled"], confirmed: ["cancelled"], cancelled: [] }),
  def("membership", "Membership", "nonprofit-memberships", "fundraising", [donor, f("membershipType", "Membership type", "text", true), money("dues", "Dues"), f("benefits", "Benefits", "long"), f("renewal", "Renewal date", "date", true), f("graceDays", "Grace period (days)", "number"), f("paymentReference", "Dues payment reference"), notes], ["draft", "active", "lapsed", "cancelled"], { draft: ["active"], active: ["lapsed", "cancelled"], lapsed: ["active", "cancelled"], cancelled: [] }),
  def("governance", "Board meeting / policy / action", "nonprofit-governance", "governance", [choice("category", "Type", ["meeting", "policy", "board_action", "filing"]), f("minutes", "Minutes / policy / action", "long", true), due, owner, f("approver", "Approver"), evidence], ["draft", "reviewed", "approved", "completed"]),

  def("client", "Service client", "service-clients", "services", [f("email", "Billing email", "email", true), f("phone", "Phone"), f("billingAddress", "Billing address", "long"), owner, notes]),
  def("location", "Service location", "service-clients", "services", [client, f("address", "Address", "long", true), f("access", "Access instructions", "long"), notes]),
  def("inquiry", "Service inquiry", "service-intake", "services", [client, f("scope", "Requested work", "long", true), choice("source", "Source", ["website", "phone", "email", "referral", "other"]), owner, due, evidence], ["draft", "qualified", "closed"]),
  def("rate", "Service rate", "service-catalog", "services", [ref("client", "Client-specific rate", ["client"], false), choice("basis", "Billing method", ["fixed", "hourly", "materials", "milestone", "deposit", "recurring"]), money("rate", "Price / hourly rate"), money("minimum", "Minimum charge"), money("travel", "Travel charge"), f("effective", "Effective date", "date", true), f("expires", "Expiration", "date"), notes]),
  def("proposal", "Service proposal", "service-proposals", "services", [client, ref("inquiry", "Inquiry", ["inquiry"], false), f("scope", "Scope and deliverables", "long", true), f("exclusions", "Exclusions", "long", true), money(), f("expires", "Offer expiration", "date", true), f("acceptedBy", "Customer acceptance recorded by"), evidence], ["draft", "sent", "accepted", "declined", "expired"], { draft: ["sent"], sent: ["accepted", "declined", "expired"], accepted: [], declined: [], expired: [] }),
  def("agreement", "Service agreement", "service-agreements", "services", [client, ref("proposal", "Accepted proposal", ["proposal"]), f("terms", "Terms, payment schedule and cancellation policy", "long", true), money("deposit", "Required deposit"), f("signedBy", "Customer signatory", "text", true), evidence], ["draft", "signed", "cancelled"], { draft: ["signed", "cancelled"], signed: ["cancelled"], cancelled: [] }),
  def("resource", "Staff / equipment / room", "service-resources", "services", [choice("category", "Resource type", ["staff", "equipment", "room"]), f("skills", "Skills / capabilities", "long"), f("weeklyHours", "Available hours per week", "number", true), owner, notes]),
  def("booking", "Booking", "service-booking", "services", [job, ref("resource", "Assigned resource", ["resource"]), ...dates, f("buffer", "Preparation / travel buffer (minutes)", "number"), ref("location", "Location", ["location"], false), notes], ["draft", "scheduled", "completed", "cancelled"], { draft: ["scheduled", "cancelled"], scheduled: ["completed", "cancelled"], completed: [], cancelled: [] }),
  def("job", "Work order / project", "service-work", "services", [client, ref("agreement", "Signed agreement", ["agreement"]), f("instructions", "Work instructions / deliverables", "long", true), f("requiredChecks", "Required checks (one per line)", "long", true), f("completedChecks", "Completed checks (one per line)", "long"), owner, due, money("budget", "Cost budget"), f("acceptedBy", "Customer completion acceptance"), evidence], ["draft", "scheduled", "in_progress", "completed", "accepted", "cancelled"], { draft: ["scheduled", "cancelled"], scheduled: ["in_progress", "cancelled"], in_progress: ["completed"], completed: ["accepted", "in_progress"], accepted: [], cancelled: [] }),
  def("milestone", "Project milestone / task", "service-work", "services", [job, ref("dependsOn", "Depends on milestone", ["milestone"], false), owner, due, money(), evidence], ["draft", "in_progress", "completed"]),
  def("time_entry", "Time / materials / job expense", "service-time", "services", [job, choice("category", "Category", ["labor", "travel", "materials", "subcontractor", "expense"]), f("minutes", "Minutes worked", "number"), money("cost", "Actual cost"), money("billable", "Billable amount"), f("workedOn", "Work date", "date", true), owner, f("reviewer", "Approver"), evidence], ["draft", "submitted", "approved", "rejected"], { draft: ["submitted"], submitted: ["approved", "rejected"], rejected: ["draft"], approved: [] }),
  def("field_update", "Field work update", "service-mobile", "services", [job, f("checklist", "Completed checks / field notes", "long", true), f("signoff", "Customer sign-off"), evidence, owner], ["draft", "submitted", "reviewed"]),
  def("change", "Scope change", "service-changes", "services", [job, f("scope", "Additional work and exclusions", "long", true), money(), f("scheduleImpact", "Schedule impact", "long", true), f("acceptedBy", "Customer approver"), evidence], ["draft", "submitted", "approved", "declined"], { draft: ["submitted"], submitted: ["approved", "declined"], approved: [], declined: [] }),
  def("invoice", "Service invoice", "service-billing", "money", [job, choice("method", "Billing method", ["fixed", "hourly", "materials", "milestone", "deposit", "recurring"]), ref("milestone", "Milestone being billed", ["milestone"], false), ref("contract", "Recurring agreement", ["recurring"], false), f("period", "Billing period (YYYY-MM)", "text"), money(), due, f("description", "Invoice description", "long", true)], ["draft", "issued", "void"], { draft: ["issued", "void"], issued: ["void"], void: [] }),
  def("service_payment", "Service payment / credit / refund", "service-collections", "money", [ref("invoice", "Invoice", ["invoice"]), money(), choice("direction", "Entry type", ["receipt", "refund", "credit"]), f("reference", "Unique bank / processor / credit reference", "text", true), f("paidOn", "Entry date", "date", true), evidence], ["draft", "confirmed", "reconciled"]),
  def("recurring", "Recurring service agreement", "service-recurring", "services", [client, job, f("services", "Included services", "long", true), f("includedHours", "Included hours per period", "number", true), money(), money("overageRate", "Hourly overage rate"), f("renewal", "Renewal date", "date", true), f("cancellation", "Cancellation terms", "long", true), evidence]),
  def("issue", "Complaint / callback / rework", "service-rework", "services", [job, f("issue", "Customer issue", "long", true), f("resolution", "Resolution / corrective visit", "long"), f("billable", "Additional work is billable", "boolean"), owner, due, evidence], ["draft", "assigned", "resolved", "closed"], { draft: ["assigned"], assigned: ["resolved"], resolved: ["closed", "assigned"], closed: [] }),
  def("followup", "Renewal / collection / client follow-up", "service-renewals", "services", [client, ref("job", "Work order", ["job"], false), choice("category", "Follow-up type", ["renewal", "maintenance", "proposal", "collection", "complaint"]), due, owner, f("outcome", "Contact outcome", "long"), notes], ["draft", "scheduled", "completed", "cancelled"], { draft: ["scheduled", "cancelled"], scheduled: ["completed", "cancelled"], completed: [], cancelled: [] }),
];

export function definitionFor(kind: string): RecordDefinition {
  const definition = recordDefinitions.find(d => d.kind === kind);
  if (!definition) throw new Error("Unknown business record type.");
  return definition;
}
const moduleAliases: Record<string, string[]> = {
  "nonprofit-funding": ["grant_payment", "allocation"],
  "service-completion": ["job", "milestone", "issue"],
  "service-profitability": ["job", "time_entry", "invoice"],
  "service-capacity": ["booking", "resource", "job"],
  "service-portal": ["proposal", "job", "invoice"],
};
export function definitionsForModule(module: string) {
  return recordDefinitions.filter(d => d.module === module || moduleAliases[module]?.includes(d.kind));
}
