import { inspectionReportsHtml } from "../auto-repair/inspection-html";
import { escapeHtml as esc } from "../auth/forms";
import { getBranding } from "../branding/store";
import { securityHeaders } from "../security/headers";
import { appBaseUrl } from "../connections/vault";
import { CUSTOMER_PATH } from "./accounts";
import type { customerView, previewCustomerOrder } from "./service";
const e = (v: unknown) => esc(String(v ?? ""));
const money = (value: number, currency = "USD") => `${e(currency)} ${(value / 100).toFixed(2)}`;
export function customerPage(title: string, content: string, status = 200) {
  const brand = getBranding();
  return new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)} · ${e(brand.businessName)}</title><style>body{font:16px system-ui;background:#f5f5f4;color:#17231c;max-width:950px;margin:auto;padding:24px}header{display:flex;justify-content:space-between;align-items:center;gap:20px}article,section{background:white;padding:22px;border:1px solid #d5ddd7;border-radius:12px;margin:18px 0}h1{font-size:1.8rem}p{white-space:pre-wrap;line-height:1.5}label{display:block;margin:14px 0}input,select,textarea,button{padding:10px;border:1px solid #8f9c94;border-radius:6px;font:inherit;max-width:100%;box-sizing:border-box}input:not([type=checkbox]),textarea{width:100%}input[type=number]{width:100px}button{background:#2c4939;color:white;cursor:pointer}a{color:#244936}small{color:#506359}table{border-collapse:collapse;width:100%}td,th{text-align:left;padding:12px 8px;border-bottom:1px solid #dae2dc}input:focus-visible,button:focus-visible,select:focus-visible,a:focus-visible{outline:3px solid #799e87;outline-offset:2px}.scroll{overflow:auto}.amount{font-weight:700}</style></head><body><header><strong>${e(brand.businessName)}</strong><a href="${CUSTOMER_PATH}">Customer account</a></header><main><h1>${e(title)}</h1>${content}</main></body></html>`, { status, headers: { ...securityHeaders(appBaseUrl().startsWith("https:")), "Content-Security-Policy": "default-src 'none'; style-src 'unsafe-inline'; img-src 'self'; form-action 'self' https://checkout.stripe.com; frame-ancestors 'none'; base-uri 'none'", "Content-Type": "text/html; charset=utf-8", "Cache-Control": "private, no-store", "Referrer-Policy": "no-referrer" } });
}
const action = (name: string) => `<input type="hidden" name="action" value="${name}">`;
export function customerLogin(message = "") { return customerPage("Customer sign-in", `${message ? `<p role="status">${e(message)}</p>` : ""}<section><form method="post" action="${CUSTOMER_PATH}">${action("login")}<label>Email<input type="email" name="email" autocomplete="username" maxlength="160" required></label><label>Password<input type="password" name="password" autocomplete="current-password" maxlength="200" required></label><button>Sign in</button></form><p>New customer or forgotten password? Ask the organization for a private account setup link.</p></section>`); }
export function customerInvite(token: string) { return customerPage("Set up your customer account", `<section><p>Choose a password to activate the account this organization invited you to use.</p><form method="post" action="${CUSTOMER_PATH}">${action("activate")}<input type="hidden" name="invite" value="${e(token)}"><label>New password<input type="password" name="password" minlength="14" maxlength="200" autocomplete="new-password" required></label><label>Repeat password<input type="password" name="confirmation" minlength="14" maxlength="200" autocomplete="new-password" required></label><button>Activate account</button></form></section>`); }
const acceptance = (r: { id: string; revision: number }) => `<form method="post" action="${CUSTOMER_PATH}">${action("accept")}<input type="hidden" name="id" value="${e(r.id)}"><input type="hidden" name="revision" value="${r.revision}"><label><input type="checkbox" name="accepted" value="yes" required> I accept the scope and price, or completed work, shown above.</label><button>Record my acceptance</button></form>`;
export function customerDashboard(data: Awaited<ReturnType<typeof customerView>>, notice = "") {
  return customerPage(data.company, `<p>Signed in as ${e(data.user.name)} · ${e(data.user.email)}</p>${notice ? `<p role="status">${e(notice)}</p>` : ""}<form method="post" action="${CUSTOMER_PATH}">${action("logout")}<button>Sign out</button></form>
    ${(data.config.pricing || data.config.ordering) ? `<section id="pricing"><h2>Your products and pricing</h2>${data.priceMessage ? `<p>${e(data.priceMessage)}</p>` : ""}${data.catalog.length ? `<form method="post" action="${CUSTOMER_PATH}">${action("order.preview")}<p>Prices are in USD. Review quantity discounts, freight, and the total before placing an order.</p><div class="scroll"><table><thead><tr><th>Product</th><th>Agreed price</th><th>Quantity</th></tr></thead><tbody>${data.catalog.map((s, i) => `<tr><td>${e(s.name)}<br><small>${s.unitsPerCase} units per case · Minimum ${s.minCases} cases</small></td><td>${money(s.priceCents)} / case${s.tiers.map(t => `<br><small>${t.minQty}–${t.maxQty ?? "more"} cases: ${money(t.unitPriceCents)}</small>`).join("")}</td><td>${data.config.ordering ? `<input type="hidden" name="sku.${i}" value="${e(s.id)}"><label>Quantity for ${e(s.name)}<input type="number" name="qty.${i}" min="0" max="100000" step="1" value="0"></label><label>Unit for ${e(s.name)}<select name="unit.${i}"><option value="case">Case</option><option value="bottle">Individual unit</option></select></label>` : "—"}</td></tr>`).join("")}</tbody></table></div>${data.config.ordering ? `<label>Purchase order number<input name="poNumber" maxlength="60"></label><label>Order note<textarea name="note" maxlength="280"></textarea></label><button>Review order and total</button>` : ""}</form>` : "<p>No product catalog is available for this account.</p>"}</section>` : ""}
    ${data.config.orderStatus ? `<section id="orders"><h2>Your orders</h2>${data.orders.map(o => `<article><h3>${e(o.id)}</h3><p>${e(o.status)} · ${e(o.fulfillment)} · ${e(o.createdAt.slice(0, 10))} · PO ${e(o.poNumber ?? "—")}</p>${o.shipments.map(s => `<p>${e(s.carrier)} · Tracking ${e(s.trackingNumber ?? "not supplied")} · ${e(s.createdAt.slice(0, 10))}</p>`).join("")}${o.lines.map(l => `<p>${e(l.name)} · ${l.quantity} ${e(l.unit)} · ${money(l.lineTotalCents)}</p>`).join("")}<p>Subtotal ${money(o.subtotalCents)} · Freight ${money(o.freightCents)} · <strong>Total ${money(o.totalCents)}</strong></p></article>`).join("") || "<p>No orders yet.</p>"}</section>` : ""}
    ${(data.config.booking || data.config.servicePortal) ? `<section id="appointments"><h2>Service appointments</h2><p>All times below are shown in UTC.</p>${data.appointments.map(r => `<article><h3>${e(r.title)}</h3><p>${e(new Date(r.start).toUTCString())} → ${e(new Date(r.end).toUTCString())} · ${e(r.status)}</p>${data.config.booking && r.status === "scheduled" && Date.parse(r.start) > Date.now() ? `<form method="post" action="${CUSTOMER_PATH}">${action("booking.cancel")}<input type="hidden" name="id" value="${e(r.id)}"><label><input type="checkbox" name="accepted" value="yes" required> Cancel this appointment. Payment and cancellation terms remain as agreed.</label><button>Cancel appointment</button></form>` : ""}</article>`).join("") || "<p>No appointments.</p>"}${data.config.booking ? `<h3>Available times for your agreed work</h3>${data.offers.map(o => `<article><h4>${e(o.title)}</h4><p>${e(new Date(o.start).toUTCString())} → ${e(new Date(o.end).toUTCString())}</p><p>${e(o.resource)}</p><form method="post" action="${CUSTOMER_PATH}">${action("booking.book")}<input type="hidden" name="id" value="${e(o.id)}"><label><input type="checkbox" name="accepted" value="yes" required> Reserve this appointment time.</label><button>Confirm appointment</button></form></article>`).join("") || "<p>No available times are published for your work. Contact the organization to arrange another time.</p>"}` : ""}</section>` : ""}
    ${inspectionReportsHtml(data.inspections, `${CUSTOMER_PATH}/inspection-photo/`)}
    ${data.config.servicePortal ? `<section id="service"><h2>Proposals</h2>${data.proposals.map(r => `<article><h3>${e(r.title)}</h3><small>${e(r.status)} · Expires ${e(r.expires)}</small><p>${e(r.scope)}</p><p>Exclusions: ${e(r.exclusions)}</p><p class="amount">${money(r.amount, r.currency)}</p>${r.status === "sent" ? acceptance(r) : ""}</article>`).join("") || "<p>No proposals to review.</p>"}<h2>Your work</h2>${data.jobs.map(r => `<article><h3>${e(r.title)}</h3><p>${e(r.status)} · Due ${e(r.due)}</p>${r.status === "completed" ? acceptance(r) : ""}</article>`).join("") || "<p>No current work.</p>"}<h2 id="invoices">Invoices</h2>${data.invoices.map(r => `<article><h3>${e(r.title)}</h3><p>${e(r.description)}</p><p>Amount ${money(r.amount, r.currency)} · Received ${money(r.paid, r.currency)} · Remaining ${money(r.amount - r.paid, r.currency)}</p><p>Due ${e(r.due)}.</p>${invoiceButtons(r, data)}</article>`).join("") || "<p>No issued invoices.</p>"}</section>` : ""}
    <section><details><summary>Change password</summary><form method="post" action="${CUSTOMER_PATH}">${action("password")}<label>Current password<input name="current" type="password" autocomplete="current-password" maxlength="200" required></label><label>New password<input name="password" type="password" autocomplete="new-password" minlength="14" maxlength="200" required></label><label>Repeat new password<input name="confirmation" type="password" autocomplete="new-password" minlength="14" maxlength="200" required></label><button>Change password and sign out everywhere</button></form></details></section>`);
}
export function customerOrderReview(q: Awaited<ReturnType<typeof previewCustomerOrder>>) { return customerPage("Review your order", `<section>${q.lines.map(l => `<p>${e(l.name)} · ${l.quantity} ${e(l.unit)} at ${money(l.unitPriceCents)} each · ${money(l.totalCents)}</p>`).join("")}<p>Subtotal ${money(q.subtotalCents)}</p><p>Freight ${money(q.freightCents)} · ${e(q.freightNote)}</p><p class="amount">Total ${money(q.totalCents)}</p><p>Payment terms: ${e(q.paymentTerms)} · PO ${e(q.poNumber ?? "—")}</p><p>This review expires in 15 minutes. The order will be submitted to the organization for fulfillment.</p><form method="post" action="${CUSTOMER_PATH}">${action("order.submit")}<input type="hidden" name="quote" value="${e(q.id)}"><label><input type="checkbox" name="accepted" value="yes" required> Place this order at the price and terms shown above.</label><button>Place order</button></form><p><a href="${CUSTOMER_PATH}#pricing">Change quantities</a></p></section>`); }

function invoiceButtons(r: { id: string; amount: number; paid: number; currency: string }, data: Awaited<ReturnType<typeof customerView>>) {
  const p = data.checkouts?.find(p => p.invoiceId === r.id && !["paid", "test_paid", "expired"].includes(p.status));
  if (p) return `<p>Online payment: ${e(p.status === "paid_review" ? "Received; staff are reviewing its application. Do not pay again." : p.status)}</p><form method="post" action="${CUSTOMER_PATH}">${action("payment.refresh")}<input type="hidden" name="payment" value="${e(p.id)}"><button>Check payment status</button></form>${["creating", "open"].includes(p.status) ? `<form method="post" action="${CUSTOMER_PATH}">${action("payment.start")}<input type="hidden" name="invoice" value="${e(r.id)}"><button>Continue to Stripe Checkout</button></form>` : ""}`;
  const remaining = r.amount - r.paid;
  if (remaining <= 0) return "<p>Paid in full.</p>";
  if (!data.invoicePayments || remaining < 100 || remaining > 99999999 || !["USD", "EUR", "GBP", "CAD", "AUD"].includes(r.currency)) return "<p>Contact the organization for payment instructions.</p>";
  return `${data.paymentTestMode ? "<p>Test mode: this Checkout does not collect money or settle your invoice.</p>" : ""}<form method="post" action="${CUSTOMER_PATH}">${action("payment.start")}<input type="hidden" name="invoice" value="${e(r.id)}"><button>Pay ${money(remaining, r.currency)} with Stripe</button></form>`;
}
