import { requireSectionAccess } from "@/lib/permissions/guard";
import Link from "next/link";
import { connectionCatalog } from "@/lib/connections/catalog";
import { appBaseUrl } from "@/lib/connections/vault";
import { ConnectionWizard } from "@/components/ConnectionWizard";
import { IntegrationSync } from "@/components/IntegrationSync";
import { getIntegrationStatuses } from "@/lib/integrations/status";
export const dynamic="force-dynamic";
const MESSAGES:Record<string,string>={amazon_ads_setup:"Save your Amazon Ads app credentials before signing in.",amazon_ads_authorization:"Amazon Ads authorization did not complete. Check app approval, the registered return URL and the region, then sign in again.",shopify_setup:"Finish the Shopify connection details first.",shopify_verification:"Shopify’s security check failed. Start the connection again.",shopify_exchange:"Shopify could not authorize this app. Check its client credentials and redirect URL.",qbo_state_mismatch:"QuickBooks security check failed. Start the connection again.",qbo_missing_params:"QuickBooks did not return a company authorization.",qbo_exchange_failed:"QuickBooks could not finish authorization. Check your app’s environment and redirect URL.",qbo_not_configured:"Add your QuickBooks app credentials in the wizard first."};
export default async function SettingsPage({searchParams}:{searchParams:Promise<{connected?:string;error?:string}>}){
  await requireSectionAccess("admin", "view");
const params=await searchParams,connections=connectionCatalog(),statuses=getIntegrationStatuses();return <div className="space-y-6"><header><p className="dd-eyebrow">Bring your business together</p><h1 className="mt-1 text-2xl font-bold tracking-tight">Connections</h1><p className="mt-2 text-sm text-slate-500">A simple setup for your store, your books, your maps and the tools you already use.</p></header>{params.connected&&<p role="status" className="rounded-lg bg-emerald-50 p-4 text-sm text-emerald-800">{params.connected==="shopify"?"Shopify":params.connected==="quickbooks"?"QuickBooks":"Account"} authorization saved. Open Manage connection to check the account.</p>}{params.error&&<p role="alert" className="rounded-lg bg-rose-50 p-4 text-sm text-rose-800">{MESSAGES[params.error]||"The connection did not complete. Open its wizard and try again."}</p>}<ConnectionWizard initial={connections} baseUrl={appBaseUrl()}/><Link href="/social" className="block rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Social profiles, website analytics &amp; creative</h2><p className="mt-2 text-sm text-slate-500">Drop a website or social link to start tracking. Connect Google Analytics, Gemini and OpenAI from your social workspace.</p><span className="mt-3 inline-block text-sm font-semibold text-emerald-800">Open social marketing →</span></Link><IntegrationSync ready={statuses.every(s=>s.connected)}/><p className="text-center text-xs text-slate-400">Saved credentials are encrypted on this server. Store and accounting authorization remains under your provider account.</p></div>;}
